import { Header, Footer, JsonLd } from '../components';
import { site, staffingOffer, leadQuestions, staffingFitNote } from '../data';
export const metadata = { title: `Contact ${site.brand}`, description: 'Request an outsourced call center coverage plan. Share your channels, hours, scripts, tools, escalation rules, and quality needs.' };
export default function Contact() {
 const siteAny = site as any;
 const siteUrl = siteAny.url || `https://${String(site.domain).toLowerCase()}`;
 const schema = { '@context': 'https://schema.org', '@graph': [{ '@type': 'ContactPage', name: `Contact ${site.brand}`, url: `${siteUrl}/contact` }, { '@type': 'Organization', name: site.brand, url: siteUrl }, { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: siteUrl }, { '@type': 'ListItem', position: 2, name: 'Contact', item: `${siteUrl}/contact` }] }] };
 return <><Header/><main className="section"><JsonLd data={schema} /><div className="container two"><div><p className="eyebrow">Coverage intake</p><h1>Request a call center coverage plan</h1><p className="lead">Tell us which queues need support. The next step is a practical coverage scope built around your channels, hours, scripts, tools, escalation rules, and quality needs.</p><div className="card"><h2>What the coverage team can help map</h2><ul className="list">{staffingOffer.included.map((item)=><li key={item}>{item}</li>)}</ul></div><div className="card"><h2>Questions that make the plan better</h2><ul className="list">{leadQuestions.map((q)=><li key={q}>{q}</li>)}</ul></div><p className="callout"><b>Custom coverage fit:</b> {staffingFitNote}</p></div><form className="card" action="/thank-you"><label>Name<br/><input required name="name" style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>Email<br/><input required name="email" type="email" style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>Company / website<br/><input name="company" style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>Which channels, queues, or work need coverage?<br/><textarea name="tasks" rows={6} style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>What matters most?<br/><select name="concern" style={{width:'100%', padding:12, margin:'6px 0 14px'}}><option>Phone, chat, email, or ticket coverage</option><option>Quality control and reporting</option><option>Schedule, overflow, and time zone</option><option>Tool access and data safety</option><option>Scaling beyond one queue</option></select></label><button className="btn" type="submit">Request a coverage plan</button></form></div></main><Footer/></>;
}
