import type { BlogPost } from './data';

type Draft = {
  slug: string; title: string; excerpt: string; intro: string; focus: string;
  advice: string; measure: string; handoff: string; published: '2026-08-13'; updated: '2026-08-13';
};

const drafts: readonly Draft[] = [
  { slug: 'call-center-customer-intent-mapping', title: 'Map customer intent before choosing a call route', excerpt: 'A small intent map helps a contact team ask the right first question and send work to the right queue.', intro: 'The first words in a call do not always reveal the work the customer needs. A useful intent map separates the request from the channel or product detail that brought it in.', focus: 'Group intents by the decision they require, then define the one clarifying question that distinguishes neighboring routes.', advice: 'Keep the first version to high-volume intents and give each one a clear fallback when the caller does not fit the map.', measure: 'Review route accuracy, clarification time, transfers, repeat contacts, and intents that repeatedly land in the fallback queue.', handoff: 'Send overlapping definitions to the owner of routing rules before changing live call handling.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-callback-window-communication', title: 'Communicate callback windows without overpromising', excerpt: 'Clear callback language gives customers a useful expectation while leaving room for real queue conditions.', intro: 'A callback window is a service commitment only when the team can see its owner and status. Vague promises create repeat calls and make late work harder to prioritize.', focus: 'Define the window, the approved contact method, the owner, and the update path when the original window is at risk.', advice: 'Use a range the team can actually monitor and tell the customer what will happen if more information is needed.', measure: 'Track on-time callbacks, missed windows, repeat contacts, unreachable customers, and records without a next action.', handoff: 'Escalate a high-impact missed promise to the supervisor who can reset the commitment truthfully.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-caller-verification-boundaries', title: 'Set caller-verification boundaries the queue can follow', excerpt: 'A verification boundary protects customer information while keeping ordinary calls moving.', intro: 'Verification should match the sensitivity of the request. Asking too little creates risk; asking for unnecessary detail frustrates callers and leaves notes full of information the next person does not need.', focus: 'List the minimum approved checks for each request type and the stop condition when the caller cannot complete them.', advice: 'Never improvise a substitute check. Record only the result and route an exception to the owner of the verification rule.', measure: 'Review incomplete checks, inappropriate disclosures, abandoned calls, exception volume, and verification steps that do not affect access.', handoff: 'Send identity, privacy, or account-ownership disputes through the designated protected escalation path.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-dead-air-call-handling', title: 'Handle dead-air calls with a consistent recovery path', excerpt: 'A calm dead-air procedure helps representatives recover a silent connection without blaming the caller.', intro: 'Silence can come from a muted device, a poor connection, or a customer who needs time. The representative needs a short sequence that protects the conversation and records the outcome.', focus: 'Set the check-in wording, wait interval, reconnection attempt, and final disposition for a call that remains silent.', advice: 'Use plain check-ins and avoid reading sensitive information aloud while the connection is uncertain.', measure: 'Track recovered calls, premature disconnects, repeat attempts, technical patterns, and records missing the final outcome.', handoff: 'Escalate a repeated technical pattern to the telephony owner with examples and times, not customer speculation.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-call-opening-standards', title: 'Design a call opening that earns the next useful answer', excerpt: 'A short opening can establish identity, purpose, and control without sounding scripted or rushed.', intro: 'Customers often answer a question before they understand why it is being asked. The opening should explain the role of the representative and invite the request in the customer’s own words.', focus: 'Define the greeting, permission to continue, first open question, and safe response when the caller starts with an urgent concern.', advice: 'Keep the wording natural and test it against common call types. Do not force a long checklist before understanding the reason for contact.', measure: 'Sample interruptions, repeated openings, misrouted calls, early hang-ups, and the time to identify the request.', handoff: 'Send proposed wording changes to the service owner when they alter a policy or promise.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-customer-sentiment-notes', title: 'Record customer sentiment without turning notes into labels', excerpt: 'A disciplined sentiment note preserves what the customer expressed and what the team did next.', intro: 'A label such as upset or satisfied is rarely enough for the next person. Notes should describe observable language, the service impact, and any action needed without editorializing.', focus: 'Separate the customer’s stated concern from the representative’s response and identify when a sentiment signal requires review.', advice: 'Use a short approved vocabulary only when it leads to an action. Quote minimal relevant wording and leave out personal judgments.', measure: 'Review note usefulness, escalation agreement, repeat explanations, missing actions, and labels that do not change handling.', handoff: 'Escalate a serious service, safety, or vulnerability signal to the appropriate owner rather than relying on a label.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-call-reopen-criteria', title: 'Define when a resolved call should be reopened', excerpt: 'Reopen criteria keep unresolved customer work visible without treating every new contact as the same case.', intro: 'A record can be closed correctly and still need reopening when a promised action failed or new evidence changes the decision. The team needs a shared boundary.', focus: 'Name the events that reopen a case, the evidence required, and the owner who reviews an ambiguous repeat contact.', advice: 'Link the new contact to the prior record and explain what changed. Do not reopen solely because a customer called again if the original obligation was completed.', measure: 'Track valid reopens, false reopens, repeat contacts after closure, aging, and reasons for changed ownership.', handoff: 'Send disputes about completion evidence to the owner of the case state, not to an unassigned queue.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-contact-reason-examples', title: 'Use concrete contact-reason examples to improve routing', excerpt: 'Examples make a routing vocabulary usable when customer wording does not match internal labels.', intro: 'A definition can be technically correct and still fail at the desk. Short examples show which details matter and where a similar request belongs instead.', focus: 'Write a normal example, a near match, and a stop case for each high-volume contact reason.', advice: 'Use redacted, realistic wording and review examples when services or policies change. Avoid examples that imply facts the business cannot verify.', measure: 'Compare route agreement, clarification questions, transfers, and the reasons representatives choose a neighboring label.', handoff: 'Ask the routing owner to resolve a recurring near match before adding more labels.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-customer-consent-records', title: 'Keep customer consent records clear at the point of contact', excerpt: 'A focused consent record shows what the customer agreed to, for which purpose, and what the team may do next.', intro: 'Consent is easy to misunderstand when a general permission is treated as approval for every later action. The contact record should preserve scope and source without collecting excess detail.', focus: 'Specify the approved wording, purpose, channel, timestamp, and withdrawal route for each consented action.', advice: 'Ask for the narrow permission needed and stop when the customer declines. Never infer permission from silence or prior unrelated contact.', measure: 'Review missing scope, outdated permissions, withdrawal handling, repeat asks, and actions without an attributable record.', handoff: 'Send a consent question or privacy concern to the designated compliance owner.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-silent-customer-recovery', title: 'Give a silent customer time without losing call control', excerpt: 'A measured pause-and-check approach supports callers who need time while keeping the interaction safe and purposeful.', intro: 'A pause may mean the customer is searching for information, processing a difficult answer, or facing a connection problem. The representative should offer help without filling the silence with guesses.', focus: 'Define the check-in, time boundary, assistance offer, and outcome record for a prolonged pause.', advice: 'Ask one helpful question at a time and explain what information is needed. Do not pressure the caller to disclose more than the request requires.', measure: 'Track successful recoveries, abandoned calls, repeat questions, disconnect reasons, and notes that omit the final disposition.', handoff: 'Escalate a vulnerability or safety concern through the immediate route when the caller’s words indicate one.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-contact-channel-preference', title: 'Honor contact-channel preferences across follow-up', excerpt: 'A visible channel preference prevents avoidable repeat explanations and unexpected outreach.', intro: 'A customer may prefer a call for one matter and written confirmation for another. The record should distinguish a durable preference from a request tied to a single interaction.', focus: 'Capture the preferred channel, scope, permission, source, and exception path when that channel cannot complete the request.', advice: 'Confirm the preference instead of inferring it from the last contact. Keep sensitive detail out of channels not approved for it.', measure: 'Review channel mismatches, repeat explanations, failed deliveries, preference changes, and follow-ups without a permitted method.', handoff: 'Route permission conflicts or inaccessible channels to the owner who controls contact policy.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-knowledge-gap-escalation', title: 'Turn a knowledge gap into a useful escalation', excerpt: 'A good knowledge-gap escalation gives the content owner enough evidence to improve an answer.', intro: 'Representatives should not guess when an approved answer is missing or conflicting. The escalation should preserve the customer question, source checked, and decision that is needed.', focus: 'Record the exact question, relevant service context, attempted source, risk of delay, and temporary customer wording.', advice: 'Keep the temporary response honest and identify its expiry or review point. Do not publish an unapproved answer in a shared note.', measure: 'Track repeat questions, returned escalations, time to approved answer, temporary responses, and duplicate requests.', handoff: 'Send policy or factual conflicts to the named knowledge owner with the smallest useful evidence set.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-repeat-contact-analysis', title: 'Analyze repeat contacts by unresolved customer need', excerpt: 'Repeat-contact analysis becomes actionable when it distinguishes a missed answer from a new request.', intro: 'A second contact is a signal, not a diagnosis. The team should compare the original promise, the customer’s new question, and the action that was or was not completed.', focus: 'Link related records and classify the repeat by missing information, missed commitment, transfer failure, or genuinely new need.', advice: 'Sample the conversation rather than relying on a status code. Correct the route or promise only after confirming the pattern.', measure: 'Track repeat reasons, time between contacts, ownership changes, unresolved promises, and cases that close after one clear answer.', handoff: 'Escalate a recurring repeat-contact pattern to the owner of the service step causing it.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-customer-question-capture', title: 'Capture the customer question before writing the answer', excerpt: 'A faithful question record helps the next representative understand what the customer actually needed.', intro: 'Internal categories often flatten a customer’s question into a status label. Keeping the original request in plain language protects context and makes later review more useful.', focus: 'Record the customer’s main question, relevant constraint, requested outcome, and any ambiguity that still needs clarification.', advice: 'Use a brief paraphrase and confirm it when the request is complex. Remove unnecessary personal details from general notes.', measure: 'Review question-to-route agreement, clarification rate, repeat explanations, unanswered parts, and changes made after supervisor review.', handoff: 'Send an ambiguous or high-impact question to the owner who can decide the next safe step.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-service-exception-notes', title: 'Write service-exception notes that support a real decision', excerpt: 'An exception note should explain the rule, the facts, and the decision still required.', intro: 'Exceptions become hard to govern when notes simply say approved or unusual. A decision-maker needs the normal rule, the evidence that differs, and the customer impact.', focus: 'Use a fixed structure for rule, observed facts, prior action, requested exception, and deadline.', advice: 'Separate the recommendation from the evidence and avoid promising approval. Keep the note short enough for the owner to use quickly.', measure: 'Track returned notes, decision time, repeated exceptions, missing evidence, and outcomes that differ from the initial request.', handoff: 'Route policy exceptions to the person with authority to approve them, preserving the original record.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-queue-entry-criteria', title: 'Set queue-entry criteria that protect specialist capacity', excerpt: 'A clear queue-entry rule keeps specialist work focused while giving general support a safe fallback.', intro: 'Specialist queues lose their value when every uncertain case is sent there. Entry criteria should describe the evidence needed and the work that remains after entry.', focus: 'Define eligible request types, required fields, exclusions, and the response when information is incomplete.', advice: 'Provide a return path with a reason instead of silently rejecting work. Review criteria against real examples from both normal and edge cases.', measure: 'Track accepted entries, returns, missing fields, queue age, and requests that bypassed the intended route.', handoff: 'Escalate a capacity or policy conflict to the owner of the specialist queue.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-warm-transfer-consent', title: 'Ask for consent before a warm transfer changes the conversation', excerpt: 'A brief consent step helps customers understand who will receive them and why the transfer is needed.', intro: 'Warm transfers can reduce repetition, but they also move a customer into a new conversation. The representative should explain the reason, what context will be shared, and what happens if the specialist is unavailable.', focus: 'Set the consent wording, minimum transfer summary, fallback route, and record of the customer’s choice.', advice: 'Share only relevant context and confirm the receiving person has accepted the handoff before leaving the call.', measure: 'Review declined transfers, transfer drops, repeated explanations, rejected handoffs, and transfers without a recorded reason.', handoff: 'Send failed or sensitive transfers to the supervisor who owns the route rather than repeating the attempt indefinitely.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-queue-reassignment-reasons', title: 'Record why a call moved between queues', excerpt: 'Reassignment reasons reveal whether routing is working or whether customers are carrying a hidden handoff cost.', intro: 'A transfer count does not show whether a move was necessary. A concise reassignment reason lets managers distinguish a correct specialist handoff from an avoidable route error.', focus: 'Use a small reason set covering missing skill, wrong intent, unavailable owner, customer request, and system problem.', advice: 'Choose the reason at the point of reassignment and add one sentence only when the standard options are insufficient.', measure: 'Track reassignment share, loops, time added, reason agreement, and queues that receive repeated avoidable work.', handoff: 'Escalate a recurring route error to the person who maintains the queue map.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-customer-update-cadence', title: 'Choose a customer update cadence for work that is still open', excerpt: 'A visible update cadence reduces uncertainty when a request cannot be completed in one contact.', intro: 'Silence makes customers guess whether their request still exists. A cadence should be based on the commitment and risk of the work, not on whichever team member remembers it.', focus: 'Set the next update point, responsible owner, approved channel, and truthful message when there is no new result yet.', advice: 'An update can say that review continues; it should not imply progress that has not occurred. Change the cadence when the customer’s impact changes.', measure: 'Track missed updates, repeat contacts, overdue reviews, message accuracy, and follow-ups without an assigned owner.', handoff: 'Escalate a missed high-impact update to the manager who can reset ownership and expectation.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-call-note-minimums', title: 'Set call-note minimums that preserve the next useful action', excerpt: 'A concise note standard keeps records usable without turning every call into a transcription exercise.', intro: 'Notes need enough context for the next action, not every sentence spoken. A minimum standard can protect continuity while reducing inconsistent detail.', focus: 'Require request, verified facts, action taken, next owner, customer expectation, and deadline when one exists.', advice: 'Use plain language and approved abbreviations. Never replace a missing decision with a confident-sounding summary.', measure: 'Sample note completeness, reopened questions, handoff time, duplicate work, and fields that staff routinely skip.', handoff: 'Send conflicting note requirements to the record owner for one approved standard.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-unavailable-specialist-fallbacks', title: 'Build a fallback when the right specialist is unavailable', excerpt: 'A named fallback keeps customers moving when a specialist queue or person cannot accept the handoff.', intro: 'Routing only works when the receiving capability is available. A fallback should preserve urgency, context, and customer expectations rather than sending the case through a loop.', focus: 'Define the availability check, safe interim action, callback owner, and escalation threshold for each specialist route.', advice: 'Tell the customer what is confirmed and what still needs review. Keep the original request linked to the fallback record.', measure: 'Track failed transfers, fallback age, repeat calls, abandoned contacts, and cases that lose their original context.', handoff: 'Escalate a repeated capacity failure to the service owner with impact and timestamps.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-contact-closure-check', title: 'Use a closure check before ending a customer contact', excerpt: 'A brief closure check confirms the request, next step, and customer understanding before the record is closed.', intro: 'Many repeat contacts begin with a missing final detail: the customer did not know what would happen next or the representative did not record the remaining work.', focus: 'Confirm the request addressed, action completed, pending step, owner, and timing before choosing a closed status.', advice: 'Ask the customer to confirm the practical next step in their own words. Do not close a record merely because the conversation ended politely.', measure: 'Track reopening, repeat contact within the expected window, missing promises, closure corrections, and customer questions after closure.', handoff: 'Escalate an unresolved obligation to its owner before closing the contact.', published: '2026-08-13', updated: '2026-08-13' },
];

const makePost = (draft: Draft, index: number): BlogPost => ({
  slug: draft.slug, title: draft.title, excerpt: draft.excerpt, minutes: 7 + (index % 4), keyword: draft.title,
  published: draft.published, updated: draft.updated, intro: draft.intro,
  sections: [
    { title: 'Start with the customer need', paragraphs: [draft.focus, `Write the request, the next action, and the finished record for ${draft.title.toLowerCase()}.`], items: ['Name the request', 'Show one useful example', 'State the review point', 'Name the owner'] },
    { title: 'Keep the boundary clear', paragraphs: [draft.advice, 'Use the smallest safe path first and review edge cases before widening it.'] },
    { title: 'Protect the handoff', paragraphs: [draft.handoff, 'The service team can follow approved wording, record permitted facts, and route work. Exceptions and policy decisions stay with the named owner.'], items: ['Record what happened', 'Keep sensitive detail limited', 'Name what remains', 'Escalate uncertainty'] },
    { title: 'Measure the customer outcome', paragraphs: [draft.measure, 'Pair volume with quality, timeliness, and ownership so a number leads to a practical decision.'] },
    { title: 'Close with an honest expectation', paragraphs: ['State the next confirmed action and its owner. If review is still needed, say so plainly instead of promising an outcome that has not been approved.'], items: ['Confirm the request', 'State the next step', 'Name the timing', 'Record the result'] },
    { title: 'Use consistent customer language', paragraphs: ['Give the team one sentence for the normal path and one for uncertainty. Keep the wording accurate to the authority available at the point of contact.'] },
    { title: 'Review the first sample', paragraphs: ['Look for missing fields, repeated questions, avoidable transfers, and conflicts between the written rule and the tool. Fix the rule before expanding it.'], items: ['Sample early work', 'Discuss exceptions', 'Update the example', 'Expand after review'] },
  ],
  controlTable: [
    { data: 'Normal request', agent: 'Follow the approved path and record the result', manager: 'Review samples and maintain the rule' },
    { data: 'Missing information', agent: 'Ask the approved question or pause', manager: 'Decide the safe fallback' },
    { data: 'Sensitive exception', agent: 'Do not complete it without approval', manager: 'Verify evidence and decide' },
    { data: 'Ownership conflict', agent: 'Keep the record unchanged and escalate', manager: 'Assign the owner' },
  ],
  scripts: [
    { situation: 'Normal path', text: 'I have recorded the request and will complete the approved next step.' },
    { situation: 'Needs review', text: 'This part needs review, so I will send it to the named owner.' },
    { situation: 'Unclear case', text: 'I do not want to guess. I will record what is known and confirm the next step.' },
  ],
  faqs: [{ question: 'What should happen first?', answer: draft.focus }, { question: 'What needs an owner?', answer: draft.handoff }, { question: 'What should be measured?', answer: draft.measure }],
  sources: [{ name: 'Zero Trust Architecture, SP 800-207', organization: 'National Institute of Standards and Technology', date: 'August 2020', url: 'https://csrc.nist.gov/pubs/sp/800/207/final', note: 'Supports narrow access and explicit decision boundaries.' }, { name: 'ISO 18295-1 overview', organization: 'International Organization for Standardization', date: '2017', url: 'https://www.iso.org/standard/65137.html', note: 'Supports defined contact-centre processes and service outcomes.' }],
  related: [{ label: 'Review customer support', href: '/services/omnichannel-customer-support' }, { label: 'Review operations support', href: '/services/inbound-call-handling' }, { label: 'Review reporting support', href: '/services/workforce-reporting-support' }],
  banners: [{ label: 'Scope', title: 'Define the first queue', body: 'List the work, review points, and approval limits before adding coverage.', href: '/services/inbound-call-handling', cta: 'Review operations support' }, { label: 'Review', title: 'Use representative examples', body: 'Sample early work with a named owner and fix unclear rules quickly.', href: '/services/workforce-reporting-support', cta: 'Review reporting support' }],
});

export const august13ReplacementBlogBatch: readonly BlogPost[] = drafts.map(makePost);
