import type {BlogPost} from './data';

const topics = [
  ['call-center-opening-backlog-sweep','Call Center Opening Backlog Sweep','Start the service day by finding aged, blocked, and unowned customer work before new volume hides it.','opening backlog sweep','Review age, customer impact, the last promise, blocked dependency, and current owner before changing priority.'],
  ['outsourced-call-center-interval-coverage-check','Outsourced Call Center Interval Coverage Check','Compare demand, productive capacity, specialist coverage, and escalation availability for each operating interval.','interval coverage check','Use scheduled productive time rather than roster headcount, and show training, absence, meetings, and known events separately.'],
  ['call-center-callback-attempt-record','Call Center Callback Attempt Record','Document callback attempts so the approved channel, verification state, promise, result, and next action remain connected.','callback attempt record','Capture the customer time zone, permitted channel, attempt time, verification boundary, neutral voicemail outcome, and next owner.'],
  ['call-center-knowledge-conflict-queue','Call Center Knowledge Conflict Queue','Route contradictory scripts, policies, and system guidance to a named owner without asking frontline staff to choose a rule.','knowledge conflict queue','Preserve the conflicting sources, effective dates, affected contact reason, customer impact, and safe interim response.'],
  ['outsourced-call-center-break-coverage-handoff','Outsourced Call Center Break Coverage Handoff','Keep queues and escalations owned when scheduled breaks temporarily move live coverage between team members.','break coverage handoff','Name the coverage window, active queue, open escalation, promised callback, monitoring owner, and return acceptance.'],
  ['call-center-high-impact-contact-review','Call Center High-Impact Contact Review','Review contacts involving safety, identity, payment, privacy, or material customer promises through a defined specialist lane.','high-impact contact review','Tag the observable trigger and preserve evidence without copying secrets or treating an initial report as a final finding.'],
  ['call-center-case-reopen-analysis','Call Center Case Reopen Analysis','Use reopened cases to distinguish incomplete resolution, unclear communication, new information, and incorrect closure.','case reopen analysis','Compare the original request, closure evidence, later customer contact, new facts, and ownership at each transition.'],
  ['outsourced-call-center-guidance-release-brief','Outsourced Call Center Guidance Release Brief','Release approved workflow changes with an effective time, affected scope, examples, acknowledgment, and verification sample.','guidance release brief','Identify the superseded version, decision owner, effective shift, changed action, exception path, and rollback contact.'],
  ['call-center-manual-routing-exception-log','Call Center Manual Routing Exception Log','Make manual queue moves reviewable when ordinary routing cannot place customer work with the right owner.','manual routing exception log','Record the source queue, intended destination, reason, customer promise, permissions used, receiving owner, and acceptance.'],
  ['call-center-customer-update-readiness-check','Call Center Customer Update Readiness Check','Verify source facts, approved wording, channel, timing, and next ownership before sending a material status update.','customer update readiness check','Separate confirmed facts from estimates and pending decisions, then name who owns the next update if the matter remains open.'],
  ['outsourced-call-center-shift-risk-brief','Outsourced Call Center Shift Risk Brief','Give the incoming manager a concise view of capacity, outages, overdue promises, access issues, and decision queues.','shift risk brief','Rank observable conditions by customer impact and decision deadline rather than copying every dashboard count.'],
  ['call-center-daily-control-closure','Call Center Daily Control Closure','Close daily operating controls with evidence of completion, an accepted exception, or an owned carry-forward action.','daily control closure','Reconcile each planned check with its source, result, reviewer, unresolved gap, due time, and next-day owner.'],
] as const;

export const september2BlogBatch: readonly BlogPost[] = topics.map(([slug,title,excerpt,focus,specific],index)=>({
  slug,title,excerpt,keyword:title,published:'2026-09-02',updated:'2026-09-02',minutes:9+(index%4),
  intro:`${excerpt} For Call Center Outsourced buyers, the ${focus} should be an explicit operating control with evidence and accountable ownership.`,
  sections:[
    {title:`Set the ${focus} trigger`,paragraphs:[specific,`Define when the ${focus} begins, what source is authoritative, which action is permitted, and what proves completion.`],items:['Name the source record','Use an observable trigger','Define the permitted action','Assign an accountable owner']},
    {title:'Read the live operating state',paragraphs:[`Check the current queue, schedule, approved guidance, and open customer commitments before acting. The ${focus} must respond to present conditions, not an assumed normal day.`,'Mark missing or contradictory input as an exception. A visible gap can be owned and resolved; a guessed value cannot be audited.']},
    {title:'Separate routine work from decisions',paragraphs:[`Team members can gather facts and complete approved, reversible steps. Policy, access, staffing, security, customer remedy, and other irreversible decisions remain with the named manager.`,'Escalate with the source identifier, observed condition, customer impact, action already taken, decision required, and due time.'],items:['Record observation before interpretation','Use minimum necessary access','Pause outside the approved boundary','Keep the decision with its owner']},
    {title:'Create the operating record',paragraphs:[`The ${focus} record should identify the relevant interval or case, source evidence, action, outcome, exception, next owner, and timestamp.`,'Link to authorized systems instead of copying passwords, payment data, identity answers, or unnecessary customer details into coordination notes.']},
    {title:'Test customer impact',paragraphs:[`Sample the source interaction and finished record together. Check timeliness, rework, missed promises, unresolved ownership, and whether the customer received the approved next step.`,'Counts show volume; they do not show whether the work was accurate, safe, or useful. Review a normal case and an exception.']},
    {title:'Use an exception statement',paragraphs:[`When the ${focus} instruction does not fit, use: “I preserved the current record and completed the approved step. The named owner is reviewing the remaining decision.”`]},
    {title:'Close and improve',paragraphs:[`Close the cycle only when the outcome is evidenced or an exception has been accepted by its next owner. Review repeated gaps through change control.`,'Version any approved instruction change with its reason, effective time, affected scope, and verification sample.'],items:['Reconcile planned and completed checks','Carry forward named exceptions','Approve changes before release','Verify the next live example']},
  ],
  controlTable:[{data:'Complete approved input',agent:'Complete and record the routine step',manager:'Review the agreed sample'},{data:'Missing or conflicting input',agent:'Preserve state and flag the gap',manager:'Select the fallback'},{data:'Sensitive or irreversible action',agent:'Stop at the authority boundary',manager:'Verify and decide'},{data:'Repeated exception',agent:'Link representative examples',manager:'Own correction and release'}],
  scripts:[{situation:'Routine complete',text:'“The approved step is complete and the result is recorded.”'},{situation:'Owner needed',text:'“The evidence is preserved; the named owner must decide the next action.”'},{situation:'Input conflict',text:'“The sources conflict, so I am holding the current state for review.”'}],
  faqs:[{question:`Who owns the ${focus}?`,answer:'Assign one client-side process owner and a backup who can approve exceptions and instruction changes.'},{question:'What belongs in the first sample?',answer:'Review a normal record and an exception against their source interactions and eventual outcomes.'},{question:'When can the routine expand?',answer:'Expand only after inputs, access, ownership, handoffs, and review results are stable in the pilot scope.'}],
  sources:[{name:'Cybersecurity Framework 2.0',organization:'NIST',date:'February 2024',url:'https://www.nist.gov/cyberframework',note:'Governance and accountable-control context.'},{name:'ISO 18295-1:2017 Customer contact centres',organization:'International Organization for Standardization',date:'July 2017',url:'https://www.iso.org/standard/64739.html',note:'Customer-contact process context.'}],
  related:[{label:'Review operations support',href:'/services/operations-support'},{label:'Plan reporting support',href:'/services/workforce-reporting-support'},{label:'Explore more guides',href:'/blog'}],
  banners:[{label:'Scope',title:`Define the ${focus} lane`,body:'Document triggers, tools, limits, evidence, and ownership.',href:'/contact-us',cta:'Discuss the workflow'},{label:'Review',title:'Test one controlled cycle',body:'Use representative records and a named reviewer.',href:'/services/operations-support',cta:'Review operations support'},{label:'Improve',title:'Release approved changes',body:'Keep operating decisions traceable.',href:'/blog',cta:'Read more guides'}],
}));
