import type { BlogPost } from './data';

type August14Draft = {
  slug: string;
  title: string;
  excerpt: string;
  intro: string;
  focus: string;
  practice: string;
  measure: string;
  handoff: string;
  published: '2026-08-14';
  updated: '2026-08-14';
};

const drafts: readonly August14Draft[] = [
  { slug: 'call-center-peak-hour-coverage-planning', title: 'Plan call center coverage for predictable peak hours', excerpt: 'A peak-hour coverage plan connects arrival patterns, skill needs, breaks, and a fallback owner before the queue gets busy.', intro: 'The busiest hour is a poor time to discover that only one person can handle a particular request. A coverage plan makes the likely pressure points visible while there is still time to adjust.', focus: 'Map demand by interval, note which skills each interval needs, and identify the decision that changes when coverage falls short.', practice: 'Start with the intervals that repeatedly create long waits or abandoned work. Keep the first plan small enough for a supervisor to update when the actual day differs from the forecast.', measure: 'Compare arrival volume, wait time, abandoned contacts, skill mismatch, and uncovered intervals by time block.', handoff: 'Send a coverage exception to the owner who can approve a queue change or customer expectation reset.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-break-coverage-handoff', title: 'Protect queue coverage during breaks and handoffs', excerpt: 'A simple break handoff keeps ownership clear when one person steps away and another takes over active work.', intro: 'Break coverage is more than a calendar entry. Someone needs to know which cases are open, which promises are due, and what should happen if a customer replies while the usual owner is away.', focus: 'Record the active queue, urgent cases, expected returns, and backup owner before each planned handoff.', practice: 'Use a short handoff note that names facts and next actions. Do not ask the covering person to reconstruct a case from scattered messages.', measure: 'Review missed callbacks, unattended escalations, repeat explanations, and cases reopened after a break.', handoff: 'Escalate a conflict between break coverage and a customer commitment to the shift supervisor before the gap begins.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-queue-priority-rules', title: 'Write queue priority rules people can apply consistently', excerpt: 'Priority rules work when they describe observable customer impact and give the queue a clear tie-breaker.', intro: 'A queue becomes noisy when every request is called urgent. A usable priority rule tells the team what evidence matters and who resolves a close call.', focus: 'Define priority from customer impact, time sensitivity, dependency, and approved service commitments rather than from the loudest message.', practice: 'Test the rule against ordinary cases and two borderline examples. If two people choose different priorities, revise the definition before adding another category.', measure: 'Track priority changes, aging by category, escalations, missed commitments, and cases that enter the wrong lane.', handoff: 'Send disputed priority definitions to the owner of service policy, not to the person currently carrying the queue.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-after-call-work-reduction', title: 'Reduce after-call work without losing the next action', excerpt: 'A focused after-call record keeps the next step visible while removing notes that do not help the customer or the next owner.', intro: 'After-call work grows when the record asks for everything anyone might want later. A better standard keeps the request, verified facts, action, owner, and timing that another person actually needs.', focus: 'Separate required continuity fields from optional commentary and remove duplicated information already held in the approved record.', practice: 'Sample completed notes from several call types. Shorten the form only after confirming that the next owner can act without reopening the conversation.', measure: 'Track completion time, missing fields, repeat questions, reopened records, and duplicate note content.', handoff: 'Route competing note requirements to the record owner for one approved standard.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-voice-of-customer-tagging', title: 'Use voice-of-customer tags that lead to action', excerpt: 'A small tagging scheme helps managers connect recurring customer concerns to a service owner without flattening the original feedback.', intro: 'Tags are useful when they help someone decide what to review. They become decoration when the list grows faster than the team can define or act on it.', focus: 'Choose tags for a known decision, preserve a short plain-language summary, and give each tag an owner and review path.', practice: 'Begin with recurring issues that already appear in contacts. Retire tags that do not change routing, coaching, product review, or a customer follow-up.', measure: 'Review tag agreement, uncategorized contacts, repeat themes, action completion, and tags with no owner.', handoff: 'Send a new theme to the service owner with examples and dates, without presenting a sample as a complete trend.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-escalation-acknowledgment-standard', title: 'Set an escalation acknowledgment standard', excerpt: 'An escalation is safer when the receiving owner confirms receipt and the customer update does not depend on guesswork.', intro: 'A well-written escalation can still disappear into an unattended queue. The sender and receiver need a visible acknowledgment point, a backup path, and an honest update expectation.', focus: 'Record when the escalation was sent, who should acknowledge it, what the customer was told, and what happens when the deadline passes.', practice: 'Use a primary owner and a backup for each active shift. Keep acknowledgment separate from final resolution so an early receipt does not look like a completed decision.', measure: 'Track acknowledgment time, overdue escalations, backup use, customer updates, and cases without an accountable owner.', handoff: 'Alert the backup owner when the acknowledgment window expires and preserve the original escalation.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-customer-language-access-handoff', title: 'Keep language-access needs visible through a handoff', excerpt: 'A language-access note should help the next person provide the approved support without making the customer repeat the same request.', intro: 'Language needs can be lost when a case moves between channels or teams. The record should state the requested support, the permitted option, and the next owner without guessing about a person’s identity or ability.', focus: 'Capture the customer’s stated language preference, the contact channel that can support it, and the fallback when that option is unavailable.', practice: 'Use respectful wording and record only what is needed to arrange the approved support. Avoid turning a service preference into a personal label.', measure: 'Review repeat requests, unsupported transfers, delayed responses, preference mismatches, and cases where the support need vanished at handoff.', handoff: 'Send an unavailable-language exception to the owner responsible for arranging the approved alternative.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-customer-vulnerability-escalation', title: 'Create a bounded path for vulnerability signals', excerpt: 'A vulnerability escalation gives the right owner enough context to respond without asking a frontline contact to diagnose a personal situation.', intro: 'A customer may signal distress, safety risk, or difficulty using the normal process. The contact record should preserve the observable concern and route it quickly, while decisions stay with the qualified owner.', focus: 'Define the words or circumstances that require a pause, the immediate safe response, and the person who can decide what happens next.', practice: 'Train on short, announced examples and review whether the response protected dignity, limited disclosure, and reached the correct owner.', measure: 'Track response time, repeated explanations, missed escalations, unnecessary detail, and cases without a follow-up owner.', handoff: 'Use the designated protected route for a safety or vulnerability concern; do not investigate beyond the approved scope.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-knowledge-article-owner-map', title: 'Give each call center knowledge article a clear owner', excerpt: 'An owner map makes it easier to correct stale answers, resolve conflicts, and show who approves a change.', intro: 'A knowledge article without an owner can remain published after the policy or service changes. Ownership does not mean one person writes every word. It means someone can answer whether the guidance is still approved.', focus: 'Record the article owner, affected service, source of authority, review trigger, and escalation path for conflicting information.', practice: 'Start with answers that affect customer commitments or sensitive handling. Give reviewers a way to flag uncertainty without editing approved wording themselves.', measure: 'Track overdue reviews, conflict age, unanswered flags, duplicate articles, and corrections after a customer contact.', handoff: 'Send a factual or policy conflict to the owner named on the article, with the smallest useful evidence set.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-customer-promise-register', title: 'Keep a customer promise register for open commitments', excerpt: 'A promise register links each customer commitment to an owner, deadline, evidence, and truthful update path.', intro: 'Promises are easy to lose when they live only in a call note. A focused register gives the next person a way to see what was said and what must happen before the customer is contacted again.', focus: 'Record the commitment in plain language, its source, due point, owner, status, and approved fallback when the work is late.', practice: 'Include only commitments that require future action. Close the item with evidence, not with a polite conversation ending.', measure: 'Review on-time completion, late promises, missing owners, repeat contacts, and commitments closed without evidence.', handoff: 'Escalate a late or disputed promise to the manager who can reset it honestly.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-customer-callback-ownership', title: 'Assign callback ownership that survives a busy shift', excerpt: 'Callback ownership is reliable when the record names the person, window, channel, and fallback rather than only a due date.', intro: 'A callback list can look complete while no one knows who will make the next attempt. Ownership should remain clear when a shift changes or a customer cannot be reached.', focus: 'Capture the requested window, approved channel, next attempt, responsible owner, and the condition that changes the plan.', practice: 'Give each callback one owner and one backup. Record unsuccessful attempts without pretending that a contact occurred.', measure: 'Track on-time attempts, unreachable contacts, reassignment, repeat requests, and callbacks without an outcome.', handoff: 'Send a missed high-impact callback to the supervisor who can prioritize it and reset the expectation.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-transfer-loop-prevention', title: 'Stop transfer loops before they become the customer experience', excerpt: 'A transfer-loop rule gives the queue a safe stopping point when the same request keeps moving without an owner.', intro: 'Repeated transfers add time and make the customer restate the problem. The record needs a loop signal, the reason for each move, and a person who can decide where the work belongs.', focus: 'Set a transfer limit or observable loop condition, preserve the original request, and define the next owner when normal routing fails.', practice: 'Review loop examples by cause: missing skill, unclear queue rule, unavailable specialist, or system problem. Fix the cause instead of adding another blind transfer.', measure: 'Track transfer count, time added, repeat explanations, loop causes, and cases resolved after supervisor intervention.', handoff: 'Escalate a recurring loop to the owner of the queue map with timestamps and linked case records.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-customer-record-correction-request', title: 'Route customer record correction requests safely', excerpt: 'A correction path separates the customer’s requested change from the evidence and authority needed to make it.', intro: 'A record correction may look simple but can affect identity, service history, or future contact. The first contact should capture the request accurately and avoid changing fields outside its authority.', focus: 'Define the permitted correction fields, evidence needed, approval owner, and customer update when the request remains under review.', practice: 'Repeat the requested correction in plain language and record the source. Do not overwrite the original fact to make the record look tidy.', measure: 'Review correction age, returned requests, duplicate changes, evidence gaps, and corrections later reversed.', handoff: 'Send disputed identity or historical-record questions to the protected owner for that record type.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-appointment-reschedule-handoff', title: 'Make appointment rescheduling handoffs easy to verify', excerpt: 'A rescheduling handoff keeps the requested time, confirmed availability, customer preference, and next owner together.', intro: 'Scheduling errors often begin when a request crosses a queue and the new owner sees only a vague note. A complete handoff preserves the original commitment and the choice still needed.', focus: 'Record the appointment identity, requested change, acceptable alternatives, source of availability, and confirmation status.', practice: 'Separate a request from a confirmed change. Tell the customer what is pending and do not present a tentative slot as reserved.', measure: 'Track duplicate bookings, missed confirmations, reschedule age, repeat contacts, and changes without a source record.', handoff: 'Escalate a conflict between availability and customer impact to the scheduler or service owner.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-case-ownership-reconciliation', title: 'Reconcile case ownership after queue changes', excerpt: 'A short ownership review prevents open customer work from becoming orphaned when queues, shifts, or responsibilities change.', intro: 'Queue changes can leave a case assigned to a person or group that no longer handles the work. Ownership reconciliation checks active records against the current service map.', focus: 'Compare open cases with the current queue, owner, next action, due point, and escalation path.', practice: 'Run the review at the boundary where responsibility changes. Preserve the original history and record the new owner rather than copying the case into an untraceable list.', measure: 'Track orphaned cases, reassignment age, missed deadlines, duplicate ownership, and cases returned after transfer.', handoff: 'Send an unresolved ownership conflict to the manager who controls the service boundary.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-customer-deadline-risk-review', title: 'Review customer deadlines before they become missed promises', excerpt: 'A deadline-risk review spots dependencies, missing approvals, and ownership gaps while a customer commitment can still be corrected.', intro: 'A due date is not enough if the work depends on another team or an approval nobody has requested. Review the path behind the date, not only the date itself.', focus: 'List the required action, dependency, approver, owner, customer impact, and earliest honest update point.', practice: 'Flag a deadline when a dependency has no owner or when the remaining time no longer matches the approved process. Do not hide risk by moving the due date without explanation.', measure: 'Track overdue work, dependency age, approval waits, customer updates, and commitments reset before failure.', handoff: 'Escalate deadline risk to the owner who can change the dependency or reset the customer expectation.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-contact-disposition-quality', title: 'Improve contact dispositions without chasing perfect labels', excerpt: 'A disposition is useful when it records the next business action and remains understandable to the person reviewing the case later.', intro: 'Disposition lists become unreliable when they mix outcomes, reasons, moods, and internal guesses. A smaller set tied to action gives managers better evidence.', focus: 'Define each disposition by observable outcome, required note, next owner, and the exception path for unclear contacts.', practice: 'Compare choices on the same sample with two reviewers. Remove values that do not change handling or reporting.', measure: 'Track blank dispositions, reviewer agreement, rework, uncategorized contacts, and labels with no next action.', handoff: 'Send a proposed code change to the owner of reporting definitions before it reaches the live form or queue.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-shift-handoff-summary', title: 'Write a shift handoff summary people can use', excerpt: 'A shift summary should show open customer impact, due actions, ownership, and decisions waiting for the next shift.', intro: 'A long shift note is not the same as a useful handoff. The next supervisor needs a short view of what changed, what is at risk, and who owns each next action.', focus: 'Organize the summary by urgent open work, due commitments, unresolved questions, and changes to queue conditions.', practice: 'Link each item to its source record and mark unknowns plainly. Remove background that the next shift does not need to decide or act.', measure: 'Review missed handoffs, duplicate investigation, delayed updates, stale items, and questions raised after the summary.', handoff: 'Escalate an item without an owner before the outgoing shift closes.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-script-change-approval', title: 'Approve call script changes with a visible evidence trail', excerpt: 'A script change needs a reason, owner, effective point, affected queue, and review evidence before it reaches customer conversations.', intro: 'Small wording changes can alter a promise, a verification step, or the answer to a common question. A change record makes those effects reviewable.', focus: 'Document the old wording, proposed wording, reason, authority, affected contact types, and effective date.', practice: 'Test the change against representative cases and the approval boundary. Keep prior wording available for audit rather than replacing history without explanation.', measure: 'Track returned questions, misroutes, correction notices, outdated copies, and changes made without approval.', handoff: 'Send a policy or customer-commitment change to the owner authorized to approve it.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-customer-data-minimization-notes', title: 'Keep customer notes useful and limited', excerpt: 'A field-level note standard protects continuity while reducing sensitive or irrelevant detail that can spread through later work.', intro: 'The best note is not the longest one. It contains enough verified context for the next action and leaves out secrets, unrelated history, and personal judgments.', focus: 'Define the facts required for the request, the action taken, the next owner, and the detail that must never enter the note.', practice: 'Show one good note and one overfilled note for each major contact type. Review exports and attachments as well as the main record.', measure: 'Sample relevance, unnecessary sensitive detail, missing next actions, repeated questions, and copied notes.', handoff: 'Route a disagreement about what may be recorded to the record or privacy owner.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-customer-follow-up-source-of-truth', title: 'Choose a source of truth for customer follow-up', excerpt: 'A follow-up source of truth keeps status, owner, deadline, and customer wording aligned across the people handling the case.', intro: 'Customers feel the cost of conflicting records when one screen says waiting and another says complete. A source-of-truth rule identifies which record controls each decision.', focus: 'Name the authoritative record for request status, customer promise, owner, schedule, and approved message.', practice: 'Define what happens when records disagree and who resolves the conflict. Do not silently choose the newest note if the system of record says otherwise.', measure: 'Track conflicting statuses, duplicate updates, stale owners, reopened cases, and corrections after customer contact.', handoff: 'Send a source conflict to the owner of the affected record type with both references and the decision needed.', published: '2026-08-14', updated: '2026-08-14' },
  { slug: 'call-center-customer-complaint-fact-record', title: 'Record complaint facts without turning them into findings', excerpt: 'A complaint record should preserve what the customer said, what can be verified, the requested remedy, and the owner of the review.', intro: 'A complaint needs careful separation between allegation, evidence, impact, and decision. That separation lets the reviewer act without making the first contact responsible for judging the case.', focus: 'Capture the customer’s stated concern, relevant dates, verified record facts, requested outcome, and unresolved question.', practice: 'Use neutral wording and mark what is unknown. Avoid promising a remedy before the authorized owner reviews the evidence.', measure: 'Review returned complaints, missing dates, repeat explanations, time to acknowledgment, and cases closed without a decision record.', handoff: 'Route the complaint through the designated escalation path when it concerns safety, privacy, legal interpretation, or a named staff member.', published: '2026-08-14', updated: '2026-08-14' },
];

const makePost = (draft: August14Draft, index: number): BlogPost => ({
  slug: draft.slug,
  title: draft.title,
  excerpt: draft.excerpt,
  minutes: 8 + (index % 4),
  keyword: draft.title,
  published: draft.published,
  updated: draft.updated,
  intro: draft.intro,
  sections: [
    { title: 'Start with the customer need', paragraphs: [draft.focus, `Write the request, the next action, and the finished record for ${draft.title.toLowerCase()}.`], items: ['Name the request', 'Show one useful example', 'State the review point', 'Name the owner'] },
    { title: 'Keep the first version narrow', paragraphs: [draft.practice, 'A limited first version makes unclear authority and missing information easier to find before the work expands.'] },
    { title: 'Protect the handoff', paragraphs: [draft.handoff, 'The contact team can follow approved wording, record permitted facts, and route uncertainty. Policy exceptions and sensitive decisions stay with the named owner.'], items: ['Record what happened', 'Keep sensitive detail limited', 'Name what remains', 'Escalate uncertainty'] },
    { title: 'Measure the outcome', paragraphs: [draft.measure, 'Pair volume with quality, timeliness, and ownership so a number leads to a practical decision.'] },
    { title: 'Close with an honest expectation', paragraphs: ['State the next confirmed action and its owner. If review is still needed, say so plainly instead of promising an outcome that has not been approved.'], items: ['Confirm the request', 'State the next step', 'Name the timing', 'Record the result'] },
    { title: 'Use consistent customer language', paragraphs: ['Give the team one sentence for the normal path and one for uncertainty. Keep the wording accurate to the authority available at the point of contact.'] },
    { title: 'Review the first sample', paragraphs: ['Look for missing fields, repeated questions, avoidable transfers, and conflicts between the written rule and the tool. Fix the rule before expanding it.'], items: ['Sample early work', 'Discuss exceptions', 'Update the example', 'Expand after review'] },
  ],
  controlTable: [
    { data: 'Normal request', agent: 'Follow the approved path and record the result', manager: 'Review samples and maintain the rule' },
    { data: 'Missing information', agent: 'Ask the approved question or pause', manager: 'Decide the safe fallback' },
    { data: 'Sensitive exception', agent: 'Do not complete it without approval', manager: 'Verify evidence and decide' },
    { data: 'Ownership conflict', agent: 'Keep the record unchanged and escalate', manager: 'Assign the owner' },
  ],
  scripts: [
    { situation: 'Normal path', text: 'I have recorded the request and will complete the approved next step.' },
    { situation: 'Needs review', text: 'This part needs review, so I will send it to the named owner.' },
    { situation: 'Unclear case', text: 'I do not want to guess. I will record what is known and confirm the next step.' },
  ],
  faqs: [{ question: 'What should happen first?', answer: draft.focus }, { question: 'What needs an owner?', answer: draft.handoff }, { question: 'What should be measured?', answer: draft.measure }],
  sources: [
    { name: 'Zero Trust Architecture, SP 800-207', organization: 'National Institute of Standards and Technology', date: 'August 2020', url: 'https://csrc.nist.gov/pubs/sp/800/207/final', note: 'Supports explicit access and decision boundaries.' },
    { name: 'ISO 18295-1 overview', organization: 'International Organization for Standardization', date: '2017', url: 'https://www.iso.org/standard/65137.html', note: 'Supports defined contact-centre processes and service outcomes.' },
  ],
  related: [{ label: 'Review customer support', href: '/services/customer-support' }, { label: 'Review operations support', href: '/services/operations-support' }, { label: 'Review reporting support', href: '/services/reporting-and-qa' }],
  banners: [{ label: 'Scope', title: 'Define the first queue', body: 'List the work, review points, and approval limits before adding coverage.', href: '/services/operations-support', cta: 'Review operations support' }, { label: 'Review', title: 'Use representative examples', body: 'Sample early work with a named owner and fix unclear rules quickly.', href: '/services/reporting-and-qa', cta: 'Review reporting support' }, { label: 'Handoff', title: 'Keep decisions with the owner', body: 'Document each escalation so the next manager can act without reconstructing the case.', href: '/services/customer-support', cta: 'Review customer support' }],
});

export const august14BlogBatch: readonly BlogPost[] = drafts.map(makePost);
