import type { BlogPost } from './data';

type Topic = {
  slug: string;
  title: string;
  excerpt: string;
  intro: string;
  focus: string;
  advice: string;
  measure: string;
  handoff: string;
};

const topics: readonly Topic[] = [
  { slug: 'call-center-service-level-recovery', title: 'How to recover a call center service level after a rough shift', excerpt: 'A practical recovery plan for missed calls, delayed callbacks, and the next manager review.', intro: 'Service-level recovery is a customer promise exercise, not a hunt for a single bad number. The team needs a clear picture of demand, abandoned work, and the decisions that can safely restore coverage.', focus: 'Start by separating new demand from aging work. Count calls that still need a response, callbacks that were promised, and contacts that can be closed without another customer touch.', advice: 'Set a temporary queue owner, publish the next review time, and give the team one short priority order. Avoid changing every script at once while the queue is unstable.', measure: 'Track aged contacts, first response time, recovered promises, and the number of cases waiting on a manager.', handoff: 'Escalate when the recovery plan would change a customer promise, move work across queues, or require access beyond the approved role.' },
  { slug: 'call-center-call-reason-taxonomy', title: 'Design a call reason taxonomy that supervisors can actually use', excerpt: 'Build call reason labels that improve routing and reporting without making conversations feel scripted.', intro: 'A call reason taxonomy should explain why a customer contacted the business and what work remains. It should be small enough for consistent use and detailed enough to support staffing and coaching decisions.', focus: 'Begin with the decisions the labels must support: routing, follow-up, quality review, or trend analysis. Remove labels that never change an action.', advice: 'Use plain names, one primary reason, and a secondary outcome only when it adds meaning. Give team members examples for near-neighbor reasons so the taxonomy is not guessed.', measure: 'Review uncategorized contacts, reassignment rate, label agreement in samples, and whether reports lead to a named action.', handoff: 'Send conflicting definitions to the taxonomy owner instead of letting each shift invent a new label.' },
  { slug: 'call-center-customer-verification-script', title: 'Write a customer verification script that protects the conversation', excerpt: 'A bounded verification script helps representatives confirm identity without exposing unnecessary account details.', intro: 'Verification should make the safe path obvious to the person handling the contact. It should explain what can happen before verification, what check is required, and when the request must stop.', focus: 'List low-risk information that can be discussed before verification and separate it from account changes, disclosures, and payment actions.', advice: 'Keep the language neutral and consistent. Never coach a caller through hidden answers, and never treat a familiar voice or known phone number as complete proof by itself.', measure: 'Sample verification attempts for the approved question set, result, time, and action taken after the check.', handoff: 'Escalate mismatches, repeated failed checks, and requests for exceptions to the account owner.' },
  { slug: 'call-center-call-recording-retention', title: 'Set call recording retention rules your support team can follow', excerpt: 'Turn recording retention into a clear operational rule with ownership, review limits, and documented exceptions.', intro: 'Call recordings are useful only when the business knows why they are kept, who may access them, and when they should be removed. A short operational rule reduces accidental retention and confusing requests.', focus: 'Define the purpose of recording, the approved retention period, the system of record, and the owner for deletion or legal holds.', advice: 'Keep access narrower than general ticket access. Mask or avoid sensitive details when policy permits, and document an exception rather than quietly keeping everything.', measure: 'Review access logs, deletion completion, exception age, and samples for unnecessary sensitive content.', handoff: 'Route legal, privacy, or customer-record requests to the designated owner; representatives should not make policy interpretations.' },
  { slug: 'call-center-knowledge-base-ownership', title: 'Give a call center knowledge base a real owner', excerpt: 'A knowledge base stays useful when updates, stale answers, and frontline questions have named owners.', intro: 'A knowledge base is part of the customer experience because representatives use it while a customer is waiting. Ownership means someone can approve wording, retire unsafe guidance, and resolve conflicts with policy.', focus: 'Map each high-volume topic to an owner, review date, source document, and escalation route for unanswered questions.', advice: 'Put the answer before the explanation, show effective dates, and keep old versions available only where the business needs an audit trail.', measure: 'Watch search misses, article feedback, repeat questions, outdated pages, and corrections found in quality samples.', handoff: 'Escalate an answer conflict with the policy owner and pause the uncertain response rather than choosing the more convenient wording.' },
  { slug: 'call-center-callback-promise-tracking', title: 'Track callback promises so they do not disappear between shifts', excerpt: 'Use a simple callback record to protect promised times, ownership, and customer context.', intro: 'A callback promise creates work that is easy to lose when the original representative leaves the queue. The record must carry the promised window, approved channel, reason, and next owner.', focus: 'Capture the customer time zone, best permitted channel, promised window, and the exact action expected on the callback.', advice: 'Use aging views and a backup owner. If the promise can no longer be met, update the record and route a new customer message through the approved process.', measure: 'Report on on-time callbacks, missed promises, duplicate attempts, and records without an owner.', handoff: 'Escalate missed high-impact promises and any callback where identity or contact permission is uncertain.' },
  { slug: 'call-center-complaint-triage', title: 'Build a complaint triage path that preserves customer context', excerpt: 'A complaint path can move urgent issues quickly while keeping the original facts and promised follow-up intact.', intro: 'Complaint triage is not a race to close a ticket. It is a way to identify harm, urgency, ownership, and the next safe response while preserving what the customer actually reported.', focus: 'Separate safety, legal, privacy, payment, service failure, and general dissatisfaction triggers so each has a clear owner.', advice: 'Let the representative acknowledge the concern, capture the facts, and explain the next step without promising an outcome the manager has not approved.', measure: 'Review time to acknowledgment, correct routing, repeat contacts, unresolved promises, and quality of the complaint record.', handoff: 'Escalate safety, legal, privacy, and high-impact account concerns immediately through the named path.' },
  { slug: 'call-center-appointment-reminder-quality', title: 'Improve appointment reminder quality without over-contacting customers', excerpt: 'A reminder workflow should confirm the appointment while respecting channel, timing, and customer preferences.', intro: 'Appointment reminders work when the customer can identify the appointment, understand what action is needed, and reach the right owner if something is wrong. More messages do not automatically create better attendance.', focus: 'Define the reminder window, permitted channels, minimum appointment details, and the response path for rescheduling or missing information.', advice: 'Use the customer record as the source of truth and keep reminders neutral. Do not disclose sensitive details in an unverified voicemail or message.', measure: 'Track delivered reminders, confirmations, reschedules, no-shows, and contacts needing manual review.', handoff: 'Send schedule conflicts, identity mismatches, and exceptions outside the written reschedule rule to the appointment owner.' },
  { slug: 'call-center-after-call-work-design', title: 'Reduce after-call work with a better note design', excerpt: 'Short, structured notes help the next person understand the contact without turning documentation into a second conversation.', intro: 'After-call work should preserve the customer outcome and the next action. When notes ask for every possible detail, representatives rush them; when they ask for too little, the next shift repeats the work.', focus: 'Define the minimum fields needed for disposition, promise, owner, and unresolved question. Use examples for common edge cases.', advice: 'Write notes in the order the next person needs them: result, action, owner, and deadline. Keep interpretation separate from observed facts.', measure: 'Sample notes for completeness, rework, duplicate contacts, and time spent documenting regular calls.', handoff: 'Escalate a note that contains a policy conflict or missing customer-impact detail rather than filling the gap with an assumption.' },
  { slug: 'call-center-queue-transfer-design', title: 'Design queue transfers that do not make customers repeat themselves', excerpt: 'A transfer policy can protect context, ownership, and customer effort across specialized queues.', intro: 'Transfers are sometimes necessary, but an uncontrolled transfer turns the customer into the handoff mechanism. The receiving queue needs enough context to act and a clear reason for the move.', focus: 'Define transfer triggers, required context, warm-transfer rules, and what happens when the receiving queue is unavailable.', advice: 'Use one concise transfer summary and confirm the receiving owner before releasing the customer. Do not transfer simply to remove an aging contact from a view.', measure: 'Watch repeat explanations, transfer acceptance, blind-transfer rate, abandoned transfers, and resolution after transfer.', handoff: 'Escalate a transfer loop or unavailable owner to the queue supervisor for a routing decision.' },
  { slug: 'call-center-peak-demand-playbook', title: 'Prepare a peak-demand playbook for outsourced call center coverage', excerpt: 'A peak plan gives supervisors clear choices when demand rises faster than ordinary staffing can absorb.', intro: 'Peak demand exposes hidden assumptions about queue priority, overflow, manager availability, and customer promises. A useful playbook names the trigger and the safe response before the pressure arrives.', focus: 'Define volume or wait-time signals, the first queue to protect, the overflow option, and the person who can activate the plan.', advice: 'Scale the response in steps: protect urgent work, publish a realistic promise, use approved overflow, and review the decision at a fixed time.', measure: 'Track wait time, abandonment, overflow accuracy, promise changes, and recovery time after the peak.', handoff: 'Escalate when the safe response requires a staffing change, new customer promise, or unapproved system access.' },
  { slug: 'call-center-multilingual-call-handoff', title: 'Make multilingual call handoffs clearer for customers and teams', excerpt: 'A language handoff works best when intent, sensitive terms, and ownership survive the transfer.', intro: 'Language support is more than finding someone who speaks the requested language. The handoff must preserve what the customer needs, what has already been verified, and which decision remains open.', focus: 'Record the customer intent, preferred language, approved interpretation route, and next owner without copying unnecessary personal information.', advice: 'Use the source wording for names, dates, amounts, and policy terms. Pause when a translation could change a legal, payment, or safety meaning.', measure: 'Sample handoffs for missing context, repeat explanations, correction requests, and unresolved language needs.', handoff: 'Route ambiguity in a sensitive term to the qualified owner instead of improvising a definitive answer.' },
  { slug: 'call-center-knowledge-article-feedback', title: 'Turn frontline knowledge article feedback into useful changes', excerpt: 'A lightweight feedback loop helps supervisors separate missing content from unclear wording and policy conflicts.', intro: 'Frontline feedback is valuable when it leads to a decision. A pile of vague comments does not tell the owner whether an article needs an example, a correction, or retirement.', focus: 'Ask the reviewer to identify the search, the answer used, the problem observed, and the customer or workflow impact.', advice: 'Triage feedback into clarity, accuracy, missing scenario, access issue, or policy conflict. Give each category a named next step.', measure: 'Track repeated feedback, time to decision, article corrections, search failures, and feedback that remains unowned.', handoff: 'Send policy conflicts to the policy owner and block unsafe wording until the conflict is resolved.' },
  { slug: 'call-center-queue-aging-review', title: 'Run a queue aging review that leads to decisions', excerpt: 'An aging review should expose stuck work, broken promises, and ownership gaps in a format a supervisor can act on.', intro: 'A queue can look busy without showing which contacts are at risk. Aging review makes time visible and pairs it with the reason a case has not moved.', focus: 'Group work by age, impact, current owner, blocked dependency, and promised next action rather than by raw ticket count alone.', advice: 'Use a short exception list for the manager meeting. Close items with evidence, reassign genuine ownership gaps, and document why other work remains open.', measure: 'Report oldest open work, age by reason, overdue promises, reassignment count, and unresolved blockers.', handoff: 'Escalate cases that are legally, financially, or operationally sensitive and have crossed the defined age threshold.' },
  { slug: 'call-center-customer-contact-preferences', title: 'Keep customer contact preferences accurate across channels', excerpt: 'A contact-preference workflow protects customer choice while keeping the service team aligned on the current record.', intro: 'A preference change can affect calls, messages, reminders, and future outreach. The team needs one approved record and a clear distinction between service contact and other communication purposes.', focus: 'Capture the requested channel, effective time, source interaction, and any scope limitation that the customer stated.', advice: 'Update the authorized system promptly and confirm what changed in plain language. Do not infer a broader preference from a narrow request.', measure: 'Audit update accuracy, delayed changes, conflicting records, repeat requests, and contacts sent through a disallowed channel.', handoff: 'Route legal interpretation, disputed consent, and conflicting records to the designated owner.' },
  { slug: 'call-center-disconnected-call-recovery', title: 'Recover a disconnected call without losing the safe next step', excerpt: 'A dropped call process keeps the last confirmed action, callback rules, and customer impact visible.', intro: 'When a call disconnects, the team may know only part of the request. Recovery should preserve what was confirmed, use an approved contact route, and avoid disclosing account details to an unverified person.', focus: 'Record the last confirmed step, permitted callback channel, retry rule, customer impact, and owner for the next attempt.', advice: 'Use the approved callback path and a neutral message. If the contact cannot be verified, leave only the permitted minimum and route the case for review.', measure: 'Track successful recoveries, repeat attempts, unresolved disconnects, verification failures, and promises made before the call ended.', handoff: 'Escalate high-impact cases, identity mismatches, and calls where the next action is unclear.' },
  { slug: 'call-center-customer-record-correction', title: 'Handle customer record corrections without overwriting the evidence', excerpt: 'A correction path should fix inaccurate data while keeping the original request, authority, and audit trail understandable.', intro: 'Customer records need correction, but an unchecked edit can erase the reason a value changed or combine two different people. A bounded process makes the correction reversible and reviewable.', focus: 'Separate simple field corrections from identity, ownership, and history changes that require approval.', advice: 'Record the source of the correction and update only permitted fields. Never merge or delete records based on name or phone similarity alone.', measure: 'Review correction accuracy, reversals, duplicate records, approval compliance, and changes lacking a source note.', handoff: 'Escalate identity mismatch, record merge, privacy, and historical-data questions to the record owner.' },
  { slug: 'call-center-supervisor-handoff-notes', title: 'Write supervisor handoff notes that shorten the next decision', excerpt: 'A concise supervisor note gives the next owner facts, risk, requested decision, and deadline in one place.', intro: 'A supervisor handoff is successful when the next owner can decide without reconstructing the conversation. It should distinguish observed facts from the representative question and the requested approval.', focus: 'Use a consistent order: case, customer impact, facts, action already taken, decision needed, deadline, and owner.', advice: 'Keep the note short and link to the protected source record when more detail is needed. Mark unknowns rather than guessing what happened.', measure: 'Sample handoffs for completeness, decision turnaround, duplicate questions, and cases returned for missing information.', handoff: 'Escalate urgent risk through the immediate channel and use the normal note for the durable record.' },
  { slug: 'call-center-service-recovery-language', title: 'Choose service-recovery language that does not overpromise', excerpt: 'Clear recovery wording acknowledges the problem while keeping commitments inside the team’s actual authority.', intro: 'Customers need a credible next step after a missed service moment. Representatives can acknowledge impact and explain the process without promising a refund, deadline, or exception that only a manager may approve.', focus: 'Write approved language for acknowledgment, current action, expected update, and escalation without claiming an outcome that is not confirmed.', advice: 'Use specific facts and a realistic update window. If the team does not yet know the answer, say what will be checked and who owns the next update.', measure: 'Review promise accuracy, repeat contacts, escalations caused by wording, and customers who received no follow-up.', handoff: 'Send compensation, policy exception, legal, safety, and executive complaints to the authorized owner.' },
  { slug: 'call-center-inbox-aging-controls', title: 'Keep a shared support inbox from becoming an invisible backlog', excerpt: 'Ownership, status, and aging controls make shared inbox work visible across shifts and channels.', intro: 'A shared inbox is a queue even when it has no queue screen. Without clear status and ownership, messages are archived, answered twice, or left waiting for a decision no one can see.', focus: 'Define the statuses, owner, backup owner, aging threshold, and rule for sensitive attachments or customer data.', advice: 'Every active message needs a next action. Restrict deletion and export rights, and use a manager view for items that are blocked or overdue.', measure: 'Track oldest message, unassigned items, duplicate replies, overdue actions, and sensitive messages without an owner.', handoff: 'Escalate an item when the requested action changes policy, requires restricted access, or has crossed its customer promise.' },
  { slug: 'call-center-qa-critical-error-taxonomy', title: 'Create a critical-error taxonomy for call center quality reviews', excerpt: 'A critical-error taxonomy helps quality reviewers act consistently on privacy, payment, safety, and promise failures.', intro: 'Quality reviews become useful when serious errors are defined separately from preferences about style. The taxonomy should identify the customer risk, immediate containment, and final owner.', focus: 'Start with observable categories such as unauthorized disclosure, unsafe payment handling, missed identity checks, harmful advice, and inaccurate commitments.', advice: 'Give each category a required action and evidence rule. Do not let a reviewer invent a new severity level during a difficult sample.', measure: 'Report critical errors by category, repeat rate, containment time, reviewer agreement, and open corrective actions.', handoff: 'Route critical errors immediately to the named manager or incident owner; coaching notes alone are not enough.' },
  { slug: 'call-center-queue-ownership-map', title: 'Map queue ownership before outsourcing another call center task', excerpt: 'A queue ownership map clarifies scope, decision rights, backup coverage, and where escalations go.', intro: 'Outsourced coverage works better when ownership is explicit. The representative can handle the defined service work, while the client-side owner remains visible for policy, staffing, and exception decisions.', focus: 'Document scope, systems, hours, primary owner, backup, approval limits, and the evidence required at handoff.', advice: 'Keep the map close to the workflow and review it after a queue, tool, or policy changes. A named owner should be able to answer an unresolved question during every covered shift.', measure: 'Track unowned escalations, decision age, incorrect routing, backup use, and changes made without an owner review.', handoff: 'Escalate a missing owner or conflicting responsibility before adding volume to the queue.' },
  { slug: 'call-center-pilot-exit-criteria', title: 'Set pilot exit criteria before expanding outsourced call center coverage', excerpt: 'Evidence-based exit criteria help a team expand, revise, pause, or stop a pilot with less guesswork.', intro: 'A pilot should end with a decision, not simply with the calendar. Exit criteria turn early work into evidence about quality, safe handoffs, access, customer impact, and manager capacity.', focus: 'Define the minimum evidence for expansion and the findings that require revision, pause, or stop before launch.', advice: 'Review representative work, unresolved exceptions, quality samples, access findings, customer promises, and the owner’s ability to review the next stage.', measure: 'Use a small decision pack with quality, timeliness, escalation, rework, and open-risk measures.', handoff: 'Escalate a blocked decision to the accountable owner rather than quietly treating missing evidence as approval.' },
];

const makeSections = (t: Topic): BlogPost['sections'] => [
  { title: 'Start with the decision the workflow must support', paragraphs: [t.focus, `Write the starting signal, the permitted action, and the finished record for ${t.title.toLowerCase()}. This gives the person doing the work a usable boundary instead of a vague target.`], items: ['Name the queue or record', 'Show one good completed example', 'List the fields and response window', 'Name the reviewer and escalation owner'] },
  { title: 'Keep the first version narrow', paragraphs: [t.advice, 'Use one channel or task type at first. A small sample review reveals missing inputs and unclear authority before the problem is spread across every shift.'] },
  { title: 'Make the authority line visible', paragraphs: ['A representative can collect facts, use approved language, update permitted fields, and route work. A manager keeps policy exceptions, sensitive decisions, access changes, and unresolved conflicts.', `For this topic, the practical boundary is simple: ${t.handoff}`], items: ['Follow the approved workflow', 'Record the evidence needed for review', 'Pause when authority is unclear', 'Send the case to the named owner'] },
  { title: 'Measure outcomes a supervisor can act on', paragraphs: [`A useful review for ${t.title.toLowerCase()} combines volume with quality and ownership. ${t.measure}`, 'Numbers should lead to a decision, such as changing an example, reassigning an owner, or narrowing the scope.'] },
  { title: 'Protect context during handoffs', paragraphs: [`Every handoff should state what happened, what remains, and who owns the next action. ${t.handoff}`, 'Keep secrets and unnecessary customer details out of general notes. Point the owner to the approved source record when more evidence is required.'] },
  { title: 'Use language that keeps expectations honest', paragraphs: [`Give the team one sentence for the normal path and one sentence for uncertainty. In ${t.title.toLowerCase()}, the representative should acknowledge the request, state the approved next step, and pause before making an unapproved commitment.`] },
  { title: 'Review the first sample and then improve', paragraphs: ['Review early work on a fixed schedule with the named owner. Look for repeated questions, missing fields, avoidable transfers, and cases where the written rule conflicts with the tool.', `Once the first review is clean, expand carefully. Keep a dated note of what changed in the ${t.title.toLowerCase()} workflow and why.`], items: ['Sample early work', 'Discuss exceptions with the owner', 'Update the checklist and example', 'Expand only after quality is stable'] },
];

export const august13BlogBatch: readonly BlogPost[] = topics.slice(0, 22).map((t, index) => ({
  slug: t.slug,
  title: t.title,
  excerpt: t.excerpt,
  minutes: 8 + (index % 5),
  keyword: t.title,
  published: '2026-08-13',
  updated: '2026-08-13',
  intro: t.intro,
  sections: makeSections(t),
  controlTable: [
    { data: 'Standard case', agent: 'Follow the written path and record the result', manager: 'Review samples and maintain the rule' },
    { data: 'Missing information', agent: 'Ask the approved question or pause', manager: 'Decide the safe fallback' },
    { data: 'Sensitive exception', agent: 'Do not complete it without approval', manager: 'Verify evidence and decide' },
    { data: 'Ownership conflict', agent: 'Keep the record unchanged and escalate', manager: 'Assign the owner and document the rule' },
  ],
  scripts: [
    { situation: 'Normal path', text: 'I have recorded the request and will complete the approved next step.' },
    { situation: 'Needs review', text: 'I have the details I need. This part requires review, so I will send it to the named owner.' },
    { situation: 'Unclear case', text: 'I do not want to guess. I will record what is known and confirm the next step.' },
  ],
  faqs: [
    { question: 'What should happen first?', answer: t.focus },
    { question: 'What should remain with a manager?', answer: t.handoff },
    { question: 'What should the first review measure?', answer: t.measure },
  ],
  sources: [{ name: 'Zero Trust Architecture, SP 800-207', organization: 'National Institute of Standards and Technology', date: 'August 2020', url: 'https://csrc.nist.gov/pubs/sp/800/207/final', note: 'Supports explicit access and decision boundaries.' }, { name: 'ISO 18295-1 overview', organization: 'International Organization for Standardization', date: '2017', url: 'https://www.iso.org/standard/65137.html', note: 'Supports defined contact-centre processes and service outcomes.' }],
  related: [{ label: 'Review customer support', href: '/services/customer-support' }, { label: 'Review operations support', href: '/services/operations-support' }, { label: 'Review reporting and QA', href: '/services/reporting-and-qa' }],
  banners: [{ label: 'Scope', title: 'Define the first queue', body: 'List tasks, tools, review points, and approval limits before adding coverage.', href: '/services/customer-support', cta: 'Review customer support' }, { label: 'Review', title: 'Use representative examples', body: 'Sample early work with a named owner and fix unclear rules quickly.', href: '/services/reporting-and-qa', cta: 'Review reporting support' }, { label: 'Handoff', title: 'Keep decisions visible', body: 'Record the next owner whenever the work crosses an authority line.', href: '/services/operations-support', cta: 'Review operations support' }],
}));
