import type {BlogPost} from './data';

type Topic={slug:string;title:string;excerpt:string;image:string;opening:string;trigger:string;record:string;boundary:string;test:string};

const topics:readonly Topic[]=[
 {slug:'outsourced-call-center-missed-transfer-recovery-log',title:'When a Call Transfer Fails: Build a Recovery Log',excerpt:'A failed transfer needs a clear owner and a promised next step before the customer disappears between queues.',image:'/blog-aug20/outsourced-call-center-escalation-routing-map.png',opening:'The line dropped after the introduction. The first queue assumed the specialist had answered, while the specialist never received the call.',trigger:'Open the log whenever a transfer disconnects, returns, rings without acceptance, or reaches the wrong destination.',record:'Record the customer purpose, transfer time, destination, last confirmed owner, contact permission, promised follow-up, and the person who accepted recovery.',boundary:'Representatives can restore contact and repeat approved information. Supervisors decide routing exceptions, while client owners keep authority over remedies and policy.',test:'Sample failed transfers alongside the next customer contact. Check whether the recovery happened within the stated window and addressed the original need.'},
 {slug:'call-center-after-hours-message-ownership-routine',title:'Who Owns the After-Hours Message?',excerpt:'An after-hours message is useful only when the morning team can see the promise, priority basis, and accepting owner.',image:'/blog-aug21/outsourced-call-center-after-hours-escalation.webp',opening:'A careful overnight note can still fail if it lands in an inbox nobody checks at shift change.',trigger:'Use the routine for every message taken outside the receiving team\'s staffed hours.',record:'Keep the contact reason, safe callback details, customer time zone, urgency evidence, prohibited disclosures, target queue, due time, and acknowledgment event.',boundary:'Overnight staff may apply the approved priority map. They cannot invent an emergency category or promise an outcome controlled by the client.',test:'Trace routine, urgent, and misrouted messages through the first staffed hour. Count accepted handoffs separately from messages merely sent.'},
 {slug:'outsourced-call-center-customer-correction-readback',title:'Use a Readback Before Saving Customer Corrections',excerpt:'A short readback catches wrong digits and misunderstood spellings before a customer correction enters several systems.',image:'/blog-aug23/outsourced-call-center-customer-identity-check.png',opening:'The customer corrects one digit in a phone number, but the representative hears another. The mistake then travels into reminders and callbacks.',trigger:'Use a readback after the approved identity check and before saving a customer-supplied correction.',record:'Record the field changed, verification result, customer-confirmed value, source channel, time, systems updated, confirmation sent, and unresolved mismatch.',boundary:'Representatives may change only approved fields. Ownership, protected identity data, disputed records, and access changes stay with the authorized client role.',test:'Review reversed corrections, undelivered confirmations, and repeat contacts. Compare the recording with the saved value without copying restricted data into the audit.'},
 {slug:'call-center-consult-hold-checkback-standard',title:'Set a Checkback Standard for Consult Holds',excerpt:'Customers waiting during an internal consult need a truthful update and an escape route before the answer arrives.',image:'/blog-aug20/outsourced-call-center-peak-coverage-trigger.png',opening:'An internal question can take five minutes even when the representative expected thirty seconds. Silence makes that ordinary delay feel abandoned.',trigger:'Start the checkback clock whenever the customer waits while a representative consults another person or system.',record:'Track the hold start, question sent, consulted owner, promised checkback, each update, customer preference, approved alternative, and return outcome.',boundary:'The representative can offer approved choices and explain what remains unknown. Managers own exceptions and customer remedies.',test:'Listen around the checkback threshold. Verify that updates contain new, accurate context and that disconnected contacts enter the recovery path.'},
 {slug:'outsourced-call-center-reopened-ticket-context-check',title:'Check the Context Before Working a Reopened Ticket',excerpt:'A reopened ticket should preserve the customer\'s original issue while making the new reason and current owner obvious.',image:'/blog-aug20/outsourced-call-center-channel-switch-continuity.png',opening:'A ticket reopens after the customer replies "still broken." Without the earlier decision and promise, the next person starts the investigation again.',trigger:'Run the check when a closed or pending record returns to active work.',record:'Preserve the original request, prior resolution claim, customer\'s new information, reopening reason, current evidence, next action, owner, and due time.',boundary:'Queue staff may resume approved troubleshooting. A manager decides disputed closure, compensation, or a policy exception.',test:'Sample repeat reopenings and tickets that changed teams. Ask a reviewer to identify the remaining problem using only the record and approved sources.'},
 {slug:'call-center-obsolete-script-quarantine',title:'Quarantine an Obsolete Call Center Script',excerpt:'Old wording should leave the live workspace without erasing the evidence needed to understand earlier customer contacts.',image:'/blog-aug21/outsourced-call-center-knowledge-change-notice.webp',opening:'A new script does not help when the old version still appears first in search results and personal bookmarks.',trigger:'Quarantine a script when its owner replaces, suspends, or limits the approved wording.',record:'Keep the retired version, replacement link, decision owner, effective time, affected queues, required acknowledgment, exception path, and archive location.',boundary:'Representatives use the active version and report conflicts. Only the content owner can approve wording or restore a retired script.',test:'Search from the tools agents actually use. Test bookmarks, copied snippets, offline files, and shift handoffs for stale wording.'},
 {slug:'outsourced-call-center-queue-overflow-return-rule',title:'Write a Return Rule for Overflow Calls',excerpt:'Overflow coverage needs a defined way to return unresolved work without resetting age or dropping the customer promise.',image:'/blog-aug20/outsourced-call-center-queue-priority-calibration.png',opening:'Overflow keeps the phone answered, but the harder cases often circle back after the primary queue is already busy again.',trigger:'Apply the return rule when overflow staff reach a task, permission, or knowledge limit.',record:'Record the original arrival, customer need, completed work, boundary reached, evidence collected, promised update, destination, and accepting owner.',boundary:'Overflow staff complete the documented lane. Primary supervisors own exceptions, specialist routing, and changes to priority.',test:'Review returned work by reason and age. Confirm that the original clock and customer promise survive the routing event.'},
 {slug:'call-center-account-note-opinion-cleanup',title:'Remove Opinions From Customer Account Notes',excerpt:'Account notes should preserve observable facts and customer statements without turning a representative\'s impression into lasting history.',image:'/blog-aug21/outsourced-call-center-complaint-deescalation-record.webp',opening:'A label such as "difficult caller" tells the next representative almost nothing, yet it can shape every later interaction.',trigger:'Review a note when it contains a judgment, unsupported motive, informal diagnosis, or label unrelated to the next permitted action.',record:'Keep the customer\'s stated concern, observable event, verified facts, action taken, open question, owner, and next review point.',boundary:'Representatives may correct their notes under the approved audit rule. Managers and privacy owners handle disputed history, retention, and protected records.',test:'Use paired reviewers to separate facts from conclusions. Check whether the cleaned note still supports the next authorized action.'},
 {slug:'outsourced-call-center-callback-number-confirmation',title:'Confirm the Callback Number Without Exposing the Account',excerpt:'A callback-number check should confirm a safe contact path without reading private account details to an unverified caller.',image:'/blog-aug21/outsourced-call-center-callback-promise-ledger.webp',opening:'Reading a full stored number feels efficient, but it can disclose account information before the caller has cleared the required check.',trigger:'Use the confirmation step whenever a callback promise depends on a customer-supplied or stored number.',record:'Record the source of the number, masked confirmation, permitted purpose, local time window, channel consent, verification state, owner, and expiry.',boundary:'Representatives follow the approved confirmation wording. Identity, consent, and restricted-account exceptions go to the client owner.',test:'Sample changed numbers, shared numbers, failed verification, and unreachable callbacks. Compare the promise record with the actual attempt.'},
 {slug:'call-center-escalation-acknowledgment-clock',title:'Start the Escalation Clock at Acknowledgment',excerpt:'Sending an escalation is not the same as having an owner; measure the time until someone accepts the next decision.',image:'/blog-aug20/outsourced-call-center-escalation-routing-map.png',opening:'The ticket shows an instant escalation, but nobody reads it for forty minutes. A sent timestamp hides the period when the work had no owner.',trigger:'Start the clock when frontline authority ends and stop it only at a defined acknowledgment event.',record:'Capture the trigger, impact, sending time, destination, fallback deadline, accepting person, acknowledgment time, decision due time, and customer update.',boundary:'Frontline staff send complete evidence and use the fallback. Managers define severity, response targets, and policy decisions.',test:'Compare sent, delivered, viewed, and accepted events. Include items returned for missing information and escalations still open at cutoff.'},
 {slug:'outsourced-call-center-disposition-evidence-spot-check',title:'Spot-Check the Evidence Behind Call Dispositions',excerpt:'A disposition code should agree with what happened on the contact and what remains open for the customer.',image:'/blog-aug20/outsourced-call-center-qa-sample-selection.png',opening:'A dashboard can show hundreds of resolved calls while the notes describe voicemails, transfers, and promises still waiting for action.',trigger:'Run a spot-check on a fixed sample after each reporting period and whenever one disposition shifts unexpectedly.',record:'Compare the selected code with the contact event, note, customer promise, ownership state, follow-up task, and eventual outcome.',boundary:'Reviewers report mismatches and definition gaps. Managers change taxonomy, coaching, or reporting rules.',test:'Blind the reviewer to agent identity where practical. Include ordinary records, rare codes, short contacts, and records marked complete after an attempt.'},
 {slug:'call-center-shift-end-open-promise-sweep',title:'Sweep Open Customer Promises Before Shift End',excerpt:'A shift should close with every unresolved customer promise assigned, due, and visible to the next team.',image:'/blog-aug20/outsourced-call-center-absence-handoff-protocol.png',opening:'The last ten minutes of a shift are where small promises vanish: a callback after lunch, an email after approval, or a status check when a system returns.',trigger:'Run the sweep before handoff and again when an unplanned early departure changes ownership.',record:'List each open promise, customer purpose, source contact, due time and zone, dependency, last action, next action, accepting owner, and fallback.',boundary:'Representatives reconcile their own records and flag gaps. Supervisors assign unowned work and decide capacity tradeoffs.',test:'Check the next shift\'s first actions against the handoff. Review promises found late, accepted without context, or closed without a customer-facing result.'},
] as const;

const sources=[
 {name:'Cybersecurity Framework 2.0',organization:'NIST',date:'February 2024',url:'https://www.nist.gov/cyberframework',note:'Governance, ownership, and review context.'},
 {name:'Privacy Framework',organization:'NIST',date:'January 2020',url:'https://www.nist.gov/privacy-framework',note:'Purpose and data-minimization context.'},
 {name:'ISO 18295-1:2017 Customer contact centres',organization:'International Organization for Standardization',date:'July 2017',url:'https://www.iso.org/standard/64739.html',note:'Customer-contact process context.'},
] as const;

const makePost=(t:Topic,i:number):BlogPost=>({slug:t.slug,title:t.title,excerpt:t.excerpt,keyword:t.title,published:'2026-09-07',updated:'2026-09-07',minutes:8+i%4,heroImage:t.image,intro:t.opening,sections:[
 {title:'When to use this routine',paragraphs:[t.trigger,'Define the event in plain language so two shifts start the same process from the same evidence.']},
 {title:'Build the working record',paragraphs:[t.record,'Use approved fields and link the source record. Mark unknown facts as unknown instead of filling the gap from memory.']},
 {title:'Keep authority visible',paragraphs:[t.boundary,'The handoff should name the person who can decide the exception and the safe action while the decision is pending.']},
 {title:'Test it with real work',paragraphs:[t.test,'Use a fixed period and preserve records still open at the cutoff. A small, well-defined sample is more useful than a large sample with shifting rules.']},
 {title:'Review and repair',paragraphs:['Separate a missed step from a missing rule, unavailable owner, broken tool, or conflicting source. Repair the operating cause before expanding the lane.','Track the customer-facing result as well as internal activity. A sent note, changed code, or routed ticket does not by itself prove that the promise was completed.']},
 {title:'Make the handoff usable',paragraphs:['Write for the next trained person who has the approved source but did not hear the original contact. Keep the customer need, verified state, open decision, and next permitted action close together.']},
 {title:'Set a review cadence',paragraphs:['Review early samples while the decision owner is available. After the routine is stable, keep a smaller recurring sample and reopen the design when tools, permissions, or customer promises change.']},
],faqs:[{question:'Who should own an exception?',answer:'The client should name the role with authority before live work begins and provide a fallback for uncovered hours.'},{question:'What should the first audit include?',answer:'Use ordinary work, one boundary case, one handoff, and every item still unresolved at the cutoff.'}],sources,related:[{label:'Browse call center research',href:'/research'},{label:'Review operations support',href:'/services/operations-support'},{label:'Discuss the workflow',href:'/contact-us'}],banners:[{label:'Scope',title:'Write the operating boundary',body:'Define the trigger, record, owner, and fallback before adding volume.',href:'/contact-us',cta:'Discuss the workflow'},{label:'Pilot',title:'Test one real queue',body:'Review a small sample with the decision owner available.',href:'/services/operations-support',cta:'Review operations support'},{label:'Review',title:'Repair the recurring gap',body:'Use contact evidence to fix the source, ownership, or fallback rule.',href:'/blog',cta:'Read more guides'}]});

export const september7BlogBatch:readonly BlogPost[]=topics.map(makePost);
