import type {BlogPost} from './data';

type Topic={slug:string;title:string;excerpt:string;image:string;situation:string;routine:string;record:string;limit:string;audit:string};

const topics:readonly Topic[]=[
  {slug:'call-center-voicemail-duplicate-prevention',title:'Stop Duplicate Work From Voicemail Follow-Ups',excerpt:'A voicemail and a later live call should become one visible customer need, not two competing promises.',image:'/blog-aug23/outsourced-call-center-crm-duplicate-prevention.png',situation:'A customer leaves a message, then reaches the live queue before the message is reviewed. Two representatives begin the same work and offer different next steps.',routine:'Search the approved contact fields before creating a new task. When a likely match appears, confirm the customer need and attach the newer contact to the existing record.',record:'Keep the voicemail time, live-contact time, matching basis, current owner, newest promise, superseded task, and any uncertainty about whether the requests are the same.',limit:'Frontline staff may link records under the approved matching rule. They should not merge disputed identities, restricted accounts, or clearly different requests.',audit:'Sample linked and unlinked same-day contacts. Check whether the surviving record preserves the latest customer instruction and one accountable owner.'},
  {slug:'outsourced-call-center-translation-request-handoff',title:'Build a Safe Handoff for Translation Requests',excerpt:'Language support works better when the next person receives the customer purpose without unnecessary private details.',image:'/blog-aug20/outsourced-call-center-channel-switch-continuity.png',situation:'A representative recognizes a language need but forwards the caller with a vague label or repeats sensitive details before an interpreter is connected.',routine:'Use the approved language-support path, explain the transfer, and pass only the minimum context needed to resume the request.',record:'Record the requested language, channel, accessibility need if volunteered, verification state, customer purpose, connection result, owner, and fallback.',limit:'Representatives do not ask family members to interpret protected information or improvise legal and medical translations. Client policy owners define approved providers and exceptions.',audit:'Review transfers that failed, took unusually long, or returned to the first queue. Verify that identity and consent steps were not assumed across the handoff.'},
  {slug:'call-center-ticket-attachment-safety-check',title:'Check Customer Attachments Before Routing a Ticket',excerpt:'An attachment can change who may open a ticket and where its contents are allowed to travel.',image:'/blog-aug21/outsourced-call-center-consent-capture-review.webp',situation:'A customer adds an image or document to an ordinary service request, and the ticket is forwarded before anyone checks the approved handling lane.',routine:'Treat unexpected attachments as unreviewed until the authorized workflow identifies file type, business purpose, and safe destination.',record:'Capture the source channel, filename, stated purpose, scanning status, access group, routing decision, owner, and whether a safer resubmission was requested.',limit:'Queue staff should not download files to personal storage, copy contents into chat, or decide that sensitive material is harmless. Security and privacy owners handle exceptions.',audit:'Test a sample of attachment tickets from receipt to closure. Check access history, copied notes, exports, and rejected or quarantined files.'},
  {slug:'outsourced-call-center-customer-time-zone-capture',title:'Capture the Customer Time Zone Before Promising Contact',excerpt:'A callback window is incomplete until both sides know which local clock controls it.',image:'/blog-aug21/outsourced-call-center-callback-promise-ledger.webp',situation:'A representative promises a morning callback, but the customer and specialist are working from different time zones.',routine:'Confirm the customer-facing local window in plain language and store the normalized zone or offset in the approved field.',record:'Keep the customer location only when needed, named time zone, local window, UTC equivalent, daylight-saving assumption, channel permission, due owner, and confirmation.',limit:'Staff may explain the recorded window but should not infer location from an area code or use location data for an unrelated purpose.',audit:'Review promises near daylight-saving changes, midnight, and shared queues. Compare the stored value with the actual attempt and customer-facing message.'},
  {slug:'call-center-refund-request-evidence-package',title:'Prepare a Refund Request Without Promising Approval',excerpt:'A complete evidence package helps an authorized owner decide while keeping the representative inside the service boundary.',image:'/blog-aug20/outsourced-call-center-escalation-routing-map.png',situation:'The customer asks for a refund and the representative, trying to help, speaks as if approval is certain before the policy owner reviews the facts.',routine:'Acknowledge the request, explain the decision path, gather the approved evidence, and give a truthful update time rather than an outcome promise.',record:'Record the transaction reference, customer-stated reason, relevant delivery or service facts, prior contacts, amount requested, evidence gaps, decision owner, and update due time.',limit:'Only the authorized client role approves money movement, exceptions, or policy interpretation. Representatives should not predict the decision.',audit:'Sample approved, declined, and pending requests. Check package completeness, decision time, wording used with the customer, and whether follow-up matched the decision.'},
  {slug:'outsourced-call-center-live-chat-idle-session-close',title:'Close an Idle Live-Chat Session Without Losing the Request',excerpt:'An idle-chat rule should protect capacity while leaving the customer a clear way to continue unfinished work.',image:'/blog-aug23/outsourced-call-center-channel-switch-continuity.png',situation:'A customer stops responding during a multi-step request. The session closes, but the work record does not say what remains open.',routine:'Send the approved checkback, state the closure window, save the completed steps, and provide a safe return path before ending the session.',record:'Keep the last customer message, checkback times, completed action, unresolved question, verification state, closure reason, follow-up owner, and return instructions.',limit:'Representatives may close under the published rule. They should not mark the customer need resolved merely because the channel became idle.',audit:'Compare idle closures with repeat contacts and reopened cases. Review sessions closed just before a response and cases with an outstanding promise.'},
  {slug:'call-center-warm-transfer-introduction-standard',title:'Standardize the Warm-Transfer Introduction',excerpt:'A brief introduction should tell the receiving person what the customer needs, what was verified, and what remains undecided.',image:'/blog-aug20/outsourced-call-center-escalation-routing-map.png',situation:'The customer reaches a specialist but must repeat the entire story because the sender introduced only a name and account number.',routine:'Before connecting, summarize the customer purpose, completed approved checks, action already taken, open question, and authority needed.',record:'Log the sending queue, receiving owner, consent to transfer, verified state, concise purpose, open decision, introduction result, and fallback if connection fails.',limit:'Do not announce sensitive details before confirming the receiving person and approved channel. The introduction transfers context, not decision authority.',audit:'Listen to the introduction and the first minute after connection. Check repetition, conflicting claims, missing ownership, and failed-transfer recovery.'},
  {slug:'outsourced-call-center-status-page-message-use',title:'Use Status-Page Messages Without Overpromising',excerpt:'A public incident notice can support a customer update, but it does not prove an individual account is affected or fixed.',image:'/blog-aug21/outsourced-call-center-knowledge-change-notice.webp',situation:'A service status page reports an incident and the queue begins telling every caller that the incident explains their problem.',routine:'Match the approved notice to the customer symptom and affected scope, while keeping uncertain cases open for normal investigation.',record:'Capture the notice version, publish time, stated scope, customer symptom, account check allowed, wording used, next update, owner, and resolution evidence.',limit:'Representatives may repeat current approved language. Incident cause, restoration estimates, credits, and account-specific conclusions stay with authorized owners.',audit:'Review contacts before, during, and after the notice. Check whether stale wording remained in use and whether customers outside the stated scope were misclassified.'},
  {slug:'call-center-form-submission-confirmation-gap',title:'Repair the Gap After a Customer Form Submission',excerpt:'A successful submit screen is not the same as a received, owned, and reviewable customer request.',image:'/blog-aug20/outsourced-call-center-customer-promise-reconciliation.png',situation:'The customer sees a confirmation page, but the downstream record is delayed or rejected and nobody owns the missing request.',routine:'Define the evidence of receipt, the expected acknowledgment window, and the lookup path when the customer reports no response.',record:'Keep the form type, customer-supplied reference, submission time, confirmation event, downstream record ID, routing result, owner, due time, and recovery action.',limit:'Support staff should not request the customer to resubmit sensitive information until the approved search and safe-channel checks are complete.',audit:'Reconcile confirmation events against created records for a fixed period. Include duplicates, validation failures, delayed processing, and records still missing at cutoff.'},
  {slug:'outsourced-call-center-pronunciation-note-boundary',title:'Keep Pronunciation Notes Useful and Respectful',excerpt:'A pronunciation note should support the next conversation without storing guesses, labels, or unnecessary identity details.',image:'/blog-aug21/outsourced-call-center-complaint-deescalation-record.webp',situation:'A representative wants to help colleagues say a customer name correctly but writes a subjective description that becomes permanent account history.',routine:'Ask and record only the customer-provided pronunciation in the approved field, using the supported phonetic format or an explicit preference.',record:'Keep the name field governed by policy, customer-provided pronunciation, source and time, permitted display location, correction request, and reviewer if disputed.',limit:'Do not infer ethnicity, gender, origin, or preferred form of address. Protected identity changes and disputed records go to the authorized owner.',audit:'Review notes for customer attribution, neutral wording, field placement, access, and whether corrections propagate to the tools used on the next contact.'},
  {slug:'call-center-unavailable-specialist-update',title:'Give a Useful Update When the Specialist Is Unavailable',excerpt:'An unavailable specialist should trigger a bounded next step, not a vague request for the customer to try again later.',image:'/blog-aug20/outsourced-call-center-absence-handoff-protocol.png',situation:'The queue reaches an authority boundary, but the needed specialist is absent and no backup or update time is visible.',routine:'State what remains undecided, name the approved interim action, assign the fallback, and give a realistic next-update window.',record:'Record the customer need, boundary reached, primary specialist, absence state, backup contacted, interim action, customer preference, update time, and owner.',limit:'Frontline staff cannot make the specialist decision or expose internal schedules. Managers define backup coverage and high-impact escalation.',audit:'Review unavailable-owner cases by shift and decision type. Check update timeliness, repeat contacts, expired promises, and work left unowned.'},
  {slug:'outsourced-call-center-survey-opt-out-handoff',title:'Carry Survey Opt-Outs Across Support Channels',excerpt:'A customer who declines a survey should not have to repeat that choice after every channel switch or follow-up.',image:'/blog-aug23/outsourced-call-center-consent-capture-review.png',situation:'The customer declines a post-contact survey in chat but receives another invitation after a related phone follow-up.',routine:'Store the choice in the approved preference system, define its scope, and suppress only the survey contact covered by that choice.',record:'Keep the choice, channel, time, stated scope, linked customer or case identifier, source, effective period, systems updated, confirmation, and exception owner.',limit:'Do not interpret a survey opt-out as a broader marketing or service-contact preference. Privacy and policy owners decide ambiguous or jurisdiction-specific cases.',audit:'Trace opt-outs through chat, voice, email, and reopened cases. Check delayed synchronization, duplicate invitations, preference expiry, and correction handling.'},
] as const;

const sources=[
 {name:'Cybersecurity Framework 2.0',organization:'NIST',date:'February 2024',url:'https://www.nist.gov/cyberframework',note:'Governance and ownership context.'},
 {name:'Privacy Framework',organization:'NIST',date:'January 2020',url:'https://www.nist.gov/privacy-framework',note:'Purpose and data-minimization context.'},
 {name:'ISO 18295-1:2017 Customer contact centres',organization:'International Organization for Standardization',date:'July 2017',url:'https://www.iso.org/standard/64739.html',note:'Customer-contact process context.'},
] as const;

const makePost=(t:Topic,i:number):BlogPost=>({slug:t.slug,title:t.title,excerpt:t.excerpt,keyword:t.title,published:'2026-09-08',updated:'2026-09-08',minutes:8+i%4,heroImage:t.image,intro:t.situation,sections:[
 {title:'Recognize the operating gap',paragraphs:[t.situation,'Define the trigger so each shift starts the same routine from observable evidence.']},
 {title:'Run the routine',paragraphs:[t.routine,'Use the approved source of truth and mark missing information as unknown instead of completing the story from memory.']},
 {title:'Build the handoff record',paragraphs:[t.record,'Keep the customer need, current state, next permitted action, due time, and accepting owner together.']},
 {title:'Hold the authority line',paragraphs:[t.limit,'Name the decision owner and the safe fallback before the queue handles live cases.']},
 {title:'Audit real contacts',paragraphs:[t.audit,'Use a fixed period, preserve open cases at cutoff, and separate an incomplete record from an unfavorable outcome.']},
 {title:'Repair the recurring cause',paragraphs:['Classify each miss as a definition, training, tool, capacity, permission, or ownership gap. Repair the source rather than adding a reminder that cannot be followed.']},
 {title:'Keep the routine current',paragraphs:['Recheck the workflow after a system, policy, queue, or owner changes. Retire stale wording from search results, bookmarks, and handoff documents.']},
],faqs:[{question:'Who owns an exception?',answer:'The client should name the role with decision authority and a backup before live work begins.'},{question:'What belongs in the first review?',answer:'Include ordinary work, boundary cases, handoffs, and every item still open at the cutoff.'}],sources,related:[{label:'Browse call center research',href:'/research'},{label:'Review operations support',href:'/services/operations-support'},{label:'Discuss the workflow',href:'/contact-us'}],banners:[{label:'Scope',title:'Write the operating boundary',body:'Define the trigger, evidence, owner, and fallback.',href:'/contact-us',cta:'Discuss the workflow'},{label:'Pilot',title:'Test one queue first',body:'Review representative work with a decision owner available.',href:'/services/operations-support',cta:'Review operations support'},{label:'Review',title:'Repair the source gap',body:'Use customer-contact evidence to improve the routine.',href:'/blog',cta:'Read more guides'}]});

export const september8BlogBatch:readonly BlogPost[]=topics.map(makePost);
