import type {BlogPost} from './data';

const published='2026-10-09';
const image='/blog-aug20/outsourced-call-center-qa-sample-selection.png';
const sources=[
  {name:'Customer contact centres, Part 1',organization:'International Organization for Standardization',date:'2017',url:'https://www.iso.org/standard/64739.html',note:'Customer-contact process and outcome context.'},
  {name:'Cybersecurity Framework 2.0',organization:'National Institute of Standards and Technology',date:'2024',url:'https://www.nist.gov/cyberframework',note:'Governance, access, response, and recovery context.'},
  {name:'Privacy Framework',organization:'National Institute of Standards and Technology',date:'2020',url:'https://www.nist.gov/privacy-framework',note:'Privacy-risk and data-processing context.'}
];
type Draft={slug:string;title:string;excerpt:string;focus:string;caseStudy:string;service:string;headings:string[]};
const drafts:Draft[]=[
  {slug:'callcenteroutsourced-priority-intake-triage',title:'Outsourced Call Center Priority Intake Triage',excerpt:'A practical guide for outsourced call center teams to sequence new requests by evidence, impact, and accepted ownership.',focus:'sequence new requests by evidence, impact, and accepted ownership in a bounded outsourced call center workflow',caseStudy:'A promised evening callback enters a shared list without a time zone, and the next shift marks it complete after one unverified attempt.',service:'/services/operations-support',headings:['Define a callback promise','Preserve customer-local time','Separate attempt from completion','Accept ownership across shifts','Route failed verification safely','Review missed promises','Close with customer evidence']},
  {slug:'callcenteroutsourced-exception-owner-map',title:'Outsourced Call Center Exception Owner Map',excerpt:'A practical guide for outsourced call center teams to route ambiguous work to an authorized decision owner.',focus:'route ambiguous work to an authorized decision owner in a bounded outsourced call center workflow',caseStudy:'A new reason code absorbs billing disputes and ordinary invoice questions, making the apparent dispute rate fall overnight.',service:'/services/reporting-and-qa',headings:['State the reporting decision','Define every reason boundary','Preserve an unknown route','Test historical comparability','Train with edge cases','Monitor recoding patterns','Retire old labels cleanly']},
  {slug:'callcenteroutsourced-source-record-verification',title:'Outsourced Call Center Source Record Verification',excerpt:'A practical guide for outsourced call center teams to confirm the governing record before work begins.',focus:'confirm the governing record before work begins in a bounded outsourced call center workflow',caseStudy:'A complaint is transferred three times; every team believes another group owns the next customer update.',service:'/services/customer-support',headings:['Separate receipt from resolution','Record stated customer impact','Assign the next update owner','Protect allegations from inference','Escalate material conditions','Audit broken promises','Close the stated issue']},
  {slug:'callcenteroutsourced-handoff-acceptance-receipt',title:'Outsourced Call Center Handoff Acceptance Receipt',excerpt:'A practical guide for outsourced call center teams to prove the receiving team accepted the next action.',focus:'prove the receiving team accepted the next action in a bounded outsourced call center workflow',caseStudy:'A quality analyst can download full recordings for queues outside the assigned review scope because an inherited group was never removed.',service:'/services/reporting-and-qa',headings:['Define the permitted purpose','Inventory direct and inherited access','Minimize review fields','Control exports and copies','Test revocation events','Review exception access','Document recertification']},
  {slug:'callcenteroutsourced-backlog-aging-review',title:'Outsourced Call Center Backlog Aging Review',excerpt:'A practical guide for outsourced call center teams to separate active handling from documented waiting states.',focus:'separate active handling from documented waiting states in a bounded outsourced call center workflow',caseStudy:'Average wrap time improves while reopened contacts increase because representatives select generic dispositions and omit promised next steps.',service:'/services/reporting-and-qa',headings:['Define the required record','Choose a representative sample','Link notes to customer need','Check promises and ownership','Separate delay from accuracy','Calibrate reviewers','Repair system causes']},
  {slug:'callcenteroutsourced-quality-sample-calibration',title:'Outsourced Call Center Quality Sample Calibration',excerpt:'A practical guide for outsourced call center teams to align reviewers on observable acceptance evidence.',focus:'align reviewers on observable acceptance evidence in a bounded outsourced call center workflow',caseStudy:'An article reaches its review date during a product change, remains searchable, and gives representatives a rule the business no longer supports.',service:'/services/tier-one-technical-support',headings:['Treat review date as a trigger','Name the source owner','Rank customer consequence','Provide a safe interim path','Remove competing versions','Verify retrieval after change','Close the evidence trail']},
  {slug:'callcenteroutsourced-access-scope-recertification',title:'Outsourced Call Center Access Scope Recertification',excerpt:'A practical guide for outsourced call center teams to keep permissions aligned with current duties.',focus:'keep permissions aligned with current duties in a bounded outsourced call center workflow',caseStudy:'A customer repeats identity details and the full complaint after a language transfer because only the call, not the case context, moved.',service:'/services/customer-support',headings:['Record stated language choice','Preserve verified context','Limit unnecessary repetition','Confirm receiving skill','Set a fallback promise','Review transfer outcomes','Protect equitable service']},
  {slug:'callcenteroutsourced-change-control-release-note',title:'Outsourced Call Center Change Control Release Note',excerpt:'A practical guide for outsourced call center teams to publish a dated rule change with rollback context.',focus:'publish a dated rule change with rollback context in a bounded outsourced call center workflow',caseStudy:'Representatives keep urgent exceptions in personal messages because the official escalation queue does not show who accepted the decision.',service:'/services/operations-support',headings:['List decisions that need authority','Define a complete decision packet','Timestamp owner acceptance','Protect urgent stop rules','Add absence coverage','Measure decision age','Return reusable guidance']},
  {slug:'callcenteroutsourced-capacity-overflow-trigger',title:'Outsourced Call Center Capacity Overflow Trigger',excerpt:'A practical guide for outsourced call center teams to surface demand that exceeds the safe service window.',focus:'surface demand that exceeds the safe service window in a bounded outsourced call center workflow',caseStudy:'Two same-day contacts share an order number but concern different problems; an automatic merge closes the unresolved delivery complaint.',service:'/services/operations-support',headings:['Define duplicate versus related','Use approved linkage fields','Preserve separate needs','Control irreversible merges','Reconcile promises','Sample false matches','Repair intake causes']},
  {slug:'callcenteroutsourced-client-decision-packet',title:'Outsourced Call Center Client Decision Packet',excerpt:'A practical guide for outsourced call center teams to prepare facts without transferring client authority.',focus:'prepare facts without transferring client authority in a bounded outsourced call center workflow',caseStudy:'A representative repeats an old restoration time after the incident owner has withdrawn the estimate.',service:'/services/customer-support',headings:['Define what support may state','Separate observation from estimate','Version every message','Set the next update time','Map channel ownership','Test stale-message removal','Close after reconciliation']},
  {slug:'callcenteroutsourced-correction-propagation-check',title:'Outsourced Call Center Correction Propagation Check',excerpt:'A practical guide for outsourced call center teams to reconcile corrected facts across dependent systems.',focus:'reconcile corrected facts across dependent systems in a bounded outsourced call center workflow',caseStudy:'A customer is promised a refund amount before the authorized owner reviews a partial shipment and prior credit.',service:'/services/customer-support',headings:['Separate request from entitlement','Verify the transaction boundary','Cite the governing source','Record prior remedies','Name the decision owner','Communicate without promising','Reconcile decision and payment']},
  {slug:'callcenteroutsourced-monthly-control-closeout',title:'Outsourced Call Center Monthly Control Closeout',excerpt:'A practical guide for outsourced call center teams to close open exceptions and preserve review evidence.',focus:'close open exceptions and preserve review evidence in a bounded outsourced call center workflow',caseStudy:'A provider removes system-outage contacts from the response metric without preserving which customers still waited for an answer.',service:'/services/reporting-and-qa',headings:['Define the measured clock','List permitted exclusions','Retain the excluded population','Require evidence and approval','Show customer impact separately','Audit changing definitions','Publish comparable results']}
];
const facts=[
  'Freeze the queue, channel, customer population, observation period, systems, and current instruction version before changing the workflow.',
  'Record the authoritative source, event timestamp with offset, permitted action, accountable owner, next decision, and evidence of acceptance.',
  'Keep customer facts, representative actions, manager decisions, and final outcomes in separate fields so an operational note cannot masquerade as approval.',
  'Include an ordinary case, a missing-input case, a cross-shift handoff, and a case that reaches the documented stop condition.',
  'Measure counts with denominators and segment waiting on customers, systems, providers, and authorized client decisions rather than averaging unlike delays.',
  'Preserve corrections and superseded instructions with reasons; do not overwrite the history that a later reviewer needs to reconstruct the customer journey.',
  'Close only when the evidence supports the status, the receiving owner accepted the next action, and any remaining uncertainty is explicitly assigned.'
];
const make=(d:Draft):BlogPost=>({slug:d.slug,title:d.title,excerpt:d.excerpt,keyword:d.slug.replaceAll('-',' '),published,minutes:12,heroImage:image,intro:`${d.title} turns ${d.focus} into a reviewable operating control. The goal is not to automate judgment. It is to connect customer need, source evidence, authority, timing, exceptions, and closure so an outsourced team can act without guessing.`,sections:d.headings.map((title,index)=>({title,paragraphs:[
  `${facts[index]} For ${d.focus}, begin with the customer consequence and the exact decision the record must support. Broad instructions reward speed while hiding different obligations. The provider may prepare evidence, follow approved steps, and route exceptions; authorized client owners retain policy, refund, access, privacy, safety, employment, legal, and irreversible decisions. State that boundary where work happens, not only in a contract.`,
  `${d.caseStudy} Treat this as a test case rather than an anecdote. Preserve the original event, applicable source, system state, action, promise, owner, and unresolved question. Ask whether another qualified reviewer can reconstruct the path without private memory. If the evidence conflicts, show both sources and stop at the approved boundary instead of selecting the convenient answer.`,
  `Pilot the control in one bounded queue. Review normal and exception cases, record missing evidence as missing, and compare the final outcome with the original customer need. Expand only when ownership survives shift and company boundaries, corrections reach the governed source, and the reporting definitions remain stable. Link the record to the relevant [service lane](${d.service}) while keeping the business owner accountable for the consequential decision.`
]})),faqs:[{question:`What should a buyer verify first for ${d.focus}?`,answer:'Verify scope, authoritative inputs, decision ownership, stop conditions, and closure evidence before comparing speed or price.'},{question:'How should the first pilot be limited?',answer:'Use one bounded queue with ordinary and exception cases, stable definitions, and a named reviewer.'},{question:'Who owns policy exceptions?',answer:'The authorized client owner retains policy and risk decisions; the provider records facts and routes beyond-scope cases.'}],sources,related:[{label:'Review the service catalog',href:'/services'},{label:'Explore call center research',href:'/research'},{label:'Discuss a bounded pilot',href:'/contact-us'}]});
export const october9BlogBatch:readonly BlogPost[]=drafts.map(make);

// This October 9 control starts from one bounded observation, preserves missing evidence as missing, and keeps the consequential decision with the named accountable owner.
