import type { BlogPost } from './data';

type Draft = {
  slug: string; title: string; excerpt: string; intro: string; focus: string;
  practice: string; measure: string; handoff: string;
  published: '2026-08-17'; updated: '2026-08-17';
};

const drafts: readonly Draft[] = [
  { slug: 'call-center-inbound-call-triage', title: 'Triage inbound calls without sending the wrong work downstream', excerpt: 'A call triage rule helps a frontline team identify the customer need, urgency, and right next owner before a transfer adds more delay.', intro: 'The first queue often has the least context and the most pressure. A triage rule should make the next question clear without asking the caller to repeat a story that the record already contains.', focus: 'Separate the reason for contact from the requested outcome, then define the smallest question that distinguishes ordinary handling from specialist review.', practice: 'Start with the call types that create the most avoidable transfers. Give the team a fallback for unclear language and review that fallback instead of inventing a new category on the spot.', measure: 'Compare transfer rate, clarification time, repeat explanations, specialist returns, and contacts that leave the first queue without an owner.', handoff: 'Send an unresolved routing pattern to the person who owns the queue map, with examples that show the competing interpretations.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-omnichannel-case-linking', title: 'Link phone, chat, and email contacts without losing the customer story', excerpt: 'A cross-channel case link preserves the request, completed action, and next owner when a customer changes channels.', intro: 'A new channel should not erase the work already done. Linking contacts is useful when the next person can tell what was asked, what was confirmed, and what remains open.', focus: 'Define when contacts belong to one case, what evidence supports the link, and which record remains authoritative for the next action.', practice: 'Use a narrow matching rule based on approved identifiers and the customer request. When identity or ownership is uncertain, keep the records separate and escalate the ambiguity.', measure: 'Review duplicate cases, repeated explanations, incorrect links, unresolved promises, and time spent reconciling records.', handoff: 'Route a disputed link or identity concern to the protected record owner rather than merging records to make the queue look tidy.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-appointment-setting-confirmation', title: 'Make outbound appointment setting easy to confirm', excerpt: 'A confirmation standard keeps an appointment request, approved details, customer consent, and next step together.', intro: 'An appointment is not confirmed just because a time was discussed. The record should distinguish a proposed slot from an accepted one and show who owns the next action.', focus: 'Record the purpose, permitted time options, customer response, confirmation source, and follow-up when the appointment remains tentative.', practice: 'Give the team approved language for uncertainty. Do not imply availability, attendance, or a completed booking until the authorized system confirms it.', measure: 'Track confirmed appointments, tentative contacts, duplicate bookings, missed confirmations, and customers who call back for status.', handoff: 'Send schedule conflicts or exceptions to the owner who controls availability and customer commitments.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-order-status-escalation', title: 'Handle order-status calls when the system and customer disagree', excerpt: 'A bounded order-status escalation keeps the visible record, customer report, and next verification step separate.', intro: 'Status calls become difficult when one system says complete while the customer reports that the expected result did not happen. The frontline role is to capture the conflict accurately and route the decision.', focus: 'Record the order reference, displayed status, customer observation, relevant timing, and the exact question the next owner must answer.', practice: 'Use the approved status source and avoid guessing at causes. Tell the customer what is confirmed and what needs review rather than choosing the most reassuring explanation.', measure: 'Review repeat contacts, unresolved status conflicts, time to owner acknowledgment, incorrect reassurances, and cases closed without evidence.', handoff: 'Send a status conflict to the order owner with both source records and no unsupported conclusion.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-tier-one-technical-support-boundary', title: 'Set a tier-one technical support boundary that callers can follow', excerpt: 'A tier-one boundary keeps routine troubleshooting moving while routing security, data-loss, and specialist cases to the right owner.', intro: 'Technical support slows down when frontline staff must decide whether every unusual symptom is safe to handle. A written boundary explains what can be checked, what must stop, and who receives the case.', focus: 'List approved checks, observable stop conditions, information that must not be requested, and the specialist path for unresolved symptoms.', practice: 'Test the boundary with ordinary failures and one case that looks similar but carries more risk. Keep the first response factual and avoid diagnosing beyond the approved scope.', measure: 'Track successful first contacts, repeat troubleshooting, unsafe requests, specialist returns, and cases without a clear next step.', handoff: 'Escalate security, data-loss, access-control, or unclear technical conditions through the designated specialist route.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-collections-reminder-call-compliance', title: 'Keep collections reminder calls within a clear service boundary', excerpt: 'A reminder-call boundary helps the team use approved wording, protect account information, and route disputes without making unauthorized promises.', intro: 'Reminder calls require careful control because the caller may ask for a different arrangement or raise a dispute. The frontline role should be clear about what it can state and what requires review.', focus: 'Define permitted identification, approved reminder language, stop conditions, dispute capture, and the owner for account or policy decisions.', practice: 'Use the smallest approved disclosure and record the response without adding judgment. Never improvise a payment arrangement or threaten an outcome the policy does not state.', measure: 'Review disclosure exceptions, disputed accounts, returned escalations, incomplete records, and contacts that require a second explanation.', handoff: 'Send disputes, vulnerability signals, legal questions, or arrangement requests to the authorized account owner.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-win-back-call-eligibility', title: 'Define win-back call eligibility before outreach begins', excerpt: 'An eligibility rule keeps customer win-back outreach focused on approved records and gives the team a safe response when the record does not fit.', intro: 'Win-back work can become careless when a broad list is treated as permission to contact anyone. A useful rule connects the contact purpose, approved audience, channel, and opt-out path.', focus: 'Name the source record, allowed contact reason, exclusion conditions, approved channel, and action when a customer declines or asks not to be contacted.', practice: 'Review a small sample before outreach expands. Separate a customer preference from a temporary campaign list and do not infer permission from an old interaction.', measure: 'Track eligible contacts, opt-outs, wrong-record attempts, repeat outreach, unanswered requests, and records missing a permitted channel.', handoff: 'Route permission conflicts or exclusion questions to the owner of contact policy before another attempt is made.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-dispatch-coordination-proof', title: 'Give dispatch coordination a proof-of-handoff standard', excerpt: 'A dispatch handoff is reliable when the request, location detail, assigned owner, timing, and acknowledgment are visible in one record.', intro: 'Dispatch work often crosses a phone team and a field or operations team. The handoff should show what was requested and what the receiving person accepted, not just that a message was sent.', focus: 'Record the service request, approved location detail, urgency, assigned owner, expected arrival or update point, and acknowledgment status.', practice: 'Keep customer-facing timing separate from internal estimates. If the receiving team has not accepted the work, say that plainly and use the fallback path.', measure: 'Review unacknowledged dispatches, duplicate assignments, missed updates, repeat calls, and records with no accountable owner.', handoff: 'Escalate an unaccepted or high-impact dispatch to the shift owner who can reassign it and reset the customer expectation.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-survey-call-neutrality', title: 'Keep survey calls neutral when a customer gives unexpected feedback', excerpt: 'A neutral survey path protects the customer response while giving the team a safe route for complaints, opt-outs, and urgent concerns.', intro: 'Survey callers need to collect feedback without steering the answer or turning a serious concern into a score. The script should make the purpose clear and provide a separate path when the contact is no longer a survey.', focus: 'Define the introduction, permitted questions, opt-out wording, response record, and trigger that moves a contact to support or escalation.', practice: 'Use the customer’s words for a concern and avoid arguing with a negative answer. Keep an incomplete survey distinct from a resolved service issue.', measure: 'Review completion, opt-outs, prompted answers, complaint escalations, duplicate outreach, and records that mix feedback with case resolution.', handoff: 'Route safety, privacy, service, or vulnerability concerns to the relevant owner without interpreting the survey score as a finding.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-workforce-reporting-interval-review', title: 'Review workforce reports by interval before changing coverage', excerpt: 'An interval review helps managers distinguish a real coverage gap from a reporting artifact or a single unusual period.', intro: 'A daily total can hide when the queue was under-covered and why. Reporting support is more useful when it preserves the interval, skill, channel, and exception behind the number.', focus: 'Compare demand, planned coverage, actual availability, work type, and known exceptions before recommending a schedule change.', practice: 'Check the source definitions first. Do not turn a late status update, system outage, or unusual contact mix into a staffing conclusion without review.', measure: 'Track interval variance, uncovered skill need, data exceptions, correction rate, and decisions that changed after source validation.', handoff: 'Send a disputed metric definition to the reporting owner and keep the underlying records available for review.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-qa-critical-error-boundary', title: 'Separate critical QA errors from coaching preferences', excerpt: 'A quality rubric is fairer when it distinguishes customer-impacting failures from wording choices that need coaching but do not change the outcome.', intro: 'A score loses meaning when every preference is treated as a failure. The rubric should identify the evidence that requires immediate review and leave style disagreements in a separate category.', focus: 'Define critical errors by observable customer or process impact, then document the evidence and owner for review.', practice: 'Calibrate the rubric with examples that contain one issue at a time. Keep personal style out of the critical category unless the approved standard makes it a real requirement.', measure: 'Compare reviewer agreement, critical-error rate, coaching returns, disputed scores, and rubric items that produce inconsistent decisions.', handoff: 'Send a scoring conflict to the QA owner rather than changing a representative’s outcome from an isolated disagreement.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-crm-cleanup-safe-fields', title: 'Choose safe CRM cleanup fields for outsourced support', excerpt: 'A field-level cleanup plan removes repeat errors while keeping account ownership, policy decisions, and customer history with the manager.', intro: 'CRM cleanup is useful when a team knows which fields may be corrected and which changes require evidence or approval. A broad request to make records look complete creates new risk.', focus: 'Separate formatting and duplicate-work fixes from identity, ownership, financial, and historical changes that need review.', practice: 'Start with a small field list and compare every update to its source. Preserve the original value where the system supports history and stop when the source is unclear.', measure: 'Review missing fields, incorrect corrections, duplicate records, returned updates, and changes made without a source.', handoff: 'Route identity, ownership, policy, or historical-record conflicts to the record owner.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-shift-coverage-exception-log', title: 'Use a shift coverage exception log that leads to action', excerpt: 'A coverage exception log helps supervisors see what changed, who was affected, and which decision is still needed.', intro: 'Coverage changes happen for many reasons, but a list of absences alone does not show the customer impact. The log should connect the exception to the queue and the response.', focus: 'Record the interval, affected skill or channel, reason category, temporary action, owner, and point for review.', practice: 'Keep facts separate from assumptions about performance or cause. Close an exception only when the coverage response and remaining risk are recorded.', measure: 'Track uncovered intervals, queue impact, late escalations, repeated exceptions, and changes that lacked an owner.', handoff: 'Send staffing, employment, or schedule-policy decisions to the manager authorized to make them.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-escalation-queue-aging', title: 'Control escalation queue aging with an explicit next action', excerpt: 'An aging review keeps escalations moving by showing the last action, waiting dependency, owner, and customer update point.', intro: 'An escalation can remain visible and still be unattended. Age becomes useful only when the team can see what is blocking the decision and who must act next.', focus: 'Group open escalations by next action and dependency, not by age alone, then set an owner and review point for each group.', practice: 'Keep an old case from being hidden by a new note. If the customer expectation must change, record the approved update rather than quietly moving the due point.', measure: 'Review age by owner, overdue acknowledgments, blocked dependencies, customer updates, and escalations returned without a decision.', handoff: 'Escalate an aging item to the manager who can remove the dependency or assign a different decision owner.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-inbox-to-queue-routing', title: 'Turn a shared support inbox into a queue with ownership', excerpt: 'Inbox routing works when every message receives a reason, owner, next action, and visible fallback instead of sitting under a shared label.', intro: 'A shared inbox can make work look available while nobody owns it. A small routing rule turns messages into work records without asking the team to classify every possible edge case.', focus: 'Define the first categories, required fields, response owner, escalation trigger, and treatment of messages that do not fit.', practice: 'Route by the customer request and action required, not by the sender’s tone. Keep a review lane for unclear messages and use it to improve the rule.', measure: 'Track unassigned age, misroutes, first response, reopened messages, duplicate replies, and fallback volume.', handoff: 'Send recurring misroutes to the owner of the inbox taxonomy with representative messages and the decision needed.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-customer-authentication-failure', title: 'Give the queue a safe path when customer authentication fails', excerpt: 'An authentication-failure path protects customer information while giving the caller a clear next step that does not rely on improvised checks.', intro: 'A failed check is a process result, not an invitation to ask for more personal detail. The team needs a consistent pause, limited explanation, and protected escalation option.', focus: 'List the approved checks, the stop condition, the information that must not be disclosed, and the channel for an authorized review.', practice: 'Use neutral wording and record the result rather than the sensitive answers. Never create a substitute check because the queue is busy or the caller is persuasive.', measure: 'Review failed checks, repeat attempts, inappropriate disclosures, abandoned contacts, and exceptions sent through the wrong route.', handoff: 'Send identity or account-ownership disputes to the designated protected owner.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-customer-follow-up-deadline', title: 'Set a follow-up deadline the support queue can actually monitor', excerpt: 'A follow-up deadline is useful when it names the owner, source of the commitment, review point, and customer update if the work remains open.', intro: 'A date in a note does not create ownership. The queue needs a visible deadline and a rule for what happens before it passes.', focus: 'Separate the customer’s requested timing from the team’s confirmed commitment, then record the owner and update path.', practice: 'Choose deadlines that the assigned queue can see and review. When a dependency makes the date unsafe, escalate early instead of waiting for the miss.', measure: 'Track on-time updates, overdue items, dependency age, repeat contacts, and deadlines without a named owner.', handoff: 'Send a deadline risk to the manager who can change the dependency or reset the expectation truthfully.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-call-recording-access-boundary', title: 'Set a call-recording access boundary for quality review', excerpt: 'A recording-access rule lets QA reviewers use approved evidence without spreading customer conversations beyond the people and purpose that need them.', intro: 'Recordings can help clarify a disputed interaction, but broad access creates a second problem. The role should define who may review, why, how findings are recorded, and when access stops.', focus: 'Specify the approved purpose, reviewer role, retention or source rule, redaction need, and escalation route for sensitive content.', practice: 'Use the smallest excerpt or summary needed for the review. Keep customer secrets out of general QA notes and do not download recordings to personal locations.', measure: 'Review access exceptions, repeated requests, sensitive-content handling, disputed findings, and records that lack a review purpose.', handoff: 'Route privacy, legal, or access-policy questions to the owner of recording governance.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-callback-failure-recovery', title: 'Recover failed callbacks without creating another promise gap', excerpt: 'A failed-callback procedure preserves the attempt, reason, approved channel, and next owner before the team tries again.', intro: 'A missed callback is not fixed by adding another due date. The team should know whether the customer was unreachable, the queue lacked capacity, the number was wrong, or the work was never assigned.', focus: 'Record the attempt outcome, source of the contact detail, next permitted channel, owner, and customer expectation that remains valid.', practice: 'Do not label a customer unreachable after one ambiguous result. Use the approved retry rule and escalate when the original commitment is no longer achievable.', measure: 'Track failed reasons, successful recovery, repeat attempts, stale contact details, and callbacks that lose their owner.', handoff: 'Send a missed high-impact commitment to the supervisor who can prioritize the work and communicate a new expectation.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-service-level-exception-review', title: 'Review service-level exceptions without hiding queue conditions', excerpt: 'An exception review explains why a response target was missed and which customer or operating condition needs a decision.', intro: 'A missed target can result from demand, staffing, a system problem, an unusual contact type, or a measurement mistake. Treating every miss as the same produces weak action.', focus: 'Record the target, observed result, affected work, known condition, customer impact, and decision still needed.', practice: 'Keep the original measurement and label the exception separately. Do not rewrite the target or remove a miss simply because the cause is understandable.', measure: 'Review misses by interval and cause, repeat conditions, customer updates, data corrections, and actions completed after review.', handoff: 'Send a policy or target-definition dispute to the service owner, and an immediate coverage problem to the shift manager.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-knowledge-answer-confidence', title: 'Give customer support a safe answer-confidence rule', excerpt: 'An answer-confidence rule tells the queue when an approved response is enough and when uncertainty must become an escalation.', intro: 'Support staff often know most of an answer but not the one detail that changes the outcome. A confidence rule prevents a polished guess from becoming a customer commitment.', focus: 'Define the approved source, the missing fact that blocks an answer, the temporary wording, and the owner who resolves the gap.', practice: 'Let the team state what is known and what is being checked. Keep temporary wording short, accurate, and tied to a review point.', measure: 'Track returned answers, repeat questions, time to approved guidance, unsupported promises, and knowledge gaps that recur.', handoff: 'Send a factual or policy conflict to the named knowledge owner with the customer question and source checked.', published: '2026-08-17', updated: '2026-08-17' },
  { slug: 'call-center-manager-review-sample-design', title: 'Choose manager review samples that reveal handoff risk', excerpt: 'A manager review sample should include ordinary work and the edge cases that test ownership, escalation, and customer expectation.', intro: 'A sample made only of easy contacts can look clean while the risky work moves elsewhere. Review design should reflect the queue’s actual decisions and failure points.', focus: 'Choose samples by work type, outcome, escalation, and exception so the manager can see where the written boundary holds or fails.', practice: 'Set the sample before reading the records and record why each item was chosen. Keep the review factual, with coaching and policy changes separated from the evidence.', measure: 'Track sample coverage, agreement, recurring boundary failures, returned work, and actions that remain unowned.', handoff: 'Send a repeated boundary failure to the manager who can change the process, training, access, or staffing decision.', published: '2026-08-17', updated: '2026-08-17' },
];

const makePost = (draft: Draft, index: number): BlogPost => ({
  slug: draft.slug, title: draft.title, excerpt: draft.excerpt, minutes: 8 + (index % 4), keyword: draft.title,
  published: draft.published, updated: draft.updated, intro: draft.intro,
  sections: [
    { title: 'Start with the decision the caller needs', paragraphs: [draft.focus, 'Write the requested outcome, the confirmed facts, and the next action in language another person can use.'], items: ['Name the request', 'Separate facts from assumptions', 'State the review point', 'Name the owner'] },
    { title: 'Keep the first operating rule narrow', paragraphs: [draft.practice, 'A small first version makes unclear authority visible before it spreads across more channels or shifts.'] },
    { title: 'Protect the handoff', paragraphs: [draft.handoff, 'The support team can follow approved wording, record permitted facts, and route uncertainty. Sensitive decisions and policy exceptions remain with the named owner.'], items: ['Record what happened', 'Limit sensitive detail', 'Name what remains', 'Escalate uncertainty'] },
    { title: 'Measure the work that matters', paragraphs: [draft.measure, 'Pair volume with quality, timeliness, and ownership so a number leads to a practical decision.'] },
    { title: 'Close with an honest expectation', paragraphs: ['State the next confirmed action and its owner. If review is still needed, say so plainly instead of promising an outcome that has not been approved.'], items: ['Confirm the request', 'State the next step', 'Name the timing', 'Record the result'] },
    { title: 'Use language the queue can repeat', paragraphs: ['Give the team one sentence for the normal path and one for uncertainty. Keep both accurate to the authority available at the point of contact.'] },
    { title: 'Review a representative sample', paragraphs: ['Look for missing fields, repeated questions, avoidable transfers, and conflicts between the written rule and the tool. Fix the rule before expanding it.'], items: ['Sample early work', 'Discuss exceptions', 'Update the example', 'Expand after review'] },
  ],
  controlTable: [
    { data: 'Ordinary request', agent: 'Follow the approved path and record the result', manager: 'Maintain the rule and review samples' },
    { data: 'Missing information', agent: 'Ask the approved question or pause', manager: 'Decide the safe fallback' },
    { data: 'Sensitive exception', agent: 'Stop and route it without guessing', manager: 'Verify evidence and decide' },
    { data: 'Ownership conflict', agent: 'Preserve the record and escalate', manager: 'Assign the accountable owner' },
  ],
  scripts: [
    { situation: 'Normal path', text: 'I have recorded the request and will complete the approved next step.' },
    { situation: 'Needs review', text: 'This part needs review, so I will send it to the named owner.' },
    { situation: 'Unclear case', text: 'I do not want to guess. I will record what is known and confirm the next step.' },
  ],
  faqs: [{ question: 'What should happen first?', answer: draft.focus }, { question: 'What needs an owner?', answer: draft.handoff }, { question: 'What should be measured?', answer: draft.measure }],
  sources: [{ name: 'ISO 18295-1 overview', organization: 'International Organization for Standardization', date: '2017', url: 'https://www.iso.org/standard/65137.html', note: 'Supports defined contact-centre processes and service outcomes.' }, { name: 'Zero Trust Architecture, SP 800-207', organization: 'National Institute of Standards and Technology', date: '2020', url: 'https://csrc.nist.gov/pubs/sp/800/207/final', note: 'Supports explicit access and decision boundaries.' }],
  related: [{ label: 'Review customer support', href: '/services/omnichannel-customer-support' }, { label: 'Review operations support', href: '/services/operations-support' }, { label: 'Review reporting support', href: '/services/workforce-reporting-support' }],
  banners: [{ label: 'Scope', title: 'Define the first queue', body: 'List the work, review points, and approval limits before adding coverage.', href: '/services/operations-support', cta: 'Review operations support' }, { label: 'Review', title: 'Use representative examples', body: 'Sample early work with a named owner and fix unclear rules quickly.', href: '/services/workforce-reporting-support', cta: 'Review reporting support' }, { label: 'Handoff', title: 'Keep decisions with the owner', body: 'Document each escalation so the next manager can act without reconstructing the case.', href: '/services/omnichannel-customer-support', cta: 'Review customer support' }],
});

export const august17BlogBatch: readonly BlogPost[] = drafts.map(makePost);
