import type {BlogPost} from './data';

const topics = [
  ['call-center-shift-opening-readiness-check','Call Center Shift-Opening Readiness Check','Open each support shift with a control check covering queue health, system access, current notices, staffing, and escalation ownership.','shift opening','Confirm the phone and case queues accept work, named users can reach only required tools, and the current customer notice is visible before the first contact.'],
  ['outsourced-call-center-daily-capacity-brief','Outsourced Call Center Daily Capacity Brief','Turn staffing, forecast, backlog, and known events into one daily capacity decision managers and outsourced teams can act on.','daily capacity','Compare scheduled coverage with interval demand, aged work, training time, absences, and planned campaigns instead of relying on headcount alone.'],
  ['call-center-unresolved-case-rollover','Call Center Unresolved Case Rollover','Carry open customer cases across shifts without losing the promise, evidence, dependency, or accountable next owner.','case rollover','Separate actively owned cases from work waiting on a customer, blocked by an internal decision, or due for a promised update.'],
  ['call-center-live-queue-priority-rules','Call Center Live-Queue Priority Rules','Define observable priority rules so urgency, customer impact, age, and specialist needs are handled consistently.','live-queue priority','Write signals the routing system and supervisor can observe, including safety impact, outage, promised callback, age, and required skill.'],
  ['outsourced-call-center-attendance-exception-handoff','Outsourced Call Center Attendance Exception Handoff','Handle absences and emergency schedule changes through a private, owned coverage workflow rather than the customer queue.','attendance exceptions','Capture only the scheduling facts needed to protect coverage; keep medical, payroll, and personnel details in authorized systems.'],
  ['call-center-first-hour-quality-sample','Call Center First-Hour Quality Sample','Use a small first-hour review to catch access, script, routing, and documentation problems before they spread through a shift.','first-hour sampling','Compare representative source interactions with approved guidance, dispositions, notes, and promised next steps.'],
  ['call-center-customer-promise-register','Call Center Customer Promise Register','Track callbacks, updates, credits under review, and other commitments with a due time and accountable owner.','customer promises','Record the exact commitment, customer time zone, approved channel, due window, dependency, and owner in the system of record.'],
  ['outsourced-call-center-intraday-reforecast','Outsourced Call Center Intraday Reforecast','Reforecast the remaining day when demand, handle time, absence, or outage makes the opening staffing plan unreliable.','intraday reforecasting','Use completed intervals and current backlog to update expected demand and available productive time for the hours that remain.'],
  ['call-center-escalation-response-clock','Call Center Escalation Response Clock','Give every escalation an acknowledgment deadline, decision deadline, backup owner, and customer-update requirement.','escalation clocks','Start from a defined event and distinguish acknowledgment from resolution so a received alert is not mistaken for a completed decision.'],
  ['call-center-end-of-shift-reconciliation','Call Center End-of-Shift Reconciliation','Close each shift by reconciling open contacts, promised follow-ups, queue states, incidents, and accepted handoffs.','shift reconciliation','Compare the phone platform, CRM, ticket queue, callback list, and escalation record for unfinished or mismatched work.'],
  ['outsourced-call-center-daily-access-anomaly-review','Outsourced Call Center Daily Access Anomaly Review','Review failed sign-ins, unusual permission requests, shared-account signals, and unexpected exports without making agents investigators.','access anomalies','Collect the timestamp, named account, system, observed event, and business task without passwords, codes, or copied customer data.'],
  ['call-center-next-day-action-log','Call Center Next-Day Action Log','Convert daily operating findings into an owned list of decisions, fixes, and verification steps for the next service day.','next-day actions','Include only actions with a clear outcome, owner, due time, source evidence, and definition of completion.'],
] as const;

export const september1BlogBatch: readonly BlogPost[] = topics.map(([slug,title,excerpt,focus,specific],index)=>({
 slug,title,excerpt,keyword:title,published:'2026-09-01',updated:'2026-09-01',minutes:9+(index%4),intro:`${excerpt} For Call Center Outsourced buyers, ${focus} should be a visible operating record rather than a habit that depends on who is online.`,
 sections:[
  {title:`Define the ${focus} decision`,paragraphs:[specific,`State the trigger, permitted action, finish condition, and evidence. The written ${focus} rule must work during an ordinary interval and a pressured one.`],items:['Name the authoritative record','Set an observable trigger','Define a complete result','Assign the decision owner']},
  {title:'Start with the current operating state',paragraphs:[`Read the live queue, schedule, and approved notices before acting. Historical averages inform ${focus}, but they do not replace current state.`,'Mark unavailable or conflicting inputs explicitly. A reviewer can resolve a visible gap, not an assumption hidden in a completed status.']},
  {title:'Keep authority with the right owner',paragraphs:[`Team members may collect facts and complete approved reversible steps for ${focus}. Managers retain policy, staffing, access, security, and customer-remedy decisions.`,'Use named accounts and current guidance. Escalate an exception with its source evidence, customer impact, next owner, and due time.'],items:['Record facts separately from recommendations','Use minimum necessary access','Keep sensitive decisions with the owner','Publish approved changes through change control']},
  {title:'Measure the result, not just activity',paragraphs:[`Review whether the ${focus} record produced the intended queue and customer outcome. Pair counts with timeliness, rework, missed handoffs, and exceptions.`,`Sample the source and finished record together to test whether the action preserved the customer promise and next-owner context.`]},
  {title:'Build an executable handoff',paragraphs:['Identify the case or interval, observed condition, action taken, open decision, impact, owner, and due time.','Keep secrets and unnecessary customer data out of coordination notes; link to the approved source where permitted.'],items:['Reference the source record','State what changed','Name the open decision','Obtain next-owner acceptance']},
  {title:'Use a safe pause statement',paragraphs:[`When the ${focus} rule does not cover the situation, say: “I preserved the current record and completed the approved step. The named owner is reviewing the remaining decision.”`]},
  {title:'Review before expanding',paragraphs:[`Review ${focus} exceptions, delays, rework, and customer impact after the first cycle. Update instructions only through the named owner.`,`Record the effective time, reason, and verification sample while preserving the earlier record.`],items:['Review normal work and an exception','Approve and date changes','Brief affected coverage','Verify the next live example']},
 ],
 controlTable:[{data:'Complete routine input',agent:'Complete the documented reversible step',manager:'Review the agreed sample'},{data:'Missing or conflicting input',agent:'Pause and record the gap',manager:'Choose the fallback'},{data:'Sensitive or irreversible decision',agent:'Preserve context and escalate',manager:'Verify and decide'},{data:'Repeated process failure',agent:'Tag examples without inventing a fix',manager:'Own correction and change control'}],
 scripts:[{situation:'Approved action',text:'“I completed the documented step and recorded the result.”'},{situation:'Decision required',text:'“The facts are recorded; the named owner must decide the remaining action.”'},{situation:'Input missing',text:'“I will not guess; I am documenting what is missing.”'}],
 faqs:[{question:`Who owns ${focus}?`,answer:'Assign one client-side process owner and a backup who can decide exceptions and approve changes.'},{question:'What should the first review include?',answer:'Compare representative source and finished records, including a normal case and an exception.'},{question:'When should the routine expand?',answer:'Expand after inputs, permissions, handoffs, and review results are stable for the pilot scope.'}],
 sources:[{name:'Cybersecurity Framework 2.0',organization:'NIST',date:'February 2024',url:'https://www.nist.gov/cyberframework',note:'Governance and accountable-control context.'},{name:'ISO 18295-1:2017 Customer contact centres',organization:'International Organization for Standardization',date:'July 2017',url:'https://www.iso.org/standard/64739.html',note:'Customer-contact process context.'}],
 related:[{label:'Review operations support',href:'/services/operations-support'},{label:'Plan reporting support',href:'/services/workforce-reporting-support'},{label:'Explore more guides',href:'/blog'}],banners:[{label:'Scope',title:`Document the ${focus} lane`,body:'Define the trigger, tools, limits, evidence, and owner.',href:'/contact-us',cta:'Discuss the workflow'},{label:'Review',title:'Test one operating cycle',body:'Use representative records and a named reviewer.',href:'/services/operations-support',cta:'Review operations support'},{label:'Improve',title:'Version approved changes',body:'Keep decisions traceable as the routine improves.',href:'/blog',cta:'Read more guides'}],
}));
