import type { BlogPost } from './data';

type Draft = {
  slug: string;
  title: string;
  excerpt: string;
  intro: string;
  focus: string;
  advice: string;
  measure: string;
  handoff: string;
  published: '2026-08-13';
  updated: '2026-08-13';
};

const drafts: readonly Draft[] = [
  { slug: 'call-center-call-disposition-accuracy', title: 'Improve call disposition accuracy without slowing the queue', excerpt: 'A practical way to make disposition choices consistent enough for routing and reporting.', intro: 'A disposition is useful only when it describes what happened and what should happen next. Too many labels create guesses; too few hide work that still needs an owner.', focus: 'List the decisions the disposition must support, then write one plain definition and one example for each high-volume choice.', advice: 'Put the outcome before the detail. If two labels lead to the same action, combine them and review the edge cases with a supervisor.', measure: 'Compare label agreement in a small sample, reassignment rate, uncategorized calls, and follow-up work created by each outcome.', handoff: 'Send a disputed definition or a new customer situation to the person who owns routing rules.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-call-quality-calibration', title: 'Run a call quality calibration that reviewers can repeat', excerpt: 'A focused calibration session helps reviewers apply the same quality standard to similar calls.', intro: 'Quality scores become hard to trust when reviewers use different versions of the rubric. Calibration gives them a shared example and a place to record why a score was chosen.', focus: 'Choose a small set of calls that represent normal work and common edge cases. Mark the exact rubric line each reviewer used.', advice: 'Discuss disagreements by returning to the written standard. Change the rubric only through its owner, and keep the old version identifiable.', measure: 'Track score spread, disagreement reasons, review completion, and corrections after the calibration.', handoff: 'Escalate a rubric conflict to the quality owner instead of averaging incompatible scores.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-voicemail-triage', title: 'Create a voicemail triage rule that protects urgent callers', excerpt: 'A clear voicemail rule separates urgent requests from routine follow-up and keeps ownership visible.', intro: 'Voicemails arrive without the questions a live conversation would normally answer. Triage should identify urgency, permitted callback details, and the next owner before anyone promises a response.', focus: 'Define the urgent signals, minimum note fields, callback window, and route for messages that lack enough information.', advice: 'Use a neutral callback message and avoid repeating private details. Keep one queue for messages awaiting clarification so they do not vanish in personal inboxes.', measure: 'Review time to first review, missed urgent messages, duplicate callbacks, and notes without an owner.', handoff: 'Send safety, privacy, payment, and identity concerns through the named escalation path.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-order-status-calls', title: 'Handle order-status calls with a dependable answer path', excerpt: 'A status-call workflow keeps source data, customer wording, and promised follow-up aligned.', intro: 'Customers calling about an order usually want a simple answer, but the record may contain a delay, a handoff, or an exception. The team needs a source of truth and a safe fallback when it is incomplete.', focus: 'Name the system that confirms status, the details that may be disclosed, and the owner for late or disputed orders.', advice: 'Repeat the status in plain language and state the next confirmed event. Do not invent a delivery date from an estimate that the team cannot verify.', measure: 'Track repeat status calls, answer accuracy, unresolved delays, and promises that were later changed.', handoff: 'Escalate missing records, disputed delivery information, and requests for an exception.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-refund-request-routing', title: 'Route refund requests without making promises too early', excerpt: 'A refund intake path can gather the facts while leaving approval with the right owner.', intro: 'A representative can record why a customer wants a refund and explain what will be reviewed. Approval should stay with the person who owns the policy and account authority.', focus: 'Capture the transaction reference, request reason, relevant dates, and the approved review window without exposing unnecessary payment information.', advice: 'Use conditional language until the owner decides. Keep the customer updated on the review step, not an outcome that is still uncertain.', measure: 'Review routing accuracy, missing intake fields, repeat contacts, and requests that received an unauthorized promise.', handoff: 'Send exceptions, disputed charges, and policy questions to the designated owner.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-peak-shift-handoff', title: 'Write a peak-shift handoff that the next supervisor can use', excerpt: 'A short shift handoff records queue condition, open promises, and decisions still waiting.', intro: 'A busy shift leaves behind more than a number. The next supervisor needs to know which contacts are aging, which promises are at risk, and what decision is already in motion.', focus: 'Use a fixed order for queue state, urgent work, promised callbacks, staffing constraints, and unresolved owner questions.', advice: 'Write facts first and label estimates as estimates. Include the next review time so the handoff does not become a static status note.', measure: 'Check whether the next shift can find open owners, overdue promises, and the reason for each exception without asking the previous supervisor.', handoff: 'Escalate an immediate customer or safety risk through the live path, then preserve the detail in the durable handoff.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-call-tagging-guide', title: 'Build a call tagging guide for cleaner staffing decisions', excerpt: 'Good tags connect customer demand to a decision about coverage, training, or routing.', intro: 'Tags should answer a business question. When a label is added because it sounds plausible rather than because it changes an action, reports become decorative.', focus: 'Start with the staffing and service decisions the report must support. Keep the tag set small enough for a representative to apply during a normal call.', advice: 'Show a near-match example for every common tag. Retire labels that no longer lead to a report, route, or review.', measure: 'Look at tag agreement, missing tags, reassignment, and whether weekly reports produce a named action.', handoff: 'Ask the reporting owner to resolve overlapping definitions before a new tag enters the live queue.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-chat-concurrency-rules', title: 'Set chat concurrency rules around response quality', excerpt: 'A chat limit should reflect message complexity, response timing, and the help available to the team.', intro: 'More simultaneous chats can look efficient until replies become rushed or customers repeat themselves. A sensible limit starts with the kind of work the queue receives.', focus: 'Separate simple status questions from troubleshooting or sensitive requests, then set a starting limit for each type.', advice: 'Give the representative a visible way to pause new chats and a clear route for a conversation that needs another owner.', measure: 'Track first reply time, missed questions, transfers, abandoned chats, and quality samples by concurrency level.', handoff: 'Escalate when the queue limit no longer protects response quality or when a chat needs specialist access.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-customer-language-preferences', title: 'Capture language preferences without losing customer context', excerpt: 'A language preference record should help the next contact start in the right place.', intro: 'Language preference is a service detail, not a substitute for understanding the request. The record should carry the requested language, the reason for contact, and any approved interpretation route.', focus: 'Define where preference is stored, when it may be updated, and how a team member handles a language need the current queue cannot cover.', advice: 'Use the customer’s own stated preference and do not infer it from a name, accent, or prior contact.', measure: 'Review repeat explanations, incorrect routing, delayed language support, and preference changes that lack a source interaction.', handoff: 'Escalate sensitive terminology or a missing qualified language route to the service owner.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-call-backlog-cleanup', title: 'Clean an old call backlog without hiding unresolved work', excerpt: 'A backlog cleanup separates completed work from contacts that still need a real response.', intro: 'Old contacts create pressure to close records quickly. The safer approach is to identify what is complete, what is still owed, and what cannot be resolved without a decision.', focus: 'Group the backlog by age, reason, last action, promised next step, and current owner before changing statuses.', advice: 'Use a small review queue for uncertain records. A closed status should point to evidence, not merely a lack of recent activity.', measure: 'Report verified closures, reopened contacts, overdue promises, duplicate records, and unresolved items by age.', handoff: 'Escalate records involving safety, payment, privacy, or a customer promise that cannot be met.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-call-transfer-context', title: 'Preserve customer context during a specialist transfer', excerpt: 'A concise transfer note reduces repetition and gives the receiving specialist a usable starting point.', intro: 'A transfer should move the work, not the burden of explaining it. The receiving person needs the request, facts already confirmed, action taken, and decision still open.', focus: 'Define the minimum transfer summary and the conditions for a warm transfer, a queue transfer, or a callback.', advice: 'Read back the summary when the customer is present and correct it before releasing the contact. Do not copy unrelated account details.', measure: 'Watch repeat explanations, rejected transfers, transfer loops, abandoned transfers, and resolution after the handoff.', handoff: 'Send a transfer loop or unavailable specialist to the supervisor who owns queue routing.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-contact-reason-review', title: 'Review contact reasons to find the work behind the volume', excerpt: 'A reason review turns call counts into questions about scripts, service gaps, and coverage.', intro: 'Volume alone does not explain why customers call. A reason review combines the customer question with the result and any follow-up the business had to create.', focus: 'Compare the most common reasons with repeat contacts, transfers, resolution, and unresolved ownership.', advice: 'Review a sample of each high-volume reason before changing staffing or scripts. Keep a clear distinction between a customer need and a process defect.', measure: 'Track reason share, first-contact resolution, repeat contact rate, transfer rate, and follow-up age.', handoff: 'Escalate a growing reason that signals a service or policy problem to its accountable owner.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-customer-escalation-intake', title: 'Improve escalation intake before a manager sees the case', excerpt: 'A complete escalation note lets a manager decide quickly while preserving the customer’s actual concern.', intro: 'Escalation is a handoff of decision-making, not a way to discard a difficult contact. The intake should tell the manager why the case crossed the boundary and what has already been tried.', focus: 'Capture the customer request, verified facts, impact, current promise, action taken, and decision needed.', advice: 'Separate evidence from the representative’s recommendation. If the request is urgent, use the immediate channel and keep the written note concise.', measure: 'Review missing fields, decision time, returned escalations, repeat contacts, and cases sent to the wrong owner.', handoff: 'Use the named urgent route for safety, legal, privacy, or high-impact account concerns.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-shift-coverage-gaps', title: 'Spot shift coverage gaps before customers feel them', excerpt: 'A coverage review connects schedule gaps to queue demand and the customer promises at risk.', intro: 'A schedule can look full while the wrong skill or channel is uncovered. Coverage review should show when demand arrives, what work needs a particular capability, and who can make a change.', focus: 'Compare interval demand with available coverage, skill requirements, breaks, and known absence rather than relying on total headcount.', advice: 'Flag the first decision point and the temporary response. Keep a manager approval step for schedule changes and customer promises.', measure: 'Track wait time by interval, abandoned contacts, uncovered skills, overtime requests, and recovery after a gap.', handoff: 'Escalate a gap that needs staffing, schedule, or service-promise changes to the accountable manager.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-support-inbox-ownership', title: 'Give every shared support inbox message an owner', excerpt: 'A simple ownership rule prevents shared inbox messages from being answered twice or left unseen.', intro: 'A shared inbox behaves like a queue even when it has no queue screen. Status, owner, next action, and age make the work visible across shifts.', focus: 'Define the allowed statuses, the backup owner, the aging threshold, and the rule for messages that need a policy decision.', advice: 'Keep the customer message linked to the internal record. Do not archive a message until the required response or handoff is recorded.', measure: 'Review unowned messages, duplicate replies, first response time, aged items, and reopened threads.', handoff: 'Send a policy conflict or sensitive customer request to the named owner instead of leaving it in a general inbox.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-appointment-change-calls', title: 'Handle appointment-change calls with one source of truth', excerpt: 'A controlled appointment-change path reduces double booking and unclear customer promises.', intro: 'Appointment changes combine customer preference, calendar availability, and sometimes a rule about notice. The person handling the call needs a current calendar and a defined fallback.', focus: 'Name the calendar source, permitted changes, required confirmation, and route for exceptions or missing availability.', advice: 'Repeat the final date and time with the relevant time zone. Record the request before making a change and do not promise an opening that is not confirmed.', measure: 'Track reschedules, duplicate bookings, no-shows after a change, confirmation accuracy, and exceptions awaiting review.', handoff: 'Escalate schedule conflicts, identity uncertainty, and changes outside the written rule.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-customer-record-merge-review', title: 'Review possible duplicate customer records safely', excerpt: 'A duplicate review protects history by separating evidence from a tempting quick merge.', intro: 'Two similar names or phone numbers do not prove that records belong to one person. A merge can remove context that another team needs, so it deserves a narrow review path.', focus: 'List the approved matching fields, required authority, audit note, and stop conditions for a possible duplicate.', advice: 'Do not merge on a single shared value. Leave uncertain records unchanged and link the review request to the evidence used.', measure: 'Review confirmed matches, reversals, duplicate reopenings, missing audit notes, and false-positive reviews.', handoff: 'Send identity, privacy, ownership, and historical-record questions to the record owner.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-after-hours-message-design', title: 'Write after-hours messages that set a safe expectation', excerpt: 'An after-hours message should state what happens next without implying live coverage that is not available.', intro: 'Customers need to know whether to leave a message, use another channel, or wait for the next staffed period. The message should be short, accurate, and consistent with the queue’s actual ownership.', focus: 'Set the staffed window, urgent exception route, message fields, and expected first response without promising a result.', advice: 'Use plain language and avoid asking callers to disclose sensitive details in a voicemail. Review the message when hours or escalation paths change.', measure: 'Track messages received outside coverage, urgent-route use, repeat calls, and responses outside the stated window.', handoff: 'Escalate any urgent message according to its named route, then record the action in the approved system.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-customer-follow-up-ownership', title: 'Make customer follow-up ownership visible across shifts', excerpt: 'A follow-up record should make the promised action, owner, deadline, and current status easy to find.', intro: 'Follow-up fails when it lives in memory or a private note. A shared record gives the next shift enough context to protect the customer promise.', focus: 'Capture the reason for follow-up, approved channel, promised window, owner, backup owner, and completion evidence.', advice: 'Review aging follow-ups at the start of each shift. If a deadline is at risk, update the record and route a truthful customer update through the approved channel.', measure: 'Track on-time completion, overdue items, missing owners, duplicate attempts, and follow-ups reopened by the customer.', handoff: 'Escalate a missed high-impact promise or an uncertain contact permission to the owner.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-call-script-change-control', title: 'Control call script changes so the live team sees one answer', excerpt: 'A small change-control rule prevents old and new call wording from circulating at the same time.', intro: 'A script change affects what customers hear and what the team records. Without one owner and an effective date, different representatives may follow incompatible instructions.', focus: 'Record the reason for the change, approving owner, exact wording, effective date, and retired version.', advice: 'Publish one current version and show a clear example of the changed line. Remove outdated copies from the places the team actually uses.', measure: 'Review version usage, coaching corrections, customer confusion, repeat contacts, and changes missing approval.', handoff: 'Escalate a policy conflict or urgent wording change to the owner who can approve it.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-urgent-call-identification', title: 'Identify urgent calls with a rule the queue can apply', excerpt: 'An urgent-call rule should be specific enough to trigger action and narrow enough to avoid false alarms.', intro: 'Urgency is easy to claim and hard to manage when the rule is vague. The team needs observable signals, a response path, and a record of what was done.', focus: 'Define the signals that require immediate review, the questions allowed at intake, and the owner who receives the alert.', advice: 'Do not promise priority outcomes before the owner confirms them. Record the caller’s words and the action taken rather than a dramatic summary.', measure: 'Review urgent-call agreement, response time, missed signals, false escalations, and unresolved urgent records.', handoff: 'Use the immediate escalation path for safety, legal, privacy, or serious service-impact concerns.', published: '2026-08-13', updated: '2026-08-13' },
  { slug: 'call-center-weekly-queue-review', title: 'Make the weekly queue review lead to a decision', excerpt: 'A short queue review connects service data to an owner, a next action, and a date for checking the result.', intro: 'A weekly queue meeting can become a tour of dashboards. It is more useful when every exception has a reason, a decision owner, and a follow-up point.', focus: 'Bring only the measures that change a choice: aging work, response time, repeat contact, quality findings, and open promises.', advice: 'Write the decision beside the number. Keep unresolved questions visible and close the meeting with one owner and a review date for each material action.', measure: 'Track actions completed, recurring exceptions, stale decisions, queue age, and whether the same issue returns the following week.', handoff: 'Escalate a decision that requires policy, staffing, access, or commercial authority to its owner.', published: '2026-08-13', updated: '2026-08-13' },
];

const makePost = (draft: Draft, index: number): BlogPost => ({
  slug: draft.slug, title: draft.title, excerpt: draft.excerpt, minutes: 8 + (index % 4), keyword: draft.title,
  published: draft.published, updated: draft.updated, intro: draft.intro,
  sections: [
    { title: 'Start with the decision', paragraphs: [draft.focus, `Write the starting signal, permitted action, and finished record for ${draft.title.toLowerCase()}.`], items: ['Name the record or queue', 'Show one completed example', 'List the review point', 'Name the owner'] },
    { title: 'Keep the first version narrow', paragraphs: [draft.advice, 'Use one channel or task type first. Review a small sample before adding more work.'] },
    { title: 'Keep the authority line visible', paragraphs: ['The service team can collect facts, follow approved wording, update permitted fields, and route work. Managers keep exceptions, sensitive decisions, and policy changes.', draft.handoff], items: ['Follow the written path', 'Record the evidence', 'Pause when authority is unclear', 'Escalate to the named owner'] },
    { title: 'Measure what a supervisor can use', paragraphs: [draft.measure, 'Pair volume with quality, timeliness, and ownership so a number leads to a practical decision.'] },
    { title: 'Protect context during handoffs', paragraphs: [draft.handoff, 'Keep unnecessary customer details out of general notes and point the owner to the protected source record.'], items: ['State what happened', 'State what remains', 'Name the next owner', 'Record the deadline'] },
    { title: 'Use honest customer language', paragraphs: ['Give the team one sentence for the normal path and one for uncertainty. State the next confirmed action without promising an outcome that still needs approval.'] },
    { title: 'Review the first sample', paragraphs: ['Look for missing fields, repeated questions, avoidable transfers, and conflicts between the written rule and the tool. Fix the rule before expanding it.'], items: ['Sample early work', 'Discuss exceptions', 'Update the example', 'Expand only after review'] },
  ],
  controlTable: [
    { data: 'Routine request', agent: 'Follow the approved path and record the result', manager: 'Review samples and maintain the rule' },
    { data: 'Missing information', agent: 'Ask the approved question or pause', manager: 'Decide the safe fallback' },
    { data: 'Sensitive exception', agent: 'Do not complete it without approval', manager: 'Verify evidence and decide' },
    { data: 'Ownership conflict', agent: 'Keep the record unchanged and escalate', manager: 'Assign the owner' },
  ],
  scripts: [
    { situation: 'Normal path', text: 'I have recorded the request and will complete the approved next step.' },
    { situation: 'Needs review', text: 'This part needs review, so I will send it to the named owner.' },
    { situation: 'Unclear case', text: 'I do not want to guess. I will record what is known and confirm the next step.' },
  ],
  faqs: [
    { question: 'What should happen first?', answer: draft.focus },
    { question: 'What stays with a manager?', answer: draft.handoff },
    { question: 'What should the first review measure?', answer: draft.measure },
  ],
  sources: [{ name: 'Zero Trust Architecture, SP 800-207', organization: 'National Institute of Standards and Technology', date: 'August 2020', url: 'https://csrc.nist.gov/pubs/sp/800/207/final', note: 'Supports narrow access and explicit decision boundaries.' }, { name: 'ISO 18295-1 overview', organization: 'International Organization for Standardization', date: '2017', url: 'https://www.iso.org/standard/65137.html', note: 'Supports defined contact-centre processes and service outcomes.' }],
  related: [{ label: 'Review customer support', href: '/services/omnichannel-customer-support' }, { label: 'Review operations support', href: '/services/inbound-call-handling' }, { label: 'Review reporting support', href: '/services/workforce-reporting-support' }],
  banners: [{ label: 'Scope', title: 'Define the first queue', body: 'List the work, review points, and approval limits before adding coverage.', href: '/services/inbound-call-handling', cta: 'Review operations support' }, { label: 'Review', title: 'Use representative examples', body: 'Sample early work with a named owner and fix unclear rules quickly.', href: '/services/workforce-reporting-support', cta: 'Review reporting support' }, { label: 'Handoff', title: 'Keep decisions visible', body: 'Record the next owner whenever work crosses an authority line.', href: '/services/omnichannel-customer-support', cta: 'Review customer support' }],
});

export const august13ReplacementBlogBatch: readonly BlogPost[] = drafts.map(makePost);
