import type {BlogPost} from './data';
import {makeBuyerGuide,type Topic} from './blog-sep23';

export const october2BlogPublicationDate='2026-10-02'; // reconcile immediately before the sole push
const image='/blog-aug20/outsourced-call-center-qa-sample-selection.png';

const topics:readonly Topic[]=[
 {slug:'outsourced-call-center-discovery-workshop',title:'How to Run an Outsourced Call Center Discovery Workshop',excerpt:'Turn customer journeys, volumes, systems, authority, and exceptions into an implementation-ready operating brief.',decision:'leave discovery with approved scope, named owners, evidence gaps, and decisions rather than a presentation',scenario:'Sales assumptions reach implementation as facts, while frontline exceptions and system dependencies remain undocumented.',inputs:'customer reasons, channel and interval demand, languages, systems, data, identity, actions, promises, escalations, quality, reporting, risks, and owners',pilot:'replay representative journeys and exceptions with operations, technology, risk, and provider participants',metric:'decisions closed, evidence gaps, unowned dependencies, journey coverage, assumption age, and acceptance',boundary:'Discovery documents the operating truth; authorized client owners still approve policy, risk, commercial, and launch decisions.',image},
 {slug:'call-center-outsourcing-risk-register',title:'Build a Call Center Outsourcing Risk Register That Drives Action',excerpt:'Connect each outsourcing risk to a customer consequence, early signal, control, owner, and tested response.',decision:'prioritize observable customer and operating exposure instead of maintaining a generic risk list',scenario:'A register says service disruption is high risk but names no trigger, fallback, customer message, or decision owner.',inputs:'journeys, critical systems, data, suppliers, staffing, sites, controls, incidents, dependencies, obligations, thresholds, and owners',pilot:'simulate loss of a system, site, supplier, skill, decision owner, and trusted data source',metric:'open exposure, overdue controls, trigger detection, response time, recovery evidence, recurrence, and residual acceptance',boundary:'The provider owns its controls; the buyer owns business appetite, customer remedies, and acceptance of residual risk.',image},
 {slug:'inbound-call-routing-requirements',title:'Inbound Call Routing Requirements Before Outsourcing',excerpt:'Specify intent, skill, identity, language, priority, fallback, and transfer context before routing production calls.',decision:'route from explicit evidence and authority rather than phone number, menu choice, or agent availability alone',scenario:'A caller selects billing, reaches a general queue, repeats verification, and loses context during a second transfer.',inputs:'entry numbers, menus, intents, languages, skills, identity states, hours, priority, transfers, callbacks, failures, and owners',pilot:'place synthetic calls through every normal, ambiguous, unavailable, urgent, multilingual, and after-hours path',metric:'correct destination, context retained, repeat verification, transfers, loops, abandons, safe fallback, and resolution',boundary:'Routing may place work; it cannot establish identity, entitlement, urgency, or permission for a material action.',image},
 {slug:'customer-support-escalation-playbook',title:'Customer Support Escalation Playbook for an Outsourced Team',excerpt:'Give representatives a usable path from trigger recognition to owner acceptance, customer update, and closure.',decision:'escalate by customer impact and authority boundary with one accountable accepting owner',scenario:'A representative posts an urgent case in chat, but nobody accepts it and the customer receives no next-update time.',inputs:'triggers, severity, permitted containment, customer wording, owners, backups, channels, timers, evidence, closure, and review',pilot:'exercise safety, privacy, payment, outage, abusive-contact, missed-promise, and unavailable-owner scenarios',metric:'trigger accuracy, acceptance time, update timeliness, transfers, unresolved age, containment, closure evidence, and recurrence',boundary:'Frontline staff identify and contain within scope; specialists make legal, security, policy, and remedy decisions.',image},
 {slug:'order-support-exception-matrix',title:'Order Support Exception Matrix for Outsourced Service',excerpt:'Define what agents may answer, change, pause, or escalate at each order and fulfillment state.',decision:'tie every permitted action to item state, evidence, customer impact, and an authorized exception owner',scenario:'An agent promises cancellation from a storefront status while the warehouse has already packed one of three items.',inputs:'order and line states, payments, fraud holds, warehouse events, carriers, addresses, cancellations, refunds, replacements, and owners',pilot:'test split shipments, stale events, duplicate orders, address changes, damaged items, payment conflicts, and partial cancellation',metric:'correct actions, prevented duplicates, promise accuracy, exception age, transfers, refunds reconciled, and repeat contacts',boundary:'Support reports verified state and executes listed actions; merchants retain eligibility, fraud, refund, and policy exceptions.',image},
 {slug:'omnichannel-support-case-ownership',title:'Omnichannel Support Case Ownership Without Duplicate Work',excerpt:'Keep one accountable owner while calls, email, chat, text, and portal events arrive at different times.',decision:'link contacts from approved evidence, reconcile current state, and assign one owner before material action',scenario:'An email refund request arrives after chat already issued a replacement, and two agents act from different case views.',inputs:'channel identifiers, event and receipt time, case links, state versions, pending work, actions, promises, conflicts, and owners',pilot:'replay delayed, duplicated, out-of-order, identity-conflicting, reopened, and simultaneous contacts',metric:'correct linkage, duplicate actions, ownership gaps, stale-state work, unresolved conflicts, repeats, and final outcomes',boundary:'Similarity suggests review but never proves identity or authorizes merging customer records.',image},
 {slug:'appointment-setting-list-readiness',title:'Appointment-Setting List Readiness Before Outbound Calling',excerpt:'Validate purpose, source, suppression, time zone, eligibility, and slot availability before a list reaches agents.',decision:'release only records with a current approved purpose, contact state, local-time basis, and bookable workflow',scenario:'A stale export includes cancelled requests, changed preferences, and territories with no eligible appointment capacity.',inputs:'source and extraction time, purpose, consent or authority state, suppression, time zone, eligibility, availability, scripts, and owners',pilot:'sample ordinary, stale, conflicting, duplicate, reassigned-number, boundary-time, and no-capacity records',metric:'eligible records, suppressions, stale states, wrong-time attempts, bookings, reversals, complaints, and unresolved exceptions',boundary:'Agents apply approved rules; client owners determine campaign classification, eligibility, contact requirements, and exceptions.',image},
 {slug:'tier-one-support-scope-document',title:'Write a Tier-One Technical Support Scope Document',excerpt:'Translate products, device contexts, diagnostics, access, prohibited actions, and escalation into usable frontline limits.',decision:'permit only versioned diagnostic steps whose evidence, reversibility, and ownership boundary are known',scenario:'A customer asks an agent to change a security setting on an employer-managed device outside the approved product scope.',inputs:'products, versions, device ownership, identity, entitlements, symptoms, tools, logs, data classes, steps, stop rules, and owners',pilot:'test unknown devices, sensitive logs, unavailable tools, risky changes, accessibility needs, outages, and failed recovery',metric:'scope accuracy, safe resolution, prohibited steps stopped, escalations, repeats, evidence exposure, and recovery',boundary:'Tier one gathers bounded evidence and performs approved reversible steps; product, security, and engineering owners decide exceptions.',image},
 {slug:'call-center-transition-knowledge-transfer',title:'Knowledge Transfer for an Outsourced Call Center Transition',excerpt:'Move source-backed decisions and exceptions into searchable, owned knowledge that survives launch and shift changes.',decision:'accept knowledge only when its authority, audience, effective time, examples, and conflict path are visible',scenario:'Training slides contradict the live policy, while experienced staff answer edge cases from private messages.',inputs:'source documents, owners, versions, effective dates, journeys, examples, exceptions, search terms, training, and retirement rules',pilot:'have new workers answer ordinary, ambiguous, changed, conflicting, and high-impact cases from the knowledge system alone',metric:'findability, answer accuracy, conflicts, unknown handling, update latency, certification, repeats, and retired content',boundary:'The provider maintains and applies approved knowledge; client policy owners resolve ambiguity and authorize change.',image},
 {slug:'outsourced-call-center-governance-meeting',title:'Run an Outsourced Call Center Governance Meeting That Makes Decisions',excerpt:'Use a decision-led operating review instead of reading dashboards aloud and carrying the same actions forward.',decision:'spend meeting time on customer impact, exceptions, evidence, tradeoffs, and decisions with named owners',scenario:'The monthly review celebrates average service while severe complaints, old escalations, and disputed metrics remain unresolved.',inputs:'customer outcomes, interval service, quality defects, complaints, repeats, staffing, changes, risks, actions, decisions, and evidence',pilot:'trace one successful journey, one failure, one exception, one disputed metric, and one overdue decision end to end',metric:'decisions made, action age, recurrence, accepted evidence, dependency resolution, customer recovery, and forecast accuracy',boundary:'Governance coordinates accountability but does not transfer specialist, employment, legal, privacy, or security authority.',image},
 {slug:'call-center-service-recovery-workflow',title:'Call Center Service Recovery Workflow After a Customer Failure',excerpt:'Separate acknowledgment, containment, remedy, correction, and prevention so a closed ticket does not hide unresolved harm.',decision:'restore the customer outcome while preserving facts and assigning corrective work to the right owner',scenario:'A missed callback is closed after an apology although the original request, downstream action, and recurrence risk remain open.',inputs:'customer account of impact, verified chronology, promises, actions, authority, remedy options, dependencies, communications, and cause evidence',pilot:'reconstruct missed promises, duplicate actions, incorrect information, transfer loops, outages, and inaccessible service',metric:'acknowledgment, containment, remedy time, repeat contact, reopen rate, displaced harm, corrective action, and recurrence',boundary:'Representatives acknowledge and contain within authority; authorized owners decide compensation, liability, policy, and systemic change.',image},
 {slug:'call-center-vendor-exit-plan',title:'Call Center Vendor Exit Plan: Protect Customers and Operating Continuity',excerpt:'Plan data return, access removal, knowledge transfer, queue cutover, open-work ownership, and evidence before termination pressure.',decision:'prove continuity and controlled separation before removing the incumbent path',scenario:'The contract ends while callbacks, complaints, recordings, credentials, numbers, and undocumented knowledge remain with the provider.',inputs:'channels, numbers, systems, accounts, data, records, knowledge, open work, suppliers, assets, obligations, cutover, and owners',pilot:'rehearse queue transfer, open-case migration, access revocation, data return, failed deletion, rollback, and customer messaging',metric:'inventory coverage, migrated work, reconciled records, revoked access, returned assets, deletion evidence, defects, and stability',boundary:'Exit execution follows approved legal, privacy, security, records, commercial, and customer-continuity decisions.',image}
] as const;

export const october2BlogBatch:readonly BlogPost[]=topics.map((topic,index)=>{
 const post=makeBuyerGuide(topic,index,october2BlogPublicationDate);
 return {...post,intro:`${topic.excerpt} This guide gives buyers a practical way to define the work, test the weak points, and preserve accountable decisions before outsourced volume expands.`,minutes:13+(index%4)};
});
