export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; sections: readonly { heading: string; body: string }[]; sources?: readonly { name: string; url: string }[]; keyStats?: readonly string[]; takeaways?: readonly string[]; faqs?: readonly { question: string; answer: string }[]; related?: readonly string[]; internalLinks?: readonly string[] };

export const fleetServices: readonly FleetService[] = [
  {
    slug: 'inbound-call-handling',
    title: 'Inbound Call Handling',
    desc: 'Add Filipino agents to your inbound queue for approved questions, message taking, appointment help, and clean manager handoffs.',
    tasks: [
      'Answer approved billing, order, booking, and account questions',
      'Take complete messages and confirm the best callback time',
      'Book or move appointments inside written scheduling rules',
      'Tag each call and send urgent or unusual cases to a manager',
    ],
    controls: [
      'Give each Filipino agent a named phone and CRM account',
      'Keep refunds, policy exceptions, and sensitive account changes with your manager',
      'Review a daily sample of recordings, call notes, and dispositions',
      'Set one escalation path for safety, legal, payment, or upset-customer calls',
    ],
    firstWeek: [
      'Share ten common call reasons, approved answers, and transfer rules',
      'Run practice calls before the agent enters the live queue',
      'Start with one queue and a limited shift while a manager is available',
      'Review the first twenty calls and fix gaps before adding more hours',
    ],
  },
  { slug: 'omnichannel-customer-support', title: 'Omnichannel Customer Support', desc: 'Build a Philippines-based omnichannel customer support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'outbound-appointment-setting', title: 'Outbound Appointment Setting', desc: 'Build a Philippines-based outbound appointment setting workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'order-management-support', title: 'Order Management Support', desc: 'Build a Philippines-based order management support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'tier-one-technical-support', title: 'Tier-One Technical Support', desc: 'Build a Philippines-based tier-one technical support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'collections-reminder-calls', title: 'Collections Reminder Calls', desc: 'Build a Philippines-based collections reminder calls workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'customer-win-back-support', title: 'Customer Win-Back Support', desc: 'Build a Philippines-based customer win-back support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'dispatch-coordination', title: 'Dispatch Coordination', desc: 'Build a Philippines-based dispatch coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'survey-and-feedback-calls', title: 'Survey and Feedback Calls', desc: 'Build a Philippines-based survey and feedback calls workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'workforce-reporting-support', title: 'Workforce Reporting Support', desc: 'Build a Philippines-based workforce reporting support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

// Add reviewed, source-backed original research here. The templates and sitemap update automatically.
const researchSources = [
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST Zero Trust Architecture, SP 800-207', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' },
  { name: 'NIST Digital Identity Guidelines, SP 800-63B', url: 'https://pages.nist.gov/800-63-3/sp800-63b.html' },
  { name: 'CISA Phishing Guidance', url: 'https://www.cisa.gov/stopthinkconnect' },
  { name: 'PCI DSS Document Library', url: 'https://www.pcisecuritystandards.org/standards/pci-dss/' },
  { name: 'FTC Telemarketing Sales Rule', url: 'https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule' },
  { name: 'FCC TCPA Consumer Guide', url: 'https://www.fcc.gov/general/telemarketing-and-robocalls' },
  { name: 'U.S. Department of Labor, FLSA', url: 'https://www.dol.gov/agencies/whd/flsa' },
  { name: 'ISO 18295-1 Customer Contact Centres', url: 'https://www.iso.org/standard/73338.html' },
] as const;

const researchBody = (title: string, finding: string, actions: string): ResearchPost => ({
  slug: title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), title,
  excerpt: finding, published: '2026-08-07', sources: researchSources,
  sections: [
    { heading: 'Method and evidence', body: `This desk review compares the operating question in ${title.toLowerCase()} with current guidance from NIST, CISA, PCI SSC, the FTC, the FCC, the U.S. Department of Labor, and ISO. The sources describe controls and obligations; they do not measure the performance of any individual outsourced team. Recommendations below are operating inferences, not legal advice.` },
    { heading: 'What the evidence supports', body: finding },
    { heading: 'Operating design', body: actions },
    { heading: 'Manager review questions', body: 'Which queue, customer data, and systems are in scope? What can an agent complete without approval? Which events require immediate escalation? Who owns the record, quality review, and policy decision? Recheck these answers whenever the workflow or channel changes.' },
  ],
});

const researchBodyV2 = (title: string, finding: string, actions: string, related: readonly string[]): ResearchPost => ({
  ...researchBody(title, finding, actions),
  published: '2026-08-08',
  keyStats: ['10 authoritative sources reviewed', '4 operating decisions to document', '3 named review owners required'],
  takeaways: [finding, actions, 'Use the evidence to define scope and controls; do not treat a source as proof of a vendor performance.'],
  related,
  internalLinks: ['/services/inbound-call-handling', '/services/omnichannel-customer-support'],
  faqs: [
    { question: 'Does this research set one universal operating rule?', answer: 'No. It identifies evidence-backed control questions; the client owner must set the approved workflow for the applicable jurisdiction, data, and channel.' },
    { question: 'What should a manager review first?', answer: 'Confirm the queue, systems, data, approval limits, escalation path, and record owner before assigning the task.' },
  ],
});

const researchBodyV3 = (first: string, second: string, third: string, fourth: string | readonly string[], fifth?: readonly string[], published = '2026-08-10'): ResearchPost => {
  const explicitSlug = fifth ? first : undefined;
  const title = fifth ? second : first;
  const finding = fifth ? third : second;
  const actions = fifth ? fourth as string : third;
  const related = (fifth || fourth) as readonly string[];
  return {
    ...researchBodyV2(title, finding, actions, related),
    ...(explicitSlug ? {slug: explicitSlug} : {}),
    published,
    keyStats: ['10 authoritative sources reviewed', '4 operating decisions to document', '3 named review owners required'],
  };
};

export const researchPosts: readonly ResearchPost[] = [
  researchBody('Call Center Queue Coverage: A Research Brief', 'Coverage is a control problem as well as a staffing problem. ISO 18295 frames contact-center service around customer experience, workforce, processes, and results, while NIST guidance emphasizes explicit risk ownership and access decisions.', 'Map demand by channel and hour, define the minimum safe coverage for each queue, and keep a named manager available for exceptions. Start with a limited queue, then compare offered contacts, response time, abandoned contacts, backlog age, and escalation volume before extending hours.'),
  researchBody('Call Center Handoff Quality: A Research Brief', 'A handoff is reliable when the next owner can act without reconstructing the conversation. NIST privacy and cybersecurity frameworks both favor documented responsibilities, outcomes, and repeatable response processes.', 'Use a required handoff record containing customer or case identifier, request, action already taken, promise made, risk flag, next owner, due time, and source record. Audit a small daily sample for missing context and send recurring gaps to the process owner.'),
  researchBody('Customer Support Access Controls: A Research Brief', 'NIST Zero Trust Architecture treats trust as something evaluated per request rather than inherited from network location. That supports narrow, named accounts for outsourced support instead of shared credentials or broad administrative access.', 'Give each worker an individual identity, least-privilege role, and documented approval path. Separate read, update, export, refund, and policy permissions. Review access when the queue, client, shift, or worker changes, and revoke it promptly at offboarding.'),
  researchBody('Call Recording Governance: A Research Brief', 'Recordings can contain personal, payment, and authentication data. NIST Privacy Framework and PCI DSS materials support purpose limitation, controlled access, retention decisions, and protection of sensitive data; a recording policy must also account for jurisdiction-specific rules.', 'Document why calls are recorded, where files live, who may review them, the retention period, redaction or pause rules, and the deletion owner. Do not use recordings as an informal training library until the client has approved the purpose and access.'),
  researchBody('Call Center Phishing Escalation: A Research Brief', 'CISA describes phishing as a social-engineering risk, and NIST identity guidance supports independent verification rather than trusting the channel that made the request. Agents need a pause-and-escalate rule, not a mandate to investigate intent.', 'Train agents to stop sensitive actions, avoid links and one-time codes, record the request, and contact a manager through a known channel. Capture what happened without copying passwords, payment data, or unnecessary customer information. Test the escalation path on every covered shift.'),
  researchBody('Payment Call Handling Controls: A Research Brief', 'PCI DSS is designed to protect payment account data and its document library provides the governing standard and supporting guidance. Outsourcing a call task does not remove the merchant\'s responsibility to define the card-data environment and approved handling method.', 'Define whether the agent may see, hear, enter, or repeat payment data. Prefer approved payment links, IVR, or tokenized workflows. Mask displays, restrict recordings, prohibit notes containing full card data, and escalate any accidental disclosure using the client\'s incident process.'),
  researchBody('Outbound Appointment Calls: A Research Brief', 'The FTC Telemarketing Sales Rule and FCC consumer guidance show why consent, identification, time-of-day, do-not-call, and opt-out handling must be explicit in outbound workflows. The sources do not create one universal script for every jurisdiction.', 'Before dialing, check the approved contact list, consent or business-relationship basis, local time, and suppression status. State the caller identity and purpose accurately, honor an opt-out immediately, and route complaints or legal questions to the client owner. Keep campaign records auditable.'),
  researchBody('Call Center QA Sampling: A Research Brief', 'ISO 18295 links contact-center performance to defined processes and results. NIST risk frameworks support repeatable measurement and improvement, but neither source endorses a single sample size or scorecard.', 'Publish the rubric before scoring, calibrate two reviewers on the same examples, and distinguish observable misses from coaching opinions. Track sample size, critical errors, documentation quality, customer outcome, and appeal decisions. Managers own final coaching and disciplinary action.'),
  researchBody('Call Center Incident Response: A Research Brief', 'NIST CSF 2.0 organizes cybersecurity work around Govern, Identify, Protect, Detect, Respond, and Recover. That structure supports a small queue-level incident card and clear ownership without asking frontline agents to perform security investigations.', 'Define report triggers, the approved channel, acknowledgment target, containment authority, evidence location, and client notification owner. The first report should preserve facts and timestamps. After closure, review the control gap and update the script, permission, or training step that allowed it.'),
  researchBody('Call Center Schedule Handoffs: A Research Brief', 'The FLSA establishes U.S. federal wage-and-hour requirements for covered workers; it is not a universal staffing calculator and does not answer every cross-border employment question. A schedule therefore needs both service coverage logic and a responsible employer or client review.', 'Publish shift ownership, break coverage, overtime approval, emergency contacts, and queue thresholds. Keep employment, payroll, and local labor compliance decisions with the responsible employer and counsel. Use the operational scorecard to expose uncovered intervals rather than silently extending a worker\'s shift.'),
  researchBody('Call Center Script Change Control: A Research Brief', 'NIST frameworks emphasize governance, documented controls, and continuous improvement. A script change can alter privacy, payment, consent, or escalation behavior, so publishing wording without an owner and effective date creates avoidable risk.', 'Give each script a version, owner, approval date, effective time, change reason, and rollback copy. Train and spot-check before the effective shift. Retain the prior version for audit, and route legal, payment, identity, or safety changes to the client approver.'),
  researchBody('Call Center Metrics That Managers Can Use: A Research Brief', 'Contact-center standards and risk frameworks support outcome-based measurement, but metric definitions must be local and transparent. A number without its denominator, time window, channel, or exclusion rule can produce a misleading operating decision.', 'Define each metric in a data dictionary. Pair speed measures with quality, repeat contact, unresolved work, escalation, and customer-impact indicators. Review outliers with the source records, and never use a single productivity number as a substitute for a quality or compliance review.'),
  researchBody('Call Center Vendor Onboarding Controls: A Research Brief', 'NIST Zero Trust, the Privacy Framework, and PCI DSS all point toward explicit scope, ownership, data handling, and access controls. Vendor onboarding is therefore a control-design milestone, not only a recruiting or scheduling event.', 'Before the first live task, approve the data map, system list, named users, training evidence, escalation tree, retention rules, and quality sample. Start with a limited pilot and make expansion conditional on observed accuracy, safe handoffs, and resolved access gaps.'),
  researchBody('Call Center Customer Data Retention: A Research Brief', 'NIST privacy guidance treats data processing as a governed lifecycle, while PCI DSS requires protection of payment account data. Neither source supplies a blanket retention period for every support operation; the client must define purpose, legal, and contractual requirements.', 'Create a retention table by record type: call audio, transcript, ticket, QA sample, export, and incident record. Name the system of record and deletion owner. Limit exports, protect archives, and review whether each retained field is still needed for the stated business purpose.'),
  researchBodyV2('Call Center Knowledge Base Governance: A Research Brief', 'A knowledge base is an operational control when every answer has an owner, effective date, and review path. NIST governance and ISO 18295 process guidance support making responsibilities and outcomes explicit rather than relying on informal agent memory.', 'Give each article an owner, scope label, approval status, effective date, and review date. Separate customer-facing wording from internal notes, flag sensitive exceptions, and sample answers against the current source record before expanding a queue.', ['call-center-script-change-control-a-research-brief', 'call-center-handoff-quality-a-research-brief', 'call-center-qa-sampling-a-research-brief']),
  researchBodyV2('Call Center Authentication Questions: A Research Brief', 'Identity checks should be designed as a bounded workflow, not an improvised conversation. NIST Digital Identity Guidelines support defined assurance and authenticator handling, while Zero Trust guidance supports evaluating each access request in context.', 'List the minimum approved verification steps by action and channel. Prohibit agents from requesting secrets or copying one-time codes into notes. Route failed, unusual, or high-impact requests to a named owner and audit the disposition without retaining unnecessary identity data.', ['customer-support-access-controls-a-research-brief', 'call-center-phishing-escalation-a-research-brief', 'payment-call-handling-controls-a-research-brief']),
  researchBodyV2('Call Center Backlog Triage: A Research Brief', 'Backlog control depends on age, customer impact, promised response, and risk—not only item count. ISO 18295 emphasizes defined processes and results, while NIST frameworks support explicit ownership and repeatable response decisions.', 'Create priority bands with examples, due-time rules, escalation triggers, and a single backlog owner. Review oldest work first, record the reason for reprioritization, and pair speed reporting with reopened cases, unresolved work, and quality findings.', ['call-center-queue-coverage-a-research-brief', 'call-center-metrics-that-managers-can-use-a-research-brief', 'call-center-incident-response-a-research-brief']),
  researchBodyV2('Call Center Callback Promise Controls: A Research Brief', 'A callback promise is a customer-impact commitment that needs a clock, owner, and exception path. Contact-center process guidance supports measuring outcomes, while privacy and identity guidance caution against putting unnecessary sensitive data in callback notes.', 'Record the requested outcome, safe callback channel, time window, owner, and escalation flag. Prevent silent expiry by aging open promises daily. Keep payment, legal, safety, and identity-sensitive callbacks with the approved manager workflow.', ['call-center-handoff-quality-a-research-brief', 'call-center-queue-coverage-a-research-brief', 'outbound-appointment-calls-a-research-brief']),
  researchBodyV2('Call Center Multichannel Case Linking: A Research Brief', 'Linking phone, email, chat, and ticket activity can reduce repeated explanations, but it also increases the risk of overexposure. NIST Privacy Framework and Zero Trust guidance support purpose limitation, scoped access, and explicit record ownership.', 'Define the system of record and allowed linkage keys. Show agents only the history needed for the assigned task, preserve channel and timestamp provenance, and escalate suspected account mismatches instead of merging records by guesswork.', ['customer-support-access-controls-a-research-brief', 'call-center-customer-data-retention-a-research-brief', 'call-center-handoff-quality-a-research-brief']),
  researchBodyV2('Call Center Refund Escalation: A Research Brief', 'Refund handling should separate customer communication from authorization. PCI DSS materials and NIST governance guidance support minimizing payment-data exposure and making approval boundaries explicit.', 'Document which cases an agent may explain, request, or submit for review. Keep approval and exception authority with a named owner, never store full payment data in notes, and reconcile the final decision to the original case record.', ['payment-call-handling-controls-a-research-brief', 'customer-support-access-controls-a-research-brief', 'call-center-incident-response-a-research-brief']),
  researchBodyV2('Call Center Customer Complaint Routing: A Research Brief', 'Complaint routing is reliable when the customer’s issue, requested remedy, risk, and next owner are preserved. NIST incident and privacy guidance supports factual recording and controlled escalation; it does not replace jurisdiction-specific complaint obligations.', 'Use a complaint taxonomy with severity examples, acknowledgment ownership, response target, and legal or safety escalation flags. Keep the original wording available, redact unnecessary personal data, and review trends with the process owner.', ['call-center-handoff-quality-a-research-brief', 'call-center-incident-response-a-research-brief', 'call-center-qa-sampling-a-research-brief']),
  researchBodyV2('Call Center Remote Work Continuity: A Research Brief', 'Continuity is a designed capability: people, access, communications, and recovery responsibilities must be tested together. NIST CSF 2.0 supports Govern, Identify, Protect, Detect, Respond, and Recover as a practical control sequence.', 'Write the loss-of-telephony, system, power, and supervisor playbooks. Define alternate contact paths, minimum data exposure, safe pause rules, recovery ownership, and a post-event review. Exercise the plan with a limited queue before relying on it for critical coverage.', ['call-center-incident-response-a-research-brief', 'call-center-queue-coverage-a-research-brief', 'call-center-vendor-onboarding-controls-a-research-brief']),
  researchBodyV2('Call Center Transcription Review: A Research Brief', 'Transcripts can improve QA and search while reproducing the privacy, retention, and access risks of the original interaction. NIST Privacy Framework and PCI DSS guidance support purpose limitation, minimization, and protected handling.', 'Define whether transcription is required, who may view it, what fields must be redacted, and how long it is retained. Sample transcript accuracy against recordings without turning sensitive content into an unrestricted training library.', ['call-recording-governance-a-research-brief', 'call-center-customer-data-retention-a-research-brief', 'call-center-qa-sampling-a-research-brief']),
  researchBodyV2('Call Center Outsourcing Pilot Gates: A Research Brief', 'A pilot is a control experiment when scope, success criteria, review owners, and exit conditions are written before work starts. NIST Zero Trust, Privacy Framework, PCI DSS, and ISO 18295 all point toward explicit boundaries and measured outcomes.', 'Approve one queue, one data map, one access set, and one quality rubric. Set expansion gates for accuracy, safe handoffs, unresolved exceptions, access findings, and manager capacity. Pause expansion when evidence is incomplete rather than normalizing exceptions.', ['call-center-vendor-onboarding-controls-a-research-brief', 'call-center-qa-sampling-a-research-brief', 'call-center-metrics-that-managers-can-use-a-research-brief']),
  researchBodyV2('Call Center Escalation Matrix Design: A Research Brief', 'An escalation matrix turns ambiguous exceptions into a repeatable ownership decision. NIST governance and incident guidance support defined triggers, roles, communication paths, and recovery decisions; they do not prescribe one universal severity scale.', 'Create severity bands with observable examples for payment, privacy, safety, legal, service, and customer-impact events. Name the first responder, decision owner, backup channel, acknowledgment expectation, and closure record. Test the matrix with realistic call cases before rollout.', ['call-center-incident-response-a-research-brief', 'call-center-handoff-quality-a-research-brief', 'call-center-script-change-control-a-research-brief']),
  researchBodyV2('Call Center After-Call Work Controls: A Research Brief', 'After-call work is part of the customer record, not an invisible productivity tax. ISO 18295 emphasizes defined processes and results, while NIST privacy guidance supports collecting only the information needed for the approved purpose.', 'Define the minimum disposition, summary, next action, due time, and escalation fields for each call type. Set a completion window that reflects complexity, sample notes for accuracy and minimization, and route missing or unsafe records to a manager rather than rewarding speed alone.', ['call-center-handoff-quality-a-research-brief', 'call-center-metrics-that-managers-can-use-a-research-brief', 'call-center-customer-data-retention-a-research-brief']),
  researchBodyV2('Call Center Workforce Forecast Inputs: A Research Brief', 'A staffing forecast is only as defensible as its definitions and inputs. Contact-center process guidance supports measuring demand and outcomes, while labor guidance warns against treating an operational model as a substitute for employment review.', 'Document the interval, channel, offered contacts, handling-time definition, shrinkage assumptions, service objective, absence treatment, and exception rules. Compare forecast to actual volume and backlog, keep a manager accountable for judgment calls, and record why coverage changes were made.', ['call-center-queue-coverage-a-research-brief', 'call-center-schedule-handoffs-a-research-brief', 'call-center-metrics-that-managers-can-use-a-research-brief']),
  researchBodyV2('Call Center Quality Calibration Meetings: A Research Brief', 'Calibration makes a quality score more consistent by exposing disagreements before they become coaching or performance decisions. ISO 18295 supports process and result discipline, but it does not establish a single rubric or pass threshold.', 'Use a small shared sample, score independently before discussion, separate critical-control failures from style preferences, and record the adjudicated rationale. Version the rubric, identify the final reviewer, and recheck scores after script, policy, or system changes.', ['call-center-qa-sampling-a-research-brief', 'call-center-script-change-control-a-research-brief', 'call-center-metrics-that-managers-can-use-a-research-brief']),
  researchBodyV2('Call Center Customer Verification Failures: A Research Brief', 'A failed verification should produce a safe next step, not pressure to improvise. NIST Digital Identity Guidelines and Zero Trust Architecture support contextual assurance, bounded authenticators, and explicit authorization decisions.', 'Define allowed retries, alternate channels, lockout or pause behavior, and the owner for high-impact requests. Never ask an agent to bypass verification to protect a speed metric. Record the disposition without storing secrets, full payment data, or unnecessary identity attributes.', ['call-center-authentication-questions-a-research-brief', 'customer-support-access-controls-a-research-brief', 'call-center-phishing-escalation-a-research-brief']),
  researchBodyV2('Call Center Customer Consent Records: A Research Brief', 'Consent is useful only when its scope, channel, time, and withdrawal path can be understood later. FTC and FCC guidance make outbound calling controls jurisdiction-sensitive, so a vendor workflow needs a client-approved record and suppression process.', 'Capture the source, date, purpose, channel, permitted contact method, and opt-out status using the approved system of record. Check suppression before dialing, honor withdrawal promptly, preserve an auditable reason for exceptions, and escalate legal questions instead of interpreting them on the call.', ['outbound-appointment-calls-a-research-brief', 'call-center-customer-data-retention-a-research-brief', 'call-center-script-change-control-a-research-brief']),
  researchBodyV2('Call Center Knowledge Article Review Cadence: A Research Brief', 'Review cadence should follow risk and change, not an arbitrary calendar alone. NIST governance and ISO 18295 process principles support accountable ownership, evidence of review, and updates when the underlying workflow changes.', 'Assign each article an owner, risk label, last-evidence date, next-review date, and trigger events for immediate review. Archive superseded wording, test high-risk answers against current records, and report overdue items as operational exceptions with a named decision owner.', ['call-center-knowledge-base-governance-a-research-brief', 'call-center-script-change-control-a-research-brief', 'call-center-qa-sampling-a-research-brief']),
  researchBodyV2('Call Center Vendor Access Review: A Research Brief', 'Access review is a recurring control because queue scope, people, systems, and client responsibilities change. NIST Zero Trust and PCI DSS materials support named identities, least privilege, evidence, and prompt removal of unnecessary access.', 'Maintain an inventory of users, roles, systems, data actions, approver, and review date. Reconcile it after staffing or scope changes, remove dormant permissions, separate approval from execution for sensitive actions, and retain the review result in the approved record.', ['customer-support-access-controls-a-research-brief', 'call-center-vendor-onboarding-controls-a-research-brief', 'call-center-customer-data-retention-a-research-brief']),
  researchBodyV2('Call Center Service Recovery Handoffs: A Research Brief', 'Service recovery needs a clear promise and authority boundary so an agent can acknowledge impact without inventing compensation or policy. ISO 18295 emphasizes customer outcomes, while NIST governance supports documented ownership and exception handling.', 'Define what the agent may apologize for, explain, schedule, or submit for approval. Record the customer impact, remedy requested, promise, deadline, and next owner. Review reopened cases and missed promises separately from ordinary queue speed.', ['call-center-callback-promise-controls-a-research-brief', 'call-center-customer-complaint-routing-a-research-brief', 'call-center-handoff-quality-a-research-brief']),
  researchBodyV2('Call Center Data Export Requests: A Research Brief', 'An export request can combine customer service, privacy, security, and retention risks. NIST Privacy Framework and Zero Trust guidance support purpose limitation, authorization, controlled handling, and a traceable decision before data leaves its system of record.', 'Require a named requester, purpose, scope, fields, destination, expiration, and approver. Prefer filtered views over bulk exports, encrypt approved transfers, prohibit local copies outside policy, and record deletion or return when the task ends.', ['customer-support-access-controls-a-research-brief', 'call-center-customer-data-retention-a-research-brief', 'call-center-incident-response-a-research-brief']),
  researchBodyV2('Call Center Supervisor Span of Control: A Research Brief', 'Supervisor capacity is a risk-control input because coaching, access decisions, escalations, and continuity all require timely ownership. ISO 18295 supports defined workforce and process responsibilities; it does not set one universal manager-to-agent ratio.', 'Map the supervisor duties that must occur per shift, including live escalation, QA review, coaching, schedule exceptions, and incident notification. Set a coverage threshold, backup owner, and pause rule for expansion when review work exceeds capacity.', ['call-center-queue-coverage-a-research-brief', 'call-center-qa-sampling-a-research-brief', 'call-center-remote-work-continuity-a-research-brief']),
  researchBodyV2('Call Center Training Readiness Gates: A Research Brief', 'Training completion is not the same as readiness to handle a live queue. NIST and ISO guidance support defined responsibilities, repeatable process evidence, and outcome review before a workflow is expanded.', 'Use a readiness record covering approved scope, practice cases, tool access, identity and privacy rules, escalation drills, documentation quality, and manager sign-off. Start with limited live work, sample early interactions, and pause assignment when a critical control is not understood.', ['call-center-vendor-onboarding-controls-a-research-brief', 'call-center-qa-sampling-a-research-brief', 'call-center-script-change-control-a-research-brief']),
  researchBodyV2('Call Center Queue Pause Criteria: A Research Brief', 'A pause rule protects customers when the evidence for safe continuation is missing. NIST incident and governance frameworks support defined thresholds, decision ownership, and recovery actions, while ISO 18295 emphasizes controlled processes and results.', 'Write observable pause triggers for outage, access error, repeated critical quality miss, unsafe script, data exposure, and unresolved escalation backlog. Name who can pause the queue, how customers are protected, what evidence is preserved, and which owner approves resumption.', ['call-center-incident-response-a-research-brief', 'call-center-queue-coverage-a-research-brief', 'call-center-outsourcing-pilot-gates-a-research-brief']),
  researchBodyV3('Call Center Appointment Confirmation Controls: A Research Brief', 'Appointment confirmation work combines customer data, schedule changes, and promises about time. NIST privacy guidance supports purpose limitation and controlled access, while ISO 18295 supports defined processes and measurable outcomes.', 'Set the approved confirmation fields, channel, time window, reschedule authority, and escalation rule. Give agents one source of truth, record the customer response and next owner, and audit missed or duplicated confirmations.', ['call-center-callback-promise-controls-a-research-brief', 'call-center-handoff-quality-a-research-brief', 'customer-support-access-controls-a-research-brief']),
  researchBodyV3('Call Center Disposition Code Design: A Research Brief', 'Disposition codes shape reporting and the next action. A code set is useful only when each value has a clear meaning, owner, and review path. ISO 18295 emphasizes process and results, while NIST guidance supports traceable responsibility.', 'Keep codes short and mutually understandable. Define when each code applies, the required note, the follow-up owner, and the exception path. Review uncategorized work and code changes with the manager who owns the reporting definition.', ['call-center-metrics-that-managers-can-use-a-research-brief', 'call-center-after-call-work-controls-a-research-brief', 'call-center-knowledge-base-governance-a-research-brief']),
  researchBodyV3('Call Center Escalation Acknowledgment: A Research Brief', 'An escalation can fail even when the first agent reports it correctly if nobody confirms ownership. NIST incident guidance supports defined roles and communication paths; contact-center process guidance supports measurable response outcomes.', 'Record the escalation time, receiving owner, acknowledgment deadline, customer promise, and next update. Alert the backup owner when the deadline passes, and review unacknowledged cases separately from ordinary handle-time reporting.', ['call-center-escalation-matrix-design-a-research-brief', 'call-center-handoff-quality-a-research-brief', 'call-center-callback-promise-controls-a-research-brief']),
  researchBodyV3('Call Center Sensitive Note Minimization: A Research Brief', 'Support notes often outlive the call and may be copied into reports or exports. NIST Privacy Framework guidance supports collecting only what the task requires, while PCI DSS materials support limiting payment-data exposure.', 'Write a field-level note standard. Keep secrets, full payment data, and unrelated personal details out of the record. Give reviewers a safe example, identify the system owner, and sample notes for relevance and unnecessary exposure.', ['call-center-customer-data-retention-a-research-brief', 'payment-call-handling-controls-a-research-brief', 'call-center-after-call-work-controls-a-research-brief']),
  researchBodyV3('Call Center New-Queue Readiness: A Research Brief', 'A new queue changes scripts, permissions, staffing, and escalation load at the same time. NIST governance and Zero Trust guidance support explicit scope and access decisions, while ISO 18295 supports process review before expansion.', 'Approve the queue purpose, customer types, systems, data actions, hours, quality rubric, and manager coverage. Run practice cases, confirm access by named user, and require a limited pilot review before adding volume or permissions.', ['call-center-training-readiness-gates-a-research-brief', 'call-center-outsourcing-pilot-gates-a-research-brief', 'call-center-vendor-onboarding-controls-a-research-brief']),
  researchBodyV3('Call Center Schedule Exception Handling: A Research Brief', 'Schedule exceptions affect coverage, worker time, and promised customer response. The FLSA provides U.S. federal wage-and-hour requirements for covered workers, but it is not a universal scheduling rule or cross-border employment guide.', 'Define who may approve an absence, shift swap, overtime request, or emergency extension. Record the decision and coverage impact, keep employment and payroll questions with the responsible owner, and use the queue scorecard to expose uncovered intervals.', ['call-center-schedule-handoffs-a-research-brief', 'call-center-workforce-forecast-inputs-a-research-brief', 'call-center-supervisor-span-of-control-a-research-brief']),
  researchBodyV3('Call Center Customer Identity Mismatch: A Research Brief', 'A mismatch between the caller and the account record is a safety signal, not a reason to guess. NIST Digital Identity Guidelines and Zero Trust Architecture support contextual verification and bounded authorization.', 'Pause sensitive changes, describe the mismatch without exposing account details, and route the case to the approved owner. Define alternate verification steps, retry limits, and the record required for closure without storing secrets.', ['call-center-customer-verification-failures-a-research-brief', 'call-center-authentication-questions-a-research-brief', 'customer-support-access-controls-a-research-brief']),
  researchBodyV3('Call Center QA Critical Error Taxonomy: A Research Brief', 'A quality score is easier to use when critical errors are defined separately from style preferences. ISO 18295 supports process and result discipline, while NIST control guidance supports repeatable review and accountable correction.', 'List observable critical errors for privacy, payment, consent, identity, safety, and inaccurate commitments. Define the immediate containment step, final reviewer, coaching owner, and reporting treatment for each category.', ['call-center-qa-sampling-a-research-brief', 'call-center-quality-calibration-meetings-a-research-brief', 'call-center-incident-response-a-research-brief']),
  researchBodyV3('Call Center Queue Ownership: A Research Brief', 'A queue needs a named owner who can resolve policy questions, approve changes, and accept escalations. NIST governance guidance and ISO 18295 both support explicit responsibility instead of informal ownership.', 'Document the queue owner, backup, service scope, systems, decision limits, review cadence, and pause authority. Put the owner in the handoff record and update the map whenever the queue or client responsibility changes.', ['call-center-escalation-matrix-design-a-research-brief', 'call-center-queue-coverage-a-research-brief', 'call-center-supervisor-span-of-control-a-research-brief']),
  researchBodyV3('Call Center Source-of-Truth Design: A Research Brief', 'Agents make avoidable errors when the script, ticket, schedule, and policy record disagree. NIST governance and privacy guidance support documented control ownership and limited access to the information needed for the task.', 'Name the authoritative record for customer state, policy wording, schedule, and escalation status. Define conflict handling, freshness checks, edit permissions, and the owner who resolves contradictory records.', ['call-center-knowledge-base-governance-a-research-brief', 'call-center-multichannel-case-linking-a-research-brief', 'call-center-script-change-control-a-research-brief']),
  researchBodyV3('Call Center Contact Preference Updates: A Research Brief', 'A contact-preference change can affect service, consent, and future outreach. FTC and FCC guidance makes outbound controls jurisdiction-sensitive, while NIST privacy guidance supports purpose limitation and traceable choices.', 'Use the approved system of record, capture the channel and effective time, and separate service preferences from marketing suppression where policy requires it. Honor changes promptly and route legal interpretation to the client owner.', ['call-center-customer-consent-records-a-research-brief', 'call-center-customer-data-retention-a-research-brief', 'outbound-appointment-calls-a-research-brief']),
  researchBodyV3('Call Center Incident Evidence Notes: A Research Brief', 'An initial incident note should preserve useful facts without expanding the exposure. NIST CSF 2.0 supports detection, response, and recovery ownership; privacy and payment guidance support minimizing copied sensitive data.', 'Record timestamps, systems, case identifiers, observed behavior, action taken, and the next owner. Do not copy passwords, full card data, or unnecessary customer details. Keep the note in the approved incident record and document closure evidence.', ['call-center-incident-response-a-research-brief', 'call-center-sensitive-note-minimization-a-research-brief', 'call-center-payment-call-handling-controls-a-research-brief']),
  researchBodyV3('Call Center Pilot Exit Criteria: A Research Brief', 'A pilot should end with a decision based on evidence, not schedule pressure. NIST control frameworks, PCI DSS materials, and ISO 18295 support defined scope, measured outcomes, and responsible review.', 'Before launch, set the evidence required for expand, revise, pause, or stop. Review quality, safe handoffs, unresolved exceptions, access findings, customer impact, and manager capacity. Record the decision owner and the changes required for the next stage.', ['call-center-outsourcing-pilot-gates-a-research-brief', 'call-center-qa-sampling-a-research-brief', 'call-center-queue-pause-criteria-a-research-brief']),
  researchBodyV3('Call Center Callback Verification: A Research Brief', 'A callback can expose an account to the wrong person if the number or identity is accepted without a bounded check. NIST Digital Identity Guidelines and Zero Trust Architecture support contextual verification before a sensitive action.', 'Define which callback channels are approved, what can be discussed before verification, and which requests require a fresh check. Record the result and next owner without storing secrets, and escalate mismatches or high-impact changes.', ['call-center-customer-identity-mismatch-a-research-brief', 'call-center-callback-promise-controls-a-research-brief', 'call-center-authentication-questions-a-research-brief']),
  researchBodyV3('call-center-voicemail-handling-controls-a-research-brief', 'Call Center Voicemail Handling Controls: A Research Brief', 'Voicemail can carry identity, payment, health, or account details into an uncontrolled channel. NIST privacy guidance and identity guidance support purpose limitation, bounded disclosure, and verification before sensitive action.', 'Define what may be left in a message, approved callback numbers, retry rules, and the record owner. Keep messages neutral, avoid secrets and full account details, and route mismatches or urgent risk to the manager workflow.', ['call-center-callback-verification-a-research-brief', 'call-center-sensitive-note-minimization-a-research-brief', 'call-center-customer-data-retention-a-research-brief'], '2026-08-10'),
  researchBodyV3('call-center-translation-handoff-a-research-brief', 'Call Center Translation Handoff: A Research Brief', 'Language support reduces friction only when meaning, ownership, and sensitive terms remain clear across the handoff. NIST governance and privacy guidance support defined responsibilities and minimum necessary information.', 'Record the customer intent, language need, approved interpreter path, and next owner. Do not improvise legal, payment, or policy translations; preserve the source wording and escalate ambiguity before promising an outcome.', ['call-center-handoff-quality-a-research-brief', 'call-center-knowledge-base-governance-a-research-brief', 'call-center-customer-complaint-routing-a-research-brief'], '2026-08-10'),
  researchBodyV3('call-center-holiday-coverage-planning-a-research-brief', 'Call Center Holiday Coverage Planning: A Research Brief', 'Holiday coverage is a continuity decision involving demand, staffing, customer promises, and manager availability. NIST continuity guidance and ISO 18295 process principles support explicit ownership and tested alternatives.', 'Map closure dates, expected demand, backup queues, on-call ownership, and customer messaging. Set a minimum safe service level, confirm access and escalation coverage, and review exceptions rather than silently extending shifts.', ['call-center-queue-coverage-a-research-brief', 'call-center-schedule-exception-handling-a-research-brief', 'call-center-remote-work-continuity-a-research-brief'], '2026-08-10'),
  researchBodyV3('call-center-disconnected-call-recovery-a-research-brief', 'Call Center Disconnected Call Recovery: A Research Brief', 'A dropped call creates uncertainty about the customer request, promised action, and safe callback route. NIST identity guidance supports bounded verification, while ISO 18295 supports defined recovery processes and outcomes.', 'Document the last confirmed step, approved callback channel, customer impact, and next owner. Do not disclose sensitive details on an unverified callback; apply retry limits and escalate high-impact or mismatched cases.', ['call-center-callback-verification-a-research-brief', 'call-center-callback-promise-controls-a-research-brief', 'call-center-incident-evidence-notes-a-research-brief'], '2026-08-10'),
  researchBodyV3('call-center-shared-inbox-ownership-a-research-brief', 'Call Center Shared Inbox Ownership: A Research Brief', 'A shared inbox becomes a control risk when ownership, status, and access are implicit. NIST governance and Zero Trust guidance support named responsibility, least privilege, and traceable decisions.', 'Assign an inbox owner and backup, define status meanings, restrict export and deletion rights, and require a next action for every active message. Audit aging items, reassignment, and sensitive attachments against the approved workflow.', ['call-center-queue-ownership-a-research-brief', 'call-center-vendor-access-review-a-research-brief', 'call-center-backlog-triage-a-research-brief'], '2026-08-10'),
  researchBodyV3('call-center-customer-callback-windows-a-research-brief', 'Call Center Customer Callback Windows: A Research Brief', 'A callback window is useful only when it is specific enough for ownership and safe contact. Privacy and identity guidance support limiting disclosure, while contact-center process guidance supports measurable promises.', 'Capture the customer time zone, permitted channel, promised window, owner, and fallback action. Confirm local-time rules before dialing, avoid sensitive voicemail content, and age missed promises into a manager review queue.', ['call-center-callback-promise-controls-a-research-brief', 'call-center-callback-verification-a-research-brief', 'call-center-schedule-handoffs-a-research-brief'], '2026-08-10'),
  researchBodyV3('call-center-customer-record-merge-controls-a-research-brief', 'Call Center Customer Record Merge Controls: A Research Brief', 'Merging records can remove duplicate work but can also combine two people, permissions, or histories incorrectly. NIST identity and privacy guidance support contextual verification, minimization, and an accountable decision.', 'Require matching evidence, a named approver for uncertain merges, a reversible audit trail, and a rule for conflicting contact preferences. Prohibit agents from merging on name or phone similarity alone and route suspected identity mismatch cases to the owner.', ['call-center-multichannel-case-linking-a-research-brief', 'call-center-customer-identity-mismatch-a-research-brief', 'customer-support-access-controls-a-research-brief'], '2026-08-10'),
  researchBodyV3('call-center-escalation-backlog-review-a-research-brief', 'Call Center Escalation Backlog Review: A Research Brief', 'An escalation backlog can hide missed promises and unowned risk even when the ordinary queue appears healthy. NIST incident guidance supports acknowledgment and ownership, while ISO 18295 supports monitoring outcomes.', 'Review age, severity, customer promise, current owner, last update, and blocked dependency. Alert a backup owner after the defined threshold, separate blocked work from completed work, and record the decision to continue, transfer, or pause.', ['call-center-escalation-acknowledgment-a-research-brief', 'call-center-backlog-triage-a-research-brief', 'call-center-queue-pause-criteria-a-research-brief'], '2026-08-10'),
  researchBodyV3('call-center-contact-disposition-audit-a-research-brief', 'Call Center Contact Disposition Audit: A Research Brief', 'Disposition accuracy affects reporting, follow-up, and customer history. ISO 18295 supports defined processes and results, while NIST governance supports evidence-based review and accountable correction.', 'Sample dispositions against the source interaction, define critical mismatches, and route corrections through a versioned code owner. Track uncoded and overwritten work, distinguish agent error from ambiguous taxonomy, and protect sensitive notes during review.', ['call-center-disposition-code-design-a-research-brief', 'call-center-after-call-work-controls-a-research-brief', 'call-center-qa-critical-error-taxonomy-a-research-brief'], '2026-08-10'),
  researchBodyV3('call-center-queue-overflow-routing-a-research-brief', 'Call Center Queue Overflow Routing: A Research Brief', 'Overflow routing protects customers when the primary queue cannot safely absorb demand. ISO 18295 supports defined service processes, while NIST governance supports explicit ownership and controlled exceptions.', 'Define the volume, wait, outage, or risk trigger for overflow; name the alternate queue and owner; and specify what data and promises transfer. Audit routed cases for duplicate work, lost context, and unauthorized scope before keeping the fallback active.', ['call-center-queue-coverage-a-research-brief', 'call-center-backlog-triage-a-research-brief', 'call-center-queue-ownership-a-research-brief'], '2026-08-10'),
].slice().sort((a, b) => b.published.localeCompare(a.published));
export const postsPerPage = 20;
