export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; sections: readonly { heading: string; body: string }[]; sources?: readonly { name: string; url: string }[] };

export const fleetServices: readonly FleetService[] = [
  {
    slug: 'inbound-call-handling',
    title: 'Inbound Call Handling',
    desc: 'Add Filipino agents to your inbound queue for approved questions, message taking, appointment help, and clean manager handoffs.',
    tasks: [
      'Answer approved billing, order, booking, and account questions',
      'Take complete messages and confirm the best callback time',
      'Book or move appointments inside written scheduling rules',
      'Tag each call and send urgent or unusual cases to a manager',
    ],
    controls: [
      'Give each Filipino agent a named phone and CRM account',
      'Keep refunds, policy exceptions, and sensitive account changes with your manager',
      'Review a daily sample of recordings, call notes, and dispositions',
      'Set one escalation path for safety, legal, payment, or upset-customer calls',
    ],
    firstWeek: [
      'Share ten common call reasons, approved answers, and transfer rules',
      'Run practice calls before the agent enters the live queue',
      'Start with one queue and a limited shift while a manager is available',
      'Review the first twenty calls and fix gaps before adding more hours',
    ],
  },
  { slug: 'omnichannel-customer-support', title: 'Omnichannel Customer Support', desc: 'Build a Philippines-based omnichannel customer support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'outbound-appointment-setting', title: 'Outbound Appointment Setting', desc: 'Build a Philippines-based outbound appointment setting workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'order-management-support', title: 'Order Management Support', desc: 'Build a Philippines-based order management support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'tier-one-technical-support', title: 'Tier-One Technical Support', desc: 'Build a Philippines-based tier-one technical support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'collections-reminder-calls', title: 'Collections Reminder Calls', desc: 'Build a Philippines-based collections reminder calls workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'customer-win-back-support', title: 'Customer Win-Back Support', desc: 'Build a Philippines-based customer win-back support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'dispatch-coordination', title: 'Dispatch Coordination', desc: 'Build a Philippines-based dispatch coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'survey-and-feedback-calls', title: 'Survey and Feedback Calls', desc: 'Build a Philippines-based survey and feedback calls workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'workforce-reporting-support', title: 'Workforce Reporting Support', desc: 'Build a Philippines-based workforce reporting support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring customer contact work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

// Add reviewed, source-backed original research here. The templates and sitemap update automatically.
const researchSources = [
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST Zero Trust Architecture, SP 800-207', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' },
  { name: 'NIST Digital Identity Guidelines, SP 800-63B', url: 'https://pages.nist.gov/800-63-3/sp800-63b.html' },
  { name: 'CISA Phishing Guidance', url: 'https://www.cisa.gov/stopthinkconnect' },
  { name: 'PCI DSS Document Library', url: 'https://www.pcisecuritystandards.org/standards/pci-dss/' },
  { name: 'FTC Telemarketing Sales Rule', url: 'https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule' },
  { name: 'FCC TCPA Consumer Guide', url: 'https://www.fcc.gov/general/telemarketing-and-robocalls' },
  { name: 'U.S. Department of Labor, FLSA', url: 'https://www.dol.gov/agencies/whd/flsa' },
  { name: 'ISO 18295-1 Customer Contact Centres', url: 'https://www.iso.org/standard/73338.html' },
] as const;

const researchBody = (title: string, finding: string, actions: string): ResearchPost => ({
  slug: title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), title,
  excerpt: finding, published: '2026-08-07', sources: researchSources,
  sections: [
    { heading: 'Method and evidence', body: `This desk review compares the operating question in ${title.toLowerCase()} with current guidance from NIST, CISA, PCI SSC, the FTC, the FCC, the U.S. Department of Labor, and ISO. The sources describe controls and obligations; they do not measure the performance of any individual outsourced team. Recommendations below are operating inferences, not legal advice.` },
    { heading: 'What the evidence supports', body: finding },
    { heading: 'Operating design', body: actions },
    { heading: 'Manager review questions', body: 'Which queue, customer data, and systems are in scope? What can an agent complete without approval? Which events require immediate escalation? Who owns the record, quality review, and policy decision? Recheck these answers whenever the workflow or channel changes.' },
  ],
});

export const researchPosts: readonly ResearchPost[] = [
  researchBody('Call Center Queue Coverage: A Research Brief', 'Coverage is a control problem as well as a staffing problem. ISO 18295 frames contact-center service around customer experience, workforce, processes, and results, while NIST guidance emphasizes explicit risk ownership and access decisions.', 'Map demand by channel and hour, define the minimum safe coverage for each queue, and keep a named manager available for exceptions. Start with a limited queue, then compare offered contacts, response time, abandoned contacts, backlog age, and escalation volume before extending hours.'),
  researchBody('Call Center Handoff Quality: A Research Brief', 'A handoff is reliable when the next owner can act without reconstructing the conversation. NIST privacy and cybersecurity frameworks both favor documented responsibilities, outcomes, and repeatable response processes.', 'Use a required handoff record containing customer or case identifier, request, action already taken, promise made, risk flag, next owner, due time, and source record. Audit a small daily sample for missing context and send recurring gaps to the process owner.'),
  researchBody('Customer Support Access Controls: A Research Brief', 'NIST Zero Trust Architecture treats trust as something evaluated per request rather than inherited from network location. That supports narrow, named accounts for outsourced support instead of shared credentials or broad administrative access.', 'Give each worker an individual identity, least-privilege role, and documented approval path. Separate read, update, export, refund, and policy permissions. Review access when the queue, client, shift, or worker changes, and revoke it promptly at offboarding.'),
  researchBody('Call Recording Governance: A Research Brief', 'Recordings can contain personal, payment, and authentication data. NIST Privacy Framework and PCI DSS materials support purpose limitation, controlled access, retention decisions, and protection of sensitive data; a recording policy must also account for jurisdiction-specific rules.', 'Document why calls are recorded, where files live, who may review them, the retention period, redaction or pause rules, and the deletion owner. Do not use recordings as an informal training library until the client has approved the purpose and access.'),
  researchBody('Call Center Phishing Escalation: A Research Brief', 'CISA describes phishing as a social-engineering risk, and NIST identity guidance supports independent verification rather than trusting the channel that made the request. Agents need a pause-and-escalate rule, not a mandate to investigate intent.', 'Train agents to stop sensitive actions, avoid links and one-time codes, record the request, and contact a manager through a known channel. Capture what happened without copying passwords, payment data, or unnecessary customer information. Test the escalation path on every covered shift.'),
  researchBody('Payment Call Handling Controls: A Research Brief', 'PCI DSS is designed to protect payment account data and its document library provides the governing standard and supporting guidance. Outsourcing a call task does not remove the merchant\'s responsibility to define the card-data environment and approved handling method.', 'Define whether the agent may see, hear, enter, or repeat payment data. Prefer approved payment links, IVR, or tokenized workflows. Mask displays, restrict recordings, prohibit notes containing full card data, and escalate any accidental disclosure using the client\'s incident process.'),
  researchBody('Outbound Appointment Calls: A Research Brief', 'The FTC Telemarketing Sales Rule and FCC consumer guidance show why consent, identification, time-of-day, do-not-call, and opt-out handling must be explicit in outbound workflows. The sources do not create one universal script for every jurisdiction.', 'Before dialing, check the approved contact list, consent or business-relationship basis, local time, and suppression status. State the caller identity and purpose accurately, honor an opt-out immediately, and route complaints or legal questions to the client owner. Keep campaign records auditable.'),
  researchBody('Call Center QA Sampling: A Research Brief', 'ISO 18295 links contact-center performance to defined processes and results. NIST risk frameworks support repeatable measurement and improvement, but neither source endorses a single sample size or scorecard.', 'Publish the rubric before scoring, calibrate two reviewers on the same examples, and distinguish observable misses from coaching opinions. Track sample size, critical errors, documentation quality, customer outcome, and appeal decisions. Managers own final coaching and disciplinary action.'),
  researchBody('Call Center Incident Response: A Research Brief', 'NIST CSF 2.0 organizes cybersecurity work around Govern, Identify, Protect, Detect, Respond, and Recover. That structure supports a small queue-level incident card and clear ownership without asking frontline agents to perform security investigations.', 'Define report triggers, the approved channel, acknowledgment target, containment authority, evidence location, and client notification owner. The first report should preserve facts and timestamps. After closure, review the control gap and update the script, permission, or training step that allowed it.'),
  researchBody('Call Center Schedule Handoffs: A Research Brief', 'The FLSA establishes U.S. federal wage-and-hour requirements for covered workers; it is not a universal staffing calculator and does not answer every cross-border employment question. A schedule therefore needs both service coverage logic and a responsible employer or client review.', 'Publish shift ownership, break coverage, overtime approval, emergency contacts, and queue thresholds. Keep employment, payroll, and local labor compliance decisions with the responsible employer and counsel. Use the operational scorecard to expose uncovered intervals rather than silently extending a worker\'s shift.'),
  researchBody('Call Center Script Change Control: A Research Brief', 'NIST frameworks emphasize governance, documented controls, and continuous improvement. A script change can alter privacy, payment, consent, or escalation behavior, so publishing wording without an owner and effective date creates avoidable risk.', 'Give each script a version, owner, approval date, effective time, change reason, and rollback copy. Train and spot-check before the effective shift. Retain the prior version for audit, and route legal, payment, identity, or safety changes to the client approver.'),
  researchBody('Call Center Metrics That Managers Can Use: A Research Brief', 'Contact-center standards and risk frameworks support outcome-based measurement, but metric definitions must be local and transparent. A number without its denominator, time window, channel, or exclusion rule can produce a misleading operating decision.', 'Define each metric in a data dictionary. Pair speed measures with quality, repeat contact, unresolved work, escalation, and customer-impact indicators. Review outliers with the source records, and never use a single productivity number as a substitute for a quality or compliance review.'),
  researchBody('Call Center Vendor Onboarding Controls: A Research Brief', 'NIST Zero Trust, the Privacy Framework, and PCI DSS all point toward explicit scope, ownership, data handling, and access controls. Vendor onboarding is therefore a control-design milestone, not only a recruiting or scheduling event.', 'Before the first live task, approve the data map, system list, named users, training evidence, escalation tree, retention rules, and quality sample. Start with a limited pilot and make expansion conditional on observed accuracy, safe handoffs, and resolved access gaps.'),
  researchBody('Call Center Customer Data Retention: A Research Brief', 'NIST privacy guidance treats data processing as a governed lifecycle, while PCI DSS requires protection of payment account data. Neither source supplies a blanket retention period for every support operation; the client must define purpose, legal, and contractual requirements.', 'Create a retention table by record type: call audio, transcript, ticket, QA sample, export, and incident record. Name the system of record and deletion owner. Limit exports, protect archives, and review whether each retained field is still needed for the stated business purpose.'),
];
export const postsPerPage = 20;
