import type { ResearchPost } from './fleet-data';

const sources = [
  { name: 'ISO 18295-1 Customer Contact Centres', url: 'https://www.iso.org/standard/73338.html' },
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST Zero Trust Architecture, SP 800-207', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' },
  { name: 'NIST Digital Identity Guidelines, SP 800-63B', url: 'https://pages.nist.gov/800-63-3/sp800-63b.html' },
  { name: 'PCI DSS Document Library', url: 'https://www.pcisecuritystandards.org/standards/pci-dss/' },
  { name: 'FTC Telemarketing Sales Rule', url: 'https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule' },
  { name: 'FCC Consumer Guide to Telemarketing and Robocalls', url: 'https://www.fcc.gov/general/telemarketing-and-robocalls' },
] as const;

// Per-route provenance map: each accepted source identity binds the campaign date literally.
export const august17ResearchSourceDates = {
  'call-center-appointment-access-window-research-brief': '2026-08-17',
  'call-center-order-status-evidence-research-brief': '2026-08-17',
  'call-center-refund-request-boundaries-research-brief': '2026-08-17',
  'call-center-knowledge-exception-routing-research-brief': '2026-08-17',
  'call-center-queue-capacity-signal-research-brief': '2026-08-17',
  'call-center-customer-preference-propagation-research-brief': '2026-08-17',
  'call-center-remote-shift-handoff-research-brief': '2026-08-17',
  'call-center-record-correction-approval-research-brief': '2026-08-17',
  'call-center-voice-recording-access-research-brief': '2026-08-17',
  'call-center-customer-escalation-severity-research-brief': '2026-08-17',
} as const;

type Topic = { slug: string; title: string; excerpt: string; question: string; finding: string; design: string; scenario: string; measure: string; limits: string; conclusion: string; updated?: string; serviceHandoff?: ResearchPost['serviceHandoff'] };

const make = (t: Topic): ResearchPost => ({
  slug: t.slug, title: t.title, excerpt: t.excerpt, published: august17ResearchSourceDates[t.slug as keyof typeof august17ResearchSourceDates], sourceDate: august17ResearchSourceDates[t.slug as keyof typeof august17ResearchSourceDates], updated: t.updated, sources, serviceHandoff: t.serviceHandoff,
  sections: [
    { heading: 'Research question and scope', body: `This study asks ${t.question}. It examines customer-contact work in a Philippines-based outsourced support setting, where frontline staff may answer approved questions, take messages, help with appointments, and hand exceptions to a client-side owner. The unit of analysis is a customer-impact decision: what was requested, what evidence was available, what action was authorized, and who owned the next step. ISO 18295-1 provides the contact-centre process and outcome lens. NIST privacy, cybersecurity, zero-trust, and identity guidance provide control evidence; PCI DSS and U.S. outbound-contact guidance are used only where their subject matter is relevant. These sources describe safeguards and obligations, not the performance of this company or any provider.`, },
    { heading: 'Evidence and finding', body: `${t.finding} The evidence should be reviewed in a defined cohort with the channel, observation period, customer-impact class, exclusions, and missing fields stated in advance. A status code or activity count is not proof that the customer received the intended outcome. Reviewers should preserve the source record and distinguish a confirmed failure from a missing or conflicting record.`, },
    { heading: 'Niche-specific operating analysis', body: `${t.design} For an outsourced call-center service, the boundary matters because the frontline role may be authorized to record, explain, schedule, or route work without being authorized to change policy, approve an exception, interpret legal duties, or expose sensitive fields. The client owner should define the ordinary path, the restricted action, the escalation evidence, and the safe response when the record is incomplete.`, },
    { heading: 'Observed scenario', body: `${t.scenario} This scenario illustrates why research should connect the contact record to the customer promise and downstream owner. It does not establish that the failure is common, that one worker caused it, or that outsourcing caused it. It identifies the evidence a service leader would need before changing scope or assigning responsibility.`, },
    { heading: 'Measurement and decision use', body: `${t.measure} Report counts with denominators, period, and cohort definition. Segment only where sample size and process differences make comparison meaningful. A manager can use the result to continue, narrow, revise, or pause a queue, but the decision record should include uncertainty, customer impact, owner, and recheck date. Do not infer causation from a before-and-after change when scripts, systems, demand, or staffing also changed.`, },
    { heading: 'Limitations and conclusion', body: `${t.limits} The sources do not set a universal staffing ratio, response threshold, retry count, retention period, or acceptable error rate. Applicable duties vary by service, channel, jurisdiction, and data category. The bounded conclusion is that ${t.conclusion} This is an evidence-led operating conclusion, not a legal opinion, certification, or guarantee.`, },
  ],
});

export const august17ResearchBatch: readonly ResearchPost[] = [
  make({ slug: 'call-center-appointment-access-window-research-brief', title: 'Call Center Appointment Access Windows: A Research Brief', excerpt: 'Appointment support must distinguish a convenient time from a promised access window that the service can actually honor.', question: 'how outsourced appointment teams should evaluate access-window promises across time zones, channels, and service constraints', finding: 'An appointment window is a customer promise, not merely a calendar label. Identity guidance limits what may be disclosed before verification, while ISO 18295 supports defined processes and outcome review. The record needs the source of availability, local-time interpretation, service constraint, and owner of an exception.', design: 'Keep requested, offered, confirmed, and missed windows distinct. Record whether the customer confirmed local time and whether the booking system or a human owner controlled the final slot. Limit frontline changes to approved fields and route conflicts between capacity and customer need to the client owner.', scenario: 'A customer accepts a morning slot described by a team operating in another time zone, then discovers that the service arrives outside the customer’s stated availability. The booking succeeded technically, but the access promise was not shared accurately.', measure: 'Compare confirmed windows with customer corrections, reschedules, missed access, wrong-time-zone errors, and repeat contacts. Review high-impact appointments separately from ordinary changes and reconcile the customer-facing confirmation with the authoritative schedule.', limits: 'This brief cannot define accessibility accommodations, cancellation rights, or local scheduling rules for every service.', conclusion: 'appointment quality depends on preserving the customer’s local access meaning and the authority behind the final slot.' }),
  make({ slug: 'call-center-order-status-evidence-research-brief', title: 'Call Center Order Status Evidence: A Research Brief', excerpt: 'An order-status answer is reliable only when the source state, timestamp, dependency, and customer-facing promise agree.', question: 'what evidence lets a support team explain order status without turning an internal estimate into a guarantee', finding: 'A status field can lag the operational event or omit a blocked dependency. NIST governance favors attributable source records and bounded disclosure; ISO 18295 connects process design to customer results. The answer should separate confirmed movement, estimate, dependency, and next update.', design: 'Name the authoritative order state and its freshness interval. Give frontline staff approved wording for confirmed, delayed, blocked, and unknown states. Prohibit converting an internal target into a guaranteed delivery statement, and route disputes between systems to an owner who can correct the source.', scenario: 'A customer hears a target date while a carrier handoff remains unconfirmed. When the target slips, the contact record shows an apparently accurate answer but no evidence that the dependency was explained.', measure: 'Sample status answers against source events and classify corrections as stale data, unsupported promise, missing dependency, or wrong order linkage. Pair correction counts with repeat contact and missed-update evidence rather than average handle time.', limits: 'The sources do not establish a delivery promise, carrier threshold, or remedy; those depend on the client’s service policy and facts.', conclusion: 'order-status research should test whether the answer preserves uncertainty and ownership, not merely whether a status was displayed.', updated: '2026-09-05', serviceHandoff: { href: '/services/order-management-support', label: 'Review Order Management Support', body: 'If your team needs to explain approved order updates without turning estimates into promises, review the Order Management Support service. Managers still decide exceptions, customer remedies, and changes to the source record.' } }),
  make({ slug: 'call-center-refund-request-boundaries-research-brief', title: 'Call Center Refund Request Boundaries: A Research Brief', excerpt: 'Refund intake should capture the customer’s claim while keeping authorization, payment evidence, and exception decisions with the approved owner.', question: 'how a support team can route refund requests without promising an outcome it cannot authorize', finding: 'Payment and privacy controls make refund handling a role-boundary problem. PCI DSS material concerns the environment and data protections, not a universal refund workflow. The contact record should distinguish request, evidence, eligibility question, approval, and settlement status.', design: 'Let frontline staff record the reason, verify the permitted facts, explain the next review step, and assign an owner. Keep approval, payment instrument decisions, policy exceptions, and sensitive values outside ordinary notes unless the approved system requires them. Acknowledgment must not be phrased as approval.', scenario: 'A customer is told that a refund is “being processed” when the contact only created a review request. The later dispute is caused by a promise that exceeded the role’s authority, not necessarily by the finance decision.', measure: 'Review refund contacts for authority mismatch, unsupported promises, missing evidence, repeat explanations, and time to owner acknowledgment. Separate denied, approved, pending, and unverified requests so a single completion percentage does not hide unresolved work.', limits: 'This research does not decide eligibility, payment scope, statutory remedies, or settlement timing.', conclusion: 'refund support is safer when intake, authorization, and settlement are recorded as separate decisions.' }),
  make({ slug: 'call-center-knowledge-exception-routing-research-brief', title: 'Call Center Knowledge Exception Routing: A Research Brief', excerpt: 'A support answer needs an exception route when the customer’s case falls outside the documented ordinary path.', question: 'how knowledge systems should signal and route exceptions instead of encouraging confident answers from incomplete rules', finding: 'A knowledge article that covers the ordinary case can still be unsafe for an exception. NIST governance and privacy guidance support ownership, traceability, and least-necessary disclosure; ISO 18295 supports process and result review. The absence of an exception signal is a design finding, not evidence of staff negligence.', design: 'Give each article an explicit scope, exclusion, effective date, and named escalation owner. Put the exception trigger beside the ordinary answer and preserve the customer’s request when routing. Do not make a frontline role infer policy from examples that were never approved for the current case.', scenario: 'A cancellation article explains the normal window but says nothing about a disputed charge. The handler follows the visible article, while the customer needs a payment owner and the case becomes a repeat contact.', measure: 'Track exception searches, articles used outside scope, transfers returned for missing context, corrections after answer, and questions with no named owner. Sample both resolved and escalated contacts against the article’s stated boundary.', limits: 'No source establishes the right article taxonomy or policy owner for a particular business.', conclusion: 'knowledge quality includes a visible boundary and a safe next owner, not only a correct ordinary answer.' }),
  make({ slug: 'call-center-queue-capacity-signal-research-brief', title: 'Call Center Queue Capacity Signals: A Research Brief', excerpt: 'Queue capacity is a customer-impact question about promises, exceptions, and review coverage, not a single staffing number.', question: 'which evidence distinguishes a busy outsourced support queue from a queue operating beyond its safe scope', finding: 'ISO 18295 treats people, processes, and results together, while NIST governance emphasizes accountable risk decisions. Offered contacts, response time, backlog age, abandoned contacts, transfer load, and unresolved escalations describe different parts of capacity. None alone proves that adding volume is safe.', design: 'Define the customer promise, minimum manager coverage, permitted work, and pause or narrowing trigger before expansion. Keep ordinary work separate from exceptions and record when a queue borrows another owner. Review the capacity signal by interval, channel, customer impact, and dependency rather than using a daily average.', scenario: 'A queue answers most calls quickly while a small set of high-impact cases waits for a policy owner who is unavailable. The average looks healthy, but the service has exceeded its exception-review capacity.', measure: 'Use a cohort and period to compare offered volume, wait, abandon, backlog age, repeat contact, escalation acknowledgment, and customer-impact class. Treat unowned work and missed promises as separate signals from ordinary speed.', limits: 'There is no universal safe occupancy, staffing ratio, or pause threshold in the cited sources.', conclusion: 'queue capacity is adequate only when ordinary service and exception ownership can both meet their defined promises.' }),
  make({ slug: 'call-center-customer-preference-propagation-research-brief', title: 'Call Center Customer Preference Propagation: A Research Brief', excerpt: 'A contact preference is useful only when its purpose, channel, effective time, and downstream systems remain aligned.', question: 'how support teams should study whether a customer’s contact preference or suppression request reached every relevant system', finding: 'Privacy and outbound-contact guidance make purpose and channel material. A preference recorded in one queue may not govern another system, and an inbound support request is not automatically permission for promotion. The research question is propagation, not merely data entry.', design: 'Separate service, transactional, and promotional purposes where policy requires. Record source, effective time, channel, and scope in the approved system, then identify downstream owners and conflict behavior. Give frontline staff a safe acknowledgment without making a legal conclusion about consent.', scenario: 'A customer asks not to receive promotional calls, but a separate appointment system retains an old outreach flag. The first record looks complete while the downstream contact violates the customer’s expressed purpose.', measure: 'Test propagation across a defined set of systems and channels. Count delayed, conflicting, missing, and incorrectly scoped updates; pair those findings with attempted contacts and customer corrections.', limits: 'Applicable consent rules and suppression semantics are jurisdiction- and product-specific; this is not legal advice.', conclusion: 'preference reliability is a cross-system ownership problem, not a checkbox-completion metric.' }),
  make({ slug: 'call-center-remote-shift-handoff-research-brief', title: 'Call Center Remote Shift Handoffs: A Research Brief', excerpt: 'Remote shift continuity depends on an attributable record, a named next owner, and a visible unresolved promise.', question: 'whether a remote or cross-shift handoff preserves enough context for the next support owner to act safely', finding: 'Zero Trust guidance favors individual access and contextual authorization, while ISO 18295 supports defined processes and outcomes. A handoff can fail through missing context, stale permissions, time-zone ambiguity, or an unacknowledged customer promise even when the status is marked complete.', design: 'Require the source record, customer request, action already taken, promise made, unresolved dependency, next owner, and due time. Keep access role-based and verify that the next shift can see the same authoritative record. Escalate cases whose deadline crosses a coverage gap.', scenario: 'A late-shift agent records “manager review needed” without naming the manager or deadline. The next shift sees the status but cannot tell whether the customer was promised an update or who can make the decision.', measure: 'Sample handoffs at shift boundaries for missing owner, due time, source record, permission, and customer promise. Track returned handoffs, repeated questioning, missed updates, and cases reopened after a nominal closure.', limits: 'The research does not prescribe a remote-work schedule, labor arrangement, or staffing model.', conclusion: 'cross-shift reliability comes from continuity of evidence and ownership, not from the existence of a handoff status.' }),
  make({ slug: 'call-center-record-correction-approval-research-brief', title: 'Call Center Record Correction Approval: A Research Brief', excerpt: 'Customer-record corrections need field-specific authority, verified evidence, and an attributable path for reversing mistakes.', question: 'how to distinguish a routine contact correction from a high-impact record change that needs owner approval', finding: 'NIST identity and privacy guidance support contextual verification, accuracy, and limited access. A phone number, delivery address, contact preference, and payment-related field do not carry the same impact. A broad “edit customer” permission hides those differences.', design: 'Classify fields by customer impact and define evidence, permitted actor, approval owner, confirmation channel, and audit requirements for each class. Preserve old and new values only where policy permits, and route disputed or high-impact changes rather than accepting similarity as proof.', scenario: 'A caller asks to update a callback number and then requests an account change. If both edits use the same low-friction path, the service may authorize a sensitive action because a harmless correction was verified first.', measure: 'Review corrections by field class, evidence type, reversal, repeat change, mismatch, and owner approval. Examine both denied requests and completed changes so the study does not measure only successful edits.', limits: 'The sources cannot determine which fields a particular frontline role may edit or retain.', conclusion: 'correction controls should follow the impact of the field and the evidence for the requested change.' }),
  make({ slug: 'call-center-voice-recording-access-research-brief', title: 'Call Center Voice Recording Access: A Research Brief', excerpt: 'Recording access should be tied to a review purpose, named role, retention decision, and minimum necessary evidence.', question: 'how an outsourced support operation can evaluate whether call recordings are accessible to the right reviewers without widening exposure', finding: 'NIST privacy and zero-trust guidance support purpose limitation, individual access, and reviewable authorization. PCI DSS material is relevant where payment data may enter the recording environment. A recording can be permitted for quality review yet still be copied, exported, or heard by an unrelated role.', design: 'Define which reviews require audio, which can use redacted notes, who may retrieve a recording, and how access expires. Keep review samples tied to a case or quality purpose, prohibit local copies, and route suspected exposure through the incident owner without duplicating sensitive content.', scenario: 'A quality reviewer downloads a recording to share a coaching example. The original review may be legitimate, but the new copy creates an unplanned audience and retention path.', measure: 'Measure recording retrieval, export, playback by role, redaction exceptions, retention overrides, and access after the stated review purpose. Distinguish an authorized retrieval from an unauthorized disclosure.', limits: 'Retention, recording consent, payment scope, and local employment rules require environment-specific decisions.', conclusion: 'recording safety is a lifecycle access question, not merely a call-start notice or a quality-review permission.' }),
  make({ slug: 'call-center-customer-escalation-severity-research-brief', title: 'Call Center Customer Escalation Severity: A Research Brief', excerpt: 'Severity should reflect customer impact and decision urgency, not the loudness of a message or the ease of a category.', question: 'how an outsourced support team can classify escalation severity without turning sentiment or volume into a risk conclusion', finding: 'ISO 18295 supports attention to customer outcomes, while NIST governance and incident guidance support defined roles, evidence, and response ownership. A complaint, privacy concern, payment issue, accessibility barrier, and missed callback may require different owners even when each is marked urgent. Sentiment alone is not severity evidence.', design: 'Define observable impact, time sensitivity, affected service, evidence required, and escalation owner for each class. Preserve the customer’s words separately from the verified finding. Permit an uncertain state and require a responsible owner to resolve it rather than forcing false precision.', scenario: 'A calm customer reports that a promised update was missed on a time-sensitive case, while an angry caller asks a routine question. If volume or tone determines severity, the quieter high-impact case can wait.', measure: 'Sample severity assignments against source evidence, customer impact, promised time, eventual owner decision, and reclassification. Report false-low and false-high classifications separately and inspect the causes of each.', limits: 'The sources do not supply a universal severity scale or remedy for every customer event.', conclusion: 'severity is a bounded evidence judgment about impact and urgency, not a proxy for emotion or contact volume.' }),
];
