import type {ResearchPost} from './fleet-data';
import {september25Cala102ResearchBatch as prior} from './research-sep25-cala102.ts';

const published='2026-09-28';
const iso={name:'ISO 18295-1:2017, Customer contact centres',url:'https://www.iso.org/standard/64739.html'};
const privacy={name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'};
const csf={name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'};
const identity={name:'NIST SP 800-63-4, Digital Identity Guidelines',url:'https://pages.nist.gov/800-63-4/'};
const zero={name:'NIST SP 800-207, Zero Trust Architecture',url:'https://csrc.nist.gov/pubs/sp/800/207/final'};
const ftcOrder={name:'eCFR, 16 CFR Part 435, Mail, Internet, or Telephone Order Merchandise',url:'https://www.ecfr.gov/current/title-16/chapter-I/subchapter-D/part-435'};
const ftcTsr={name:'FTC, Complying with the Telemarketing Sales Rule',url:'https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule'};

type Seed={slug:string;title:string;excerpt:string;image:string;sources:ResearchPost['sources'];links:string[];sections:ResearchPost['sections']};
const make=(seed:Seed,index:number):ResearchPost=>({
  ...seed,published,sourceDate:published,internalLinks:['/research',...seed.links],
  keyStats:['One defined operating cohort','One authoritative state record','Unknown and conflicting states reported separately'],
  takeaways:['Measure the decision boundary, not activity alone.','Keep source events separate from agent interpretation.','Escalate exceptions to a named client owner before expanding the workflow.'],
  faqs:[
    {question:'Does this research make a legal, security, or compliance determination?',answer:'No. It is an operational research method. Authorized legal, privacy, security, commercial, and policy owners must apply requirements to the actual service, data, contract, and jurisdiction.'},
    {question:'Does this brief prescribe one universal target?',answer:'No. A useful threshold depends on the customer journey, risk, source quality, channel, authority boundary, and client decision owner.'}
  ],
  serviceHandoff:{href:'/contact-us',label:'Map a controlled support lane',body:'Choose one queue, document permitted actions and exceptions, and test the handoff before adding volume.'},
  sections:[...seed.sections,...prior[index].sections.slice(3).map(section=>section.heading==='Replication record and source notes'?{...section,body:section.body.replace('September 25, 2026','September 28, 2026')}:section)]
});

export const september28Cala105ResearchBatch:readonly ResearchPost[]=[
  make({slug:'inbound-ivr-intent-handoff-drift-research',title:'Intent Drift Between IVR Selection and Inbound Agent Handoff',excerpt:'An IVR choice is routing evidence, not a verified customer need; research should test where labels, context, and authority diverge before the agent acts.',image:'/research-aug20/escalation-path-design.png',sources:[iso,privacy,identity,csf],links:['/services/inbound-call-handling','/research/outsourced-call-center-transfer-continuity-measurement'],sections:[
    {heading:'Decision question and inbound boundary',body:'How often does the reason inferred from an interactive voice response selection still match the customer’s stated need when an outsourced inbound representative accepts the contact? The unit is one offered contact linked to the IVR path, menu version and language, key or speech input, routing label, transfer history, agent opening question, customer-stated purpose, identity state, permitted action, correction event, next owner, and disposition. The IVR selection can help place a contact, but it does not establish identity, urgency, entitlement, or consent. A caller may choose the nearest available label, misunderstand a translated prompt, reuse an old shortcut, or have several needs. The provider may confirm the purpose, correct an operational label, and route within written authority. It should not treat the menu choice as a customer admission, reveal account information because a sensitive queue was selected, or force the customer to restart simply because the initial route was wrong. The client owns menu design, authentication, priority rules, specialist access, emergency handling, and remedies when routing causes harm.'},
    {heading:'Primary-source basis and interpretation',body:'ISO 18295-1 provides customer-contact service and performance context across inbound and outbound channels. The NIST Privacy Framework supports a defined purpose and proportionate handling of contact metadata. NIST Digital Identity Guidelines separate identity evidence from convenient signals, while Cybersecurity Framework 2.0 supports governed roles, observable events, response, and improvement. These sources support explicit definitions, minimal data use, attributable routing changes, and an owned exception path. They do not prove the customer’s intent, require one menu depth, select an authentication level, or establish that transfer avoidance is always desirable. A quick transfer can be the safe result when the first queue lacks authority. Analysis must therefore distinguish routing accuracy, customer effort, authority fit, and completed outcome instead of collapsing them into one containment rate.'},
    {heading:'Cohort method, counterexamples, and failure modes',body:'Freeze the menu version and declare an observation window. Include answered, abandoned, transferred, misrouted, language-assisted, and unresolved contacts; do not sample only completed calls. Stratify by entry label, language, time band, transfer count, and customer impact. Have a second reviewer code the opening exchange without seeing the original route, then reconcile disagreements. Test a billing label used for an order-status question, a technical-support label chosen after an outage message, a caller with two needs, a speech-recognition fallback, a transferred caller whose original selection is lost, and an urgent statement that does not fit any menu. Compare routing logs, approved transcript or recording evidence, CRM reason, agent correction, accepting-owner acknowledgment, and final status. Report exact matches, partial matches, corrected labels, safe transfers, loops, disconnects, unknowns, and unresolved cases separately. Common failures include rewarding containment after the wrong action, counting an agent correction as caller error, exposing sensitive context in a transfer note, preserving stale intent across a second need, and redesigning a menu from a convenience sample. The result is observational; it can locate drift but cannot by itself prove whether wording, recognition, customer strategy, training, or queue design caused it.'}
  ]},0),
  make({slug:'omnichannel-delayed-message-duplicate-action-research',title:'Duplicate-Action Risk from Delayed Omnichannel Messages',excerpt:'When messages arrive late or out of order, support needs event time, receipt time, state version, and an accountable conflict path before repeating a customer-facing action.',image:'/research-aug20/channel-switch-continuity.png',sources:[privacy,csf,zero,iso],links:['/services/omnichannel-customer-support','/research/call-center-cross-channel-contact-linkage-research-brief'],sections:[
    {heading:'Decision question and omnichannel boundary',body:'How should an outsourced omnichannel queue decide whether to act when an email, chat, text, portal message, or integration event arrives after another channel may already have changed the customer’s case? The unit is one proposed action linked to message event time, platform receipt time, channel, permitted customer identifier, conversation and case identifiers, last known state version, prior action, pending work, worker view time, conflict check, decision, and next owner. A delayed message can still be valid evidence, but sequence of arrival is not necessarily sequence of customer intent. The provider may reconcile current authoritative state, acknowledge uncertainty, and pause a duplicate action. It should not issue a second refund, replacement, cancellation, booking, or escalation because an old message appears unread; nor should it merge records merely because text looks similar. The client owns identity-linking rules, system-of-record priority, material-action authority, conflict remedies, retention, and incident response.'},
    {heading:'Primary-source basis and interpretation',body:'The NIST Privacy Framework supports purpose-aware handling and minimized linkage of customer data. Cybersecurity Framework 2.0 provides outcomes for governance, protection, detection, response, recovery, and improvement. NIST Zero Trust Architecture supports explicit decisions for each user, asset, and resource rather than inherited trust between connected systems. ISO 18295-1 supplies customer-contact process and outcome context across channels. Together these sources support attributable events, controlled access, current-state checks, and owned recovery. They do not declare one channel authoritative, prove that two identifiers belong to the same person, establish a safe deduplication window, or decide whether a completed customer remedy can be reversed. A delivery receipt is evidence about transport, not comprehension; a CRM timestamp may show ingestion rather than the moment the customer sent the message.'},
    {heading:'Cohort method, race cases, and failure modes',body:'Declare a fixed cohort of cases with messages on at least two channels or with a measured ingestion delay. Preserve both event and receipt timestamps with zones, connector status, state version, action identifier, worker decision, conflict result, and unresolved status. Sample ordinary and high-impact actions separately, because a duplicate informational reply and a duplicate financial remedy have different consequences. Test an email delayed behind a chat cancellation, a text response received after an appointment was changed by phone, two agents opening the same queue item, an integration retry that creates a second event, a customer replying from an unlinked address, and a service outage that replays messages. Compare source-channel logs, integration events, authoritative case history, action-system records, customer updates, and owner acknowledgment. Report proposed, suppressed, confirmed, duplicated, reversed, escalated, and unknown actions separately. Common failures include sorting only by ingestion time, overwriting the earlier record, treating fuzzy text similarity as identity proof, closing both cases after one action, and hiding unresolved conflicts inside an average response time. Observed association between delay and duplication cannot prove causation; platform retries, staffing, interface design, and policy ambiguity may also shape the result.'}
  ]},1),
  make({slug:'order-support-address-change-fulfillment-boundary-research',title:'Address-Change Boundaries After Order Fulfillment Begins',excerpt:'An address request is not one reversible update once allocation, labels, carrier possession, fraud controls, and customer notices have moved to different states.',image:'/research-aug20/customer-promise-reconciliation.png',sources:[ftcOrder,privacy,csf,iso],links:['/services/order-management-support','/research/order-support-split-shipment-status-reconciliation-research'],sections:[
    {heading:'Decision question and order boundary',body:'What may an outsourced order-support representative promise when a customer requests an address change after some part of fulfillment has begun? The unit is one order line linked to verified customer and order context, request time, old and proposed address in appropriately masked form, reason, item state, warehouse action, label state, carrier possession, intercept option if any, fraud or security hold, payment or tax dependency, customer update, authority decision, and final outcome. A change entered in the storefront is not proof that the warehouse or carrier accepted it. The provider may describe confirmed states, perform a listed update before the client’s cutoff, or submit a controlled exception. It should not promise rerouting from a text-field edit, expose the existing address before suitable verification, cancel shipped inventory, create a replacement to disguise uncertainty, or interpret fraud signals. The merchant owns eligibility, identity requirements, intercepts, fees, taxes, loss allocation, replacement, refund, and exceptions.'},
    {heading:'Primary-source basis and interpretation',body:'The authoritative eCFR text for 16 CFR Part 435 provides concepts relevant to covered mail, internet, and telephone merchandise transactions, including shipment and refund obligations. The NIST Privacy Framework supports purposeful and proportionate handling of customer and address data. Cybersecurity Framework 2.0 supports governed records, reliable information, response, and recovery. ISO 18295-1 supplies customer-contact process and outcome context. These sources support truthful state communication, minimized address exposure, attributable changes, and a named exception owner. They do not create a universal address-change right, determine carrier liability, define an acceptable identity check for every merchant, or prove physical parcel location. Client legal and policy owners must apply obligations to the actual product, promise, transaction, geography, and evidence.'},
    {heading:'Lifecycle method, split states, and failure modes',body:'Map accepted, payment reviewed, allocated, picked, packed, label created, tendered, carrier accepted, in transit, delivered, intercepted, returned, cancelled, replaced, refunded, and unknown separately for every line and parcel. Define which state record is authoritative for each transition. Test a request before allocation, a label generated but not tendered, two parcels in different states, an apartment-unit correction, a change across tax jurisdictions, a gift order, a suspected account takeover, a carrier intercept with no final confirmation, and a customer who moved after dispatch. Compare order history, warehouse events, carrier events, approved risk decisions, customer messages, and remedy instructions. Report changes accepted, rejected, partially applied, intercepted, returned, duplicated, misdelivered, escalated, and unresolved. Common failures include changing only the customer profile, applying one parcel outcome to every line, reading label creation as possession, quoting a carrier estimate as confirmation, collecting a full address in unrestricted notes, and issuing a second shipment while the first remains recoverable. The study can identify inconsistent states and decision delays; it cannot establish who caused a loss or which remedy is legally required.'}
  ]},2),
  make({slug:'outbound-appointment-location-eligibility-research',title:'Location and Eligibility Evidence in Outbound Appointment Setting',excerpt:'A free calendar slot is not necessarily bookable when service area, visit mode, eligibility, resource, and customer location have not been reconciled.',image:'/research-aug21/callback-timezone-integrity.png',sources:[privacy,identity,ftcTsr,iso],links:['/services/outbound-appointment-setting','/research/outbound-appointment-reschedule-collision-research'],sections:[
    {heading:'Decision question and appointment boundary',body:'How should an outsourced appointment-setting team determine whether an offered slot is usable when service location, customer location, remote or in-person mode, eligibility, and assigned resource may differ? The unit is one proposed slot linked to the approved contact basis, customer identity state, stated service, permitted location evidence, service-area rule version, visit mode, resource qualification supplied by the client, availability check time, booking result, confirmation wording, exception, and final status. The provider may apply published client rules, offer current approved slots, and route an eligibility exception. It should not infer residence from caller ID, collect unnecessary location detail, interpret licensure or benefits rules, disclose another customer’s booking, override a service-area restriction, or represent a tentative hold as confirmed. The client owns eligibility, geography, resource assignment, accessibility, fees, exceptions, and remedies.'},
    {heading:'Primary-source basis and interpretation',body:'The NIST Privacy Framework supports purpose-aware handling of location, identity, and scheduling data. NIST Digital Identity Guidelines provide a risk-based lens for identity evidence without equating convenient attributes with proof. FTC Telemarketing Sales Rule guidance is relevant where a campaign is covered and addresses truthful disclosures, calling restrictions, do-not-call handling, and records. ISO 18295-1 supplies customer-contact process context. These sources support bounded data collection, approved contact rules, attributable bookings, and accurate customer communication. They do not decide whether an appointment campaign is legally covered, set a service radius, certify a provider, determine benefit eligibility, or prescribe one verification method. Those remain client legal, policy, and service-delivery decisions.'},
    {heading:'Cohort method, boundary cases, and failure modes',body:'Declare one service line, rule version, and observation period. Include booked, declined, waitlisted, redirected, cancelled, and unresolved offers rather than only completed appointments. Test a customer near a service-area boundary, a remote visit available in one jurisdiction but not another, a mobile service whose resource changes, an address that fails normalization, a preferred location with no eligible resource, a caregiver booking for someone else, and an integration that shows capacity without the required visit mode. Compare the approved eligibility source, calendar resource, location rule, booking history, customer confirmation, and exception-owner acknowledgment. Keep the customer’s statement separate from verified or client-supplied eligibility evidence. Report eligible and confirmed, eligible but unavailable, ineligible, redirected, exception-pending, duplicate, and unknown offers. Common failures include using a postal code as identity proof, exposing the reason another slot is unavailable, booking first and checking rules later, storing precise location without need, changing a visit mode to force availability, and claiming the customer was ineligible when the source merely timed out. The result can test rule execution and evidence quality, not the fairness or legality of the underlying client policy.'}
  ]},3),
  make({slug:'tier-one-support-diagnostic-evidence-redaction-research',title:'Diagnostic-Evidence Redaction Before Tier-One Escalation',excerpt:'Screenshots and logs can speed escalation while also carrying passwords, tokens, customer data, and unrelated system context that the receiving team does not need.',image:'/research-aug21/consent-provenance.png',sources:[zero,identity,privacy,csf,iso],links:['/services/tier-one-technical-support','/research/call-center-sensitive-field-exposure-research-brief'],sections:[
    {heading:'Decision question and technical-support boundary',body:'What evidence should outsourced tier-one support collect, minimize, and transfer when a case needs technical escalation? The unit is one evidence item linked to case purpose, source system, collector, collection time, approved method, visible data classes, redaction or structured extraction, access group, transfer route, receiving-owner acknowledgment, retention instruction, and disposition. A screenshot or log excerpt may show a useful error state, but it can also expose credentials, tokens, account identifiers, internal hostnames, unrelated customers, or personal desktop content. A tier-one worker may follow a client-approved collection guide, stop when prohibited data appears, and route through the controlled case platform. The worker should not request passwords, copy complete logs by default, use personal capture tools, alter original evidence silently, send files through consumer messaging, or retain local copies. The client owns diagnostic tooling, evidence classes, security response, access, redaction rules, retention, and exceptions.'},
    {heading:'Primary-source basis and interpretation',body:'NIST Zero Trust Architecture supports explicit authorization for users, assets, and resources rather than trusting a transfer because it occurs inside a familiar network. NIST Digital Identity Guidelines help separate authentication secrets from ordinary support evidence. The Privacy Framework supports purpose limitation and minimized personal-data handling, while Cybersecurity Framework 2.0 supports governance, protection, detection, response, recovery, and improvement. ISO 18295-1 supplies customer-contact process context. Together these sources support a stated evidence purpose, least necessary access, attributable handling, and an owned incident path. They do not approve a capture tool, guarantee that automated redaction finds every secret, specify universal retention, or authorize tier one to investigate a suspected breach. Tool design, client architecture, contract, and applicable law remain material.'},
    {heading:'Cohort method, exposure tests, and failure modes',body:'Define a cohort of escalated cases and inventory evidence without reproducing sensitive values in the research dataset. Code evidence type, requested diagnostic question, collection method, data classes visible, redaction method, residual risk, receiver, access result, deletion state, and whether the escalation could be resolved from structured fields instead. Use synthetic test cases to evaluate password fields, API tokens, session cookies, customer identifiers, another user’s record, payment data, health-related text, internal addresses, and a multi-monitor capture. Separately review real events under approved access and have a second reviewer test the classification guide. Compare case records, evidence-store audit events, access grants, security alerts, receiver acknowledgment, and retention actions. Report necessary and minimized, over-collected, blocked, re-requested, misrouted, inaccessible, incident-escalated, deleted, and unknown items. Common failures include black boxes that can be reversed, cropping while metadata remains, pasting logs into unrestricted notes, granting a broad team access, treating upload success as receiver acceptance, and deleting the case copy while an unmanaged download persists. The study can show control gaps; it cannot prove that an unseen copy does not exist or that exposed data was misused.'}
  ]},4)
];
