import type {ResearchPost} from './fleet-data';
import {september28Cala105ResearchBatch as prior} from './research-sep28-cala105.ts';

const published='2026-10-02'; // reconcile to the actual first-live date before the combined push
const iso={name:'ISO 18295-1:2017, Customer contact centres',url:'https://www.iso.org/standard/64739.html'};
const privacy={name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'};
const csf={name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'};

export const october2Cala106ResearchBatch:readonly ResearchPost[]=[
  {
    slug:'inbound-call-abandonment-callback-offer-research',
    title:'Callback Offers and Inbound Call Abandonment: An Evidence Framework',
    excerpt:'A callback offer can reduce time on hold, but only a linked record of consent, queue position, customer time zone, attempted contact, and final ownership can show whether it resolved demand or merely renamed abandonment.',
    published,
    sourceDate:published,
    image:'/research-aug21/callback-timezone-integrity.png',
    sources:[iso,privacy,csf],
    internalLinks:['/research','/services/inbound-call-handling','/blog/inbound-call-volume-forecasting'],
    keyStats:['One offered inbound contact is the unit of analysis','Queue exit and callback completion are separate events','Unknown outcomes remain visible'],
    takeaways:['Do not classify acceptance of a callback as resolution.','Preserve the customer-local promise and the queue conditions at offer time.','Give every failed or disputed callback a named next owner.'],
    faqs:[
      {question:'Does a callback offer always improve customer experience?',answer:'No. The result depends on truthful timing, customer choice, successful contact, continuity of context, and whether the original need is actually resolved.'},
      {question:'Should an accepted callback disappear from abandonment reporting?',answer:'No. Report the original queue exit and the later callback outcome separately so managers can distinguish demand, waiting behavior, attempted recovery, and completed service.'}
    ],
    serviceHandoff:{href:'/contact-us',label:'Design an accountable inbound callback lane',body:'Start with one queue, define the promise and failure path, and review linked queue and callback evidence before expanding.'},
    sections:[
      {heading:'Decision question and operating boundary',body:'When does an offered callback represent a dependable alternative to waiting, and when does it simply move an unresolved inbound contact out of the visible queue? The unit of analysis is one offered inbound contact linked to arrival time, configured queue, estimated wait shown or spoken to the customer, offer wording and version, customer choice, permitted callback number, customer-local time zone, promised window, retained or released queue position, attempt events, authentication state, conversation outcome, disposition, repeat contact, and next owner. These fields should remain connected without treating a telephone number as identity proof or copying unnecessary customer data into a reporting file. The provider may present client-approved choices, record the customer’s selection, make an attempt inside a defined operating window, restore supplied context, and route exceptions. It should not claim that accepting the offer resolves the request, silently reset priority, conceal a failed attempt, expose sensitive context in voicemail, or close the case because a dial event occurred. The client owns offer eligibility, queue priority, retry policy, authentication, recording and consent rules, hours, remedies, and exceptions. The research question is therefore narrower than whether callbacks are good: it asks whether each customer promise can be reconstructed from observable events and whether the final state is truthful.'},
      {heading:'Primary-source basis and careful interpretation',body:'ISO 18295-1 provides a customer-contact-centre frame for service requirements, customer experience, processes, people, and performance. The NIST Privacy Framework supports purpose-aware data processing, proportionate collection, governance, and communication about privacy risk. NIST Cybersecurity Framework 2.0 supports governed roles, protected information, detection of unexpected states, response, recovery, and improvement. Together, these sources support a defined callback purpose, minimized contact data, attributable events, protected access, a visible exception path, and review against the customer outcome. They do not prescribe a universal wait threshold, prove that a callback number belongs to the caller, determine whether consent is legally sufficient, or declare one retry pattern appropriate for every service. They also do not make an estimated wait a guaranteed promise. That distinction matters because a technically successful dial can still be an operational failure: the call may arrive outside the stated local window, reach another person, omit the original context, disconnect before an agent accepts it, or produce a second queue journey. Conversely, an unanswered attempt may have followed the approved process while leaving the need unresolved. Reporting must keep process conformance, contact success, customer effort, and resolution separate rather than compressing them into one callback completion percentage.'},
      {heading:'Cohort design, event linkage, and counterexamples',body:'Choose a declared queue, offer configuration, and observation window before extracting records. Include contacts that accepted, declined, ignored, or never received the offer, along with ordinary answered and abandoned contacts needed to understand selection effects. Freeze the definitions used during the period. Link events using approved operational identifiers rather than names, free-text similarity, or shared telephone numbers. Preserve event timestamps with offsets and distinguish offer time, queue-exit time, scheduled time, dial time, agent-accept time, customer-answer time, and final-update time. Stratify results by interval, stated wait band, language, routing path, customer-local window, retained-position rule, attempt result, and impact of the underlying request. Test counterexamples explicitly: a customer accepts but calls again before the callback; a dialer connects to voicemail and marks success; an agent receives the callback without the IVR reason; the customer answers but cannot complete authentication; a callback crosses midnight or daylight-saving boundaries; the queue recovers before the promised attempt; two requests share one number; a network retry creates duplicate calls; and a high-impact contact is offered a lane that lacks the required authority. Compare queue events, callback platform events, telephony disposition, approved recording or transcript evidence where permitted, case history, repeat-contact evidence, and receiving-owner acknowledgment. Do not infer customer satisfaction from silence or infer causal improvement from a before-and-after average without accounting for demand mix, staffing, outages, and self-selection.'},
      {heading:'Measures that preserve the customer journey',body:'Report offered, accepted, declined, ordinary answered, ordinary abandoned, callback attempted, callback connected, authenticated where required, request completed, transferred, repeat-contacted, failed, cancelled, duplicate, and unknown states separately. Pair counts with denominators and a declared observation period. Useful intervals include time from acceptance to first valid attempt, deviation from the customer-local promise, time from connection to an authorized owner, and time to final known outcome. A queue-exit rate answers a different question from resolution. A dialer connection rate answers a different question from speaking with the intended customer. A low average can hide a long tail of missed high-impact promises, so show distributions or bands and inspect exceptions. Maintain a reconciliation table in which every accepted offer reaches exactly one current state, while allowing later events to change that state without erasing history. If identifiers cannot be linked safely, classify the outcome as unknown rather than joining records speculatively. Review repeat contacts as evidence of possible unresolved demand, not automatic proof that the callback failed, because customers may have a second need. The strongest operational view follows the promise from the original arrival through a final owner and keeps uncertainty measurable.'},
      {heading:'Failure modes, controls, and replication record',body:'Common failure modes include removing accepted offers from abandonment counts without a companion outcome; starting the clock at dial time; using server time instead of the customer-local promise; marking voicemail, busy, or no-answer as completed service; discarding the original routing context; exposing account details before authentication; allowing parallel queue and callback work to trigger duplicate actions; and closing records after the configured retry limit with no accountable owner. Controls should make these states visible. Version the offer wording and eligibility rule. Record whether queue position is retained. Protect callback numbers and restrict exports. Use neutral voicemail text. Pass only necessary context to the accepting worker. Require an idempotency or conflict check before a material account action. Route missed high-impact promises to a named client owner, and define when callback offers pause during outages or capacity loss. For replication, record the query window, systems consulted, event definitions, exclusions, linkage success, unknown count, reviewer, and source access date. Have a second reviewer trace a sample from arrival through final status and challenge any state inferred from one system alone. This observational method can reveal broken promises, missing links, and misleading classifications. It cannot by itself prove that callbacks caused a change in satisfaction, determine a legal consent rule, or set the correct staffing plan. Those decisions require the actual jurisdiction, contract, customer population, risk, and client policy.'},
      ...prior[0].sections.slice(5)
    ]
  },
  {
    slug:'omnichannel-case-reopen-state-reconciliation-research', title:'Reopened Omnichannel Cases: State Reconciliation Before New Action',
    excerpt:'A reopened contact is not automatically a continuation or a new case; support should reconcile the prior outcome, new evidence, pending work, and current owner before acting.', published, sourceDate:published,
    image:'/research-aug20/channel-switch-continuity.png', sources:[iso,privacy,csf],
    internalLinks:['/research','/services/omnichannel-customer-support','/research/omnichannel-delayed-message-duplicate-action-research'],
    keyStats:['One reopened customer need is the unit of analysis','Prior closure and current state remain distinct','Duplicate and unknown actions stay visible'],
    takeaways:['Reconcile before repeating a customer-impacting action.','Preserve why the earlier case closed and what changed.','Assign one current owner without erasing prior responsibility.'],
    faqs:[{question:'Is every new message a reopened case?',answer:'No. The rule should distinguish new evidence about the same need, a separate need, a delayed message, and a duplicate event.'},{question:'Does reopening prove the first resolution failed?',answer:'No. The customer may have new information or a different need; the review must trace evidence rather than infer blame.'}],
    serviceHandoff:{href:'/contact-us',label:'Map an omnichannel reconciliation lane',body:'Define closure, reopening, conflict checks, and owner acceptance for one case family before adding channels.'},
    sections:[
      {heading:'Decision question and operating boundary',body:'When an email reply, chat, call, portal update, or integration event arrives after a case is marked closed, how should an outsourced support queue determine the current state without duplicating work or suppressing a legitimate new need? The unit is one customer need linked to permitted identifiers, original channel, prior case and closure reason, last verified state, customer promise, later event time, receipt time, new evidence, related open work, conflict check, worker decision, current owner, and final outcome. Closure is a workflow state, not proof that the customer accepted the outcome or that every downstream action completed. The provider may compare authoritative records, reopen within documented authority, create a separately linked case when the need is distinct, and pause a material action when state conflicts. It should not copy a prior resolution into a new message, repeat a refund or replacement, merge records from text similarity alone, erase the original closure, or blame a worker before checking delayed events. The client owns identity linkage, system priority, closure rules, material-action authority, retention, remedies, and exception decisions.'},
      {heading:'Primary-source basis and interpretation',body:'ISO 18295-1 provides customer-contact process and outcome context across channels. The NIST Privacy Framework supports purpose-aware linkage and proportionate handling of customer records. NIST Cybersecurity Framework 2.0 supports governed state, detection of unexpected conditions, response, recovery, and improvement. These sources support attributable events, current-state checks, controlled access, explicit ownership, and preserved uncertainty. They do not decide that two contacts belong to one person, define a universal closure code, make a CRM state authoritative, or prove that reopening was caused by poor service. A platform receipt time may differ from the customer event time, and a completed support note may precede a delayed downstream action. Analysis must therefore separate contact linkage, workflow conformance, customer outcome, duplicate prevention, and owner response. Source pages were checked October 2, 2026; the conclusions are operational inferences rather than vendor-performance claims or legal determinations.'},
      {heading:'Cohort method, race cases, and limitations',body:'Declare the case family, systems of record, closure definitions, linkage rule, and observation window. Include cases reopened automatically, reopened by a worker, linked as a new need, left closed, duplicated, and unresolved. Test a delayed email after a chat refund, a customer with two simultaneous needs, a portal update after an agent closure, an integration retry, a downstream task still pending, an identity mismatch, a message from an unlinked address, and a case reopened after the policy version changed. Compare channel events, case history, action-system records, customer communications, pending-task state, and receiving-owner acknowledgment. Report correctly continued, separately linked, duplicated, suppressed, mismerged, owner-pending, resolved, and unknown outcomes separately. Common failures include sorting only by receipt time, overwriting the prior state, treating similar wording as identity proof, closing both records after one action, and using reopen rate as an individual score. The design can reveal reconciliation gaps but cannot prove causation or satisfaction from status records alone.'},
      ...prior[1].sections.slice(3)
    ]
  },
  {
    slug:'order-support-partial-cancellation-evidence-research', title:'Partial Order Cancellation Evidence Across Fulfillment States',
    excerpt:'Cancelling one order line requires item-level state, authority, dependency, refund, and customer-message evidence; an order-level label is too coarse.', published, sourceDate:published,
    image:'/research-aug20/customer-promise-reconciliation.png', sources:[iso,privacy,csf],
    internalLinks:['/research','/services/order-management-support','/research/order-support-address-change-fulfillment-boundary-research'],
    keyStats:['One order line is the unit of analysis','Cancellation and refund are separate outcomes','Split and unknown states remain visible'],
    takeaways:['Do not infer every line state from the order header.','Confirm the authoritative transition before promising cancellation.','Keep fulfillment, payment, and customer updates linked but distinct.'],
    faqs:[{question:'Does a cancellation request mean the item is cancelled?',answer:'No. It records customer intent; the responsible system or owner must confirm whether the transition occurred.'},{question:'Does this brief determine refund rights?',answer:'No. Client policy and authorized legal owners must decide eligibility and obligations for the actual transaction.'}],
    serviceHandoff:{href:'/contact-us',label:'Define an item-level order lane',body:'Map permitted item states, cancellation cutoffs, refund ownership, and split-order exceptions before assigning volume.'},
    sections:[
      {heading:'Decision question and order boundary',body:'What evidence allows an outsourced order-support representative to say that selected items, rather than an entire order, have been cancelled? The unit is one order line linked to verified order context, customer request time, quantity, bundle or promotion dependency, inventory allocation, pick and pack state, label and parcel association, carrier possession, cancellation command, accepting system, payment authorization, refund or release state, tax and shipping dependency, customer update, exception owner, and final outcome. A request, button click, or order-header status does not prove that every intended line changed. The provider may submit an approved action before a defined cutoff, describe confirmed states, and route conflicting or irreversible cases. It should not cancel substitute lines, promise a refund from a pending command, conceal a bundle dependency, create replacement transactions to simulate success, or interpret fraud and legal rights. The merchant owns eligibility, item dependencies, fulfillment cutoffs, fees, payment action, exceptions, and remedies.'},
      {heading:'Evidence basis and careful interpretation',body:'ISO 18295-1 supplies customer-contact process and outcome context. The NIST Privacy Framework supports purposeful, proportionate use of order and customer information. NIST Cybersecurity Framework 2.0 supports governed records, protected access, observable transitions, response, and recovery. Checked October 2, 2026, these sources support explicit state definitions, attributable actions, minimized disclosure, and an accountable exception path. They do not create a right to cancel, establish inventory ownership, prove a parcel location, define a refund deadline, or select the authoritative commerce platform. An order line may be cancellation-eligible while its paired discount, shipment fee, gift item, or payment allocation requires a separate decision. The study must keep customer request, accepted cancellation, physical stop, payment release, refund completion, and communication as distinct events. Legal and policy owners must apply transaction-specific obligations.'},
      {heading:'Lifecycle method, split states, and limitations',body:'Freeze one workflow version and declare the observation window. Map requested, accepted, rejected, allocated, picked, packed, labelled, tendered, stopped, shipped, returned, payment-released, refunded, and unknown at line and parcel level. Include full, partial, failed, duplicate, and abandoned attempts. Test two lines in different warehouses, a bundle with shared discount, one line already tendered, a partial quantity, a tax-changing cancellation, a gift, a marketplace line, and a command acknowledged by the storefront but rejected downstream. Compare order history, warehouse events, carrier state, payment records, customer communications, and owner acknowledgment. Report eligible and confirmed, partially confirmed, too late, dependency-held, refund-pending, duplicated, customer-corrected, and unresolved separately. Common failures include changing only the header, reading label creation as possession, issuing a refund before cancellation is durable, and applying one parcel event to all items. The research can locate inconsistent states and delayed decisions; it cannot establish causation, liability, or the remedy owed.'},
      ...prior[2].sections.slice(3)
    ]
  },
  {
    slug:'outbound-appointment-reminder-preference-research', title:'Contact Preferences in Outbound Appointment Reminders',
    excerpt:'An appointment reminder needs a defined service purpose, current channel preference, local-time basis, and suppression path instead of a generic permission flag.', published, sourceDate:published,
    image:'/research-aug21/callback-timezone-integrity.png', sources:[iso,privacy,csf],
    internalLinks:['/research','/services/outbound-appointment-setting','/research/outbound-appointment-location-eligibility-research'],
    keyStats:['One planned reminder is the unit of analysis','Purpose and channel preference are separate fields','Suppressed and unknown outcomes remain visible'],
    takeaways:['Bind each reminder to its approved service purpose.','Check current schedule and preference state before contact.','Preserve local time, source, and effective time for every change.'],
    faqs:[{question:'Does agreeing to an appointment authorize every follow-up?',answer:'No. The client must define the purpose, channel, timing, and applicable contact rules.'},{question:'Is message delivery proof the customer received the reminder?',answer:'No. Delivery evidence describes a platform event, not identity, comprehension, or attendance.'}],
    serviceHandoff:{href:'/contact-us',label:'Design a bounded reminder lane',body:'Choose one appointment workflow, document purpose and preferences, and test suppression before expanding outreach.'},
    sections:[
      {heading:'Decision question and appointment boundary',body:'How should an outsourced appointment-setting team reconcile reminder purpose, channel preference, cancellation state, local time, and opt-out evidence before a call, text, or email? The unit is one planned reminder linked to appointment identifier, campaign purpose, contact source, identity state, schedule version, current appointment status, channel preference and scope, effective time, customer-local zone source, quiet or service window, queue snapshot, attempt, delivery evidence, response, correction, and final owner. A stored telephone number or an earlier booking message is not a universal permission flag. The provider may apply a client-approved service workflow, confirm current state, use the selected channel, and suppress or escalate uncertainty. It should not convert reminders into promotion, override a preference to meet volume, disclose appointment details to another person, contact after cancellation, or invent a time zone. The client owns campaign classification, lawful basis, accessibility, timing, retries, scripts, suppression, exceptions, and remedies.'},
      {heading:'Primary-source basis and interpretation',body:'ISO 18295-1 provides customer-contact process and outcome context. The NIST Privacy Framework supports purpose limitation, customer participation, minimized contact data, and governed processing. NIST Cybersecurity Framework 2.0 supports reliable information flows, protection, detection, response, and improvement. Reviewed October 2, 2026, these sources support explicit purpose, attributable preference changes, current-state checks, accurate communication, and owned exceptions. They do not authorize a channel, classify a particular campaign, determine consent, define quiet hours, or prove that a delivered message reached the intended customer. A preference may apply to one purpose, appointment, brand, or channel rather than every future interaction. Researchers must distinguish source facts, client rules, worker observations, customer instructions, and legal conclusions. Useful evaluation separates suppression conformance, contact success, schedule accuracy, attendance, and customer impact.'},
      {heading:'Cohort method, preference conflicts, and limitations',body:'Declare the appointment type, reminder purposes, channels, preference source hierarchy, local-time rule, and period. Include attempted, suppressed, delivered, failed, corrected, cancelled, and unresolved reminders. Test cancellation immediately before queue export, a text opt-out with email still approved, a caregiver number, a reassigned number, a daylight-saving boundary, a language preference, two appointments, an integration outage, and conflicting CRM and messaging-platform states. Compare schedule history, preference events, effective timestamps, campaign snapshots, dialer or message records, customer responses, and owner acknowledgment. Report correctly contacted, correctly suppressed, stale-state attempted, wrong-channel, outside-window, wrong-recipient risk, corrected, and unknown separately. Common failures include overwriting preference history, sorting by ingestion instead of event time, treating no response as permission, and blaming a worker for a locked stale list. The study can measure observed rule execution and propagation delay; it cannot infer comprehension, satisfaction, attendance causation, or legal sufficiency from delivery logs.'},
      ...prior[3].sections.slice(3)
    ]
  },
  {
    slug:'tier-one-support-device-ownership-boundary-research', title:'Device-Ownership Boundaries in Tier-One Technical Support',
    excerpt:'Diagnostic authority changes when a device is client-managed, customer-owned, shared, employer-controlled, or unknown; tier one should establish the boundary before instructing changes.', published, sourceDate:published,
    image:'/research-aug21/consent-provenance.png', sources:[iso,privacy,csf],
    internalLinks:['/research','/services/tier-one-technical-support','/research/tier-one-support-diagnostic-evidence-redaction-research'],
    keyStats:['One device-context decision is the unit of analysis','Ownership, management, and user authority are separate','Unknown devices follow a safe fallback'],
    takeaways:['Do not infer device authority from account access.','Match each diagnostic instruction to a documented ownership class.','Escalate unknown or high-impact changes before execution.'],
    faqs:[{question:'Does this research authorize remote access?',answer:'No. The client must define tools, identity, consent, device classes, permissions, logging, and prohibited actions.'},{question:'Can a customer-owned device receive the same steps as a managed device?',answer:'Not automatically. Available controls, data exposure, reversibility, support scope, and authority may differ.'}],
    serviceHandoff:{href:'/contact-us',label:'Map a controlled tier-one lane',body:'Classify device contexts, permitted diagnostics, stop conditions, and escalation owners before assigning technical contacts.'},
    sections:[
      {heading:'Decision question and technical-support boundary',body:'What must an outsourced tier-one worker establish before asking a customer to change settings, install software, share a screen, collect logs, restart equipment, or grant remote access? The unit is one proposed instruction linked to case purpose, customer identity state, device identifier in minimized form, asserted owner, management authority, primary user, environment, data sensitivity, approved support scope, instruction version, reversibility, backup or recovery dependency, customer agreement, observed result, escalation, and final disposition. Account access does not prove ownership of the device or authority to alter an employer, school, household, or managed asset. The provider may ask bounded classification questions, use approved low-risk steps for the confirmed class, stop at prohibited data, and route uncertainty. It should not disable security controls, request credentials, install unapproved tools, access unrelated files, claim ownership, or continue after a conflicting management signal. The client owns tool approval, device classes, verification, permitted changes, consent, security response, recovery, and exceptions.'},
      {heading:'Primary-source basis and interpretation',body:'ISO 18295-1 supplies customer-contact process and outcome context. The NIST Privacy Framework supports purpose-aware and proportionate handling of device and user information. NIST Cybersecurity Framework 2.0 supports governance, asset understanding, protection, detection, response, recovery, and improvement. Checked October 2, 2026, these sources support defined scope, least-necessary evidence, attributable instructions, protected access, stop conditions, and recovery ownership. They do not prove who owns a device, approve remote-support software, authorize a configuration change, set a universal authentication level, or guarantee that a reversible-looking action has no business impact. A personally purchased device may still be employer-managed; a client-owned endpoint may be used by several people; and an unknown device may expose other customers or systems. Analysis must separate ownership claim, management evidence, user authority, support entitlement, technical feasibility, and actual outcome.'},
      {heading:'Cohort method, device cases, and limitations',body:'Declare the supported products, device classes, instruction versions, tools, and review period. Include completed, stopped, escalated, refused, reversed, incident-linked, and unresolved contacts. Test a client-issued managed laptop, a personal phone with work profile, a shared family tablet, an employer computer, a public kiosk, a virtual desktop, an accessibility device, a device showing another user’s session, and a caller unable to determine management status. Use synthetic cases for risky steps and inspect real records only through approved access. Compare asset or management evidence where available, support entitlement, case notes, tool audit events, customer confirmation, security alerts, receiving-owner acknowledgment, and recovery actions. Report correctly classified, safe-step completed, prohibited-step stopped, ownership-conflict escalated, overreached, reversed, incident-routed, and unknown separately. Common failures include treating administrator access as authority, collecting serial numbers without need, using personal screen-capture tools, and marking a reboot as resolution. The study can reveal control gaps; it cannot establish legal ownership, detect every hidden management control, or prove absence of downstream harm.'},
      ...prior[4].sections.slice(3)
    ]
  }
];
