import type {ResearchPost} from './fleet-data';
const sources=[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},{name:'ISO 18295-1 Customer contact centres',url:'https://www.iso.org/standard/64739.html'}] as const;
const studies=[
 ['call-center-intraday-demand-variance-research-brief','Call Center Intraday Demand Variance: A Research Brief','Intraday demand variance is useful only when arrivals, handle time, backlog, shrinkage, and channels share a defined interval.','Compare forecast and actual demand by interval, then separate volume error from handle-time change, absence, outage, or transferred work.','No universal variance threshold follows from the sources; low volume may still require action when impact or skill scarcity is high.'],
 ['call-center-shift-handoff-completeness-research-brief','Call Center Shift Handoff Completeness: A Research Brief','A complete shift handoff preserves open work, customer promises, blockers, evidence, and acceptance by the next owner.','Audit for a source identifier, verified action, open decision, due time, impact, next owner, and acceptance.','Field presence alone cannot prove service quality; compare the handoff with the source interaction and eventual outcome.'],
 ['call-center-escalation-latency-research-brief','Call Center Escalation Latency: A Research Brief','Escalation latency contains two clocks: time to owner acknowledgment and time to an authorized decision or safe next action.','Define the start event and impact class, measure acknowledgment and decision separately, and identify missing evidence or authority.','A shorter clock is not automatically safer when it rewards unsupported decisions; compare consistent case classes.'],
 ['call-center-customer-promise-fulfillment-research-brief','Call Center Customer Promise Fulfillment: A Research Brief','Promise fulfillment connects the commitment, customer time zone, channel, due window, dependency, owner, and final outcome.','Classify on-time completion, unreachable attempts, renegotiated promises, missed promises, and unresolved work from approved records.','The method cannot decide which promises to authorize; policy, jurisdiction, channel, and customer circumstances remain client-owned.'],
 ['outsourced-call-center-daily-control-review-research-brief','Outsourced Call Center Daily Control Review: A Research Brief','A daily control review should test live operating risks and produce named decisions instead of repeating dashboard totals.','Review queue availability, staffing exceptions, access anomalies, current guidance, overdue promises, critical quality findings, and unowned escalations.','This review does not replace incident, workforce, privacy, or policy governance; it routes issues to those owners.'],
] as const;
export const september1ResearchBatch: readonly ResearchPost[]=studies.map(([slug,title,excerpt,method,limits],index)=>({slug,title,excerpt,published:'2026-09-01',sourceDate:'2026-09-01',sources,keyStats:[`${3+index} operating variables defined`,'2 decision clocks separated','1 accountable review owner required'],takeaways:[excerpt,method,limits],sections:[{heading:'Research question and scope',body:`This desk review examines ${title.replace(': A Research Brief','').toLowerCase()} in an outsourced customer-contact operation. It evaluates control design, not a vendor, workforce, or country.`},{heading:'Evidence reviewed',body:'NIST CSF 2.0 supplies governance and improvement context. The NIST Privacy Framework informs minimization. ISO 18295-1 supplies customer-contact process context. The sources are design inputs, not proof of an operational result.'},{heading:'Method',body:method},{heading:'Interpretation limits',body:limits},{heading:'Manager decision',body:'Name the queue, observation period, source systems, exclusions, authorized owner, and customer-protection action. Preserve definitions with the result so comparisons remain valid.'}],faqs:[{question:'Does this provide a universal benchmark?',answer:'No. Thresholds depend on the queue, customer impact, service promise, and approved policy.'},{question:'What should be validated first?',answer:'Validate source records, definitions, period, exclusions, and owner before interpreting a result.'}],related:[],internalLinks:['/research','/services/workforce-reporting-support'],serviceHandoff:{href:'/contact-us',label:'Discuss a controlled operating lane',body:'Use this research to define a narrow workflow, evidence fields, review cadence, and manager-owned boundary.'}}));
