import type { ResearchPost } from './fleet-data';

const common = [
  { name: 'ISO 18295-1 Customer Contact Centres', url: 'https://www.iso.org/standard/73338.html' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
] as const;

const depth: Record<string, string> = {
  'call-center-knowledge-article-retirement-research-brief': 'A transition review should also inspect the moments around the change, not only the final library state. Sample searches made before approval, on the effective date, and after the replacement has been in use. Ask whether a worker could tell that the old answer was no longer authoritative, whether the new answer named its scope, and whether the exception route reached a person with authority. Compare routine and unusual requests because a replacement can work for the common case while failing at the boundary that creates the most escalation. Preserve the prior source, approval evidence, and reason for retirement in the non-public record, while keeping public guidance focused on customer use. If a search result points to two current-looking answers, stop treating the issue as training alone. It may be a governance conflict that requires the client owner to choose precedence. A small, repeatable review gives managers evidence for a targeted repair and prevents a freshness label from becoming an unsupported service claim.',
  'call-center-channel-switch-continuity-research-brief': 'Continuity should be tested at the handoff seam, where a customer’s intent meets a different channel’s constraints. Review whether the original channel captured the customer’s preferred response method, whether the receiving channel can safely carry that preference, and whether the time spent waiting changes the promise. Include accessibility needs without exposing unnecessary medical or personal detail. Test a case that must return to the original channel and a case that cannot. A customer should not be required to repeat information merely because the internal record is long, but a receiving worker should not inherit authority merely because a transcript exists. The evidence should separate a missing field from a policy requirement and a tool limitation from a worker choice. That distinction tells the client owner whether to change the form, permission, routing rule, or approved language. Channel continuity is credible when the next role can act from attributable evidence and the customer knows what happens next.',
  'call-center-escalation-path-design-research-brief': 'Escalation maps also need a change-control trail. A route that was valid during one client process may become wrong after a system migration, policy revision, leave period, or new service scope. Record the effective date, impacted queues, temporary fallback, and the person who accepted the change. Review returned cases for evidence that the map itself was stale rather than assuming the worker chose badly. A route should state what happens when the required evidence is unavailable: narrow the response, pause the action, seek an approved source, or notify a named owner. Those are different outcomes and should not be hidden inside a generic pending status. Managers can use a short route rehearsal before expanding volume, while the client owner retains the decision about policy and remedy. The research value lies in making the path reproducible under ordinary pressure, including the pressure created by an unavailable owner.',
  'call-center-absence-handoff-protocol-research-brief': 'Temporary coverage should have an explicit beginning and end. At activation, identify the cases and permissions transferred; at closure, confirm which cases returned, which remained with the backup, and whether temporary access was removed or reviewed. This protects continuity without turning a person’s absence into a public operational story. Review whether the handoff includes only what the replacement needs for the permitted action, especially when notes contain personal or payment-related details. A backup who can see a record but cannot decide the issue is not an owner; the protocol should make that limitation visible. Likewise, a person who can approve a policy exception may not be the right recipient for every routine case. The client owner and manager should agree the distinction before an absence occurs. Testing this boundary during calm periods is more informative than discovering it when a promise is already late.',
  'call-center-customer-promise-reconciliation-research-brief': 'Reconciliation should distinguish a checkpoint from a result. A worker may be authorized to promise that a review will be started or that an update will be sent by a time, while only a client owner can promise the eventual remedy. Record the dependency that separates those events and state what the customer will hear if it remains unresolved. Review language for false precision, especially when a source offers a range, estimate, or status without a confirmed completion event. Include corrected promises in the sample, because a timely correction can be evidence of a working control rather than a failure to hide. The manager can coach a bounded update, but should not replace the client’s policy decision with a smoother script. The strongest measure is not the number of confident commitments; it is the share that can be traced to an owner, source, checkpoint, and supported next action.'
};
const scopeNote = 'Any review should state the observation window, unit of analysis, missing fields, and owner of the next decision. Facts should remain separate from recommendations, and unknown outcomes should remain unknown rather than being treated as successful completion. The support role can preserve evidence and apply an approved route; it cannot create a client policy from a pattern in the sample. This boundary keeps the research useful for managers while avoiding unsupported claims about a particular team, result, location, or credential.';

// Release-gate repair notes. These are deliberately route-specific so the
// article body carries its own methodology and auditable external evidence,
// rather than relying only on the shared metadata list rendered at the end.
const repairNotes: Record<string, string> = {
  'call-center-knowledge-article-retirement-research-brief': 'The evidence register for this question should link the control frame directly: ISO 18295-1 (https://www.iso.org/standard/73338.html), NIST Cybersecurity Framework 2.0 (https://www.nist.gov/cyberframework), and the NIST Privacy Framework (https://www.nist.gov/privacy-framework). Methodologically, select a fixed window around each retirement, pair the article record with searches and sampled contacts, and code whether the old answer was visible, whether the replacement was attributable, and whether an exception owner was reachable. Treat a missing owner or effective date as an observed gap, not as evidence that the article was safely retired. A second reviewer should reconstruct the worker’s available answer without consulting later policy. This design separates a documented fact, such as a supersession record, from an inference about search ranking or training lag. It also prevents the review from confusing a tidy index with a safe customer-contact transition. The sample should include ordinary requests, unusual requests, and contacts that crossed a shift, because retirement defects often appear where the replacement has narrower scope. The cited standards guide governance and protection questions; they do not establish a universal retention period or prove that any particular library improved service.' ,
  'call-center-channel-switch-continuity-research-brief': 'For this study, the evidence register should connect ISO 18295-1 (https://www.iso.org/standard/73338.html), NIST Cybersecurity Framework 2.0 (https://www.nist.gov/cyberframework), and NIST Digital Identity Guidelines (https://pages.nist.gov/800-63-3/). Use a fixed observation window and select cases by switch reason before reviewing outcomes, so an outage, accessibility request, and customer preference are not blended into one average. Compare the transferred fields with the action the receiving role actually performed. Have an independent reviewer decide whether the receiving record contained enough approved evidence and whether any field should have been reverified for the new channel. Record repeat explanations, abandoned transfers, duplicate cases, and privacy corrections, including cases that closed successfully. A successful closure is a fact about an outcome; it is not proof that every copied field was necessary or that identity authority carried across channels. The method should preserve uncertainty when the linkage, timestamp, or owner is missing. These sources provide a control frame for process, access, and identity assurance, while client policy determines the permitted action and channel-specific verification.' ,
  'call-center-escalation-path-design-research-brief': 'The route study should cite ISO 18295-1 (https://www.iso.org/standard/73338.html), NIST Cybersecurity Framework 2.0 (https://www.nist.gov/cyberframework), and NIST incident-handling guidance (https://csrc.nist.gov/pubs/sp/800/61/r2/final) as distinct evidence sources. Start with a fixed-period inventory of escalation events and a separate tabletop sample. For every case, record the trigger, evidence attached, receiving role, authority available, acknowledgment event, customer update, fallback, return reason, and closure evidence. Ask a second reviewer to route the same scenarios using only the recorded map; disagreement is a finding about route clarity, not automatically a worker failure. Separate facts such as an unacknowledged handoff from analysis about capacity, severity, or stale ownership. Include a route whose named owner is unavailable and a case whose impact changes after intake. This makes the method sensitive to the conditions that turn an org chart into an unowned queue. The cited incident guidance is a preparedness and response reference, not a customer-service severity taxonomy, and none of the sources selects a client remedy, staffing ratio, or legal decision.' ,
  'call-center-absence-handoff-protocol-research-brief': 'The evidence set for absence continuity should link ISO 18295-1 (https://www.iso.org/standard/73338.html), NIST Cybersecurity Framework 2.0 (https://www.nist.gov/cyberframework), and the U.S. Department of Labor FLSA overview (https://www.dol.gov/agencies/whd/flsa). Study planned and unexpected absences separately within a defined observation window. Sample active cases at activation, then check acceptance, next action, customer update, closure, and access review after coverage ends. An independent reviewer should determine whether the replacement could act from the handoff without reading unrelated personal detail and whether the stated authority limit was respected. Count unaccepted cases and silent closures as continuity findings rather than successful transfers. Keep employment, leave, wage, and scheduling interpretation outside the service-record analysis; the Department of Labor page is background for covered U.S. workers, not a universal cross-border rule. Facts are timestamps, owners, permissions, and events. Analysis concerns whether the protocol preserved the customer obligation. This separation helps a manager repair queue ownership without turning one absence record into an unsupported judgment about a person.' ,
  'call-center-customer-promise-reconciliation-research-brief': 'The research register should identify ISO 18295-1 (https://www.iso.org/standard/73338.html), NIST Cybersecurity Framework 2.0 (https://www.nist.gov/cyberframework), and the FTC Mail, Internet, or Telephone Order Merchandise Rule (https://www.ecfr.gov/current/title-16/chapter-I/subchapter-D/part-435) as separate sources. Use a fixed cohort of promises and follow each from the original wording through its checkpoint, completion, change, failure, or unknown outcome. Sample ordinary promises as well as complaints and late cases. A second reviewer should compare the customer-facing statement with the source, authority, dependency, time zone, owner acknowledgment, and observed event. Code whether the record supports a checkpoint promise or only an estimate; do not turn a missing outcome into success. The FTC rule is a narrow legal example for covered merchandise orders, not a general service promise standard, so the client owner and qualified advisers retain jurisdictional interpretation. This method separates recorded facts from analysis about unsupported precision, and it lets managers address source quality or coaching without claiming that a lower promise count alone proves better service.'
};

const rawAugust20ResearchBatch: readonly ResearchPost[] = [
  {
    slug: 'call-center-knowledge-article-retirement-research-brief',
    title: 'Call Center Knowledge-Article Retirement: A Research Brief',
    excerpt: 'Retiring a knowledge article is a customer-contact control decision: the old answer must stop guiding work without erasing the evidence that explains the change.',
    published: '2026-08-20', sourceDate: '2026-08-20', image: '/research-aug20/knowledge-article-retirement.png', sources: common,
    sections: [
      { heading: 'The research question', body: 'When should an outsourced call-center team retire a knowledge article, and what evidence shows that the replacement is safe to use? The question is narrower than whether a library looks tidy. A stale answer can direct a worker toward an expired promise, an incorrect access step, or a workaround that no longer belongs to the queue. Yet deleting the page can remove the history needed to explain why an answer changed. This brief studies retirement as a controlled transition between source versions. It concerns customer support, appointment, order, and service-status work in which the frontline role needs an authoritative answer but cannot set policy. The conclusion is intended for managers and client owners deciding how to keep daily support reliable.' },
      { heading: 'Evidence and scope', body: 'ISO 18295-1 supplies a contact-centre lens: defined processes, capable people, customer outcomes, and review of results. NIST CSF 2.0 frames governance, asset knowledge, protection, detection, response, and recovery as accountable activities. The NIST Privacy Framework adds purpose and risk considerations when an article contains customer-data handling instructions. These sources describe control principles; they do not say how many articles a library should contain or establish a universal freshness interval. The research therefore treats an article as a source object with an owner, scope, effective date, permitted audience, linked workflow, and supersession relationship. It does not evaluate a particular vendor or claim that a shorter article is automatically safer.' },
      { heading: 'Methodology', body: 'A practical study begins with a fixed observation window and a sample of articles that were retired, amended, retained, or flagged by a worker. For each item, preserve the title, version, authorizing owner, effective date, customer reason, systems or channels affected, linked script, and replacement identifier. Then sample contacts that occurred before and after the change. Review whether the worker could see which version was current, whether the old answer was blocked or clearly marked, and whether an exception path existed when the new answer did not cover the customer’s situation. Have a second reviewer reproduce the decision from the records available at the time. Count unknown ownership and missing effective dates rather than silently excluding them.' },
      { heading: 'What the evidence can show', body: 'Facts include the recorded change request, the source version, the approval or owner, the dates, the article access trail where available, and the customer-contact outcome. Analysis begins when those facts are interpreted: repeated use of a superseded answer may indicate weak visibility, search ranking, training lag, or a missing transition message. The evidence cannot select among those explanations without testing them. A retirement record is stronger when it states why the old answer no longer applies, what replaces it, which queue is affected, and what a worker should do if the replacement is silent on an edge case. A hidden deletion makes the next reviewer reconstruct policy from memory.' },
      { heading: 'Route-specific evidence register', body: 'The external control frame is ISO 18295-1 at https://www.iso.org/standard/73338.html, NIST Cybersecurity Framework 2.0 at https://www.nist.gov/cyberframework, and the NIST Privacy Framework at https://www.nist.gov/privacy-framework. For this research question, select a fixed window around each retirement and pair the source record with sampled searches and customer contacts. Code whether the superseded answer was visible, whether the replacement was attributable, whether its scope covered the request, and whether an exception owner could be reached. A second reviewer should reconstruct the answer available at the time without consulting later policy. A recorded supersession, owner, and effective date are facts; an inference about search ranking, training lag, or transition risk must be labeled as analysis. Include ordinary requests, unusual requests, and contacts crossing a shift. These sources guide governance, process, and privacy questions, but they do not establish a universal retention period or prove that retirement improved service.' },
      { heading: 'Outsourced operating implications', body: 'In outsourced support, the frontline role should use the approved current source, identify a conflict, capture the customer’s request, and route policy uncertainty. It should not rewrite an article to make an interaction easier, preserve a convenient exception as if it were policy, or decide that a client-owned instruction is obsolete. The manager needs a visible change channel, a named reviewer, a release note in language the queue can use, and a fallback owner for the first contacts after publication. A client owner decides policy, effective date, retention, and exceptions. The article steward maintains source relationships and search labels. These boundaries keep content maintenance from becoming an unapproved policy function.' },
      { heading: 'Measures and scenario', body: 'Useful measures include the share of active articles with an owner and effective date, searches returning a superseded item, contacts that cite a retired answer, escalation reasons after a change, and time from approval to queue acknowledgment. Consider a service-status rule that changes after a client system migration. The old page is removed, but the search index still surfaces a cached excerpt and the new page omits the exception for delayed cases. Agents answer routine contacts correctly while exception contacts are transferred repeatedly. The issue is not solved by deleting more pages; the study should identify the stale discovery path and the missing exception owner. Measures should be segmented by queue and case class.' },
      { heading: 'Limitations', body: 'A contact sample can reveal a transition failure without estimating the performance of every queue. Search logs may not prove which article a worker read, a closed ticket may not prove that the customer received the intended answer, and a later correction can change the apparent outcome. The cited standards do not define a legally sufficient archive, a search-ranking rule, or a content-management product. Product policy, jurisdiction, language, accessibility, and retention requirements remain client decisions. If the sample contains only incidents, it will overrepresent visible failures; if it contains only successful closures, it will miss silent workarounds. Report the denominator, unavailable fields, and changed definitions with every comparison.' },
      { heading: 'Evidence-led conclusion', body: 'The research supports retiring a knowledge article only as part of an attributable handoff: identify the reason, effective version, replacement, affected support scope, and response when the new source does not answer the case. A visible supersession record is more useful than a clean library that conceals its history. For CallCenterOutsourced.com, the operational boundary is to follow the client-approved source, preserve a customer-impacting conflict, and escalate an unsupported answer. The evidence does not support a universal aging threshold or a claim that article deletion improves service by itself. Reliable knowledge work comes from controlled authority and observable transitions.' },
    ],
  },
  {
    slug: 'call-center-channel-switch-continuity-research-brief',
    title: 'Call Center Channel-Switch Continuity: A Research Brief',
    excerpt: 'Moving a customer from phone to chat, email, or a callback is safe only when the request, authority, promise, and next owner survive the channel change.',
    published: '2026-08-20', sourceDate: '2026-08-20', image: '/research-aug20/channel-switch-continuity.png', sources: [common[0], common[1], { name: 'NIST Digital Identity Guidelines', url: 'https://pages.nist.gov/800-63-3/' }],
    sections: [
      { heading: 'Question and decision boundary', body: 'What information must remain intact when a customer-contact case changes channel, and what must be verified again? A phone call that becomes chat, email, or a scheduled callback is not merely a formatting change. The new channel can alter identity assurance, disclosure risk, response timing, accessibility, and the role permitted to act. This brief examines continuity for outsourced inbound support and follow-up, with attention to the moment a case leaves the original interaction. It does not treat channel switching as a reason to copy the entire transcript everywhere. The decision boundary is practical: preserve enough approved context for the next owner to act safely, while minimizing unrelated or sensitive detail.' },
      { heading: 'Source frame', body: 'ISO 18295-1 connects customer-contact processes with people, resources, and results, which supports examining the case across its full path rather than scoring each channel alone. NIST CSF 2.0 supports governance, access control, protection, and response ownership. NIST Digital Identity Guidelines distinguish identity assurance from a familiar contact detail, so a successful switch does not automatically carry the same authority into a new channel. None of these sources prescribes one transcript format, identity factor, or service-level target. The study uses them as a control frame and keeps client policy, channel rules, and jurisdiction-specific requirements with the responsible owner.' },
      { heading: 'Study design', body: 'Select a defined cohort of cases that switched channel and a comparison group that stayed in one channel. For each case, record the original request, source channel, identity state, permitted action, information transferred, receiving channel, time stamps, promise, receiving acknowledgment, outcome, and correction. Code the switch reason: customer preference, accessibility, system outage, queue overflow, sensitive action, or agent request. Ask an independent reviewer to reconstruct the next safe action using only the handoff record. Include abandoned switches and cases where the customer repeated the story; those are evidence of continuity cost. Do not use a successful closure as proof that every transferred field was necessary or authorized.' },
      { heading: 'Interpretation', body: 'Facts are the fields that were recorded and the actions that occurred. Analysis asks whether the handoff preserved meaning and whether the next role could distinguish a customer statement from a verified fact, a proposed remedy from an approved one, and a promise from an estimate. A copied transcript may retain detail but hide the current owner or expose information unnecessary to the new channel. A short handoff may be safer but insufficient if it omits the exact request or customer-impact deadline. The useful unit is therefore a bounded case summary linked to source evidence, not a universal minimum number of words. Unknown identity, missing timestamps, and unresolved scope should remain visible.' },
      { heading: 'Route-specific methodology and evidence', body: 'Use ISO 18295-1 at https://www.iso.org/standard/73338.html, NIST Cybersecurity Framework 2.0 at https://www.nist.gov/cyberframework, and NIST Digital Identity Guidelines at https://pages.nist.gov/800-63-3/ as distinct sources. Draw a fixed observation window, stratify switched cases by reason such as outage, accessibility request, or customer preference, and compare them with cases that stayed in one channel. Record the request, identity state, transferred fields, receiving action, acknowledgment, promise, correction, and outcome. Have an independent reviewer decide whether the next action was supported and whether the receiving channel required re-verification. Repeat explanations, abandoned transfers, duplicate cases, and privacy corrections belong in the sample, including cases that closed successfully. Those observations are facts; whether a missing field reflects a form defect, policy requirement, tool limitation, or worker choice is analysis. The sources provide a control frame, while the client sets permitted actions and channel-specific verification.' },
      { heading: 'Scenario in an outsourced queue', body: 'A caller reports a failed delivery and asks for a status update. The phone agent cannot access a carrier system, so the case moves to email. The email contains the customer’s full history but not which address was verified, what the agent promised, or who owns the carrier lookup. The receiving worker asks for information already supplied, while a sensitive attachment remains in a broad inbox. A better handoff would state the request, permitted next action, approved evidence reference, customer’s preferred response channel, time window, and receiving owner. The client decides remedy and disclosure policy; the support role records and routes rather than improvising a replacement promise.' },
      { heading: 'Measures', body: 'Measure repeat-story requests, switch abandonment, time to acknowledgment, missing-owner rate, unauthorized disclosure findings, duplicate cases, promise misses, and corrections after a channel change. Separate routine informational contacts from identity, payment, complaint, safety, and policy cases because their continuity requirements differ. Compare outcomes by switch reason and receiving team; aggregate averages can make an outage-driven transfer look like ordinary customer preference. A low repeat-contact rate can also be misleading if cases disappear into an unmonitored channel. Preserve the original and receiving timestamps, define the denominator before sampling, and label changes in channel tooling or routing rules.' },
      { heading: 'Limitations and conclusion', body: 'A retrospective sample cannot prove that the channel switch caused a repeat contact, and delivery logs cannot prove that a message was read. Identity requirements depend on the action, account type, jurisdiction, and client policy. The evidence-led conclusion is that continuity is a relationship among request, authority, promise, source, channel, and next owner. An outsourced team should transfer the minimum approved context that allows the next safe decision, recheck what the new channel requires, and make uncertainty routable. Channel count is not a service-quality measure by itself; traceable ownership is the more defensible signal.' },
    ],
  },
  {
    slug: 'call-center-escalation-path-design-research-brief',
    title: 'Call Center Escalation-Path Design: A Research Brief',
    excerpt: 'An escalation path is a decision system, not a list of names: it must show authority, evidence, acknowledgment, fallback, and customer impact.',
    published: '2026-08-20', sourceDate: '2026-08-20', image: '/research-aug20/escalation-path-design.png', sources: [common[0], common[1], { name: 'NIST Computer Security Incident Handling Guide', url: 'https://csrc.nist.gov/pubs/sp/800/61/r2/final' }],
    sections: [
      { heading: 'Research question', body: 'How can a customer-contact operation tell whether an escalation path is usable before a high-impact case is waiting inside it? Many teams possess an org chart and still cannot answer who may decide, who must acknowledge, or what happens when the named owner is unavailable. This research focuses on outsourced call-center queues handling exceptions, complaints, account concerns, service interruptions, and promises that exceed frontline authority. It studies the path as a chain from intake to decision and customer update. It does not prescribe a staffing ratio, a severity scale, or a client’s remedy policy. Those are decisions for the business owner.' },
      { heading: 'Evidence frame', body: 'ISO 18295-1 supports explicit contact processes, workforce responsibilities, and review of customer results. NIST CSF 2.0 frames governance and response as owned activities rather than informal heroics. NIST incident-handling guidance adds preparation, detection, analysis, containment, recovery, and lessons learned for incidents, while not turning every complaint into a security incident. Taken together, the sources support asking whether a route has scope, evidence, authority, timing, acknowledgment, and recovery. They do not establish the correct path for every company. Legal interpretation, credits, refunds, account changes, and safety decisions remain with authorized client owners.' },
      { heading: 'Method', body: 'Map one queue’s escalation routes using records from a fixed period. For each route, capture trigger, required evidence, receiving role, allowed decision, acknowledgment expectation, customer promise, backup, return condition, and closure evidence. Then test the map with tabletop cases that include a routine exception, a missing source, a conflicted instruction, an absent owner, and a case whose severity changes after intake. Review actual escalations separately from drills. Have a second reviewer attempt to route each case without relying on personal knowledge. Record where the map is ambiguous, where access blocks the receiving role, and where the fallback is only a phone number with no durable record.' },
      { heading: 'Findings to separate', body: 'A route can fail because the frontline worker lacked evidence, the receiving owner lacked authority, the queue used the wrong severity, the acknowledgment clock was undefined, or the case returned without a reason. These are different facts and should not collapse into “agent escalation error.” Analysis may suggest a form field, a routing rule, a backup owner, or a narrower service scope, but the remedy should follow the observed mechanism. A route that accepts every case may look responsive while creating an unowned downstream backlog. A route that rejects almost every case may protect capacity while hiding customer harm. Both need outcome evidence, not just transfer counts.' },
      { heading: 'Route-specific methodology and evidence', body: 'The study uses ISO 18295-1 at https://www.iso.org/standard/73338.html, NIST Cybersecurity Framework 2.0 at https://www.nist.gov/cyberframework, and NIST incident-handling guidance at https://csrc.nist.gov/pubs/sp/800/61/r2/final. Start with a fixed-period inventory of live escalations and a separate tabletop sample. For each case record the trigger, evidence attached, receiving role, authority available, acknowledgment, customer update, fallback, return reason, and closure evidence. Ask a second reviewer to route the same scenarios using only the map that existed at that time. Include an unavailable owner and a case whose impact changes after intake. An unacknowledged handoff is a fact; conclusions about capacity, severity, or stale ownership are analysis and should be tested against the record. Incident guidance informs preparedness and response, not a universal customer-service severity taxonomy, staffing ratio, or client remedy.' },
      { heading: 'Operating roles', body: 'The frontline role identifies the request, uses approved evidence, states only the promise it is authorized to make, and sends a complete bounded handoff. A supervisor owns immediate triage, coaching against an approved rule, and backup notification. The client owner decides policy, remedy, scope, and exceptions that require business authority. A service coordinator maintains the route map and effective dates but cannot silently change decision rights. This division matters for CallCenterOutsourced.com: outsourced support can make the path observable and reliable without pretending to own the customer policy behind it.' },
      { heading: 'Scenario and measures', body: 'Suppose a customer disputes a charge and also reports that a promised service window was missed. The frontline worker sends the case to a billing route that has authority over the charge but no owner for the missed promise. The customer receives two partial updates and repeats the story. Research should measure acknowledgment by route, return reasons, handoff completeness, customer-update misses, time to decision, and cases with no backup. Segment by impact and dependency. Do not reward a low transfer rate if unresolved exceptions remain in the original queue. Preserve the route version used at the time so later map changes do not rewrite history.' },
      { heading: 'Limits and conclusion', body: 'Tabletop success does not prove live availability, and a short observation window can miss leave periods, outages, or seasonal demand. Incident guidance is not a customer-service severity taxonomy, and ISO does not provide an escalation matrix. The evidence-led conclusion is that a path is dependable when a worker can identify the trigger, attach sufficient evidence, reach an authorized owner, receive acknowledgment, and activate a fallback without losing the customer promise. Escalation design should make authority visible and uncertainty actionable; it should not turn transfer volume into a performance claim.' },
    ],
  },
  {
    slug: 'call-center-absence-handoff-protocol-research-brief',
    title: 'Call Center Absence Handoff Protocols: A Research Brief',
    excerpt: 'An absence handoff protects customer continuity when it transfers active work, decision rights, and promises without exposing more personal information than the next role needs.',
    published: '2026-08-20', sourceDate: '2026-08-20', image: '/research-aug20/absence-handoff-protocol.png', sources: [common[0], common[1], { name: 'U.S. Department of Labor FLSA Overview', url: 'https://www.dol.gov/agencies/whd/flsa' }],
    sections: [
      { heading: 'The question', body: 'What should move when a support worker is absent so active customer work remains safe, attributable, and within scope? Absence planning is often reduced to a rota, but customer-impact work contains promises, pending decisions, restricted data, and dependencies that do not pause when a person is unavailable. This brief examines handoffs for outsourced customer-contact teams serving inbound queues and back-office follow-up. It separates continuity evidence from employment administration: a coverage record can show who accepted work, while labor, scheduling, and payroll decisions belong to the responsible employer and client owners. The goal is a testable protocol, not a universal attendance rule.' },
      { heading: 'Research basis', body: 'ISO 18295-1 emphasizes the relationship among people, processes, resources, and customer results. NIST CSF 2.0 supports governance, access control, and recovery ownership when normal operations change. The U.S. Department of Labor’s FLSA overview is relevant only as U.S. federal wage-and-hour background for covered workers; it does not answer cross-border employment or client scheduling questions. These sources support naming responsibilities and protecting information during a change, but they do not establish how much notice, overtime, or leave an organization must provide. The research keeps those questions with management, HR, counsel, and the applicable jurisdiction.' },
      { heading: 'Protocol under study', body: 'Sample active cases at the moment of a planned or unplanned absence. Record current status, customer request, promise and time zone, authorized next action, sensitive-data boundary, dependency, last owner, receiving owner, acknowledgment, and closure evidence. Compare cases handed off through a defined protocol with cases left in a shared queue. Review whether the replacement worker had access that matched the role, whether the original worker’s private details were omitted, and whether the client owner knew about decisions waiting on them. Include work that was closed without a handoff; silent closure can be a continuity failure rather than a success.' },
      { heading: 'Evidence interpretation', body: 'The fact is that a case had a status, owner, and event at a particular time. The analysis asks whether the receiving role could continue safely and whether any promise became misleading when the original worker left. A long note may contain unnecessary personal information while still omitting the exact next decision. A short structured record can be more useful if it preserves the request, source, authority limit, deadline, and fallback. Reassigning a case is not the same as accepting responsibility. A receiving acknowledgment should be attributable and time-stamped, and an unaccepted case should trigger the manager’s backup path.' },
      { heading: 'Route-specific methodology and evidence', body: 'The evidence set includes ISO 18295-1 at https://www.iso.org/standard/73338.html, NIST Cybersecurity Framework 2.0 at https://www.nist.gov/cyberframework, and the U.S. Department of Labor FLSA overview at https://www.dol.gov/agencies/whd/flsa. Study planned and unexpected absences separately within a defined observation window. Sample active cases at activation, then check acceptance, next action, customer update, closure, and access review after coverage ends. An independent reviewer should determine whether the replacement could act from the handoff without reading unrelated personal detail and whether the authority limit was respected. Count unaccepted cases and silent closures as continuity findings. Timestamps, owners, permissions, and events are facts; whether the protocol preserved the customer obligation is analysis. The Labor Department source is background for covered U.S. workers, not a universal cross-border employment rule, and management, HR, counsel, and client owners retain jurisdiction over those questions.' },
      { heading: 'Scenario', body: 'A worker is unexpectedly absent while three cases wait for client approval. The shared inbox shows the subject lines but not the customer’s local time, the promised update, or whether identity was already verified. A replacement reads the full thread, exports unrelated details, and sends an update that sounds like approval. The failure combines missing handoff fields, overbroad access, and an authority boundary. A sound protocol would identify only the cases needing attention, link approved evidence, state what may be said, name the decision owner, and require a neutral customer update if approval remains pending. The client owner still decides the underlying request.' },
      { heading: 'Measures and boundaries', body: 'Measure active cases without an owner, time to receiving acknowledgment, promises missed during absence, duplicate work, sensitive-field exposure, unauthorized actions, and cases returned because the scope was unclear. Compare planned and unplanned absences, ordinary and high-impact work, and primary with backup handoffs. Do not use these measures to infer an individual’s character or employment performance from one event. The frontline role may prepare an approved handoff and update status; a manager assigns coverage and handles performance or scheduling decisions; a client owner handles policy and remedy. Access should be provisioned for the replacement role and removed or reviewed when the coverage period ends.' },
      { heading: 'Limitations and conclusion', body: 'Handoff outcomes depend on queue design, tools, client policy, and the reason for absence. A retrospective record can show missing ownership without proving why it was missing. Labor obligations vary by employer, location, contract, and jurisdiction, and the cited sources do not replace advice from the responsible specialists. The evidence-led conclusion is that absence continuity is a control of active customer work: transfer the minimum necessary context, require acceptance, preserve the promise and authority limit, and provide a named fallback. Coverage is credible when the work remains owned, not merely when a schedule contains a replacement name.' },
    ],
  },
  {
    slug: 'call-center-customer-promise-reconciliation-research-brief',
    title: 'Call Center Customer-Promise Reconciliation: A Research Brief',
    excerpt: 'A customer promise should be reconciled against source facts, authority, dependency, and the next checkpoint before it becomes an avoidable escalation.',
    published: '2026-08-20', sourceDate: '2026-08-20', image: '/research-aug20/customer-promise-reconciliation.png', sources: [common[0], common[1], { name: 'FTC Mail, Internet, or Telephone Order Merchandise Rule', url: 'https://www.ecfr.gov/current/title-16/chapter-I/subchapter-D/part-435' }],
    sections: [
      { heading: 'Research question', body: 'How can an outsourced call-center team distinguish a supported customer promise from a hopeful statement that depends on an owner or event not yet confirmed? Promises appear in callbacks, delivery updates, appointment changes, complaint follow-up, and service recovery. The operational risk is not only that a time is missed; it is that the record cannot explain what was promised, by whom, from which source, and what should happen when a dependency changes. This brief studies reconciliation between the customer-facing statement and the evidence behind it. It does not create a universal service level, sales claim, refund rule, or legal conclusion.' },
      { heading: 'Evidence scope', body: 'ISO 18295-1 provides a customer-contact frame for process clarity, workforce responsibility, and results. NIST CSF 2.0 supports governance, communication, and response ownership. The FTC merchandise rule is a narrow example of why some order promises can carry specific obligations; it is not a general rule for every service, country, or queue. The evidence set therefore distinguishes external requirements from operating inference. A promise record should identify request, customer impact, source state, authority, dependency, time zone, checkpoint, and fallback. The client owner determines the policy and applicable legal interpretation.' },
      { heading: 'Methodology', body: 'Use one defined cohort of customer promises and follow each from utterance or message through the promised event, update, completion, change, or failure. Capture the exact promise in approved notes without inventing precision that was not stated. Link the source used, the role making the statement, the receiving owner, dependency status, customer’s local time, and later correction. Classify outcomes as completed within the supported window, completed late, changed with notice, unowned, impossible from available authority, or unknown. Have a second reviewer decide whether the evidence supports the recorded classification. Keep customer complaints and ordinary completed promises in the sample so the denominator does not consist only of visible failures.' },
      { heading: 'Reconciliation logic', body: 'Facts include the source status, timestamp, owner acknowledgment, customer-facing wording, and observed outcome. Analysis asks whether the statement exceeded the source, whether the dependency was visible, or whether a later change was communicated before the customer relied on it. A promise such as “we will update you after review” has a different evidence requirement from “the order will arrive tomorrow.” The first needs a review owner and checkpoint; the second needs a supported operational source and a contingency path. A high completion percentage can conceal unsupported promises if the sample excludes cases changed before the deadline. Report unknowns rather than converting them to success.' },
      { heading: 'Route-specific methodology and evidence', body: 'The research register uses ISO 18295-1 at https://www.iso.org/standard/73338.html, NIST Cybersecurity Framework 2.0 at https://www.nist.gov/cyberframework, and the FTC Mail, Internet, or Telephone Order Merchandise Rule at https://www.ecfr.gov/current/title-16/chapter-I/subchapter-D/part-435 as separate sources. Follow a fixed cohort from the original promise through its checkpoint, completion, change, failure, or unknown outcome. Sample ordinary promises, complaints, and late cases. A second reviewer compares the wording with source, authority, dependency, time zone, owner acknowledgment, and observed event. Code whether the record supports a checkpoint promise or only an estimate; never turn a missing outcome into success. The FTC rule is a narrow legal example for covered merchandise orders, not a general service standard. Facts remain distinct from analysis about unsupported precision, and the client owner and qualified advisers retain jurisdictional interpretation.' },
      { heading: 'Operational roles', body: 'A support worker may repeat an approved status, record the customer’s requested outcome, state a supported next checkpoint, and route a dependency. It should not guarantee a client decision, invent a carrier or appointment time, promise a credit, or turn an estimate into a commitment. The manager owns coaching against approved language and reviews recurring promise failures. The client owner decides remedy, policy, exception, and what evidence qualifies for a commitment. This boundary is central to outsourced support: dependable service is not created by making more confident statements; it is created by making supported statements and preserving the next owner.' },
      { heading: 'Scenario and measures', body: 'A customer asks whether a delayed order will arrive before an event. The worker sees a carrier status but no confirmed delivery date and promises “tomorrow” to reduce uncertainty. The order later arrives after the event, and the client must handle a remedy. Reconciliation would identify the missing source, unsupported precision, and absent fallback before measuring the outcome. Useful measures include promises by type, source-supported rate, owner acknowledgment, change-notified rate, missed checkpoint, repeat contact, complaint impact, and unknown outcome. Segment by queue and dependency; do not compare a callback checkpoint with a delivery commitment as if they were identical.' },
      { heading: 'Limitations and conclusion', body: 'Public guidance does not define one wording standard, promise window, or remedy. Customer impact can be difficult to observe when the person does not contact the business again, and a source status can change after the promise without proving that the original statement was unreasonable. The evidence-led conclusion is that promise reliability depends on reconciliation: connect the words to a source, authority, dependency, owner, time zone, checkpoint, and fallback. CallCenterOutsourced.com’s role is to make those relationships visible and escalate uncertainty. A calm, bounded update is stronger evidence of dependable support than a confident but unsupported commitment.' },
    ],
  },
];

export const august20ResearchBatch: readonly ResearchPost[] = rawAugust20ResearchBatch.map(post => ({
  ...post,
  sections: post.sections.map((section, index) => index === 0 ? { ...section, body: `${section.body} ${depth[post.slug]} ${scopeNote} ${repairNotes[post.slug]}` } : section),
}));
