import type {ResearchPost} from './fleet-data';

const sources=[
 {name:'ISO 18295-1 Customer contact centres',url:'https://www.iso.org/standard/64739.html'},
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
 {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
 {name:'NIST Digital Identity Guidelines, SP 800-63B',url:'https://pages.nist.gov/800-63-3/sp800-63b.html'},
] as const;

type Study={slug:string;title:string;excerpt:string;image:string;question:string;method:string;limits:string;use:string};
const studies:readonly Study[]=[
 {slug:'call-center-voicemail-live-contact-duplication-study',title:'Voicemail and Live-Contact Duplication in Call Centers',excerpt:'A linked-record study can show when one customer need becomes competing tasks, owners, and promises.',image:'/research-aug21/case-linkage-evidence.png',question:'This study examines whether a voicemail followed by a live contact creates duplicate work for the same customer need.',method:'Select all voicemails in a fixed period and look for a live contact within a declared matching window. Link only on approved fields, then compare task creation, ownership, promises, disposition, and status at cutoff.',limits:'Shared contact details can create false matches, while different channels may contain separate requests. A duplicate-looking record does not prove that either worker acted incorrectly.',use:'Managers can refine search steps, matching rules, and ownership transfer. The results do not establish a universal matching window or identity rule.'},
 {slug:'outsourced-call-center-time-zone-promise-integrity-study',title:'Time-Zone Integrity in Outsourced Call Center Promises',excerpt:'Callback performance is interpretable only when the promised window and actual attempt use the same customer-facing clock.',image:'/research-aug21/callback-timezone-integrity.png',question:'The review asks whether callback and follow-up promises preserve the customer time zone from contact through completion.',method:'Sample promises made during a defined period. Record the stated local window, stored zone or offset, UTC conversion, daylight-saving condition, owner, attempt time, and customer-facing outcome.',limits:'Location does not reliably establish time zone, and daylight-saving rules change. A timely attempt does not prove that the customer could answer or that the underlying need was resolved.',use:'Findings can support required fields, confirmation wording, conversion tests, and exception handling. They cannot define lawful contact hours for every jurisdiction.'},
 {slug:'call-center-customer-attachment-routing-risk-review',title:'Customer Attachment Routing Risk in Support Queues',excerpt:'A bounded review can identify where customer files travel beyond the people and systems needed for the stated service purpose.',image:'/research-aug20/channel-switch-continuity.png',question:'This review studies receipt, access, copying, and routing of unexpected customer attachments in ordinary support records.',method:'Create a cohort of tickets with attachments. Inventory file type, stated purpose, scan or quarantine event, access group, downloads, copied content, routing decisions, retention state, and owner at cutoff.',limits:'System logs may omit screenshots, local copies, or access through integrations. File names do not establish contents, sensitivity, or malicious intent, and the review is not a forensic examination.',use:'Managers can narrow access, create quarantine paths, and improve resubmission guidance. Security, privacy, and legal owners must decide specific handling requirements.'},
 {slug:'outsourced-call-center-specialist-availability-continuity-analysis',title:'Specialist Availability and Customer-Promise Continuity',excerpt:'The useful measure is not simply specialist presence; it is whether boundary cases retain an owner and a truthful update path during absence.',image:'/research-aug20/absence-handoff-protocol.png',question:'The analysis asks what happens when frontline work reaches a decision boundary and the primary specialist is unavailable.',method:'Select boundary cases across a fixed schedule. Link the escalation time, primary and backup coverage, acknowledgment, interim action, promised update, decision, customer contact, and open status at cutoff.',limits:'Case severity and decision complexity vary, while informal advice may not appear in system records. Association between absence and delay does not establish causation.',use:'Leaders can map backup roles, escalation clocks, and pause rules. The analysis does not prescribe staffing ratios or transfer specialist authority.'},
 {slug:'call-center-survey-opt-out-propagation-research',title:'Survey Opt-Out Propagation Across Contact Channels',excerpt:'A cross-system cohort can test whether a customer survey choice survives channel switches without being mistaken for a broader contact preference.',image:'/research-aug21/consent-provenance.png',question:'The study examines whether survey opt-outs are recorded with enough scope and provenance to suppress covered invitations across channels.',method:'Sample opt-outs captured in voice, chat, and email. Trace the source event, stated scope, identifier, effective time, synchronization, later survey invitations, corrections, expiry, and final system state.',limits:'Preference systems may update on different schedules, and one household may share contact details. A survey opt-out does not necessarily apply to service messages, research, or marketing.',use:'Results can support field definitions, synchronization monitoring, and correction paths. Policy and privacy owners retain decisions about scope, retention, and jurisdiction.'},
] as const;

const make=(s:Study):ResearchPost=>({slug:s.slug,title:s.title,excerpt:s.excerpt,published:'2026-09-08',sourceDate:'2026-09-08',image:s.image,sources,keyStats:['1 fixed observation period','2 or more linked system events','1 accountable owner at cutoff'],takeaways:['Define the cohort before review.','Preserve unresolved work at cutoff.','Separate evidence from management inference.'],sections:[
 {heading:'Research question and scope',body:s.question+' The unit of analysis is one customer need traced only through approved operational records.'},
 {heading:'Source basis and methodology',body:'ISO 18295-1 provides customer-contact process context. NIST CSF 2.0 supports governance and ownership, while the NIST Privacy Framework and Digital Identity Guidelines inform purpose, minimization, and identity boundaries. '+s.method},
 {heading:'Findings and inference boundary',body:'Report observed counts and elapsed times with cohort definitions, exclusions, missing-data rules, and open cases. Patterns can identify where to investigate; they do not prove cause, intent, or worker performance.'},
 {heading:'Limitations',body:s.limits+' This is a bounded operational review, not legal advice, a causal experiment, or a universal industry benchmark.'},
 {heading:'Operating use',body:s.use+' Publish the review period, evidence sources, definitions, exclusions, and unresolved records beside any result.'},
],faqs:[{question:'Does this method set a universal benchmark?',answer:'No. Results are comparable only after the cohort, definitions, period, and exclusions are fixed.'},{question:'Can this review prove why a failure occurred?',answer:'No. It can locate evidence gaps and patterns for an authorized owner to investigate.'}],internalLinks:['/research','/services/operations-support'],serviceHandoff:{href:'/contact-us',label:'Plan a bounded evidence review',body:'Choose one queue, define the cohort and cutoff, and name the decision owner before sampling.'}});

export const september8ResearchBatch:readonly ResearchPost[]=studies.map(make);
