import type {ResearchPost} from './fleet-data';

const checked='2026-09-24';
const iso={name:'ISO 18295-1:2017, Customer contact centres',url:'https://www.iso.org/standard/64739.html'};
const nistCsf={name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'};
const nistPrivacy={name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'};
const nistIdentity={name:'NIST SP 800-63-4, Digital Identity Guidelines',url:'https://pages.nist.gov/800-63-4/'};
const nistZero={name:'NIST SP 800-207, Zero Trust Architecture',url:'https://csrc.nist.gov/pubs/sp/800/207/final'};
const ftcOrder={name:'eCFR, 16 CFR Part 435, Mail, Internet, or Telephone Order Merchandise',url:'https://www.ecfr.gov/current/title-16/chapter-I/subchapter-D/part-435'};
const cfpbDebt={name:'CFPB, Debt Collection Practices (Regulation F)',url:'https://www.consumerfinance.gov/rules-policy/final-rules/debt-collection-practices-regulation-f/'};
const ftcTsr={name:'FTC, Complying with the Telemarketing Sales Rule',url:'https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule'};

type Draft={slug:string;title:string;excerpt:string;image:string;sources:ResearchPost['sources'];links:string[];sections:ResearchPost['sections']};

const publish=(draft:Draft):ResearchPost=>({...draft,published:checked,sourceDate:checked,
  internalLinks:['/research',...draft.links],
  keyStats:['One defined operating cohort','One accountable exception owner','Facts, inferences, and unknowns reported separately'],
  takeaways:['Define the decision before assigning the queue.','Treat conflicting or missing records as findings.','Expand only after representative review.'],
  faqs:[
    {question:'Does this brief make a legal, security, or compliance determination?',answer:'No. It is an operational research method. Authorized legal, privacy, security, employment, commercial, and policy owners must apply requirements to the actual service, data, contract, and jurisdiction.'},
    {question:'Does the research prescribe one universal target?',answer:'No. Thresholds depend on the customer journey, risk, evidence quality, channel, authority boundary, and client decision owner.'}
  ],
  serviceHandoff:{href:'/contact-us',label:'Map a controlled support lane',body:'Choose one queue, document permitted actions and exceptions, and test the handoff before adding volume.'},
  sections:[...draft.sections,
    {heading:'Research method and evidence discipline',body:'Define the decision, observation period, eligible population, operational unit, field dictionary, time-zone convention, exclusions, and reviewer instructions before extracting records. The unit may be a contact, case, order line, appointment slot, score appeal, or reminder attempt, but it should not change midway through analysis. Preserve ordinary, adverse, open, transferred, abandoned, corrected, duplicated, and unknown outcomes unless a documented rule excludes them. Use a census for a small population; otherwise stratify a sample across channels, shifts, contact reasons, risk classes, experience levels, and outcomes. A second reviewer should independently inspect a risk-weighted subset and record disagreements rather than forcing silent consensus. Separate the customer statement, source-system event, worker action, reviewer classification, and management inference. A timestamp shows that a system recorded an event; it does not by itself prove customer understanding, downstream acceptance, or causation. Report missing fields and conflicting systems as findings. Compare periods only when scope and definitions remain materially stable. If a correction is required, preserve the first issued result and document what changed.'},
    {heading:'Measures and management decision',body:'Publish counts before percentages and pair an average or median with the oldest, slowest, highest-impact, and unknown cases. Useful fields include demand offered, handled, unresolved, transferred, reopened, corrected, awaiting client decision, lacking an owner, and outside approved scope. Measure the elapsed time between receipt, acknowledgment, next action, decision, customer update, and closure where those events exist. Do not reward speed when the action exceeded authority, weakened verification, concealed uncertainty, or created another promise. Predefine critical events that receive individual review regardless of the aggregate result. The decision owner should record a bounded outcome: continue as designed, revise a named control, narrow or pause the lane, or expand after specified evidence. Each corrective action needs an owner, due date, expected mechanism, possible adverse effect, rollback or pause condition, and review date. The result is evidence for a service decision, not a universal vendor score or a ranking of individual workers.'},
    {heading:'Implementation and review cadence',body:'Translate the research decision into a short operating brief before assigning live work. Identify the customer purpose, included and excluded requests, approved systems, allowed fields, permitted actions, prohibited actions, verification or evidence prerequisite, customer-facing wording source, escalation trigger, receiving owner, acknowledgment target, fallback owner, quality sample, and pause authority. Practice an ordinary case and a boundary case. Confirm that the receiver can see and act on the handoff without asking frontline support to make the reserved decision. During a pilot, review early cases frequently enough to catch a design defect before it becomes routine; the appropriate cadence depends on volume and severity, not a fixed universal schedule. Keep training completion separate from demonstrated readiness. After launch, inspect exceptions, repeat contacts, missing acknowledgments, records altered outside the normal path, customer complaints, and access changes. A favorable average should not erase a severe event, while one unusual event should not be presented as proof of widespread failure without population evidence. Record the effective time of each control change and compare the next cohort under the revised design.'},
    {heading:'Limitations and bounded conclusion',body:'The cited standards and public guidance describe governance, identity, privacy, security, customer-contact, commerce, or debt-collection considerations at a general level. They do not establish the correct script, staffing ratio, response time, legal basis, remedy, calendar rule, shipment status, payment status, or access decision for a particular company. Repository and system records can omit informal work, unrecorded customer effort, accessibility barriers, and actions in downstream tools. A short study can miss seasonality and rare severe events; a long study can combine periods whose routing, people, tools, scripts, permissions, or policies changed. Correlation between an operating condition and an outcome does not prove cause. The method therefore supports a narrow conclusion about whether the chosen workflow produced reviewable evidence and kept exceptions with an authorized owner during the observed period. It cannot certify a provider, predict every customer outcome, or replace legal, privacy, security, employment, commercial, or policy judgment. Retest after a material change and keep residual uncertainty visible.'},
    {heading:'Replication record and source notes',body:'Retain the research question, scope, field dictionary, inclusion and exclusion rules, source titles, publishers, URLs, September 24, 2026 check date, extraction version, minimized case references, reviewer instructions, calculations, disagreement log, missing data, competing explanations, decision, and follow-up date. Record source access dates separately from the publication dates of source documents. Link each source to the claim it supports and label operational recommendations as analysis or inference when they are not quoted requirements. Preserve effective times for changes to staffing, tools, routing, scripts, permissions, knowledge, client policy, and service objectives. Another reviewer should be able to recreate the eligible cohort and understand why a case was classified without receiving unnecessary customer content. When guidance changes, preserve the prior study and issue a truthful modification record rather than backdating the original. This creates a durable trail while keeping customer data and final business decisions in their authorized systems.'}
  ]
});

export const september24Cala101ResearchBatch:readonly ResearchPost[]=[
  publish({slug:'tier-one-support-outage-triage-evidence-research',title:'Outage-Triage Evidence in Tier-One Technical Support',excerpt:'An outsourced support lane should distinguish an individual fault from a wider service event without guessing at cause or exposing infrastructure details.',image:'/research-aug21/case-linkage-evidence.png',sources:[nistCsf,nistZero,nistPrivacy,iso],links:['/services/tier-one-technical-support','/research/tier-one-technical-support-remote-action-authority-research'],sections:[
    {heading:'Decision question and service boundary',body:'How should a tier-one outsourced support queue recognize evidence that several customer reports may belong to one service event, while keeping diagnosis and incident declarations with the authorized technical owner? The unit is one contact linked to the affected product or service, customer-observed symptom, start time as reported, channel, supported environment, approved diagnostic result, known-status source, case link, impact statement, escalation event, and next owner. The queue may collect approved facts, check a client-maintained status source, perform bounded troubleshooting, and route a suspected pattern. It should not announce a root cause, disclose another customer’s report, change production systems, or convert similarity into certainty. Incident classification, external status messages, restoration estimates, and security decisions remain with the client’s technical and incident owners.'},
    {heading:'Primary-source basis and interpretation',body:'NIST Cybersecurity Framework 2.0 organizes cybersecurity risk work around govern, identify, protect, detect, respond, and recover outcomes; that structure supports named roles, observable events, response communication, and learning. NIST Zero Trust Architecture focuses authorization on users, assets, and resources instead of granting implicit trust from network location. The NIST Privacy Framework supports processing personal data for a defined purpose and managing privacy risk. ISO 18295-1 supplies customer-contact process context. Together these sources support controlled observation, explicit authority, protected diagnostic evidence, and accountable escalation. They do not tell a support agent that similar symptoms share one cause, establish an incident-severity level, authorize a public outage statement, or select a restoration commitment. Those steps require client-owned technical evidence and decision rights.'},
    {heading:'Pattern test and failure modes',body:'Create test cases for one misconfigured device, two unrelated customers with similar wording, a confirmed status-page event, a region-specific problem, an identity failure, a suspected security event, and a known maintenance window. Compare the customer report, approved telemetry, case-link evidence, status source, action taken, and escalation acknowledgment. Count candidate patterns separately from client-confirmed events. Common failures include declaring an outage from message volume alone, repeatedly troubleshooting when a confirmed event already explains the symptom, linking cases that expose unrelated customer data, sharing an internal incident label as a customer fact, promising restoration from an engineering estimate, and closing child cases before the customer impact is addressed. The safe tier-one result may be a well-formed suspected-event handoff and a truthful next-update promise, not a diagnosis.'}
  ]}),
  publish({slug:'order-support-split-shipment-status-reconciliation-research',title:'Split-Shipment Status Reconciliation in Outsourced Order Support',excerpt:'A multi-package order needs line-level evidence so one delivered parcel does not turn the remaining items into a false completion or refund promise.',image:'/research-aug20/customer-promise-reconciliation.png',sources:[ftcOrder,nistPrivacy,nistCsf,iso],links:['/services/order-management-support','/research/order-support-delivery-address-change-evidence-research'],sections:[
    {heading:'Decision question and order boundary',body:'What evidence should an outsourced order-support representative use when one order is divided across packages, warehouses, carriers, fulfillment states, or delivery dates? The unit is one order line or package linked to the customer-visible order, item and quantity, fulfillment source, carrier acceptance if present, latest authoritative event, promised or estimated window, cancellation or refund eligibility as supplied by policy, customer statement, next action, and exception owner. The provider may explain confirmed line-level events and submit permitted requests. It should not infer that an unscanned package shipped with another parcel, mark an entire order delivered from one tracking event, promise a replacement or refund outside policy, or expose unrelated fulfillment detail. The merchant retains shipment, remedy, fraud, inventory, and exception decisions.'},
    {heading:'Primary-source basis and interpretation',body:'The eCFR text for 16 CFR Part 435 defines concepts relevant to mail, internet, or telephone order merchandise, including shipment and refund, and provides the authoritative federal rule text for covered transactions. The NIST Privacy Framework supports purpose-aware handling of customer and address information. NIST CSF 2.0 supports governed assets, reliable information, response, and improvement. ISO 18295-1 provides customer-contact process and outcome context. These sources support explicit status definitions, minimum necessary display, accountable action, and truthful communication. They do not determine whether a particular parcel is lost, choose a carrier remedy, interpret a merchant contract, or establish one global delivery promise. The client must map applicable rules and policies to the specific product, transaction, and jurisdiction.'},
    {heading:'Lifecycle reconciliation and failure modes',body:'Map each line from order acceptance through allocation, picking, packing, carrier possession, delivery, return, cancellation, replacement, and refund. Test an order with two warehouses, partial quantity, backordered line, carrier split, delivered first parcel, missing scan, address correction, and customer request to cancel only what has not shipped. Compare order-management events, warehouse records, carrier events, customer notifications, and payment or refund instructions without treating any one screen as complete by default. Common failures include repeating the header-level “shipped” state for every line, using label creation as carrier possession, treating one delivery as full completion, cancelling a fulfilled line while leaving the requested line active, duplicating a replacement, and promising one arrival date for packages with different evidence. Preserve conflicts and route them to the named owner.'}
  ]}),
  publish({slug:'call-center-qa-score-appeal-provenance-research',title:'Provenance for Call Center QA Score Appeals',excerpt:'A quality appeal is reviewable only when the interaction evidence, rubric version, original rationale, new evidence, and final authority remain distinct.',image:'/research-aug21/qa-sample-representativeness.png',sources:[nistCsf,nistPrivacy,nistZero,iso],links:['/services/call-center-reporting-qa','/research/call-center-quality-coaching-evidence-minimization-research'],sections:[
    {heading:'Decision question and review boundary',body:'How should a client evaluate appeals of outsourced quality scores without turning calibration into an informal negotiation or exposing more customer data than the decision requires? The unit is one scored criterion linked to the interaction locator, rubric and version effective at contact time, observable evidence, original reviewer classification, rationale, appeal ground, new or corrected evidence, independent reviewer, final decision, and effective time. The frontline worker or supervisor may identify a factual, rubric, evidence, or process concern. The authorized quality owner decides whether to affirm, amend, void, or remand the result. Employment consequences, contractual remedies, legal interpretations, and policy exceptions stay with their designated owners rather than being inferred from the numerical score.'},
    {heading:'Evidence basis and careful interpretation',body:'NIST CSF 2.0 supports governance, clear responsibility, assessment, response, and improvement. The NIST Privacy Framework supports purpose limitation and management of privacy risk when recordings, transcripts, screenshots, and customer records are reviewed. Zero Trust Architecture supports explicit access to a resource instead of broad inherited trust. ISO 18295-1 supplies customer-contact quality and process context. These sources support versioned criteria, attributable decisions, minimum necessary evidence, and a review trail. They do not define a universal scoring rubric, appeal period, passing score, employment outcome, or commercial remedy. An appeal rate alone does not show reviewer quality: it can change because sampling, coaching, rubric wording, case mix, or access to evidence changed.'},
    {heading:'Appeal test and failure modes',body:'Test appeals involving the wrong rubric version, missing recording segment, disputed identity step, ambiguous customer statement, system latency, approved exception, translation uncertainty, and a criterion changed after the contact. Give the appeal reviewer the preserved source evidence and effective rubric, not a rewritten summary alone. Track outcomes by appeal ground and distinguish a scoring correction from a policy change that applies prospectively. Common failures include overwriting the original score, allowing the original reviewer to be the only appeal authority, adding customer data to justify a simple criterion, applying today’s rubric retroactively, changing several criteria without reasons, and treating a successful appeal as proof of misconduct. Keep the correction attributable, preserve disagreement, and review whether recurring appeals reveal a design problem.'}
  ]}),
  publish({slug:'outbound-appointment-calendar-hold-expiration-research',title:'Calendar-Hold Expiration in Outbound Appointment Setting',excerpt:'A tentative slot needs an owner, expiry, source calendar, and confirmation state so it does not become an accidental promise or hidden capacity loss.',image:'/research-aug21/callback-timezone-integrity.png',sources:[nistPrivacy,nistIdentity,nistCsf,ftcTsr,iso],links:['/services/outbound-appointment-setting','/research/outbound-appointment-list-suppression-reconciliation-research'],sections:[
    {heading:'Decision question and appointment boundary',body:'How should an outsourced appointment-setting lane create, extend, release, or escalate a tentative calendar hold while distinguishing availability from a confirmed appointment? The unit is one slot linked to the source calendar, service and resource, displayed time zone, customer identity state, contact purpose, hold creator, creation time, expiry rule, confirmation prerequisite, reminder state, release event, collision state, and exception owner. The provider may offer current approved availability and perform listed calendar actions. It should not invent capacity, extend a hold silently, confirm without required evidence, reveal another customer’s booking, or treat a stale screen as the authoritative schedule. The client owns availability rules, overbooking, eligibility, cancellation terms, sensitive exceptions, and remedies.'},
    {heading:'Primary-source basis and interpretation',body:'The NIST Privacy Framework supports limiting customer data to a defined scheduling purpose. NIST Digital Identity Guidelines supplies a risk-based identity lens for customer-facing digital interactions, while NIST CSF 2.0 supports governed systems, access, reliable information, response, and improvement. FTC Telemarketing Sales Rule guidance is relevant to covered outbound telemarketing practices, calling restrictions, disclosures, do-not-call handling, and records. ISO 18295-1 supplies customer-contact process context. These sources support attributable calendar access, bounded purpose, current contact preferences, and reviewable customer communication. They do not define how long a slot should remain held, whether a particular call is covered, or when a business must overbook, cancel, or waive a term. Those are client and authorized legal or policy decisions.'},
    {heading:'Hold-state test and failure modes',body:'Test immediate confirmation, customer callback before expiry, callback after expiry, concurrent booking, identity uncertainty, daylight-saving transition, different customer and service time zones, capacity removed by the service team, and integration failure after the caller accepts. Reconcile the customer-facing message, calendar event history, source availability, reminder record, and release event. Distinguish offered, held, pending evidence, confirmed, expired, released, cancelled, and conflicted states. Common failures include calling a hold a booking, hiding the expiry time, storing time without its zone, renewing holds automatically after unrelated follow-up, leaving abandoned holds to consume capacity, confirming in the CRM but not the source calendar, and sending a reminder for an expired slot. A truthful recovery names the current state, next owner, and permitted alternative.'}
  ]}),
  publish({slug:'collections-reminder-payment-status-freshness-research',title:'Payment-Status Freshness in Collections Reminder Calls',excerpt:'A reminder should not repeat a stale amount or status when a payment, reversal, dispute, hold, or posting delay may have changed the account.',image:'/research-aug21/after-hours-safety-escalation.png',sources:[cfpbDebt,ftcTsr,nistPrivacy,nistIdentity,iso],links:['/services/collections-reminder-calls','/research/collections-reminder-dispute-pause-handoff-research'],sections:[
    {heading:'Decision question and reminder boundary',body:'How should a narrowly scoped outsourced reminder-call lane determine whether the approved account status is fresh enough to use before communicating an amount, due state, or next step? The unit is one attempt linked to the client-approved account reference, verified recipient state, status source, source timestamp, extract or synchronization time, payment and reversal indicators, dispute or hold state, customer statement, permitted wording, stop event, and next owner. The provider may communicate approved information, capture a customer statement, and apply a preauthorized pause. It should not adjudicate whether payment occurred, calculate a new balance, remove a dispute, promise credit reporting treatment, or continue ordinary reminder wording when the evidence conflicts. The client and authorized legal or policy owners retain account, remedy, dispute, and exception decisions.'},
    {heading:'Primary sources and uncertainty',body:'The CFPB Regulation F materials provide the federal rulemaking and implementation context for covered debt collection practices, communications, validation information, and disputes. FTC Telemarketing Sales Rule guidance may be relevant to covered calls and records, depending on the activity. NIST Privacy Framework and Digital Identity Guidelines support purpose-aware data handling and risk-based assurance. ISO 18295-1 provides customer-contact process context. These sources support controlled access, truthful source attribution, traceable status, and an owned stop path when the customer disputes or contradicts the record. They do not determine that a debt or payment is valid, set a universal freshness interval, classify every caller or account under a law, or replace client counsel. A “current” screen can still lag a payment processor or upstream account system.'},
    {heading:'Freshness test and failure modes',body:'Map when the campaign extract is created, when the source account changes, when a payment provider posts or reverses an event, when holds and disputes propagate, and when the dialer selects the next attempt. Test same-day payment, pending payment, returned payment, partial payment, disputed amount, account hold, wrong-party answer, synchronization failure, and customer evidence that conflicts with the approved screen. Record whether the lane paused and who accepted the handoff. Common failures include reading an overnight balance as real time, treating a payment reference as final settlement, retrying while a dispute hold is pending, asking for unnecessary payment details, promising an update the queue cannot observe, and overwriting the customer statement with a disposition code. Uncertainty should stop the ordinary reminder path and move the decision to the authorized owner.'}
  ]})
];
