import type {ResearchPost} from './fleet-data';

const iso={name:'ISO 18295-1 Customer contact centres',url:'https://www.iso.org/standard/64739.html'};
const nist={name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'};
const privacy={name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'};
const identity={name:'NIST Digital Identity Guidelines, SP 800-63B',url:'https://pages.nist.gov/800-63-3/sp800-63b.html'};

type Study={slug:string;title:string;excerpt:string;image:string;question:string;method:string;limits:string;use:string};
const studies:readonly Study[]=[
 {slug:'outsourced-call-center-failed-transfer-recovery-study',title:'Failed Transfer Recovery in Outsourced Call Centers',excerpt:'A paired-record study can show whether dropped and rejected transfers regain an owner before the customer has to start again.',image:'/research-aug20/escalation-path-design.png',question:'This study asks what happens after a live transfer disconnects, returns to the sender, or reaches a destination that does not accept the work.',method:'Select every failed transfer in a fixed period. Link the sending interaction, routing event, receiving record, recovery attempt, customer promise, and final status. Report time to accepted ownership separately from time to the next contact.',limits:'Telephony events may not capture a spoken acceptance, local outage, or work completed in another system. A later contact does not prove that the transfer caused the customer to call again.',use:'Managers can set a failed-transfer fallback, required handoff fields, and an acknowledgment clock. The method does not decide remedies or individual performance.'},
 {slug:'call-center-after-hours-message-continuity-research',title:'After-Hours Message Continuity: A Call Center Study',excerpt:'Message counts hide whether an overnight customer request reached an authorized owner during the next staffed period.',image:'/research-aug20/absence-handoff-protocol.png',question:'The study examines whether after-hours messages preserve enough context and ownership for the next staffed team to act.',method:'Build a cohort of messages received outside the destination queue\'s hours. Preserve local time, contact purpose, priority evidence, promised window, destination, acknowledgment, first action, and status at cutoff.',limits:'Messages may be duplicated across voicemail, email, and CRM systems. Urgency labels are not comparable until the operation defines them, and a quick acknowledgment does not prove resolution.',use:'Results can support a morning sweep, clearer priority rules, and a backup owner. Client leaders retain decisions about service levels and high-impact exceptions.'},
 {slug:'call-center-reopened-ticket-context-loss-analysis',title:'Context Loss in Reopened Call Center Tickets',excerpt:'Reopened-ticket research should measure what the next worker can recover from the record, not simply count how often a status changes.',image:'/research-aug21/case-linkage-evidence.png',question:'This analysis asks whether reopened tickets retain the original need, prior action, new customer information, and present owner.',method:'Sample tickets that reopen during a defined period. Have a reviewer identify the remaining customer problem before seeing the final outcome. Compare the reconstruction with the original contact, closure note, customer reply, and next action.',limits:'A reopening can be legitimate when circumstances change. Customer replies may introduce a separate request, while system migrations or merged tickets can leave an incomplete chronology.',use:'Managers can revise closure definitions, required notes, and routing rules. The study cannot infer carelessness or assign coaching from a status change alone.'},
 {slug:'outsourced-call-center-disposition-evidence-consistency-study',title:'Do Call Dispositions Match the Evidence?',excerpt:'A blinded consistency review can test whether completed, transferred, voicemail, and follow-up codes agree with the underlying contact record.',image:'/research-aug21/qa-sample-representativeness.png',question:'The review tests whether a selected disposition describes the observable contact outcome and any remaining customer promise.',method:'Draw a stratified sample across common and rare codes. Give reviewers the interaction, note, linked task, and published definitions without agent identity or dashboard totals. Record agreement, disagreement reason, and unresolved cases.',limits:'Recordings and transcripts can omit work completed elsewhere. Reviewer agreement may reflect the same ambiguous rule, and a code can be technically correct while the next action remains poorly documented.',use:'Use findings to repair definitions, form choices, and QA examples. Managers should investigate system and rule causes before drawing conclusions about workers.'},
 {slug:'call-center-callback-number-change-risk-review',title:'Callback Number Changes in Customer Service Records',excerpt:'A changed callback number affects identity, consent, timing, and delivery, so audit evidence needs more than a before-and-after field value.',image:'/research-aug21/callback-timezone-integrity.png',question:'This review studies how customer-supplied callback-number changes move from a contact into later outbound work.',method:'Sample number changes and link the verification event, masked old and new values, purpose, channel permission, local-time window, downstream systems, confirmation, attempts, and final result.',limits:'A successful connection does not prove that the correct person answered. Shared numbers, reassigned numbers, accessibility needs, and jurisdiction-specific contact rules require separate interpretation.',use:'The findings can support field-level permissions, readback wording, propagation checks, and a safe exception route. They do not establish a universal identity or consent rule.'},
] as const;

const make=(s:Study):ResearchPost=>({slug:s.slug,title:s.title,excerpt:s.excerpt,published:'2026-09-07',sourceDate:'2026-09-07',image:s.image,sources:[iso,nist,privacy,identity],keyStats:['1 fixed observation period','2 linked records reviewed','1 accountable owner at cutoff'],takeaways:['Define the event before sampling.','Preserve open work at the cutoff.','Separate observed facts from management decisions.'],sections:[
 {heading:'Research question and scope',body:s.question+' The unit of analysis is one customer need linked across the available contact and work records.'},
 {heading:'Source basis',body:'ISO 18295-1 supplies customer-contact process context. NIST CSF 2.0 supports defined governance and ownership. The NIST Privacy Framework and Digital Identity Guidelines inform purpose, minimization, and identity boundaries. None of these sources sets a universal queue target or proves vendor performance.'},
 {heading:'Study method',body:s.method+' Include records still open at the cutoff so the sample does not reward fast closure.'},
 {heading:'Interpretation limits',body:s.limits+' The work is a bounded operational review, not legal advice or a causal experiment.'},
 {heading:'Operating use',body:s.use+' Publish the definitions, exclusions, period, and missing-data rules beside any result.'},
],faqs:[{question:'Does this method set a universal benchmark?',answer:'No. Compare results only after the queue, event definitions, period, and exclusions are fixed.'},{question:'Can the review prove why an error happened?',answer:'No. It can locate evidence gaps and patterns that an authorized owner should investigate.'}],internalLinks:['/research','/services/operations-support'],serviceHandoff:{href:'/contact-us',label:'Plan a bounded evidence review',body:'Choose one queue, define the cohort and cutoff, and name the decision owner before sampling.'}});

export const september7ResearchBatch:readonly ResearchPost[]=studies.map(make);
