import type {ResearchPost} from './fleet-data';
import {september24Cala101ResearchBatch as prior} from './research-sep24-cala101.ts';

const published='2026-09-25';
const iso={name:'ISO 18295-1:2017, Customer contact centres',url:'https://www.iso.org/standard/64739.html'};
const privacy={name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'};
const csf={name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'};
const identity={name:'NIST SP 800-63-4, Digital Identity Guidelines',url:'https://pages.nist.gov/800-63-4/'};
const zero={name:'NIST SP 800-207, Zero Trust Architecture',url:'https://csrc.nist.gov/pubs/sp/800/207/final'};
const ftcOrder={name:'eCFR, 16 CFR Part 435, Mail, Internet, or Telephone Order Merchandise',url:'https://www.ecfr.gov/current/title-16/chapter-I/subchapter-D/part-435'};
const ftcTsr={name:'FTC, Complying with the Telemarketing Sales Rule',url:'https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule'};

type Seed={slug:string;title:string;excerpt:string;image:string;sources:ResearchPost['sources'];links:string[];sections:ResearchPost['sections']};
const make=(seed:Seed,index:number):ResearchPost=>({
  ...seed,published,sourceDate:published,internalLinks:['/research',...seed.links],
  keyStats:['One defined operating cohort','One accountable exception owner','Facts, inferences, and unknowns reported separately'],
  takeaways:['Define the customer-impact decision before measuring activity.','Preserve conflicts and unknown states instead of forcing closure.','Expand only after representative review and an owned correction path.'],
  faqs:[
    {question:'Does this research make a legal, security, or compliance determination?',answer:'No. It is an operational research method. Authorized legal, privacy, security, commercial, and policy owners must apply requirements to the actual service, data, contract, and jurisdiction.'},
    {question:'Does this brief prescribe one universal threshold?',answer:'No. Thresholds depend on the customer journey, risk, evidence quality, channel, authority boundary, and client decision owner.'}
  ],
  serviceHandoff:{href:'/contact-us',label:'Map a controlled support lane',body:'Choose one queue, document permitted actions and exceptions, and test the handoff before adding volume.'},
  sections:[...seed.sections,...prior[index].sections.slice(3).map(section=>section.heading==='Replication record and source notes'?{...section,body:section.body.replace('September 24, 2026','September 25, 2026')}:section)]
});

export const september25Cala102ResearchBatch:readonly ResearchPost[]=[
  make({slug:'inbound-support-abandoned-callback-ownership-research',title:'Callback Ownership After an Abandoned Inbound Contact',excerpt:'An abandoned contact becomes actionable only when the queue can distinguish customer departure, technical failure, callback permission, urgency, and an accountable next owner.',image:'/research-aug21/callback-timezone-integrity.png',sources:[iso,privacy,identity,csf],links:['/services/inbound-call-handling','/research/call-center-callback-number-change-risk-review'],sections:[
    {heading:'Decision question and inbound boundary',body:'When should an outsourced inbound queue create a callback after a caller disconnects before service, and what evidence is needed before a worker uses the captured number? The unit is one offered contact linked to channel, arrival time, queue event, disconnect event, any verified identity state, number source, customer callback request, contact preference, local-time interpretation, reason if known, risk marker, next owner, and final outcome. A captured caller ID is a routing signal, not proof that the number belongs to the intended customer or that a sensitive voicemail is permitted. The provider may apply a client-approved callback rule, use neutral wording, and route urgent facts. It should not infer intent from silence, disclose account information to an unverified recipient, repeatedly dial a number without a purpose rule, or mark a customer served merely because an attempt occurred. The client owns callback eligibility, attempt limits, high-risk exceptions, authentication requirements, and remedies for missed access.'},
    {heading:'Primary-source basis and interpretation',body:'ISO 18295-1 supplies customer-contact process and outcome context. The NIST Privacy Framework supports purpose-aware handling of phone numbers, contact preferences, recordings, and queue metadata. NIST Digital Identity Guidelines provide a risk-based lens for identity evidence, while Cybersecurity Framework 2.0 supports governed roles, reliable events, response, and improvement. Together they support a documented decision rule, minimum necessary disclosure, attributable action, and a recoverable exception path. They do not require every abandoned contact to receive a callback, establish a universal wait threshold, prove the identity behind caller ID, or decide whether a particular voicemail may contain case details. Those decisions depend on the service, jurisdiction, customer expectation, client policy, and actual evidence. Analysis should therefore separate source facts from operational inference and keep the unknown reason visible.'},
    {heading:'Cohort test and failure modes',body:'Define abandoned consistently before comparison: for example, exclude test calls and clearly documented wrong numbers, but preserve short contacts until the team has tested whether system failures create them. Stratify by interval, channel entry point, wait band, transfer state, language path, and known high-impact reason without claiming that one factor caused departure. Test customer hang-up before menu completion, disconnect during transfer, carrier failure, callback request, repeated attempt from the same verified account, wrong-number return, blocked caller ID, and a safety-related phrase captured before disconnect. Compare telephony events, approved CRM evidence, preference state, agent action, next-owner acknowledgment, and eventual customer outcome. Common failures include treating every captured number as consent, placing sensitive detail in voicemail, calling at an unsuitable local time, duplicating attempts across queues, counting an unanswered attempt as resolution, and losing urgency during transfer. Report offered contacts, eligible callbacks, completed verified conversations, neutral messages, suppressed attempts, duplicates, unresolved cases, and unknowns as separate counts.'}
  ]},0),
  make({slug:'omnichannel-support-attachment-intake-boundary-research',title:'Attachment Intake Boundaries in Omnichannel Customer Support',excerpt:'A customer attachment should enter support only through an approved channel, with a defined purpose, safe access path, retention owner, and alternative when the file cannot be used.',image:'/research-aug21/case-linkage-evidence.png',sources:[privacy,csf,zero,iso],links:['/services/omnichannel-customer-support','/research/call-center-sensitive-field-exposure-research-brief'],sections:[
    {heading:'Decision question and attachment boundary',body:'How should an outsourced support lane handle a file sent by chat, email, ticket, or messaging when its format, contents, identity link, or business purpose may be uncertain? The unit is one attachment event linked to the customer contact, approved channel, sender state, stated purpose, file type and size, intake result, malware or platform control result where available, access group, copied locations, retention instruction, alternate evidence path, escalation, and disposition. The provider may direct customers to an approved intake route, record whether the platform accepted the file, and route an exception without opening content in an unmanaged tool. It should not ask for broad identity documents by habit, download files to personal storage, forward content to create convenience copies, declare a file safe from its extension, or retain it after the support purpose ends. The client owns platform configuration, allowed evidence, security response, privacy rights, retention, deletion, and any decision based on the document.'},
    {heading:'Primary-source basis and interpretation',body:'The NIST Privacy Framework supports defining purpose, minimizing data, and managing privacy risk through the information lifecycle. Cybersecurity Framework 2.0 provides outcomes for governance, protection, detection, response, and recovery. Zero Trust Architecture supports explicit access decisions for users and resources rather than trust based on network location or a familiar sender. ISO 18295-1 provides customer-contact process and result context. These sources support approved channels, role-based access, observable handling, and a named response owner. They do not label a particular file safe, establish a universal retention period, decide whether identification is legally required, or authorize an outsourced worker to interpret medical, financial, legal, or identity evidence. A passed platform check is one control result, not proof that content is accurate, appropriate, or free of every risk.'},
    {heading:'Intake test and failure modes',body:'Test ordinary screenshots, unsupported formats, password-protected files, oversized media, links to third-party storage, duplicate uploads, documents containing unrelated people, apparent payment data, suspected malicious content, and a customer who cannot use the preferred channel. Observe whether the agent explains the purpose and alternative, whether the system keeps the file inside the approved boundary, whether access is limited, and whether the receiving owner acknowledges the handoff. Keep platform security results separate from business validation and customer statements. Common failures include asking a customer to resend sensitive material over ordinary email, copying a file into notes, opening it outside the controlled viewer, using a screenshot when a structured field is sufficient, leaving duplicates across systems, and closing the contact while an inaccessible file blocks action. Measures should include accepted, rejected, redirected, duplicated, inaccessible, escalated, deleted, and unresolved attachments, plus the elapsed time to an approved alternative. Review severe exposure individually even if aggregate acceptance looks favorable.'}
  ]},1),
  make({slug:'order-support-return-label-state-reconciliation-research',title:'Return-Label State Reconciliation in Outsourced Order Support',excerpt:'A return label is not a completed return: support needs separate evidence for issuance, customer receipt, carrier acceptance, warehouse processing, and the authorized remedy.',image:'/research-aug20/customer-promise-reconciliation.png',sources:[ftcOrder,privacy,csf,iso],links:['/services/order-management-support','/research/order-support-split-shipment-status-reconciliation-research'],sections:[
    {heading:'Decision question and return boundary',body:'What may an outsourced order-support representative say or do when a return label exists but the item, carrier, warehouse, refund, replacement, or cancellation state does not agree? The unit is one return line linked to order and item, return authorization if used, label issue and delivery events, carrier acceptance evidence, latest transit event, warehouse receipt and inspection state where applicable, remedy instruction, customer statement, exception owner, and next promised update. The provider may explain confirmed source events, resend an approved label, capture missing facts, and submit a permitted exception. It should not call label creation a shipped return, treat carrier acceptance as warehouse approval, promise a refund from transit evidence, combine unrelated items, or decide an exception outside written authority. The merchant retains return eligibility, inspection, inventory, fraud, refund, replacement, fee, and policy decisions.'},
    {heading:'Primary-source basis and interpretation',body:'The authoritative eCFR text for 16 CFR Part 435 defines concepts relevant to covered mail, internet, and telephone merchandise transactions, including shipment and refunds. The NIST Privacy Framework supports purposeful handling of customer, address, order, and carrier information. Cybersecurity Framework 2.0 supports governed records, reliable information, response, and improvement. ISO 18295-1 provides customer-contact process and outcome context. Together they support explicit lifecycle states, attributable updates, limited data display, and an owned exception path. They do not decide a specific return policy, determine whether an item was actually placed in a package, establish a carrier liability outcome, or prove warehouse condition. Client legal and policy owners must map applicable obligations and promises to the product, transaction, location, and evidence.'},
    {heading:'Lifecycle test and failure modes',body:'Map requested, authorized, label generated, label delivered, tendered, accepted by carrier, in transit, delivered to return location, received by warehouse, inspected, remedy approved, remedy issued, rejected, lost, expired, and unknown as separate states. Test a label never received, several labels for one item, a package with multiple items, carrier scan without warehouse receipt, warehouse receipt without line match, expired authorization, damaged item, customer-provided tracking, refund issued before inspection, and replacement already shipped. Reconcile the order system, label provider, carrier event, warehouse record, payment or remedy instruction, customer message, and exception acknowledgment. Common failures include reading “label created” as “return sent,” sending another label without invalidating the first, applying one package event to every line, promising timing from an estimate, collecting unnecessary images or identifiers, and closing the case while ownership is unclear. Report each state and conflict count before percentages; preserve the oldest and highest-impact unresolved cases.'}
  ]},2),
  make({slug:'outbound-appointment-reschedule-collision-research',title:'Reschedule-Collision Evidence in Outbound Appointment Setting',excerpt:'A reschedule is safe only when the old slot, new slot, time zone, concurrent updates, confirmation state, and downstream reminders reconcile.',image:'/research-aug21/callback-timezone-integrity.png',sources:[privacy,identity,ftcTsr,iso],links:['/services/outbound-appointment-setting','/research/outbound-appointment-calendar-hold-expiration-research'],sections:[
    {heading:'Decision question and scheduling boundary',body:'How should an outsourced appointment-setting team handle a reschedule when the customer, service team, calendar integration, or another worker may update the booking at nearly the same time? The unit is one appointment change linked to the authoritative calendar, prior event identifier and version, customer identity state, service and resource, old and new local times with zones, availability check time, requested action, write result, confirmation event, reminder state, collision result, and exception owner. The provider may offer current approved availability and make listed changes. It should not overwrite a newer event, create a second booking to avoid an error, infer that a CRM note changed the source calendar, disclose another customer’s slot, or promise capacity after a failed write. The client owns eligibility, late-change rules, overbooking, waitlists, sensitive exceptions, fees, and remedies.'},
    {heading:'Primary-source basis and interpretation',body:'The NIST Privacy Framework supports purpose-aware handling of customer and scheduling data. NIST Digital Identity Guidelines provide a risk-based lens for identity evidence. FTC Telemarketing Sales Rule guidance is relevant to covered outbound practices, restrictions, disclosures, do-not-call handling, and records. ISO 18295-1 supplies customer-contact process context. These sources support bounded access, current contact preferences, attributable changes, and accurate customer communication. They do not set a universal rescheduling window, determine whether a call is legally covered, specify concurrency controls for a calendar product, or authorize a fee waiver. Those are client technology, policy, and legal decisions. A successful screen response also does not prove downstream reminders and resource systems accepted the same change.'},
    {heading:'Collision test and failure modes',body:'Test a customer reply while the agent is editing, service-side cancellation, simultaneous booking by another channel, daylight-saving transition, changed resource, expired hold, integration timeout after submission, retry after an unknown write result, and reminder generation between the old and new events. Compare event history, version or update time, source availability, CRM record, outbound attempt, confirmation delivery, reminder state, and receiving-owner acknowledgment. Distinguish requested, pending, committed, conflicted, reverted, cancelled, and unknown changes. Common failures include deleting the old appointment before securing the new one, retrying into a duplicate, overwriting a provider update, displaying one time zone while storing another, sending confirmations for both slots, and treating a timeout as failure when the write actually succeeded. Measure confirmed reconciled changes, collisions, duplicates, stale reminders, rollbacks, unresolved writes, and customer contacts required for recovery. A safe result may be an acknowledged exception with both slots protected until the authorized owner resolves the conflict.'}
  ]},3),
  make({slug:'tier-one-support-remote-session-termination-research',title:'Remote-Support Session Termination Evidence in Tier-One Support',excerpt:'Remote assistance needs observable start, active scope, customer control, privilege, termination, and post-session evidence so access does not outlive the support purpose.',image:'/research-aug21/consent-provenance.png',sources:[zero,identity,privacy,csf,iso],links:['/services/tier-one-technical-support','/research/tier-one-support-outage-triage-evidence-research'],sections:[
    {heading:'Decision question and remote-support boundary',body:'What evidence should a client require when outsourced tier-one support initiates, uses, and ends an approved remote-assistance session? The unit is one session linked to the support case, verified customer and device context, stated purpose, approved tool, worker identity, access level, customer authorization state, start and end events, actions visible to the tool, privilege changes, file transfers if permitted, interruption, revocation request, next owner, and post-session status. A tier-one worker may perform listed diagnostic or guided actions through the approved platform. The worker should not use personal remote tools, extend access to unrelated systems, request passwords through chat, conceal actions, retain unattended access by convenience, or treat a disconnected screen as proof that every credential and process ended. The client owns tool configuration, privilege, security response, customer notice, credential rotation, evidence retention, and exceptions.'},
    {heading:'Primary-source basis and interpretation',body:'NIST Zero Trust Architecture emphasizes explicit authorization for users, assets, and resources rather than implicit trust from location. NIST Digital Identity Guidelines provide risk-based identity concepts. The Privacy Framework supports purpose limitation and managed handling of personal data, while Cybersecurity Framework 2.0 supports governance, protection, detection, response, recovery, and improvement. ISO 18295-1 supplies customer-contact process context. Together these sources support a scoped session, least necessary privilege, attributable activity, customer-aware controls, and reliable termination. They do not certify a remote-support product, require one authentication method, determine whether a customer may authorize access for an organization, or prove that a visible disconnect revoked every token. Tool behavior, system architecture, client policy, contractual terms, and applicable law remain material.'},
    {heading:'Session test and failure modes',body:'Test an ordinary guided session, customer withdrawal during work, network loss, worker shift change, privilege request, reboot and reconnect, unattended-access prompt, file transfer, suspected compromise, wrong device, and a tool reporting termination while the case remains open. Observe whether identity and device context are checked at the risk level the client selected, whether the customer can understand the active scope, whether prohibited actions are blocked, and whether end events appear in the authoritative control plane. Compare case notes, platform logs, privilege events, transferred artifacts, security alerts, and customer-facing confirmation without copying unnecessary sensitive content. Common failures include leaving a persistent agent installed, recording a password, reconnecting after consent was withdrawn, assuming screen closure removed access, sharing a session link across cases, and letting a general support role approve its own privilege expansion. Count started, refused, interrupted, revoked, completed, escalated, and technically unresolved sessions separately; individually review unauthorized or unexplained persistence.'}
  ]},4)
];
