import type {ResearchPost} from './fleet-data';

const nist={name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'};
const privacy={name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'};
const iso={name:'ISO 18295-1 Customer contact centres',url:'https://www.iso.org/standard/64739.html'};
const identity={name:'NIST Digital Identity Guidelines, SP 800-63B',url:'https://pages.nist.gov/800-63-3/sp800-63b.html'};
const pci={name:'PCI Data Security Standard',url:'https://www.pcisecuritystandards.org/standards/pci-dss/'};

export const september4ResearchBatch: readonly ResearchPost[] = [
  {
    slug:'outsourced-call-center-warm-transfer-acceptance-evidence',
    title:'Warm Transfer Acceptance Evidence in Outsourced Call Centers',
    excerpt:'A transfer log can show movement without showing whether the receiving role understood and accepted the customer’s unresolved need.',
    published:'2026-09-04',sourceDate:'2026-09-04',image:'/research-aug20/escalation-path-design.png',sources:[iso,nist,privacy],
    keyStats:['2 linked interaction records per sampled transfer','1 explicit receiving owner','4 transfer outcomes kept separate'],
    takeaways:['Measure acceptance, not merely connection.','Compare the spoken introduction with both queue records.','Treat customer repetition and returned transfers as signals, not automatic proof of failure.'],
    sections:[
      {heading:'Research question',body:'This desk-review method asks whether a warm transfer preserves enough decision context for the receiving role to continue safely. It focuses on live customer contacts that cross a skill, queue, vendor, or client boundary. The study does not assume that every transfer should be avoided or that every repeated question is unnecessary.'},
      {heading:'Evidence scope',body:'ISO 18295-1 provides a customer-contact process and responsibility frame. NIST CSF 2.0 supports governance and accountable control design. The NIST Privacy Framework supports purpose-based handling and minimization. These sources justify examining ownership and information flow, but none defines a universal transfer-acceptance score or target.'},
      {heading:'Paired-record method',body:'Select transfers from a fixed period and link the sending interaction, receiving interaction, transfer note, routing event, and eventual outcome. Define required context by contact reason: customer purpose, completed verification, action already taken, open decision, communication constraint, and next promise. Ask a reviewer to reconstruct the next action from the receiving record before showing the final outcome.'},
      {heading:'Outcome classes',body:'Keep accepted and continued, accepted then returned, disconnected before acceptance, and connected without a traceable owner separate. Record customer repetition as required re-verification, new information, clarification, or preventable reconstruction. A long transfer note should not score well when the receiving person still cannot identify the unresolved question.'},
      {heading:'Interpretation limits',body:'Routing logs may omit spoken acceptance, consult calls, screen context, or work completed outside the sampled systems. A customer may repeat details by choice. Privacy and identity rules can properly require a new check. The method can locate missing context and ownership, but it cannot assign intent or prove that a transfer caused the final customer outcome.'},
      {heading:'Operating use',body:'Use the findings to define the smallest transfer note, the accepting role, the failed-transfer fallback, and the review sample. Keep policy, remedies, access, and sensitive account decisions with the authorized client owner.'},
    ],
    faqs:[{question:'Is connection time enough to prove acceptance?',answer:'No. It shows that a routing event occurred, not that a receiving person accepted the unresolved work.'},{question:'Should every repeated question count as failure?',answer:'No. Separate required verification and new customer information from repetition caused by missing context.'}],
    internalLinks:['/blog/outsourced-call-center-warm-transfer-acceptance-check','/services/operations-support'],serviceHandoff:{href:'/contact-us',label:'Plan a controlled transfer review',body:'Define the sampled routes, required context, acceptance event, fallback, and client-owned decisions.'}
  },
  {
    slug:'call-center-voicemail-disclosure-boundary-study',
    title:'Call Center Voicemail Disclosure Boundaries: A Study Framework',
    excerpt:'A voicemail attempt reaches a device, not necessarily the intended customer, so disclosure and promise evidence need separate treatment.',
    published:'2026-09-04',sourceDate:'2026-09-04',image:'/research-aug21/callback-timezone-integrity.png',sources:[privacy,identity,iso],
    keyStats:['5 voicemail outcomes classified separately','2 evidence sources compared','1 approved disclosure rule per queue'],
    takeaways:['Do not equate a message left with a customer reached.','Study the permitted disclosure and the callback promise as separate controls.','Preserve local time and channel constraints.'],
    sections:[
      {heading:'Question and unit of analysis',body:'The study asks what a call-center record can support after an outbound attempt reaches voicemail. The unit is one attempt linked to its source task, dialer event, permitted number, local time, message decision, later contact, and final case outcome. It does not evaluate the customer’s reasons for answering or returning a call.'},
      {heading:'Research basis',body:'The NIST Privacy Framework supports examining purpose and unnecessary disclosure. NIST identity guidance explains why possession of a phone or mailbox should not automatically establish identity. ISO 18295-1 supplies the customer-contact process context. These publications do not prescribe voicemail wording, attempt limits, or jurisdiction-specific consent rules.'},
      {heading:'Classification method',body:'Classify no message permitted, approved neutral message, verified personal mailbox under the client rule, full or unavailable mailbox, and suspected wrong party. Record only observable events. Then track whether the customer returned contact, the team made another permitted attempt, the promise changed, or the task remained unresolved at the cutoff.'},
      {heading:'Review design',body:'Compare the recording or dialer evidence with the CRM disposition. Review messages left outside promised windows and records marked complete after voicemail. A second reviewer should judge compliance with the approved script without seeing whether the customer later responded, which reduces outcome-based grading.'},
      {heading:'Limitations',body:'A dialer event cannot prove who heard a message. Caller ID filtering, shared devices, transcription services, language, and customer availability all affect response. The cited sources do not create a legal conclusion. Local law, contract terms, and the client’s approved contact policy require separate review.'},
      {heading:'What managers can decide',body:'The results can support clearer disposition names, safer neutral wording, local-time controls, and a single owner for unresolved callbacks. They cannot justify broader disclosure merely because return rates are low.'},
    ],faqs:[{question:'Does a voicemail count as customer contact?',answer:'The study should report it as its own attempt outcome unless the approved definition explicitly says otherwise.'},{question:'Can the study set a universal message script?',answer:'No. Wording depends on purpose, customer permission, jurisdiction, and client policy.'}],internalLinks:['/blog/call-center-voicemail-disposition-review','/services/customer-support'],serviceHandoff:{href:'/contact-us',label:'Scope a voicemail evidence review',body:'Choose one queue, a fixed observation period, the approved script, and an owner for unresolved attempts.'}
  },
  {
    slug:'outsourced-call-center-queue-reentry-aging-analysis',
    title:'Queue Reentry and Case-Aging Analysis for Outsourced Call Centers',
    excerpt:'Cases that reenter a queue can look new in operational reports even when the customer’s original wait never stopped.',
    published:'2026-09-04',sourceDate:'2026-09-04',image:'/research-aug20/absence-handoff-protocol.png',sources:[iso,nist],
    keyStats:['2 clocks reported for each reentry','4 reentry reasons separated','1 continuous customer timeline'],
    takeaways:['Preserve original arrival beside the reentry timestamp.','Do not combine rejected, reopened, returned, and newly informed work.','Test the report definition before comparing teams.'],
    sections:[
      {heading:'Research question',body:'This analysis asks how reassignment, reopening, parking, and specialist return affect the apparent age of customer work. It examines case histories and queue events rather than employee productivity. The purpose is to learn whether reporting definitions hide accumulated wait or assign it to the wrong part of the operation.'},
      {heading:'Evidence and inference',body:'ISO 18295-1 provides context for defined contact processes and outcomes. NIST CSF 2.0 provides governance and measurement context. Neither source defines queue age. Arrival times, state changes, owners, customer promises, and action timestamps are observed facts; deciding which clock answers a management question is an operating choice that must be documented.'},
      {heading:'Cohort construction',body:'Select all cases that entered an active queue more than once during a fixed period. Preserve the first customer request time and each later reentry. Code the reason as new customer information, reopened after closure, rejected by destination, returned after specialist work, dependency resolved, or unknown. Keep cases open at the cutoff in the cohort.'},
      {heading:'Measures to compare',body:'Report elapsed time from original request, time since latest reentry, time without an accepted owner, and time waiting on the customer or an external dependency. Show distributions and individual aged cases rather than one average. Compare dashboards with the source case timeline to detect timestamp replacement or missing state transitions.'},
      {heading:'Limitations',body:'Case merges, channel changes, clock pauses, system migrations, and undocumented work can distort the timeline. A long elapsed time does not prove neglect when the customer or an external party owns the next action. Different queues may use reentry for different purposes, so cross-team rankings are unsafe without matched definitions.'},
      {heading:'Decision boundary',body:'Managers can use this analysis to revise reason codes, ownership acceptance, aging views, and closure rules. It does not decide customer remedies, performance consequences, or a universal service target.'},
    ],faqs:[{question:'Which age should the dashboard show?',answer:'Show the clock needed for the decision, but preserve original elapsed time so reentry cannot erase customer history.'},{question:'Are reopened cases always errors?',answer:'No. New customer information or a resolved dependency can legitimately restart work.'}],internalLinks:['/blog/outsourced-call-center-queue-reentry-rule','/services/workforce-reporting-support'],serviceHandoff:{href:'/contact-us',label:'Design a reentry cohort',body:'Define the clocks, states, exclusions, and owner before interpreting queue-age results.'}
  },
  {
    slug:'call-center-screen-share-sensitive-exposure-review',
    title:'Sensitive Exposure Review for Call Center Screen Sharing',
    excerpt:'Screen-share research should test where unnecessary viewing begins, how quickly support stops, and what the operation records afterward.',
    published:'2026-09-04',sourceDate:'2026-09-04',image:'/research-aug20/knowledge-article-retirement.png',sources:[privacy,nist,pci,identity],
    keyStats:['4 exposure points mapped','3 records reviewed per sampled session','1 approved stop rule'],
    takeaways:['Map the workflow before reviewing incidents.','Measure stop behavior without reproducing sensitive values.','Keep support evidence separate from incident evidence.'],
    sections:[
      {heading:'Scope of the review',body:'The review covers support sessions in which a representative can see a customer screen. It maps sign-in, identity proofing, document upload, payment, and account-recovery steps where unnecessary data may appear. It does not test the security of the screen-sharing product or determine whether a legal breach occurred.'},
      {heading:'Source basis',body:'The NIST Privacy Framework supports data minimization and purpose analysis. NIST CSF 2.0 supplies governance and response context. NIST identity guidance describes authentication risks, while PCI DSS supplies requirements relevant to payment account data. These sources inform control questions; they do not approve a particular support workflow or tool.'},
      {heading:'Workflow observation',body:'For each approved support path, identify the last screen the representative needs to see and the first sensitive step the customer should complete privately. Sample session recordings or audit events under restricted access. Record whether the representative warned the customer, paused or ended viewing, used an approved alternate path, and documented the control event without copying exposed content.'},
      {heading:'Incident separation',body:'Keep routine stop-rule compliance separate from suspected exposure response. The support record needs only the operational fact and next safe action. A restricted incident record may contain additional evidence under the client’s response plan. Reviewers should never capture a screenshot of a password, authentication secret, identity document, or payment value merely to prove that it appeared.'},
      {heading:'Limitations',body:'Recordings may omit local screens, notifications, or content hidden by the tool. The absence of visible data does not prove the customer completed the step safely. PCI DSS applies to defined payment environments and does not cover every sensitive category. Applicable law, contracts, and incident duties require qualified review.'},
      {heading:'Practical result',body:'The study can identify unclear stopping points, late warnings, overbroad representative access, and support guides that send customers through sensitive screens while sharing remains active. Client security and privacy owners decide tool configuration, incident action, retention, and acceptable workflow.'},
    ],faqs:[{question:'Should reviewers save the exposed value as evidence?',answer:'No. Record the event through the restricted incident process without duplicating the sensitive value.'},{question:'Does stopping screen share end the support case?',answer:'Not necessarily. The representative can resume after the customer completes the private step if the approved workflow allows it.'}],internalLinks:['/blog/call-center-sensitive-screen-share-stop-rule','/services/tier-one-technical-support'],serviceHandoff:{href:'/contact-us',label:'Map a safer screen-share path',body:'Identify the last necessary screen, first private step, stop wording, and incident owner.'}
  },
  {
    slug:'outsourced-call-center-duplicate-callback-collision-study',
    title:'Duplicate Callback Collisions in Outsourced Call Center Operations',
    excerpt:'Apparent duplicate callbacks need case-level comparison because the same customer and phone number can still represent different promises.',
    published:'2026-09-04',sourceDate:'2026-09-04',image:'/research-aug20/customer-promise-reconciliation.png',sources:[iso,privacy,nist],
    keyStats:['7 matching fields checked','3 collision outcomes separated','1 surviving promise owner'],
    takeaways:['Match purpose and promise, not phone number alone.','Audit cancelled tasks for lost commitments.','Review conflicting contact permissions before consolidation.'],
    sections:[
      {heading:'Research question',body:'This study asks when two outbound tasks represent the same customer commitment and what happens after the operation consolidates or executes both. It focuses on scheduled service callbacks, not sales dialing. The unit is a candidate task pair linked to the source contacts and final outcomes.'},
      {heading:'Evidence foundation',body:'ISO 18295-1 supports defined responsibilities and contact processes. The NIST Privacy Framework supports purpose-aware use of customer data, and NIST CSF 2.0 supports accountable control review. None supplies a duplicate-callback definition. The study must therefore publish its matching fields and uncertainty.'},
      {heading:'Candidate matching',body:'Create candidates using customer or case identifier, callback purpose, promised window, requested channel, verification requirement, dependency, and assigned owner. A phone-number match alone is weak because households and businesses may share numbers. Keep tasks with different consent states or customer purposes separate until an authorized reviewer resolves the conflict.'},
      {heading:'Outcome tracing',body:'Classify both callbacks made, one task cancelled with all promises preserved, one task cancelled with a lost promise, intentionally separate contacts, and unresolved at cutoff. Compare what each representative told the customer. Check whether consolidation changed the due time, removed a required specialist, or left nobody accountable.'},
      {heading:'Limitations',body:'Case identifiers can duplicate or split a single customer history. Representatives may coordinate outside the sampled systems. Two similar tasks can be legitimate, and one combined call can still fail to address both purposes. The method can expose collision patterns but cannot infer customer consent, remedy authority, or staff intent from scheduling data alone.'},
      {heading:'Manager action',body:'Use the results to improve task creation, candidate alerts, supervisor review, and the surviving record. Any automated cancellation rule should have a safe exception path and preserve every active promise. Client owners retain decisions involving consent, restricted accounts, remedies, and policy.'},
    ],faqs:[{question:'What is the safest duplicate key?',answer:'There is no single safe key. Compare identity or case, purpose, promise window, channel permission, dependencies, and owner.'},{question:'Should the later callback always be cancelled?',answer:'No. Cancel only after an approved review confirms one surviving record contains the complete commitment.'}],internalLinks:['/blog/call-center-duplicate-callback-cancellation-rule','/services/operations-support'],serviceHandoff:{href:'/contact-us',label:'Review callback collisions',body:'Build a candidate-pair sample, publish the match definition, and trace cancelled tasks to final outcomes.'}
  },
] as const;
