import type {ResearchPost} from './fleet-data';

// Cycle label 2026-10-05. Blog must reconcile these two fields to each route's
// actual first-live date in the configured site timezone before the sole push.
const published='2026-10-05';
const iso={name:'ISO 18295-1:2017, Customer contact centres',url:'https://www.iso.org/standard/64739.html'};
const privacy={name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'};
const csf={name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'};
const ai={name:'NIST Artificial Intelligence Risk Management Framework 1.0',url:'https://doi.org/10.6028/NIST.AI.100-1'};
const dole={name:'Philippines Department of Labor and Employment, Labor Advisories',url:'https://dole.gov.ph/labor-advisory/'};
const pagasa={name:'PAGASA Tropical Cyclone Information',url:'https://www.pagasa.dost.gov.ph/climate/tropical-cyclone-information'};

const commonLimits=`Source pages were checked on October 5, 2026. This is a documentary operating analysis, not a controlled experiment, legal opinion, employment instruction, or performance claim about a provider. Public frameworks state broad outcomes; they do not set a universal service level, staffing ratio, contractual allocation, or customer remedy. Local policy, contracts, system behavior, jurisdictions, and the actual customer population can change the correct design. A pilot should therefore record definitions before observation, retain unknown states, and have an authorized client owner review exceptions. Correlation between a control and an outcome does not establish causation. Small samples, seasonal demand, missing records, changed routing, and reviewer judgment can distort results. Replication requires the query window, queue, channel, inclusion rule, exclusions, system versions, source access dates, reviewer, and unresolved data limitations. These cautions are part of the conclusion rather than boilerplate: a buyer should narrow or pause the lane when the evidence cannot support the promised decision.`;

const expandedLimits=`The review record should identify who confirmed each operating assumption, when system access and routing were tested, and what evidence remained unavailable. Deliberate exclusions belong in the record so a later reviewer can distinguish an accepted scope decision from a discovery failure. Findings should bind to the relevant policy, content, interface, integration, and access versions because a later change can invalidate earlier results. Customer complaints, corrections, and repeat contacts outside the measured system should be considered where they can be linked safely. If essential evidence cannot be collected, the buyer should narrow the lane or state the uncertainty rather than replace it with a vendor claim. Review capacity is itself a constraint: generating alerts, exceptions, or follow-up work without a qualified owner creates another unmanaged queue. Track pending review by age and customer impact, name a backup, and define what condition pauses expansion. Preserve only the minimum evidence required for the stated decision and apply the approved retention rule to analytical working copies. ${commonLimits}`;

export const october5Cala108ResearchBatch:readonly ResearchPost[]=[
  {
    slug:'outsourced-call-center-shadow-queue-transition-research',
    title:'Shadow Queues During Call Center Outsourcing Transitions: A Measurement Design',
    excerpt:'A transition can look stable while requests continue through legacy inboxes, personal callbacks, and old routing rules; a shadow-queue study reconciles offered demand before leaders judge coverage.',
    published,sourceDate:published,image:'/research-aug20/absence-handoff-protocol.png',sources:[iso,privacy,csf],
    internalLinks:['/research','/services/operations-support','/blog/call-center-outsourcing-risk-register'],
    keyStats:['One customer request across all intake paths is the unit','Legacy and new queues are reconciled, not averaged','Unknown ownership remains a reportable state'],
    takeaways:['Inventory every permitted intake path before cutover.','Reconcile customer needs rather than comparing dashboard totals.','Close a legacy route only after its open promises have owners.'],
    faqs:[{question:'Is a shadow queue always unauthorized?',answer:'No. A temporary fallback may be intentional, but its purpose, owner, intake rule, and retirement condition should be explicit.'},{question:'Does matching total volume prove a clean transition?',answer:'No. The same total can hide duplicates, missed contacts, changed definitions, or work that never reached either measured queue.'}],
    serviceHandoff:{href:'/contact-us',label:'Map a reviewable transition lane',body:'Inventory one queue, its legacy paths, promises, and exception owners before changing routing.'},
    sections:[
      {heading:'Decision question and transition boundary',body:`When a company moves customer contact to an outsourced team, can leaders demonstrate that every in-scope request entered an owned path, or are legacy channels still carrying invisible demand? A shadow queue is any inbox, phone path, spreadsheet, personal callback list, portal view, integration retry, or informal message that continues to receive or retain work outside the declared operating queue. It may be an approved fallback, a forgotten route, or a temporary migration artifact. The unit of analysis is the customer need, not a ticket count. Preserve arrival channel, event time with offset, permitted linkage key, stated reason, prior promise, current system, current owner, migration state, duplicate status, final outcome, and uncertainty. The provider may classify and route work within approved rules. It should not merge identities from similar text, close a legacy record merely because a new ticket exists, or infer that silence means resolution. The client owns channel retirement, identity rules, material decisions, retention, and customer remedies. The operational question is whether continuity can be reconstructed without exposing unnecessary personal data.`},
      {heading:'Evidence basis and analytical inference',body:`ISO 18295-1 supports defined customer-contact processes, responsibilities, and attention to outcomes. NIST Cybersecurity Framework 2.0 supports governed assets, roles, detection of unexpected states, response, recovery, and improvement. The NIST Privacy Framework supports purpose-aware processing and proportionate linkage. Applied to transition work, those sources support a declared channel inventory, attributable state changes, bounded access, visible exceptions, and reconciliation. They do not say that one CRM is automatically authoritative or that two similar contacts represent one person. The research inference is that migration success must be tested across intake paths and promises, not inferred from the new platform's dashboard. A falling legacy count may mean successful retirement, broken access, changed labels, or customers abandoning that route. A rising new-queue count may reflect migration, duplicates, or new demand. Report these possibilities separately. Facts are the observed events and configured rules; analysis is the reconciliation; inference is the likely explanation; uncertainty remains explicit until an owner validates it.`},
      {heading:'Cohort construction and reconciliation method',body:`Freeze an observation window spanning a representative period before and after cutover. Inventory advertised and unadvertised routes with the people who operate telephony, email, chat, forms, CRM ingestion, and escalations. Export only approved fields. Build event groups with permitted identifiers, then sample ambiguous links manually without making free-text similarity the identity rule. Classify each need as new-only, legacy-only, present in both and safely linked, present in both but uncertain, transferred with accepted ownership, completed before transfer, or unresolved. Preserve the original timestamps and reasons. Reconcile totals from source systems to the analytical table and explain exclusions. Test cases that break easy assumptions: a delayed email enters after closure; a caller uses a different number; an integration retries; a manager keeps a private callback list; an old web form still confirms receipt; a customer raises two needs in one message; and an escalation stays in the legacy tool because the new role lacks authority. A second reviewer should trace samples in both directions—from sources to the table and from the table back to sources.`},
      {heading:'Measures, counterfactuals, and buyer decisions',body:`Useful measures include requests by intake path, linkage coverage, duplicate rate, unowned age, time to acknowledged ownership, promises carried forward, contacts requiring repeated explanation, unknown outcomes, and legacy traffic after the retirement notice. Show counts and denominators by day and reason. Do not combine waiting on a customer with waiting on an internal decision. Compare comparable intervals while documenting holidays, outages, campaign changes, and routing releases. A clean transition has no universal numerical threshold; evidence should support specific buyer decisions. If legacy-only demand persists, the buyer may keep monitored forwarding or correct public routing. If duplicates rise, it may add an idempotency check rather than coaching agents to work faster. If transferred items lack acceptance, it should repair ownership before expanding scope. If linkage is unsafe, it should improve approved identifiers rather than infer matches. The counterfactual question is not merely what volume would have occurred without outsourcing. It is which requests, promises, and exceptions would have been visible under the old and new designs and what evidence distinguishes improvement from a measurement change.`},
      {heading:'Implementation controls and worked failure path',body:`Before cutover, name every route, its authoritative owner, forwarding behavior, record retention, customer confirmation, monitored hours, and retirement condition. Create a bounded migration register for open work with the source reference, last verified state, customer promise, receiving owner, acceptance timestamp, and safe fallback. Restrict exports and delete working copies under policy. During cutover, reconcile daily and inspect the oldest unowned items, legacy-only arrivals, duplicate material actions, and failed integrations. Consider an order-status inbox that remains published on old receipts. Messages receive automated confirmations, but the outsourcing dashboard shows none. A customer follows up by phone; an agent creates a new case and sees no prior promise. The new queue's response time looks healthy while the actual journey contains delay and repetition. Correct classification is a legacy-only arrival linked under an approved rule to the later call, with the missed confirmation promise and current owner preserved. The remedy belongs to the authorized client owner. The evidence does not justify blaming either worker or declaring the new lane successful from dashboard timing alone.`},
      {heading:'Limitations and bounded conclusion',body:expandedLimits+` For this study, additional uncertainty comes from inaccessible personal worklists, inconsistent identifiers, customers who change channels, and legacy systems whose timestamps or exports are incomplete. A shadow-queue review can identify gaps and support corrective decisions, but it cannot recover contacts that left no record or prove customer sentiment from operational events. The bounded conclusion is that an outsourced transition becomes reviewable when offered demand, legacy paths, new paths, customer promises, and receiving ownership reconcile at the level of the customer need. Retirement is a controlled decision, not a date on a project plan. Leaders should require evidence that remaining routes are monitored or closed truthfully, that open promises have accepted owners, and that unknowns remain visible before they treat the transition as complete.`}
    ]
  },
  {
    slug:'philippines-call-center-weather-continuity-trigger-research',title:'Philippines Call Center Weather Continuity Triggers: Evidence Before Coverage Claims',
    excerpt:'A weather continuity plan should connect authoritative advisories, worker-safety decisions, site conditions, queue promises, and fallback ownership without turning a forecast into an automatic staffing instruction.',published,sourceDate:published,
    image:'/research-aug21/after-hours-safety-escalation.png',sources:[pagasa,dole,iso,csf],internalLinks:['/research','/services/customer-support','/blog/call-center-outsourcing-risk-register'],
    keyStats:['One service interval and affected operating site is the unit','Weather signal and management decision stay separate','Customer fallback has a named owner'],takeaways:['Use authoritative advisories as inputs, not automatic work orders.','Protect worker decisions from customer queue pressure.','Publish only coverage promises the fallback can sustain.'],
    faqs:[{question:'Does a storm signal determine whether a team must work?',answer:'No. Authorized employers and safety owners apply current law, official advisories, site conditions, and policy; a customer-service plan should not replace that decision.'},{question:'Is remote work automatically a continuity solution?',answer:'No. Power, connectivity, safe location, equipment, access, privacy, and supervision must all be assessed.'}],
    serviceHandoff:{href:'/contact-us',label:'Map a safe coverage fallback',body:'Define one queue’s customer promise, monitoring trigger, safety owner, and alternate route without predetermining employment decisions.'},
    sections:[
      {heading:'Research question and strict safety boundary',body:`How can a buyer evaluate Philippines-based call-center continuity during severe weather without asking a provider to make unsafe, unlawful, or unsupported staffing promises? The unit is one service interval at an affected operating site linked to authoritative weather information, local conditions, management decisions, available systems, actual staffing state, offered demand, customer promise, fallback route, and final outcome. PAGASA information is an evidence input, not an instruction from the client to individual workers. The employer and its authorized safety and labor owners decide suspension, evacuation, remote work, pay, transport, and return under current law and policy. Frontline workers should never be asked to interpret meteorological data or trade personal safety for a service level. A buyer may define customer communications, priority reasons, minimum safe system controls, and fallback ownership. It should not require attendance based on a forecast label, infer safe travel from connectivity, penalize people through a customer dashboard, or describe nominal roster capacity as available coverage. This boundary is essential to the integrity of the study.`},
      {heading:'Primary sources, facts, and inference',body:`PAGASA is the Philippines' national meteorological and hydrological service and publishes tropical-cyclone information. Department of Labor and Employment advisory pages publish current labor guidance, including weather-disturbance and worker-protection topics. ISO 18295-1 supports defined customer-contact responsibilities and outcomes. NIST Cybersecurity Framework 2.0 supports governed continuity, communication, response, recovery, and learning. The factual layer records what each authoritative source stated at a particular time and what the site or systems actually experienced. The decision layer records what an authorized employer or client owner decided. The analytical layer compares the plan with observed coverage and customer outcomes. These sources do not guarantee the conditions at a worker's location, prescribe one cross-company staffing response, or permit a client to override employment and safety obligations. The operational inference is narrower: truthful customer coverage depends on timely decisions, protected people, tested alternate routes, and visible capacity, not on a generic claim that a distributed team is disaster proof.`},
      {heading:'Event study and evidence collection',body:`Choose a bounded event window and identify operating sites, queues, hours, and customer-impact classes before analysis. Capture advisories with issue times, source URLs, and later updates; do not overwrite earlier states. Record authorized operational decisions and their effective times without collecting worker medical or household details. Observe site power, approved connectivity, telephony, VPN or application availability, supervisor coverage, accepted work, offered contacts, abandoned contacts, backlog, urgent escalations, public messages, and fallback activation. Distinguish planned closure, safety hold, unavailable systems, reduced capacity, demand surge, and customer-channel failure. Test the plan with exercises as well as actual events, because severe incidents are infrequent and non-comparable. Challenge scenarios should include rapidly changing forecasts, a site outside the main impact area losing power, a worker appearing online from an unsafe setting, an alternate vendor lacking current scripts, two sites sharing one telecom dependency, and recovery that restores login before quality review or escalation ownership. Review only aggregated, necessary operational evidence.`},
      {heading:'Measures that do not reward unsafe behavior',body:`Measure decision latency from an authoritative trigger to an authorized recorded decision, but never turn that interval into an individual worker score. Report the share of customer traffic covered by a tested fallback, successful routing, system availability by required function, supervisor and exception-owner coverage, urgent contacts protected, oldest unresolved promise, message accuracy, and time to stable recovery. Show unknowns and failed tests. An answer rate during disruption can be misleading if workers lack safe access to records or escalation owners. Remote login volume does not demonstrate safe or sustainable capacity. A low backlog can result from intake failure. Compare planned versus actual service states and inspect high-impact customer paths individually. Buyer decisions might include narrowing contact reasons, changing public hours, pausing outbound activity, shifting only low-risk work, or activating another approved site. Employment decisions remain with the authorized employer. The correct plan makes a reduced promise early rather than maintaining a full promise on paper while workers and customers absorb hidden risk.`},
      {heading:'Scenario analysis and continuity controls',body:`Suppose PAGASA issues evolving information for a tropical cyclone while the primary site still has power. The client dashboard remains green, but travel risk and local conditions lead the authorized employer to suspend on-site work. Some approved remote workers can connect; the voice platform works, yet the order system and escalation manager are unavailable. A plan based only on login counts would claim coverage. A truthful plan marks the lane reduced, limits work to requests that can be completed safely, routes high-impact exceptions to a named alternate owner, updates customer messaging, and preserves unanswered demand. Controls should include source monitoring by a named role, decision authority, contact trees, tested routing, least-privilege alternate access, current scripts, customer-impact priorities, status-page ownership, recovery checks, and post-event review. Exercises must verify actual call flows and system permissions, not just phone numbers on a document. No fallback should depend on a worker exposing family circumstances or using an unapproved device, network, or local copy of customer data.`},
      {heading:'Limitations and conclusion',body:expandedLimits+` Weather events vary sharply by location and time, while advisories can change faster than a scheduled report. Operational records may not capture local safety, transport, or household conditions and should not attempt to do so. This method cannot tell an employer whether an individual should work, calculate legal pay, or promise that a secondary site will remain available. It can test whether customer commitments change when verified capacity changes and whether the fallback preserves safe ownership. The bounded conclusion is that Philippines coverage is resilient when authoritative information reaches authorized decision makers, workers are protected from customer-service pressure, alternate routes are technically and operationally tested, reduced states are communicated truthfully, and recovery includes quality and exception ownership. A weather label alone proves none of those conditions.`}
    ]
  },
  {
    slug:'call-center-ai-response-assist-override-research',title:'AI Response Assist in Outsourced Call Centers: Override and Evidence Design',
    excerpt:'Response assist should be evaluated as a recommendation system whose source, version, worker action, customer impact, and override path remain observable—not as an invisible author of approved answers.',published,sourceDate:published,
    image:'/blog-aug23/outsourced-call-center-knowledge-change-notice.png',sources:[ai,privacy,csf,iso],internalLinks:['/research','/services/omnichannel-customer-support','/blog/outsourced-call-center-quality-review-cadence'],
    keyStats:['One suggestion-to-customer decision is the unit','Generated text and approved policy remain distinct','Overrides and abstentions are first-class outcomes'],takeaways:['Define where assistance may appear and where it must abstain.','Keep source authority and human accountability visible.','Sample accepted, edited, rejected, and missing suggestions.'],
    faqs:[{question:'Does human review make every AI-assisted reply safe?',answer:'No. Review quality depends on time, authority, source access, interface design, training, and the consequence of the decision.'},{question:'Should acceptance rate be the main success metric?',answer:'No. High acceptance can reflect useful help, automation bias, weak review, or narrow cases; connect it to correctness and customer outcomes.'}],
    serviceHandoff:{href:'/contact-us',label:'Define a bounded assisted-response lane',body:'Start with one low-risk reason, approved sources, abstention rules, review evidence, and a named exception owner.'},
    sections:[
      {heading:'Decision question and unit of analysis',body:`When an outsourced representative sees an AI-generated summary, classification, search result, or proposed reply, what evidence lets a buyer decide whether the assistance improved a customer interaction without weakening responsibility? The unit is one suggestion-to-decision event linked to use case, model or service version, prompt or configured instruction where retention is permitted, retrieved source identifiers, source versions, confidence or abstention state if available, displayed output, worker acceptance or edit, final customer-facing content, material action, later correction, and accountable owner. The public customer record need not expose internal prompts, and analytical exports should minimize personal data. The provider may use the tool inside an approved lane and stop when evidence is insufficient. It should not present generated text as policy, invent a refund or eligibility decision, conceal uncertainty, copy secrets into an external system, or blame a worker for overriding a suggestion. The client owns approved sources, action authority, prohibited uses, monitoring, remedy, and deployment decisions.`},
      {heading:'Source basis and separation of claims',body:`NIST AI RMF 1.0 describes voluntary risk-management outcomes organized around govern, map, measure, and manage, with attention to trustworthy characteristics across the lifecycle. The NIST Privacy Framework supports purpose-aware data processing and risk communication. NIST Cybersecurity Framework 2.0 supports governed assets, access, monitoring, response, and recovery. ISO 18295-1 contributes the customer-contact process and outcome context. These are framework facts. The analysis is that response assistance needs a defined use context, accountable roles, valid source material, testing, monitoring, incident handling, and change control. The inference is that a tool may reduce search effort in some cohorts while increasing confident error or disclosure risk in others. None of the sources certify a particular model, guarantee factuality, or make human presence an adequate control by itself. Report product behavior observed in the declared configuration and period. Separate vendor claims, test findings, live observations, reviewer judgments, and unresolved uncertainty.`},
      {heading:'Evaluation design across suggestion outcomes',body:`Map each use case before testing: summarization, intent classification, knowledge retrieval, response drafting, translation, sentiment cues, or next-action recommendation have different failure modes. Define prohibited data and decisions. Build a representative set containing ordinary requests, ambiguous wording, outdated articles, conflicting sources, multilingual or accessibility needs, prompt injection attempts, high-impact exceptions, and cases where abstention is correct. Use authorized synthetic or de-identified material where possible. In live sampling, include suggestions that were accepted unchanged, edited, rejected, unavailable, or not shown. Compare final responses with the authoritative source and the worker's actual authority. Have qualified reviewers label source support, scope, privacy, promise accuracy, tone only where operationally defined, and customer-impact severity. Record disagreement instead of forcing consensus. Re-run a stable test set after model, retrieval, instruction, or knowledge changes. Because outputs can vary, preserve configuration and repeated trials sufficient to characterize variation without claiming deterministic replication.`},
      {heading:'Metrics, automation bias, and interpretation',body:`Report source-supported response rate, unsupported claim rate, material-error rate, appropriate abstention, retrieval miss, stale-source use, prohibited-data event, worker edit and rejection patterns, review time, correction, repeat contact, escalation, and unknown outcome. Segment by use case and impact; an average can hide rare severe errors. Acceptance rate is not accuracy. Low edit distance is not evidence that the answer was right. Faster handle time can coexist with more repeat contacts or corrections. Compare assisted and unassisted cohorts only when case mix, worker experience, queue pressure, source access, and observation windows are sufficiently comparable. Watch for automation bias through errors accepted despite accessible contradictory evidence, but do not infer a worker's mental state from a click. Interface placement, time pressure, and policy may shape behavior. Review whether overrides are easy, non-punitive, and routed to improve the source or configuration. A useful system expands evidence access while preserving the worker's ability to pause and the client's responsibility for policy.`},
      {heading:'Controls and a worked high-impact example',body:`Governance should name the business owner, technical owner, data owner, quality reviewer, incident route, and customer-remedy owner. Maintain a use-case register, data-flow map, approved-source list, retention rule, version history, access controls, evaluation set, release gate, monitoring thresholds, kill switch, and rollback record. Show source links and effective dates where the interface allows. Force abstention or escalation for unsupported material actions. Consider a collections reminder where the assistant drafts that payment is overdue and threatens a consequence, although the source record shows a pending dispute. A fluent reply and fast acceptance do not convert the claim into fact. The safe design surfaces the dispute, blocks unapproved consequence language, and routes the decision to the authorized owner. Review must preserve the generated suggestion, final message, source state, and correction without exposing the customer in a broad QA export. The lesson is specific: evidence and authority must travel with the suggestion at the moment of decision.`},
      {heading:'Limitations and bounded conclusion',body:expandedLimits+` AI evaluation also faces output variability, opaque provider changes, incomplete logs, reviewer disagreement, and rapid knowledge updates. A bounded test cannot demonstrate safety for unseen languages, rare requests, adversarial inputs, or new configurations. Operational correlation cannot prove that assistance caused a customer outcome. The conclusion is therefore conditional: response assist can support an outsourced lane only when its purpose, data boundary, sources, versions, abstention behavior, worker choices, final actions, and exceptions remain reviewable. Human review is a role with time, evidence, authority, and a safe override—not a label placed after generation. Buyers should expand only after the evidence is adequate for the next specific use case.`}
    ]
  },
  {
    slug:'call-center-low-frequency-critical-contact-qa-research',title:'Low-Frequency Critical Contacts in Call Center QA: A Sampling Framework',
    excerpt:'Random quality samples can miss rare contacts with severe customer consequences; a defensible program combines representative sampling with a separately governed risk-triggered review.',published,sourceDate:published,
    image:'/research-aug21/qa-sample-representativeness.png',sources:[iso,csf,privacy],internalLinks:['/research','/services/reporting-and-qa','/blog/outsourced-call-center-quality-review-cadence'],
    keyStats:['Routine performance and critical risk use distinct samples','Selection rules are versioned before review','Detection rate is never presented without coverage'],takeaways:['Keep representative and risk-triggered findings separate.','Define critical contact triggers with inclusion examples.','Measure what the selection process could not observe.'],
    faqs:[{question:'Why not put all critical contacts into the random sample?',answer:'Rare cases may still be missed, and oversampling changes interpretation; use a separate transparent stratum and report its denominator.'},{question:'Does a triggered review prove an error occurred?',answer:'No. A trigger identifies a case for review; the evidence and authorized standard determine the finding.'}],
    serviceHandoff:{href:'/contact-us',label:'Design a risk-aware QA sample',body:'Define one queue’s ordinary frame, critical triggers, reviewer authority, and corrective-action owner before scoring.'},
    sections:[
      {heading:'The sampling problem and decision boundary',body:`A buyer wants quality assurance to describe ordinary service and still detect rare contacts involving safety, payment, identity, accessibility, threats, serious complaints, or irreversible account changes. A small simple random sample may represent common work while containing none of these cases. A sample chosen only from alerts may find problems but cannot describe overall performance. The unit is one eligible customer contact linked to the sampling frame, selection path, trigger state, approved standard version, reviewer evidence, finding, severity, disagreement, corrective decision, and follow-up. The provider may review work under defined access and route critical findings. It should not search private data without purpose, treat an alert as guilt, change the denominator after seeing results, or rank workers on incomparable case mixes. The client owns critical definitions, review authority, remedies, and policy changes. The method therefore maintains two complementary views: a probability-based sample for ordinary process estimates and a separately reported risk-triggered stratum for specified high-impact conditions.`},
      {heading:'Evidence foundation and statistical caution',body:`ISO 18295-1 supports defined customer-contact processes, monitoring, responsibilities, and service outcomes. NIST Cybersecurity Framework 2.0 supports risk governance, detection, response, recovery, and learning. The NIST Privacy Framework supports proportionate data use and privacy-risk management. These sources justify explicit objectives, bounded access, accountable review, and corrective action, but they do not specify a universal sample size, error taxonomy, or severity threshold. Basic sampling logic adds an important analytical fact: an event can be absent from a small sample even when it exists in the population. Risk-based oversampling improves exposure to selected cases but changes prevalence; results must be weighted or reported separately if leaders want a population estimate. The editorial inference is that one blended quality score is unsuitable for both routine estimation and critical-case assurance. Facts include frame size, selection probability, records reviewed, and confirmed findings. Reviewer interpretation and causal claims about why an error occurred require separate evidence.`},
      {heading:'Build the frame before selecting records',body:`Define the queue, channels, time period, eligible states, exclusions, and authoritative record before drawing a sample. Reconcile the frame to offered and handled volumes so missing channels are visible. Stratify ordinary sampling when shifts, languages, contact reasons, or channels differ materially, and record selection probabilities. Independently define risk triggers using observable events: selected disposition codes, transfer destinations, material actions, complaint markers, failed authentication followed by a change, payment-data alerts, or reopened high-impact cases. Include examples and exclusions; version the rule. Test false positives and false negatives against a qualified manual sample. Preserve a route for concerns that automated fields cannot detect. Reviewers should see the minimum necessary evidence and should not know worker identity when it is irrelevant. Re-review a subset for agreement, retaining disagreement categories. Never quietly replace unavailable recordings with easier cases. Record inaccessible, corrupted, or consent-restricted items as coverage limitations.`},
      {heading:'Reporting without a misleading composite score',body:`For the representative sample, report frame coverage, sample counts, selection design, finding rates with uncertainty appropriate to the design, reviewer agreement, and missing evidence. For the triggered stratum, report trigger volume, reviewed share, confirmed and unconfirmed findings, severity, time to containment, and false-trigger evidence. Do not combine the two into a single pass rate unless the weighting and decision purpose are explicit. Track repeat occurrence after correction, but distinguish policy ambiguity, system design, source defects, training gaps, capacity pressure, and individual execution only when evidence supports the category. A zero critical finding count is not proof of safety when triggers cover little of the relevant population. A rising triggered count can reflect better detection rather than worse work. Managers should inspect the denominator, rule changes, and customer impact before acting. Corrective actions can include source repair, interface controls, narrower authority, coaching, staffing, or escalation coverage; the data does not predetermine which response is appropriate.`},
      {heading:'Worked example and governance controls',body:`Imagine an order-support queue where address changes are rare but can redirect valuable shipments. A two-percent random sample contains no address changes for several weeks, so the general score looks strong. A risk stratum selects every address-change disposition plus a sample of shipments rerouted without that disposition. Review finds some valid changes, one duplicate system event, and one change made after incomplete verification. The trigger did not prove misconduct; it made a critical pathway observable. The client contains the affected case, reviews customer remedy, corrects the permission rule, and checks whether the interface allowed the action too early. Governance controls include a sampling charter, frame reconciliation, versioned triggers, reviewer qualification, evidence access limits, severity definitions, disagreement resolution, urgent escalation, non-retaliatory error reporting, corrective-action ownership, and periodic trigger retirement. A second reviewer verifies critical findings before consequential personnel use unless immediate customer protection requires faster containment.`},
      {heading:'Limitations and conclusion',body:expandedLimits+` Critical-event labels may be missing, incorrectly entered, or changed by the same process under review. Recordings can be unavailable, and privacy or consent rules may restrict review. Rare-event estimates have wide uncertainty, while detection rules can create selection bias. This framework cannot infer intent or individual competence from one contact. Its bounded conclusion is that credible QA uses an honest representative view for routine performance and a transparent, separately governed risk view for low-frequency critical work. Leaders should know what entered each frame, what remained unobservable, how reviewers applied the current standard, and who owns customer protection and systemic correction. A polished aggregate score is weaker evidence than a sampling design whose blind spots are visible.`}
    ]
  },
  {
    slug:'outsourced-call-center-knowledge-retrieval-zero-result-research',title:'Zero-Result Knowledge Searches in Outsourced Support: A Demand Signal Study',
    excerpt:'A zero-result search may reveal missing language, the wrong vocabulary, access limits, stale indexing, or an out-of-scope request; it should be studied before leaders conclude that agents ignored guidance.',published,sourceDate:published,
    image:'/research-aug20/knowledge-article-retirement.png',sources:[iso,privacy,csf],internalLinks:['/research','/services/tier-one-technical-support','/blog/outsourced-call-center-source-of-truth-map'],
    keyStats:['One search within one customer task is the unit','No result and no useful result remain distinct','Search logs are minimized and access controlled'],takeaways:['Link searches to task outcomes without storing unnecessary customer text.','Test vocabulary, permissions, indexing, and scope separately.','Give recurring gaps a content or policy owner.'],
    faqs:[{question:'Does a zero-result search prove an article is missing?',answer:'No. The query may use different language, the index may fail, access may be restricted, or the request may be outside approved scope.'},{question:'Should raw customer text be copied into analytics?',answer:'Not by default. Use minimized, approved fields and redact or transform sensitive content under the organization’s policy.'}],
    serviceHandoff:{href:'/contact-us',label:'Map a governed knowledge lane',body:'Review one reason family from search through customer outcome, with approved query handling and a named content owner.'},
    sections:[
      {heading:'Question, definitions, and privacy boundary',body:`What can zero-result and no-useful-result searches tell a buyer about readiness for outsourced support? A zero result means the configured search returned nothing. A no-useful-result event means results appeared but the worker could not safely use them for the customer task. These states are not interchangeable. The unit is one search within one task linked through approved, non-sensitive identifiers to query features, locale, filters, worker permissions, index version, returned document identifiers, selections, later searches, source consulted, customer action, escalation, and outcome. Raw queries may contain names, account details, health facts, payment information, or secrets; collection must be minimized, protected, and purpose-bound. The provider may flag gaps and use approved alternatives. It should not paste customer text into an uncontrolled tool, invent an answer, bypass access restrictions, or treat search failure as permission to change policy. The client owns authoritative content, access, prohibited data, scope, publication, and exception decisions.`},
      {heading:'Standards basis and competing explanations',body:`ISO 18295-1 supplies a customer-contact process and outcome lens. NIST Cybersecurity Framework 2.0 supports governance of information assets, access, monitoring, incident response, recovery, and improvement. The NIST Privacy Framework supports purpose-aware processing and proportionate treatment of personal data. Applied carefully, these sources support controlled knowledge ownership, access appropriate to the task, observable failures, protected logs, and correction. They do not state that every request needs an article or that a search click proves comprehension. At least five explanations compete when no useful answer appears: required content is absent; the article exists under different vocabulary; indexing or filters fail; the worker lacks appropriate access; or the request is outside scope and should route elsewhere. Additional possibilities include stale content being correctly rejected and ambiguous customer intent. The study should test these explanations rather than report all failures as a training deficit or all frequent queries as demand for publication.`},
      {heading:'Cohort method and query minimization',body:`Select a reason family, channels, languages, search interface, and observation period. Record system and index releases. Define search sessions by task rather than by an arbitrary short timeout, while preserving uncertainty when linkage is unavailable. Transform or classify queries under approved rules so analysts can study vocabulary without retaining unnecessary customer language. Sample zero results, results with no selection, selected results followed by another search, escalations after search, and successful first searches. Observe outcomes through source use and customer task state, not just clicks. Conduct controlled tests with approved phrases, synonyms, misspellings, product terms, and natural customer language. Test permissions using designated accounts, never borrowed credentials. Challenge cases include an article visible to supervisors but not agents, a recently published page absent from the index, an obsolete page ranking first, a multilingual query mapped incorrectly, and a legitimate request for which policy requires escalation rather than an answer. Have content and operations reviewers label causes independently.`},
      {heading:'Measures and demand interpretation',body:`Report sessions, tasks, zero results, no-useful-result classifications, query reformulation, successful source use, escalation, repeat contact, content gap, vocabulary mismatch, indexing fault, access fault, out-of-scope need, obsolete result, and unknown cause. Include denominators and protected cohorts. Measure time from confirmed content gap to owner acceptance and from approved correction to verified search behavior. Do not optimize zero-result rate alone: a system that returns irrelevant pages for everything can produce zero zero-results and still fail customers. Click-through can rise because workers are checking multiple bad results. A new article can fragment authority if an existing source should instead gain synonyms or clearer scope. Repeated out-of-scope searches may justify routing or customer messaging, not new frontline authority. Buyer decisions should connect the observed cause to a controlled response: content creation, metadata repair, indexing repair, permission correction, interface change, playbook clarification, or an explicit escalation lane.`},
      {heading:'Worked trace and operating controls',body:`Consider a technical-support queue receiving questions about account recovery. Searches for customer phrases return nothing, while an approved article titled with an internal term exists and is visible only to a different role. Some workers improvise; others escalate. The evidence shows both vocabulary and access defects, but access may be intentionally restricted because the article includes steps outside tier-one authority. The correct response is not automatic permission expansion. The owner can create a tier-one decision page with safe recognition cues and an explicit handoff, add approved synonyms, and verify the index. Controls should assign article owners, approvers, effective dates, review dates, scope labels, permitted audiences, supersession links, change logs, index monitoring, safe feedback capture, and an urgent route for harmful content. Search analytics access should be limited, retained under policy, and reviewed for prohibited data. A correction is complete only after the intended role can retrieve the current safe answer and the old result no longer competes.`},
      {heading:'Limitations and conclusion',body:expandedLimits+` Search logs observe typed behavior, not the full customer need or the worker's reasoning. Privacy controls may intentionally reduce analytical detail. Session linkage can be incomplete, and interface changes can shift behavior without changing demand. A content update may coincide with training, routing, or seasonality. The study cannot prove that a query phrase represents market demand or that a missing article caused a customer outcome. Its bounded conclusion is that zero-result evidence is useful when studied as part of a governed task trace. The buyer should distinguish absence, discoverability, indexing, permission, freshness, and scope; protect query data; assign each confirmed gap; and verify the correction in the actual role. The goal is not maximum search success. It is dependable access to the right approved answer and a safe, visible path when no such answer should exist.`}
    ]
  }
];
