import type {ResearchPost} from './fleet-data';
import {september28Cala105ResearchBatch as prior} from './research-sep28-cala105.ts';

const published='2026-10-02'; // reconcile to the actual first-live date before the combined push
const iso={name:'ISO 18295-1:2017, Customer contact centres',url:'https://www.iso.org/standard/64739.html'};
const privacy={name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'};
const csf={name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'};

export const october2Cala106ResearchBatch:readonly ResearchPost[]=[
  {
    slug:'inbound-call-abandonment-callback-offer-research',
    title:'Callback Offers and Inbound Call Abandonment: An Evidence Framework',
    excerpt:'A callback offer can reduce time on hold, but only a linked record of consent, queue position, customer time zone, attempted contact, and final ownership can show whether it resolved demand or merely renamed abandonment.',
    published,
    sourceDate:published,
    image:'/research-aug21/callback-timezone-integrity.png',
    sources:[iso,privacy,csf],
    internalLinks:['/research','/services/inbound-call-handling','/blog/inbound-call-volume-forecasting'],
    keyStats:['One offered inbound contact is the unit of analysis','Queue exit and callback completion are separate events','Unknown outcomes remain visible'],
    takeaways:['Do not classify acceptance of a callback as resolution.','Preserve the customer-local promise and the queue conditions at offer time.','Give every failed or disputed callback a named next owner.'],
    faqs:[
      {question:'Does a callback offer always improve customer experience?',answer:'No. The result depends on truthful timing, customer choice, successful contact, continuity of context, and whether the original need is actually resolved.'},
      {question:'Should an accepted callback disappear from abandonment reporting?',answer:'No. Report the original queue exit and the later callback outcome separately so managers can distinguish demand, waiting behavior, attempted recovery, and completed service.'}
    ],
    serviceHandoff:{href:'/contact-us',label:'Design an accountable inbound callback lane',body:'Start with one queue, define the promise and failure path, and review linked queue and callback evidence before expanding.'},
    sections:[
      {heading:'Decision question and operating boundary',body:'When does an offered callback represent a dependable alternative to waiting, and when does it simply move an unresolved inbound contact out of the visible queue? The unit of analysis is one offered inbound contact linked to arrival time, configured queue, estimated wait shown or spoken to the customer, offer wording and version, customer choice, permitted callback number, customer-local time zone, promised window, retained or released queue position, attempt events, authentication state, conversation outcome, disposition, repeat contact, and next owner. These fields should remain connected without treating a telephone number as identity proof or copying unnecessary customer data into a reporting file. The provider may present client-approved choices, record the customer’s selection, make an attempt inside a defined operating window, restore supplied context, and route exceptions. It should not claim that accepting the offer resolves the request, silently reset priority, conceal a failed attempt, expose sensitive context in voicemail, or close the case because a dial event occurred. The client owns offer eligibility, queue priority, retry policy, authentication, recording and consent rules, hours, remedies, and exceptions. The research question is therefore narrower than whether callbacks are good: it asks whether each customer promise can be reconstructed from observable events and whether the final state is truthful.'},
      {heading:'Primary-source basis and careful interpretation',body:'ISO 18295-1 provides a customer-contact-centre frame for service requirements, customer experience, processes, people, and performance. The NIST Privacy Framework supports purpose-aware data processing, proportionate collection, governance, and communication about privacy risk. NIST Cybersecurity Framework 2.0 supports governed roles, protected information, detection of unexpected states, response, recovery, and improvement. Together, these sources support a defined callback purpose, minimized contact data, attributable events, protected access, a visible exception path, and review against the customer outcome. They do not prescribe a universal wait threshold, prove that a callback number belongs to the caller, determine whether consent is legally sufficient, or declare one retry pattern appropriate for every service. They also do not make an estimated wait a guaranteed promise. That distinction matters because a technically successful dial can still be an operational failure: the call may arrive outside the stated local window, reach another person, omit the original context, disconnect before an agent accepts it, or produce a second queue journey. Conversely, an unanswered attempt may have followed the approved process while leaving the need unresolved. Reporting must keep process conformance, contact success, customer effort, and resolution separate rather than compressing them into one callback completion percentage.'},
      {heading:'Cohort design, event linkage, and counterexamples',body:'Choose a declared queue, offer configuration, and observation window before extracting records. Include contacts that accepted, declined, ignored, or never received the offer, along with ordinary answered and abandoned contacts needed to understand selection effects. Freeze the definitions used during the period. Link events using approved operational identifiers rather than names, free-text similarity, or shared telephone numbers. Preserve event timestamps with offsets and distinguish offer time, queue-exit time, scheduled time, dial time, agent-accept time, customer-answer time, and final-update time. Stratify results by interval, stated wait band, language, routing path, customer-local window, retained-position rule, attempt result, and impact of the underlying request. Test counterexamples explicitly: a customer accepts but calls again before the callback; a dialer connects to voicemail and marks success; an agent receives the callback without the IVR reason; the customer answers but cannot complete authentication; a callback crosses midnight or daylight-saving boundaries; the queue recovers before the promised attempt; two requests share one number; a network retry creates duplicate calls; and a high-impact contact is offered a lane that lacks the required authority. Compare queue events, callback platform events, telephony disposition, approved recording or transcript evidence where permitted, case history, repeat-contact evidence, and receiving-owner acknowledgment. Do not infer customer satisfaction from silence or infer causal improvement from a before-and-after average without accounting for demand mix, staffing, outages, and self-selection.'},
      {heading:'Measures that preserve the customer journey',body:'Report offered, accepted, declined, ordinary answered, ordinary abandoned, callback attempted, callback connected, authenticated where required, request completed, transferred, repeat-contacted, failed, cancelled, duplicate, and unknown states separately. Pair counts with denominators and a declared observation period. Useful intervals include time from acceptance to first valid attempt, deviation from the customer-local promise, time from connection to an authorized owner, and time to final known outcome. A queue-exit rate answers a different question from resolution. A dialer connection rate answers a different question from speaking with the intended customer. A low average can hide a long tail of missed high-impact promises, so show distributions or bands and inspect exceptions. Maintain a reconciliation table in which every accepted offer reaches exactly one current state, while allowing later events to change that state without erasing history. If identifiers cannot be linked safely, classify the outcome as unknown rather than joining records speculatively. Review repeat contacts as evidence of possible unresolved demand, not automatic proof that the callback failed, because customers may have a second need. The strongest operational view follows the promise from the original arrival through a final owner and keeps uncertainty measurable.'},
      {heading:'Failure modes, controls, and replication record',body:'Common failure modes include removing accepted offers from abandonment counts without a companion outcome; starting the clock at dial time; using server time instead of the customer-local promise; marking voicemail, busy, or no-answer as completed service; discarding the original routing context; exposing account details before authentication; allowing parallel queue and callback work to trigger duplicate actions; and closing records after the configured retry limit with no accountable owner. Controls should make these states visible. Version the offer wording and eligibility rule. Record whether queue position is retained. Protect callback numbers and restrict exports. Use neutral voicemail text. Pass only necessary context to the accepting worker. Require an idempotency or conflict check before a material account action. Route missed high-impact promises to a named client owner, and define when callback offers pause during outages or capacity loss. For replication, record the query window, systems consulted, event definitions, exclusions, linkage success, unknown count, reviewer, and source access date. Have a second reviewer trace a sample from arrival through final status and challenge any state inferred from one system alone. This observational method can reveal broken promises, missing links, and misleading classifications. It cannot by itself prove that callbacks caused a change in satisfaction, determine a legal consent rule, or set the correct staffing plan. Those decisions require the actual jurisdiction, contract, customer population, risk, and client policy.'},
      ...prior[0].sections.slice(5)
    ]
  }
];
