import type {ResearchPost} from './fleet-data';
const published='2026-10-09';
const image='/research-aug20/knowledge-article-retirement.png';
const sources=[
  {name:'ISO 18295-1:2017, Customer contact centres',url:'https://www.iso.org/standard/64739.html'},
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
  {name:'NIST Digital Identity Guidelines, SP 800-63-4',url:'https://pages.nist.gov/800-63-4/sp800-63.html'},
  {name:'FTC Telemarketing Sales Rule',url:'https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule'}
];
type Draft={slug:string;title:string;question:string;unit:string;example:string;links:string[]};
const drafts:Draft[]=[
  {slug:'callcenteroutsourced-queue-wait-state-evidence-study',title:'Outsourced Call Center Queue Wait-State Evidence Study',question:'whether waiting reasons explain queue age in a bounded outsourced call center workflow',unit:'whether waiting reasons explain queue age in a bounded outsourced call center workflow',example:'A callback list shows an attempt within the service window, but the customer-local window had passed and the unverified voicemail could not resolve the request.',links:['/research','/services/operations-support','/blog/outsourced-call-center-callback-ownership-ledger']},
  {slug:'callcenteroutsourced-reviewer-agreement-reliability-study',title:'Outsourced Call Center Reviewer Agreement Reliability Study',question:'whether reviewers reproduce the same conclusion in a bounded outsourced call center workflow',unit:'whether reviewers reproduce the same conclusion in a bounded outsourced call center workflow',example:'Search ranks a retired return rule above its replacement because the old page remains indexed for a common customer phrase.',links:['/research','/services/tier-one-technical-support','/blog/call-center-knowledge-article-expiry-queue']},
  {slug:'callcenteroutsourced-minimum-access-effectiveness-study',title:'Outsourced Call Center Minimum Access Effectiveness Study',question:'whether permissions are sufficient but bounded in a bounded outsourced call center workflow',unit:'whether permissions are sufficient but bounded in a bounded outsourced call center workflow',example:'A complaint moves between support, billing, and operations while each status shows transferred and no role owns the promised update.',links:['/research','/services/customer-support','/blog/outsourced-call-center-complaint-update-clock']},
  {slug:'callcenteroutsourced-handoff-completeness-observation',title:'Outsourced Call Center Handoff Completeness Observation',question:'whether a receiving team can continue without private clarification in a bounded outsourced call center workflow',unit:'whether a receiving team can continue without private clarification in a bounded outsourced call center workflow',example:'A quality role retains download permission for an unrelated queue after moving to a narrower client assignment.',links:['/research','/services/reporting-and-qa','/blog/call-center-recording-access-review']},
  {slug:'callcenteroutsourced-control-change-traceability-research',title:'Outsourced Call Center Control Change Traceability Research',question:'whether operating changes remain attributable and reversible in a bounded outsourced call center workflow',unit:'whether operating changes remain attributable and reversible in a bounded outsourced call center workflow',example:'Wrap time falls after a generic disposition is introduced, while reopened contacts reveal missing next-action ownership.',links:['/research','/services/reporting-and-qa','/blog/outsourced-call-center-after-call-work-sampling']}
];
const limits='This documentary study is not a controlled experiment, legal opinion, vendor ranking, or universal service benchmark. Public frameworks state broad outcomes and control questions; they do not prescribe one staffing ratio, service level, customer remedy, access model, or contractual allocation. Local policy, systems, jurisdictions, contracts, languages, customer populations, missing records, changed routing, and reviewer judgment can alter the correct design. Correlation does not establish causation. Small or risk-selected samples cannot be generalized automatically. Definitions, exclusions, system versions, source access dates, reviewer roles, unresolved evidence, and privacy constraints must be preserved so another authorized reviewer can understand what was and was not observed. Operational records may omit contacts that abandoned early, moved to another channel, stayed in a personal worklist, or could not be linked under approved privacy rules. Recording or transcript availability can vary by channel, jurisdiction, consent, retention, and technical failure. Customers who contact repeatedly are not interchangeable with unique customers, and a reopened case may reflect a new need rather than a failed first response. Queue mix, campaigns, outages, holidays, policy releases, staffing changes, and integration retries can shift the apparent result. Any comparison should therefore disclose coverage, denominators, missingness, uncertainty, and concurrent changes. When those facts are unavailable, the report should narrow its claim and identify the owner who can decide whether more evidence is proportionate.';
const october9EvidenceNote="This October 9 control starts from one bounded observation, preserves missing evidence as missing, and keeps the consequential decision with the named accountable owner.";
const make=(d:Draft):ResearchPost=>({slug:d.slug,title:d.title,excerpt:`A source-backed method for testing ${d.question}.`,published,sourceDate:published,updated:published,image,sources,internalLinks:d.links,keyStats:['5 authoritative public sources','1 bounded customer-contact trace','0 claimed provider outcomes'],takeaways:['Freeze the unit and sources before observation.','Keep facts, actions, decisions, and outcomes distinct.','Use findings to repair a named control rather than score a person.'],faqs:[{question:'What is the observation unit?',answer:`The proposed unit is ${d.unit}.`},{question:'Does this establish causation?',answer:'No. It is a bounded descriptive observation informed by documentary synthesis.'},{question:'Who retains consequential decisions?',answer:'Authorized client owners retain policy, customer remedy, access, privacy, security, legal, and irreversible decisions.'}],related:d.links,serviceHandoff:{href:'/contact-us',label:'Design a bounded evidence pilot',body:'Choose one queue, freeze the definitions, and name the decision and exception owners before observation.'},sections:[
  {heading:'Research question and decision boundary',body:`This study asks ${d.question}. The observation unit is ${d.unit}. Freeze the queue, channel, customer population, observation window, system versions, governing instruction, and owner roles before collecting evidence. The provider may prepare records, perform approved actions, and route exceptions. It should not invent a missing source, merge uncertain identities, make policy or remedy decisions outside scope, or treat silence as approval. The client retains material customer, policy, access, privacy, security, and legal decisions. That boundary prevents a tidy operational record from being mistaken for authority.`},
  {heading:'Authoritative evidence and analytical separation',body:`ISO 18295-1 supplies customer-contact process and outcome context. NIST Cybersecurity Framework 2.0 supports governance, identity, protection, detection, response, recovery, and learning. The NIST Privacy Framework supports purpose-aware processing and proportionate data use. NIST Digital Identity Guidelines support explicit identity and authenticator lifecycle decisions. FTC material supplies an authoritative reminder that contact purpose, channel, consent, and customer choice can carry legal consequences. These sources support traceability and named ownership, but none validates this exact workflow. Preserve source facts, operational actions, management decisions, analytical inferences, and customer outcomes in separate fields.`},
  {heading:'Sampling method and counterexamples',body:`Construct a bounded cohort that includes ordinary work, a missing-input case, a cross-shift handoff, an unavailable owner, and a case that reaches the stop condition. Reconcile the analytical table to the source population and retain excluded or inaccessible records as limitations. ${d.example} The example should be traced in both directions: from the original customer event through systems and owners, and from the final status back to the evidence. A second reviewer should classify a subset using the same frozen definitions. Disagreement may indicate an ambiguous standard rather than individual error.`},
  {heading:'Measures and interpretation',body:`Report counts with denominators, coverage, missing evidence, owner-acceptance time, active work time, decision waiting time, repeat contact, reopened work, broken promises, reviewer agreement, and unresolved customer impact where those fields are lawful and available. Do not blend unlike clocks or treat a low exception count as proof of stability. It may mean exceptions are not recorded. A faster cycle is not improvement when required evidence or customer ownership disappears. Segment by queue, reason, channel, language, shift, severity, and rule version only when sample size and privacy controls support that comparison.`},
  {heading:'Governance and corrective action',body:`Assign the business owner, operating owner, system owner, data owner, quality reviewer, incident route, and customer-remedy owner. Version definitions and retain changes with effective dates. Findings should map to a repairable control: source correction, interface change, access change, routing rule, staffing coverage, instruction clarification, reviewer calibration, or exception ownership. Every corrective action needs an acceptance test and a repeat case. Generating alerts without a qualified owner creates another unmanaged queue. Expansion should pause when serious exceptions outpace review capacity or when evidence cannot support the promised decision.`},
  {heading:'Replication worksheet and evidence lineage',body:`A replication packet for ${d.title.toLowerCase()} should begin with a frozen inventory rather than a summary slide. Record the queue and channel identifiers, covered hours, source systems, exports, report parameters, system and instruction versions, field definitions, inclusion and exclusion rules, time-zone treatment, authorized linkage keys, reviewer roles, sample selection seed or rule, and known unavailable evidence. Hash or otherwise version the working population where local controls allow. For every selected item, retain a path from the original event to the analytical row, the action taken, the accepting owner, the applicable source, the exception, the final customer state, and the review conclusion. Working copies should contain only the minimum information required for the stated decision and should follow the approved access and retention rules. A second qualified reviewer should reproduce a sample from the frozen materials and record disagreements by category rather than silently reconciling them. Changes discovered during the review belong in a new version with an effective time. This protects the study from hindsight edits and lets a later buyer distinguish a genuine operating improvement from a changed population, interface, label, or clock. Replication does not guarantee the same result in a different queue; it shows whether the method and evidence trail can be followed.`},
  {heading:'Worked decision record and repeat test',body:`Use the worked case as a decision record: ${d.example} First capture the customer need and system state before interpreting the failure. Identify the current instruction, the action each role was permitted to take, the moment ownership changed, the evidence available to the next person, and the customer-facing promise. Classify missing and contradictory evidence without inventing a likely answer. The provider can contain the operational issue, preserve the trail, and route the open decision. The authorized client owner decides any remedy, policy exception, access change, or irreversible action. The corrective record should state the specific defect, affected population, immediate containment, accountable owner, due time, acceptance test, customer communication, and whether historical cases require review. Repeat with a fresh example that changes one material condition such as channel, language, shift, source version, verification result, or owner availability. Passing the repeat supports only the corrected path under the frozen conditions. A repeat that fails for a different reason should open a new finding rather than being folded into the first. Report both successful and failed traces, reviewer disagreement, and remaining blind spots. The goal is a defensible next decision: keep scope bounded, repair and repeat, reroute the task, or pause expansion until qualified review capacity and evidence are available.`},
  {heading:'Limitations and bounded conclusion',body:`${limits} The defensible conclusion is limited to whether ${d.unit} remained traceable through the frozen checkpoints and whether exceptions reached authorized owners. The study can expose stale guidance, unsafe authority transfer, missing ownership, inaccessible evidence, inconsistent classification, or incomplete closeout. It cannot certify compliance, predict company-wide performance, establish intent, or decide a customer remedy. Buyers should expand only the specific lane whose evidence is adequate, keep unknowns visible, and rerun the observation after the named control changes.`}
]});
export const october9ResearchBatch:readonly ResearchPost[]=drafts.map(make);
