import type { ResearchPost } from './fleet-data';

const sources = [
  {name:'ISO 18295-1 Customer Contact Centres',url:'https://www.iso.org/standard/73338.html'},
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
  {name:'NIST Zero Trust Architecture, SP 800-207',url:'https://csrc.nist.gov/pubs/sp/800/207/final'},
  {name:'NIST Digital Identity Guidelines, SP 800-63B',url:'https://pages.nist.gov/800-63-3/sp800-63b.html'},
  {name:'PCI DSS Document Library',url:'https://www.pcisecuritystandards.org/standards/pci-dss/'},
] as const;

const body = (subject:string, finding:string, design:string, measure:string, limit:string) => [
  {heading:'Question and method',body:`This research brief examines ${subject} in an outsourced customer-contact operation. The unit of analysis is one customer need during a defined observation period: the reason for contact, information available, action permitted, promise made, and owner of any exception. ISO 18295-1 provides a contact-centre lens for processes, people, and outcomes. NIST CSF 2.0 and the Privacy Framework contribute governance and data-handling questions; Zero Trust and Digital Identity Guidelines contribute access and assurance questions; PCI DSS is relevant when payment data enters the interaction. These sources describe control principles and obligations, not the performance of a particular provider. A useful study samples one queue, channel, and period, then separates ordinary contacts from escalations, repeat contacts, and records with missing ownership. Results should include volume and denominator, channel, time zone, case severity, and the customer promise in force.`,},
  {heading:'Findings',body:`${finding} The evidence supports a distinction between completing a bounded request and deciding an exception. A frontline worker can follow a safe path when the request, evidence, and permitted action are clear. The worker should pause when identity, policy, customer impact, or data sensitivity changes the decision. Reviewers should inspect a representative cohort rather than only the fastest or newest records. Compare completed work with transfers, reopened contacts, missing fields, repeat explanations, and overdue promises. Interpret changes by interval and contact reason: rising volume can coexist with better service, while stable volume can hide a worsening exception queue.`,},
  {heading:'Operating implications',body:`${design} A sound design makes the ordinary path explicit and the boundary visible. Use named accounts, role-based access, one authoritative record, and a short list of permitted actions. Capture what the next owner needs without copying unrelated customer details. A handoff should state what the customer asked, what has been verified, what was done, what remains, the expected update window, and who owns the next decision. Before expanding scope, compare customer-impact risk with review capacity. This is an operating inference from the cited principles, not a legal or performance guarantee.`,},
  {heading:'Measures and review',body:`${measure} Use fixed definitions and record the cohort period. Pair speed with completion quality and ownership: response or completion time, repeat contact, transfer count, reopened work, overdue promises, exception age, and records lacking a next owner. Sample successful and failed interactions. Test competing explanations such as demand mix, coverage, changed wording, missing system data, unclear authority, or a new customer segment. The review output should be a decision with an owner, evidence, and check date rather than a score without context.`,},
  {heading:'Evidence design and decision use',body:`A useful review of ${subject} should preserve the difference between an observation, an explanation, and a decision. Start by defining the population before looking at the result. State whether the cohort contains all contacts, only completed contacts, only escalations, or a sample selected by a reviewer. Include the start and end dates, channels, queue, time zone convention, exclusions, and the reason for each exclusion. A denominator such as 42 of 600 contacts communicates more than a percentage alone, especially when the failure is concentrated in one reason or one staffed interval. Keep the original event time and the time used for reporting; converting timestamps without preserving the source can conceal a handoff delay or create a false one. Where a field is missing, label it missing. Do not turn an unknown customer preference, identity state, or owner into a successful result.

The review should also test whether the category means the same thing across people and periods. Two teams may use the same disposition for different outcomes. A low transfer rate can mean better first-contact resolution, or it can mean that workers are closing work without an appropriate owner. A high exception rate can indicate weak instructions, a difficult customer mix, or responsible escalation. Read a small set of de-identified examples beside the aggregate measure. One ordinary case, one exception, and one near miss can reveal whether the field definitions describe the real work. Examples should be minimized, access-controlled, and retained only for an approved purpose. Their role is to explain mechanism, not to replace the cohort.

For ${subject}, compare leading signals with customer-impact and control signals. A leading signal is something visible before the outcome, such as a missing source field, an unassigned handoff, or a failed verification attempt. An outcome signal is something that happened later, such as a repeat contact, missed commitment, unresolved complaint, or correction. A control signal shows whether the permitted boundary held, such as an access exception, prohibited-data alert, or use of a retired instruction. The measures should not be collapsed into one score unless the business has documented the weighting and its consequences. A manager deciding whether to expand, narrow, pause, or redesign a service needs to see which part of the chain changed.

When findings differ by channel or cohort, preserve the difference instead of averaging it away. Voice, email, chat, and callback may have different verification, response, and record constraints. A weekend interval may have a different owner path from a weekday interval. A small severe cohort deserves attention even when its share of total contacts is low. Conversely, a large low-impact cohort can dominate an average while hiding a serious exception. Report counts, denominators, range or distribution where useful, and the practical uncertainty. Avoid causal language unless the observation design can support it. A before-and-after comparison is not automatically proof that one change caused the outcome; demand, staffing, system availability, customer mix, and policy changes may also have shifted.

The decision record should name the evidence reviewed, the conclusion supported, the uncertainty remaining, the owner, and the date for recheck. If the conclusion is to continue, state the guardrails and the trigger for review. If it is to change scope, state which customer reasons or permissions are removed and how affected work will be handed off. If it is to pause, state the customer-impact risk, the safe fallback, and the accountable approver. This makes the research useful to service leaders without presenting an operating inference as a certification, legal opinion, or promise of performance.`,},
  {heading:'Interpretation boundaries',body:`For ${subject}, the central analytical risk is confusing a process signal with a cause. A longer interaction may reflect a difficult need, accessibility requirement, missing record, or appropriate verification; it is not automatically a quality failure. A short interaction may be efficient or may end before the need is understood. Combine an activity measure, customer-impact measure, control measure, and ownership measure. Keep the same population and label missing data. When samples are small, report counts and denominators and avoid ranking individuals. Mark changes to scripts, systems, roles, or escalation routes so pre-change and post-change observations are not blended.`,},
  {heading:'Limitations and conclusion',body:`${limit} The sources do not establish one staffing ratio, callback threshold, permission matrix, retention period, or acceptable error rate for every business. Rules differ by product, jurisdiction, channel, account type, and data category; compliance and legal owners must resolve those questions. The bounded conclusion is that customer contact is easier to govern when its promise, information boundary, permitted action, escalation owner, and review cohort are written before volume increases. Record what was not observed and revisit the finding after a material change.`,},
];

const make = (slug:string,title:string,excerpt:string,subject:string,finding:string,design:string,measure:string,limit:string): ResearchPost => ({slug,title,excerpt,published:'2026-08-13',sourceDate:'2026-08-13',sources,sections:body(subject,finding,design,measure,limit)});

export const august13ReplacementResearchBatch: readonly ResearchPost[] = [
  make('call-center-callback-window-confirmation-research-brief','Call Center Callback Window Confirmation: A Research Brief','A callback window is dependable only when the customer time zone, owner, channel, and fallback are explicit.','confirmation of callback windows for customers across time zones','A callback record can be operationally complete yet customer-inaccurate if it stores only a server timestamp or team-local shift. Daylight-saving transitions, shared numbers, travel, and ambiguous abbreviations create different risks. A log proves when the attempt occurred, not whether the promised local window was understood.','Store the source of the time-zone value, confirm the local window in plain language, and preserve the original promise when a conversion changes. Require a named fallback owner for a missed window and do not infer geography from an area code alone.','Compare on-time contacts, missed windows, reschedules, repeat calls, and customer corrections by zone and reason. Review clock-change periods separately.','The approved source for time zone and the remedy for a missed promise are business-specific.'),
  make('call-center-knowledge-search-authority-research-brief','Call Center Knowledge Search Authority: A Research Brief','Search results help only when the current answer, scope, owner, and retirement state are clear.','authority and relevance in knowledge search during live customer support','A searchable library is not automatically an authoritative answer. Several similar results can leave the owner, effective date, audience, or exception rule unclear. Findability therefore includes authority: a result should identify the current version and who resolves a conflict.','Give each article an owner, effective date, audience, trigger terms, scope, and retirement state. Separate policy wording from examples. Route a search with no reliable result to a named owner and record the missing question.','Track zero-result searches, repeated searches, retired-article use, transfers after search, and corrections in sampled contacts. Segment by reason and shift.','Search logs do not prove that an answer was understood or safe; taxonomy and language are local.'),
  make('call-center-role-change-access-revocation-research-brief','Call Center Role-Change Access Revocation: A Research Brief','When a support role changes, old permissions and unowned customer work can persist unless both are reviewed.','access revocation and work ownership after a customer-contact role change','Zero Trust treats access as a continuing decision rather than a permanent entitlement. A worker may move queues, lose approval authority, or change coverage. Retaining old permissions broadens effective scope; removing access without a handoff leaves customer work unowned.','Record the effective change time, systems affected, replacement owner, and verification that old permissions were removed. Review shared credentials and exports as well as application roles. Keep emergency access time-limited and attributable.','Measure time from role change to access update, stale permissions, orphaned work, failed access attempts, and exceptions awaiting review. Sample high-impact systems first.','The correct access inventory and employment process are business-specific and not determined here.'),
  make('call-center-payment-recording-exposure-research-brief','Call Center Payment Recording Exposure: A Research Brief','Payment-data exposure can persist in calls, notes, transcripts, screen captures, and quality samples even when handling was accidental.','payment-related contacts and sensitive data in recordings and downstream records','PCI DSS materials make payment scope a system and process question, not merely a training slogan. Sensitive values can enter a recording, transcript, note, attachment, or sample. A payment interaction should be designed around the approved payment path and minimum information the support role needs.','Use an approved payment channel, define what may be spoken or written, mask fields where supported, and exclude sensitive recordings from ordinary sampling. If prohibited data appears, preserve incident facts without copying the value and route containment to the accountable owner.','Audit redaction coverage, prohibited-data detections, recording exceptions, note samples, and time to containment. Separate confirmed exposure from a control alert.','PCI scope depends on the environment and role; the compliance owner determines obligations and remediation.'),
  make('call-center-accessibility-request-continuity-research-brief','Call Center Accessibility Request Continuity: A Research Brief','An accessibility request needs continuity across handoffs without forcing the customer to repeat sensitive context.','continuity of accessibility requests across customer-contact handoffs','Accessibility requests can concern channel, timing, language, assistive technology, format, or an adjustment. A generic label loses the needed action and owner. Repeatedly asking for the same context adds friction and can produce inconsistent outcomes. The record should carry only information needed to provide approved support.','Define supported channels, permitted intake questions, privacy limits, urgent indicators, and the owner who confirms an adjustment. Give a truthful next step without promising an accommodation requiring review. Keep an accessible fallback when the usual channel fails.','Review requests by type, completion time, repeat explanations, failed transfers, unresolved ownership, and customer corrections. Examine accepted and declined requests separately.','Accessibility duties vary by service and jurisdiction; staff should not improvise legal or medical conclusions.'),
  make('call-center-notification-preference-propagation-research-brief','Call Center Notification Preference Propagation: A Research Brief','A preference record must retain purpose, channel, effective time, source interaction, and ownership when it moves between systems.','propagation of customer notification preferences across service systems','A preference is not a universal permission. A customer may accept an appointment reminder while declining promotional contact, or select email for routine updates while needing another urgent route. Treating one field as a complete policy can create missed service and unwanted contact.','Separate service, transactional, and promotional purposes where policy requires it. Make changes attributable and visible across sending systems. Do not promise a preference change is active until the authoritative record confirms it.','Review changes, failed sends, opt-outs not propagated, repeat contacts, and non-preferred sends over a defined period. Reconcile the customer record with the sending system.','FTC and FCC requirements are jurisdiction- and channel-sensitive; the sources do not give a universal consent interpretation.'),
  make('call-center-customer-deadline-feasibility-research-brief','Call Center Customer Deadline Feasibility: A Research Brief','A deadline is a promise with a clock, owner, dependency, evidence of feasibility, and truthful fallback.','feasibility of deadlines communicated by customer-contact teams','Customers often hear a date as a commitment even when a representative intended a target. A reliable record identifies the event starting the clock, time zone, dependencies, responsible owner, and permitted message if the deadline is at risk. Handle time alone cannot show whether the promise was safe.','Allow representatives to state only approved windows, record the deadline source, and require a manager decision when a dependency exceeds the role authority. Before expiry, make the fallback update visible instead of replacing uncertainty with another unsupported date.','Track deadlines met, missed, changed, customer follow-ups, dependency causes, and records updated before expiry. Compare by promise type and owner, not just average completion time.','A deadline may depend on a third party or policy exception; no universal remedy is established.'),
  make('call-center-duplicate-contact-linkage-research-brief','Call Center Duplicate Contact Linkage: A Research Brief','Repeated contacts may indicate an unresolved need, routing defect, or record problem; similarity alone is not proof of duplication.','linkage of repeated customer contacts across calls, messages, and tickets','A repeat contact is not always a duplicate. The customer may add information, use another channel, or respond to a missed promise. A merge or closure based on similarity can erase chronology and hide the unresolved need. The useful unit is the linked customer need, with evidence for why records relate and what remains open.','Link records with approved identifiers and a reason for linkage. Preserve separate history when identity or purpose is uncertain. Show the owner prior promises and dependencies without copying unrelated personal or payment details.','Measure repeat contact within a defined window, unresolved need after linkage, false matches, duplicate closures, transfer loops, and time to one accountable owner. Sample linked and unlinked records.','Systems and channels may not share reliable identifiers; data-protection and retention rules govern linkage.'),
  make('call-center-customer-update-source-accuracy-research-brief','Call Center Customer Update Source Accuracy: A Research Brief','A customer update is reliable when its wording, timestamp, source record, and next-update owner agree.','accuracy of customer-facing updates against authoritative case records','A polished update can still be wrong when it summarizes a stale status, omits a dependency, or turns a target into a promise. Review should compare the language used with the source facts, the customer impact, and the permitted action. The customer needs a bounded statement of what is known, unknown, and next.','Use approved wording for normal, delayed, and unresolved states. Require the sender to consult the authoritative record and record the source time. Escalate when the requested update requires a refund, safety, legal, or policy decision outside the role.','Sample updates against source facts and measure corrections, repeat contacts, missed update windows, unsupported promises, and escalations returned for missing evidence. Segment by channel.','Appropriate wording and remedy depend on product and policy; a quality sample cannot replace the accountable decision.'),
  make('call-center-complaint-impact-evidence-research-brief','Call Center Complaint Impact Evidence: A Research Brief','Complaint evidence should preserve the customer-stated impact and the facts needed for a fair owner decision.','evidence quality in complaint intake and review','A complaint is more than a sentiment score. It may allege a missed promise, billing problem, safety issue, accessibility barrier, or repeated failure. Compressing it into a vague label forces repetition and can send the case to the wrong owner. Evidence should distinguish stated words, verified facts, prior actions, requested outcome, and decision still required.','Capture the issue and impact without editorializing, link the relevant interaction, record the promised update, and name the decision owner. Keep allegations separate from findings. Acknowledge receipt without implying resolution and preserve an urgent route for serious harm.','Review missing context, time to acknowledgment, time to owner decision, returned cases, repeat explanations, and complaints closed without answering the stated issue. Analyze severity and channel separately.','There is no universal severity scale or remedy; legal, safety, and policy owners decide from the facts.'),
];
